### PR TITLE
Add tcpwrappers package

### PR DESCRIPTION
**Pull request by uberhacker**
The tcpwrappers package provides daemon wrapper programs that report the name of the client requesting network services and the requested service.  See http://www.linuxfromscratch.org/blfs/view/6.1/basicnet/tcpwrappers.html.

Tested on:
- [x] aarch64
- [x] armv7l
- [x] i686
- [x] x86_64

### CODE REVIEW

**Comment by JL2210** [comment]
FTP? You know better...

You also might use a newer patch than LFS 6.1.

**Comment by uberhacker** [comment]
What else can you do when that is the only option available that works?

**Comment by uberhacker** [comment]
This release is already over 20 years old.  I don't think newer patches will make that much difference but who knows?

**Comment by JL2210** [comment]
Fair enough. You could still use a newer patch (8.2 is out now.)

**Comment by uberhacker** [comment]
Right, but does 8.2 have build instructions available for this package?

**Comment by JL2210** [comment]
http://www.linuxfromscratch.org/blfs/downloads/6.3/patches/tcp_wrappers-7.6-shared_lib_plus_plus-1.patch

**Comment by JL2210** [comment]
No, but 6.3 does.

**Comment by JL2210** [comment]
http://files.ichilton.co.uk/nfs/tcp_wrappers_7.6.tar.gz

**Comment by uberhacker** [comment]
It's the same exact patch. :)

**Comment by JL2210** [comment]
Yes, but the source is HTTP. Better than nothing. Also, you never know. They could have changed it.

**Comment by uberhacker** [comment]
Have you tried that source?  It's a dead link.

**Comment by JL2210** [comment]
We'd better use the 6.3 one, anyway. They might remove 6.1

**Comment by uberhacker** [comment]
I'll let you change it.  Not worth it.

**Comment by JL2210** [comment]
I'll host the tarball on GitHub, then. I don't want to have to deal with FTP.

**Comment by uberhacker** [comment]
You won't need to deal with ftp once the binaries are available unless you like pain and always want to compile everything from source.

**Comment by JL2210** [comment]
Who says that's pain?

**Comment by uberhacker** [comment]
Only you would say that. :-P  Apparently, you have all the time in the world to do all this compiling crap. :)

**Comment by JL2210** [comment]
https://github.com/JL2210/source-code/raw/master/tcp_wrappers_7.6.tar.gz

**Comment by JL2210** [comment]
I love fixing bad designs in C, build systems, and otherwise.

**Comment by JL2210** [comment]
@uberhacker, did you use my source URL?

**Pull request merged**
