### PR TITLE
Updating Node to 4.3.0 & 5.6.0 *SECURITY UPDATE*

### PR DESCRIPTION
**Pull request by thedamian**
Sorry guys. Node JUST updated like 2 days ago. HomeBrew and LinuxBrew already have the update. 

If you need to update Node right away do a "npm install -g n" then do "n stable" or "n 4.2.6" which will update your node to which ever you want.

### CODE REVIEW

**Comment by skycocker** [comment]
This would require also modifying the `version` line in each of the package files.

**Comment by thedamian** [comment]
Duh! Yes of course. I'll do that and re submit the pull.

**Comment by thedamian** [comment]
THAT took a long time! Sorry. It's fixed.

**Comment by thedamian** [comment]
Node just release a major update for a security update. 

Here's the details:
https://nodejs.org/en/blog/vulnerability/february-2016-security-releases/

Let's get up to date.

**Comment by skycocker** [comment]
@thedamian could we separate this into 2 pull requests? So we can merge the nodejs update already but talk about this symlink.

**Comment by thedamian** [comment]
Yes of course. I took it out for the last node update and then put it back for my copy and when nodejs did their security update i forgot to take it out again. My apologies

**Comment by thedamian** [comment]
Done. ONLY update for node and node_stable are here. 

I also removed a mono package I'm still working on. It'll get in there but I'm struggling to get it in. Sorry for the added ones that weren't suppose to be there.

**Comment by skycocker** [comment]
Merged with a rebase to keep commit history clean. Thanks! :)

**Pull request closed without merging**
