### PR TITLE
Add vscode again

### PR DESCRIPTION
**Pull request by JL2210**
Fully tested and working on x86_64. Hope this works/helps!

### CODE REVIEW

**Comment by uberhacker** [comment]
Nice job!

**Comment by JL2210** [comment]
Thanks.

**Comment by JL2210** [comment]
Still might need a reboot.

**Comment by VitaliyKulikov** [comment]
@JL2210 @uberhacker it's awesome. good job and thanks!
btw: do you know how to change scaling in GTK menu?

```
chronos@localhost ~/app $ gsettings get org.gnome.desktop text-scaling-factor
No such schema “org.gnome.desktop”

**Comment by JL2210** [comment]
You should see the old PR and the one for sommelierd so you can change
this. If you are part of the user group, look at the general thread.

**Comment by VitaliyKulikov** [comment]
@JL2210 cool. it works. but now, need change mouse cursor size .. seems, `XCURSOR_SIZE` is not working. i will look around. thanks

**Comment by uberhacker** [comment]
@VitaliyKulikov: @JL2210 and @ukscone deserve all the credit.  @JL2210: Did you want to add something in the wiki to help with this scaling issue?  @VitaliyKulikov: The user group @JL2210 mentioned is Slack and you are welcome to join.  Just click on the icon or text in this project's README.md and you should receive an invite.

**Comment by JL2210** [comment]
Sure. I'll add this to the wiki. Cursor size doesn't matter as long as it
works.

**Comment by uberhacker** [comment]
@JL2210: Size always matters.  Sorry, that was a bad joke.

**Comment by 5nowx** [comment]
Hello! i'm kind of new in Github, and i have some problems. 

I see your pull as merged, but i don't see the package in the current packages directory, neither on the 'crew list available' for version 1.0.3 , is this on some other version? how can i install it?

Thanks guys! great work @JL2210 !

**Comment by 5nowx** [comment]
Thanks JL2210! was my bad i tough the package was called vscode. Thanks!

**Comment by JL2210** [comment]
Sorry about getting your name wrong. This screen resolution is horrible.

**Pull request merged**
