### PR TITLE
Dart version bump, arch update, update binary source, fix #780

### LINKED ISSUE #780: Dart package needs work
This package does not install.  After examining the output, it appears `/usr/bin`, `/usr/include` and `/usr/lib` directories in the tarball should be changed to `/usr/local/...` instead.  Also, the dart.rb package file is missing description and homepage metadata.

### PR DESCRIPTION
**Pull request by dantrevino**
Dart version bump to current.  Add arm7 architecture.  Download from official repositories. Fix directory install location issues  (#780).

### CODE REVIEW

**Comment by uberhacker** [comment]
@dantrevino: Thank you for this PR.  I think we should probably remove the `else ... abort` lines.  If you are interested, you can follow the discussion over on PR #798.

**Comment by dantrevino** [comment]
Nice.  I'll update.

**Comment by lyxell** [comment]
Nice!

**Comment by uberhacker** [comment]
This package gets my vote as merge worthy.

**Comment by uberhacker** [comment]
Actually, I just tested this and it doesn't install.  See below:
```
cp: cannot stat ‘man/’: No such file or directory
dart failed to install: `cp -r man/ /usr/local/tmp/crew/dest/usr/local` exited with 1
```
Please change as shown below:
```
- system "cp -r man/ #{CREW_DEST_DIR}/usr/local"
- system "cp -r include/ #{CREW_DEST_DIR}/usr/local"
```
Apparently, there are no manpages in the source.

**Comment by dantrevino** [comment]
Odd.  I committed that change as part of the original.  Not sure what I
missed.

**Comment by dantrevino** [comment]
Commit 3 fix to man directory.  thx @uberhacker

**Comment by uberhacker** [comment]
@dantrevino: You will need to put the `depends_on 'unzip'` line inside the `class Dart < Package` block.  The following error occurs with that line outside the class.
```
/usr/local/lib/crew/packages/dart.rb:3:in `<top (required)>': undefined method `depends_on' for main:Object (NoMethodError)
```
You will probably want the depends_on line right above the `def self.install` line.  That should fix it.  Thanks for persevering. :)

**Comment by uberhacker** [comment]
@dantrevino:  Nice work.  You found the end of the tunnel!! :)

**Pull request merged**
