### PR TITLE
icu4c -> 68.1 (requires patched libxml2, recompile of wget)

### PR DESCRIPTION
**Pull request by satmandu**
Works properly:
- [x] x86_64

### CODE REVIEW

**Comment by uberhacker** [comment]
This is a core package so we will need binaries.  Did you test if this breaks gcc or any of the other compilers?

**Comment by satmandu** [comment]
This does create breakage... so best to queue this up when more packages need to get changed.
e.g. libxml will need this patch to work with ice 68.1: https://gitlab.gnome.org/GNOME/libxml2/-/commit/b516ed189eb440e909f36baca1557b98e4d9ffd7.patch

**Comment by uberhacker** [comment]
Yeah, maybe we should just hold off until it stabilizes a bit.  Any reason the older version needs to be updated?

**Comment by satmandu** [comment]
I was just going through trying to troubleshoot issues with trying to compile gnome's evolution_data_server, and there was a complaint about this library.  68.1 IS a major release though as per https://github.com/unicode-org/icu/releases

**Comment by satmandu** [comment]
This also requires wget to be recompiled after a recompiled libxml2 is installed.

**Comment by uberhacker** [comment]
See #4747.

**Pull request closed without merging**
