### PR TITLE
Update ghpages

### PR DESCRIPTION
**Pull request by sajjaadf**
Fix a little problem

### CODE REVIEW

**Comment by uberhacker** [comment]
Uh, do we really need this?  The chances of somebody going here accidentally are pretty slim.

**Comment by JL2210** [comment]
Yeah... I agree with @uberhacker.

**Comment by sajjaadf** [comment]
can't we do it for fun?

**Comment by sajjaadf** [comment]
It won't hurt, _right_?

**Comment by uberhacker** [comment]
But here's the thing: they might be in the right place intentionally and this message could end up being more confusing than helpful.

**Pull request closed without merging**
