### PR TITLE
[cabal] Correct URL error of i386 on 2.4.1 version

### PR DESCRIPTION
**Pull request by vincowl**

### CODE REVIEW

**Comment by uberhacker** [comment]
Good catch @vincowl.  Might as well upgrade.  A new version is available.

i686: https://downloads.haskell.org/~cabal/cabal-install-latest/cabal-install-3.0.0.0-i386-unknown-linux.tar.xz
x86_64: https://downloads.haskell.org/~cabal/cabal-install-latest/cabal-install-3.0.0.0-x86_64-unknown-linux.tar.xz

**Comment by uberhacker** [comment]
While we're at it, we could also update `ghc` since `cabal` needs it with the updated version:
```
https://downloads.haskell.org/~ghc/8.8.1/ghc-8.8.1-src.tar.xz.sig
```

**Comment by vincowl** [comment]
As far as I remember, there was a higher constraint that forbids upgrading these packages greater than actual ones. In october, I commented an issue about that. I'll try to find back what forces this. Greater versions already existed in October.

**Comment by vincowl** [comment]
Cf #3618 : stack forces cabal and ghc versions

**Comment by vincowl** [comment]
It should be levered up in the next stack release since 2.1.3 has been released on July and the ghc 8.8 bug has been solved in august. Cf https://github.com/commercialhaskell/stack/issues/5018

**Comment by vincowl** [comment]
It should be levered up in the next stack release since 2.1.3 has been released on July and the ghc 8.8 bug has been solved in august. Cf https://github.com/commercialhaskell/stack/issues/5018

**Pull request merged**
