### PR TITLE
Remove all SHORTARCH related stuff

### PR DESCRIPTION
**Pull request by jam7**
Removing SHORTARCH variable from crew as discussed/described in #337.

This modifies bc, clisp, ffcall, flex, fontconfig, freetype, gdal, geos, imagemagick, libgd, libjpeg, libpng, libsigsegv, libtiff, libxml2, libxslt, mapserver, openconnect and proj4.

I tested them all and all other packages depend on them on X86_64.  I also tested all except ffcal and clisp on ARM (those two are not compilable on ARM)

### CODE REVIEW

**Comment by thedamian** [comment]
@jam7 I love this.

BUT... I think you shouldn't update the package. 

if you have the new crew that doesn't have SHORTARCH you don't have the package that uses it. and vice versa.

**Comment by jam7** [comment]
@thedamian Yes, therefore I modified packages and crew.  I forgot to mention crew modification but I did.  ;)

**Comment by lyxell** [comment]
Looks good to me!

**Comment by cstrouse** [comment]
Looks good other than the tacking the suffix on the package versions. I'm with @thedamian on not liking that.

**Comment by jam7** [comment]
The reason of incrementing the version number is this modification may change the place of libraries installed.  For example, libraries installed to lib64 previously may be installed to lib after this modification.  Both should work fine because we have pkg-config.  But, I just thought it is not bad to force to upgrade by incrementing the version number.

But, if it is not acceptable, I can revert them.  Please let me know.  Thanks.

**Comment by cstrouse** [comment]
@jam7 that makes sense. I'm good with it.

**Comment by jam7** [comment]
Resolve conflicts.

**Pull request merged**
