### PR TITLE
Added sommelier package.

### PR DESCRIPTION
**Pull request by JL2210**
Fixes:

#2401 (I don't want to close this issue just yet.)

Should work. Removed dependencies and lines of incompatible code.

Tested on:

i686 [ ]
x86_64 [x]
armv7l [ ]
aarch64 [ ]

### CODE REVIEW

**Comment by ukscone** [comment]
what lines did you have to remove. on the version I used I just had to modify a variable in the makefile. didn't make any changes to the actual code

**Comment by JL2210** [comment]
The systemd references in sommelier.cc

**Comment by JL2210** [comment]
Look at the package script. Removed sd-daemon and sd_notify

**Comment by ukscone** [comment]
ah I see. a couple of seds

**Comment by uberhacker** [comment]
Thank you for the new package @JL2210!  Why do we need to remove anything?  Also, can you please test your PR before adding a bunch of new commits?  A PR should be fully tested before it is submitted.

**Comment by JL2210** [comment]
Got all the deps. Should be good now.

**Comment by uberhacker** [comment]
That doesn't answer my question about why we need to remove anything.

**Comment by JL2210** [comment]
It is tested. OpenRC is default in a Chromebook, and you cant get systemd libs. It's really just for notifications, so it should be all good.

**Comment by JL2210** [comment]
Meson doesn't like compiling only part of a project, so I just removed systemd support. It tried to install systemd on the root filesystem.

**Comment by JL2210** [comment]
It works nicely. QEMU runs in a window.

**Comment by ukscone** [comment]
so i think we are probably reasonably safe in saying chromebrew does gui :) need a few gui toolkits added and some odds and sods but looks like sommelier is the way to go

**Comment by JL2210** [comment]
Here's a bonus: Tilp works.

**Comment by ukscone** [comment]
a bit more testing and a few more things build/rebuilt and I think we should yell "chromebrew does gui" from the rooftops or at least on reddit :D

**Comment by uberhacker** [comment]
Nice work @ukscone and @JL2210.  Does vscode work?  I think @thedamian would enjoy hearing if that was successful.

**Comment by JL2210** [comment]
Not tested yet. Try doing this with tilp installed. `sommelier -X tilp`

**Comment by JL2210** [comment]
Where do I download vscode

**Comment by uberhacker** [comment]
@JL2210: FYI: qemu also works in a window with freedos and no sommelier.

**Comment by ukscone** [comment]
VScode needs one lib i couldn't get built due to dependencies and stuff. but fingers crossed @JL2210 can.

vsc is here https://code.visualstudio.com/download i took the linux tar.gz

**Comment by uberhacker** [comment]
More info here: https://github.com/skycocker/chromebrew/issues/2449

**Comment by JL2210** [comment]
Downloading right now. Will make a package if it works.

**Comment by JL2210** [comment]
I did too. Dpkg works if you download the deb.

**Comment by JL2210** [comment]
Still needs those packages. I'll create a separate PR with the deps.

**Comment by JL2210** [comment]
This is good. Ready.

**Comment by ukscone** [comment]
probably needs someone with an arm chromebook to test as well first

**Comment by JL2210** [comment]
I have a cross compiler. Works with QEMU, as long as you have the dependencies.

**Comment by ukscone** [comment]
ok. not my decision anyway :) if everyone is happy lets do it :)

**Comment by JL2210** [comment]
Those were sort of annoying.

**Comment by JL2210** [comment]
@uberhacker: What do you say? It works.

**Comment by JL2210** [comment]
I'll add an x86_64 binary if that helps. Fresh crew.

**Comment by uberhacker** [comment]
I can look at it later.  Day job going on right now. :yawn:

**Comment by JL2210** [comment]
K. Meanwhile, VS code is almost ready.

**Comment by JL2210** [comment]
Going to redo this one and make it work without conflicts.

**Comment by uberhacker** [comment]
Please test your new sommelier package fully before you submit the PR.  In the future, I want to try and get away from adding a bunch of new commits after a PR has been submitted.  And please update xwayland in a separate PR.  Thanks, I really do appreciate all your efforts.

**Pull request closed without merging**
