### PR TITLE
Add package for The Silver Searcher.

### PR DESCRIPTION
**Pull request by vince**
The Silver Searcher is an alternative to ack that is a magnitude faster. It's wonderful for searching your local filesystem and is necessary if you're going to use the vim plugin of the same name. You can read all about the package [here](https://github.com/ggreer/the_silver_searcher).

### CODE REVIEW

**Comment by uberhacker** [comment]
@vince: Thank you for adding this package.  I just tried it out and it looks amazing!  Much faster than using `grep -r something`.  I'm thinking you might want to change the package object name from `The_silver_searcher` to `Ag` instead.  Usually, it's a good idea to name the package the same as the command to avoid confusion.  You can still include silver searcher in the description so it can be found in searches.  If you change the package name and include `silver searcher` in the description, `crew search ag` and `crew search silver` will both return results.

**Comment by vince** [comment]
Arch and most other distros list it as "the_silver_searcher" which is why I changed it from Ag. Debian uses silversearcher-ag. Would that be a good compromise?

    silversearcher-ag - very fast grep-like program, altenative to ack-grep

Wow, just noticed that they have a typo in their description. :)

**Comment by uberhacker** [comment]
I never understood why we needed to be like other distros but since that has `ag` in the name, it would be easily searchable.  `crew install ag` is much easier to type. :)

**Comment by flyingP0tat0** [comment]
+1 for `ag`

**Comment by vince** [comment]
Ok, this is done. Do I need to do a new PR or will [d3d8fce](https://github.com/skycocker/chromebrew/pull/881/commits/d3d8fce6877fc6c72e0cbbc26d43de3ad04ac860) automatically be applied?

**Comment by uberhacker** [comment]
No need for another PR.  Just push with the new commit.

**Comment by lyxell** [comment]
Thanks!

**Pull request merged**
