### PR TITLE
Add bacula package

### PR DESCRIPTION
**Pull request by uberhacker**
Tested on all architectures.

### CODE REVIEW

**Comment by JL2210** [comment]
That `--datarootdir` flag should be `#{CREW_PREFIX}/share`, not `#{CREW_PREFIX}`.

**Comment by skiman6010** [comment]
I agree with how it is done.

**Comment by JL2210** [comment]
Umm... 
```
  --datarootdir=DIR       read-only arch.-independent data root [PREFIX/share]
  --datadir=DIR           read-only architecture-independent data [DATAROOTDIR]
```
This would make it so you wouldn't have to pass `--mandir=#{CREW_PREFIX}/share/man`.

**Comment by uberhacker** [comment]
You are right.  If you want to create another PR to fix it, go ahead but everything is installed in the correct location.  I will fix it on the next version, otherwise.

**Comment by JL2210** [comment]
Nah, it's not that big of a problem. Thanks.

**Pull request merged**
