### PR TITLE
Update gtk3 from 3.24.3 to 3.24.9

### PR DESCRIPTION
**Pull request by uberhacker**
Tested on all architectures.  All gtk3 apps crash on release 75.  Please revert to release 74, if possible.

### CODE REVIEW

**Comment by skiman6010** [comment]
Does gtk3 crash because of this update or just in general?

**Comment by uberhacker** [comment]
Works great on anything except release 75.  As you might already know, Google pulled the release and reverted back to 74.

**Comment by skiman6010** [comment]
Thought so, just wanted to check. Interesting because when 75 was in beta it was fine. Wonder what changed in the stable release. 76 is good as well.

**Comment by JL2210** [comment]
Darn. And I just updated.

**Pull request merged**
