### PR TITLE
Fix mandb install so it 'just works'

### PR DESCRIPTION
**Pull request by uberhacker**
See #355.

### CODE REVIEW

**Comment by jam7** [comment]
This is my personal opinion, but modifying user environment (.bashrc) quietly is not good.  I prefer old way, showing messages.  mkdir is OK since it is part of system environment, but .bashrc is...  For example, how do you think user performs install & remove & install...

On the other hand, I'm not sure about the new explanation of `mandb -c`.  Isn't it just making cache db?  man runs without it little slowly but it shows all newly added man pages without db updates.

**Comment by uberhacker** [comment]
You have a good point about modifying the user environment.  It is quite possible (although not very likely) someone may prefer a different shell other than bash.  My thought process is to make it as easy as possible for the user to configure and use the command.  In regards to `mandb -c`, here is what `man mandb` says about it:
```
       -c, --create
              By  default,  mandb  will  try  to update any previously created databases.  If a database does not exist, it will create it.  This
              option forces mandb to delete previous databases and re-create them from scratch, and implies --no-purge.  This may be necessary if
              a database becomes corrupt or if a new database storage scheme is introduced in the future.
```
Having an updated database of manual pages is pretty important.  This makes sure everything is up to date so there are no surprises.

**Comment by lyxell** [comment]
Isn't it more reasonable to use another directory instead of chowning the one in `/var`?

**Comment by uberhacker** [comment]
@lyxell: Based on the errors when mandb attempts to update cache, those were the directories targeted.  Not sure if we can easily change the cache paths.  BTW, @jam7, I restored the PAGER env variable set up instructions in the latest commit.

**Comment by uberhacker** [comment]
@lyxell: Is there any hope of this PR getting merged into master?  If not, what do I need to change?

**Comment by lyxell** [comment]
Yeah, I'll try this out soon

**Comment by uberhacker** [comment]
Closing due to unresolvable merge conflicts.

**Pull request closed without merging**
