### PR TITLE
[llvm] Update to 10.0.0

### PR DESCRIPTION
**Pull request by vincowl**

### CODE REVIEW

**Comment by uberhacker** [comment]
Kudos on the update.  This update requires a lot of work and your efforts are very much appreciated.

**Comment by vincowl** [comment]
Thanks ! Indeed, it's a lot of works but seems to be worth it

**Comment by uberhacker** [comment]
I'm going to hold off on merging this until I have time to generate the binaries because it takes an eternity to compile everything and I wouldn't want to put that burden on everybody.

**Comment by cstrouse** [comment]
The dependencies brought in from building the docs make this entirely too bloated for many people's available resources. I recommend removing that.

Also, on I ran into an issue trying to build on x86_64.

```bash
chronos@95e04cb317db /usr/local/lib/crew/packages $ crew install llvm
llvm: The LLVM Project is a collection of modular and reusable compiler and toolchain technologies. The optional packages clang, lld, lldb, polly, compiler-rt, libcxx, libcxxabi and openmp are included.
http://llvm.org/
version 10.0.0
The following packages also need to be installed: 
ocaml swig 
Do you agree? [Y/n] y
Proceeding...
ocaml: OCaml is an industrial strength programming language supporting functional, imperative and object-oriented styles
http://ocaml.org/
version 4.06.0
Precompiled binary available, downloading...
##################################################################################################################################### 100.0%
Archive downloaded
Unpacking archive using 'tar', this may take a while...
Installing...
Performing post-install...
swig: Simplified Wrapper and Interface Generator
http://www.swig.org
version 4.0.1
Precompiled binary available, downloading...
##################################################################################################################################### 100.0%
Archive downloaded
Unpacking archive using 'tar', this may take a while...
Installing...
Performing post-install...
No precompiled binary available for your platform, downloading source...
##################################################################################################################################### 100.0%##################################################################################################################################### 100.0%
Archive downloaded
Unpacking archive using 'tar', this may take a while...
gcc (GCC) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
Rename all *.la files to *.la_tmp
Downloading clang
Clang archive downloaded
Clang source code unpacked
'tools/clang-10.0.0.src' -> 'tools/clang'
Downloading lld
Lld archive downloaded
Lld source code unpacked
'tools/lld-10.0.0.src' -> 'tools/lld'
Downloading lldb
Lldb archive downloaded
Lldb source code unpacked
'tools/lldb-10.0.0.src' -> 'tools/lldb'
Downloading polly
Polly archive downloaded
Polly source code unpacked
'tools/polly-10.0.0.src' -> 'tools/polly'
Downloading compiler-rt
Compiler-rt archive downloaded
Compiler-rt source code unpacked
'projects/compiler-rt-10.0.0.src' -> 'projects/compiler-rt'
Downloading libcxx
Libcxx archive downloaded
Libcxx source code unpacked
'projects/libcxx-10.0.0.src' -> 'projects/libcxx'
Downloading libcxxabi
Libcxxabi archive downloaded
Libcxxabi source code unpacked
'projects/libcxxabi-10.0.0.src' -> 'projects/libcxxabi'
Downloading openmp
Openmp archive downloaded
Openmp source code unpacked
'projects/openmp-10.0.0.src' -> 'projects/openmp'
Downloading libunwind
Libunwind archive downloaded
Libunwind source code unpacked
'projects/libunwind-10.0.0.src' -> 'projects/libunwind'
Optional packages are ready
Change to GOLD linker.
cmake: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by cmake)
cmake: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by cmake)
cmake: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by cmake)
llvm failed to install: `cmake -DCURSES_INCLUDE_PATH='/usr/local/include/ncursesw' -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_CXX_FLAGS="-fPIC" -DCMAKE_BUILD_TYPE=Release -DLLVM_LIBDIR_SUFFIX=64 -DBUILD_SHARED_LIBS=ON -DLLVM_ENABLE_RTTI=ON -Wno-dev ..` exited with 1
```

**Comment by vincowl** [comment]
@cstrouse Really no idea... I compiled it successfully about 5 times yesterday. The error displayed seems to be an internal trouble since `GLIBCXX` and `CXXABI` relate to `libcxx` and `libcxxabi`which are intermal products. Hope this is still a network error otherwise it may be a small nightmare to debug this...

To help debugging such things we should really have a dependencies management system based on packages version depemdencies. Such packages imply too deeply nested dependencies and merging single packages PRs may lead to higher level errors. Why not working at least with one single PR involving every evolutions needed to make llvm work which means a lot of libs ? For instance here, how to be sure every needed package has been upgraded ?

Which part is involved in building the docs ?

**Comment by cstrouse** [comment]
In that example output I had already removed the docs-related stuff. Nope, not a network error. This is after another fresh install.

**Comment by vincowl** [comment]
@cstrouse could you share your new package file please ? I'll have a test here

**Comment by uberhacker** [comment]
FWIW, I was able to build this successfully with the updated sphinx binary on x86_64, although it took nearly 10 hours to complete and the resulting binary was 90+ mb. :-O

**Comment by vincowl** [comment]
Wow.... I'll have a look at my binary's size. It took me about 2h to compile. Did you manage to remove the docs part ?

**Comment by uberhacker** [comment]
I didn't try to remove anything.  I'm just the build monkey. :)

**Pull request merged**
