### PR TITLE
Add spellcheck_test script

### PR DESCRIPTION
**Pull request by uberhacker**
How I figured out the spelling errors from the last few PRs.

### CODE REVIEW

**Comment by supechicken** [comment]
Better to write this command to documents like `useful commands`?

**Comment by uberhacker** [comment]
Not sure what you mean.

**Comment by supechicken** [comment]
Since this is a wrapper script for `codespell`, it could be make sense to run it directly (`cd #{CREW_PREFIX}/lib/crew/packages; codespell`) in shell

**Comment by uberhacker** [comment]
The purpose of the wrapper script is to run from the correct location.  Otherwise, the script does not catch everything.  Also, so we can consolidate testing scripts in one area.

**Comment by saltedcoffii** [comment]
Putting all the testing scripts into tests/*.rb will make it easier to run `rake test` once we have a Rakefile

**Pull request merged**
