### PR TITLE
Add pass password manager

### PR DESCRIPTION
**Pull request by Alanaktion**
This adds the standard unix password manager from https://www.passwordstore.org/.

### CODE REVIEW

**Comment by uberhacker** [comment]
Cool!  Thank you for adding this @Alanaktion.  Might want to change `--prefix=/usr/local` to `--prefix=#{CREW_PREFIX}` instead to abstract the install location.

**Comment by Alanaktion** [comment]
Thanks, I've added it. I knew there was a variable for it, but couldn't remember what it was, and saw several hard-coded `/usr/local`s in other packages.

**Comment by uberhacker** [comment]
Yes, we need to change those other packages also.  @jam7 has a pending PR to handle similar cases like this without a configure script available.  See https://github.com/skycocker/chromebrew/pull/1206/files.

**Comment by uberhacker** [comment]
He will probably ask you to add this section also. :)
```
def self.build
   system "make"
end
```

**Comment by Alanaktion** [comment]
This program specifically does not have a `make` though, the Makefile just prints:
> Password store is a shell script, so there is nothing to do. Try `make install` instead.

**Comment by uberhacker** [comment]
Well, in that case we don't need that section.

**Comment by flyingP0tat0** [comment]
Just a little style thing: Could you please move the dependencies above the binaries (or remove the empty binaries for now)? Just to ensure the same syntax :)

**Comment by Alanaktion** [comment]
I've removed the binary lines. I just matched what I saw in other packages without binaries, but it's definitely cleaner to not have the empty hashes :)

**Pull request merged**
