### PR TITLE
glibc 2.23 rebuild for i686

### PR DESCRIPTION
**Pull request by satmandu**
Works properly:
- [x] x86_64
- [ ] i686 @uberhacker please check this on hardware...

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=glibc CREW_TESTING=1 crew update
```

### CODE REVIEW

**Comment by uberhacker** [comment]
Has this been tested on an actual i686 Chromebook device?

**Comment by satmandu** [comment]
@uberhacker No. It has not. Hence please check it when you get a chance. The binaries are versioned 2.23-1 on purpose.

**Comment by uberhacker** [comment]
Unfortunately, I get segfaults.  See below:
```
chronos@localhost ~/chromebrew/packages (glibc %=)$ crew search glibc -v
glibc: The GNU C Library project provides the core libraries for GNU/Linux systems.
https://www.gnu.org/software/libc/
Version: 2.23-1
License: LGPL-2.1+, BSD, HPND, ISC, inner-net, rc, and PCRE
chronos@localhost ~/chromebrew/packages (glibc %=)$ gencat
Segmentation fault (core dumped)
chronos@localhost ~/chromebrew/packages (glibc %=)$ getent
Segmentation fault (core dumped)
chronos@localhost ~/chromebrew/packages (glibc %=)$ iconv
Segmentation fault (core dumped)
chronos@localhost ~/chromebrew/packages (glibc %=)$ locale
Segmentation fault (core dumped)
chronos@localhost ~/chromebrew/packages (glibc %=)$ makedb
Segmentation fault (core dumped)
```

**Comment by satmandu** [comment]
What does running /usr/local/lib/libc.so.6 give you?

**Comment by uberhacker** [comment]
```
chronos@localhost ~/chromebrew/packages (glibc %=)$ /usr/local/lib/libc.so.6
GNU C Library (GNU libc) stable release version 2.23, by Roland McGrath et al.
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 11.1.0.
Available extensions:
        crypt add-on version 2.1 by Michael Glad and others
        GNU Libidn by Simon Josefsson
        Native POSIX Threads Library by Ulrich Drepper et al
        BIND-8.2.3-T5B
libc ABIs: UNIQUE IFUNC
For bug reporting instructions, please see:
<https://github.com/skycocker/chromebrew/issues/new>.
```

**Comment by satmandu** [comment]
Try setting LD_LIBRARY_PATH manually and running the glibc apps?

**Comment by uberhacker** [comment]
Set `LD_LIBRARY_PATH` to what?  It's already set to `/usr/local/lib`.

**Comment by satmandu** [comment]
> Set `LD_LIBRARY_PATH` to what?  It's already set to `/usr/local/lib`.

Was just checking to make sure it was set to that...

**Comment by satmandu** [comment]
I still think this is useful @uberhacker , as it also helps with builds of later glibc for other archs...

**Comment by uberhacker** [comment]
Shouldn't this PR have new binaries for armv7l and x86_64?

**Comment by satmandu** [comment]
> Shouldn't this PR have new binaries for armv7l and x86_64?

I believe this needs a build for i686 first.  I'll get to that early next week, probably...

**Comment by satmandu** [comment]
This works on i686. Now rebuilding glibc 2.27 on armv7l & x86_64. Plan is to leave glibc 2.32 build as is.

**Comment by satmandu** [comment]
FYI the armv7l & x86_64 builds would lock up during tests..

**Pull request closed without merging**
