### PR TITLE
Update jdk8 package

### PR DESCRIPTION
**Pull request by uberhacker**
Fix for issue #763.

### CODE REVIEW

**Comment by thedamian** [comment]
Again, or either my python is not up to snuff (possibly)

or you're just making a directory called /usr/local/usr/local and copying all the JDK8 stuff up there in this line:
    system "mkdir -p #{CREW_DEST_DIR}/usr/local"

am I wrong?

**Comment by uberhacker** [comment]
My understanding is crew will copy everything in `#{CREW_DEST_DIR}/usr/local` to the actual `/usr/local` directory during install.  This is what I needed to do to get it to actually install on my system.  Did you experience the same issue I did as explained in issue #763?

**Comment by thedamian** [comment]
I was just under the impression that #{CREW_DEST_DIR} represented "/usr/local"

If I'm write then you'll create a diretory called:
/usr/local/usr/local

and install java there.

there but there they won't be able to be called.

That's all I'm saying. I'm ok if my new JDK doesn't work. and I REALLY appriciate the help fixing it. BUT I don't think your code will put the files in the correct place unless I don't understand python correctly (which Very well may be true)

**Comment by uberhacker** [comment]
Actually, if you look at the defined constants at the top of the `crew` source, `CREW_DEST_DIR` is `/usr/local/tmp/crew/dest`.  When you install a package, all files that are extracted here will be tracked in `<package>.directorylist` and `<package>.filelist` in `/usr/local/etc/crew/meta` so they can be uninstalled cleanly.  Did you test this PR yet to see if it installs without error?

**Comment by thedamian** [comment]
I did not test this PR. 
I'll test it when I get home. 

Thank you for the fix. I appreciate it.

**Pull request merged**
