### PR TITLE
Adding package zip

### PR DESCRIPTION
**Pull request by rmrfslashbin**
## Description
Adds the Zip package to Chromebrew
Works properly:
- [x] x86_64

### CODE REVIEW

**Comment by uberhacker** [comment]
@rmrfslashbin: Thank you for the new package but I'm wondering if this updates the zip executable from ChromeOS core.  See below:
```
```

**Comment by rmrfslashbin** [comment]
@uberhacker Odd... you have a zip binary in /usr/bin?

```
chronos@localhost ~ $ ls /usr/bin/zip
ls: cannot access '/usr/bin/zip': No such file or directory
chronos@localhost ~ $ mv /usr/local/bin/zip ~/
chronos@localhost ~ $ hash -r
chronos@localhost ~ $ which zip
which: no zip in (/usr/local/bin:/usr/bin:/bin:/opt/bin:/home/chronos/user/bin:/home/chronos/user/go/bin)
```

Curious... which ChromeOS build are you running? Mine:

```
chronos@localhost ~ $ cat /etc/os-release
BUILD_ID=10176.61.0
NAME=Chrome OS
ID_LIKE=chromiumos
GOOGLE_CRASH_ID=ChromeOS
VERSION_ID=64
BUG_REPORT_URL=https://crbug.com/new
VERSION=64
HOME_URL=https://www.chromium.org/chromium-os
ID=chromeos
```

**Comment by uberhacker** [comment]
```
$ uname -m
i686
$ cat /etc/lsb-release 
CHROMEOS_RELEASE_BOARD=x86-pentiumm
CHROMEOS_DEVSERVER=http://devserver.crosbuilder.click:44225
GOOGLE_RELEASE=9592.96.2017_09_20_2221
CHROMEOS_RELEASE_BUILD_NUMBER=9592
CHROMEOS_RELEASE_BRANCH_NUMBER=96
CHROMEOS_RELEASE_CHROME_MILESTONE=60
CHROMEOS_RELEASE_PATCH_NUMBER=2017_09_20_2221
CHROMEOS_RELEASE_TRACK=developer-build
CHROMEOS_RELEASE_DESCRIPTION=9592.96.2017_09_20_2221 (Developer Build - chromium) developer-build x86-pentiumm
CHROMEOS_RELEASE_NAME=Chromium OS
CHROMEOS_RELEASE_BUILD_TYPE=Developer Build - chromium
CHROMEOS_RELEASE_VERSION=9592.96.2017_09_20_2221
CHROMEOS_AUSERVER=http://update.crosbuilder.click:44225/update
```
Apparently, zip is not included in Pixelbooks?  Maybe we need the package after all.

**Comment by rmrfslashbin** [comment]
Seems to be the case. That'a an odd util to drop off a platform.

**Comment by uberhacker** [comment]
Even odder would be if you didn't have unzip either.  I'll go ahead and merge this while shaking my fist at the Google engineers.

**Pull request merged**
