### PR TITLE
Add package Qb64

### PR DESCRIPTION
**Pull request by superloach**
Hooray, I fixed my own issue! (#2569) 🤣

### CODE REVIEW

**Comment by uberhacker** [comment]
I tested this on a i686 Chrome OS VM and it looks like a BSOD (aka Black Screen of Death). LoL

screenshot 2018-08-20 at 3 45 50 pm

I'll try to test on armv7l and provide more feedback in a bit.

**Comment by superloach** [comment]
Hmm, that sucks. Perhaps @FellippeHeitor would know something about this?

Also, `x86_64` screenshots just for brags (`WIDTH` is weird and I'm out of practice, don't judge 😛)
image

**Comment by FellippeHeitor** [comment]
I'm glad to see it working! About the black screen, though: no idea.

**Comment by superloach** [comment]
I can't really tell much from that screenshot, but it appears that the Sommelier window doesn't have a "title" bar (even though it doesn't forward titles 😒). Stupid question, but will other GUI apps run properly in that VM?

**Comment by superloach** [comment]
If I had an i686 machine (or an easy way to emulate one), I'd be totally willing to maintain a fork for it. Unfortunately... *I don't.* 😅

**Comment by uberhacker** [comment]
Do you have a Windows or Mac or even Linux system?  You could run a VM like I have it set up.

**Comment by superloach** [comment]
We have our Windows 10 desktop, but it literally has the same specs as my Acer R11, it's sad.
I also have a broken Thinkpad T410, which I used to have Arch Linux on. Currently working on repairing that, in fact.

In short, not really no.

**Comment by JL2210** [comment]
@uberhacker, are you still using that crappy i686 VM from CrosBuilder?

**Comment by uberhacker** [comment]
Yes, unfortunately.  But it is the only VM I could get to work halfway decently.

**Pull request merged**
