### PR TITLE
Update git to 2.13.0

### PR DESCRIPTION
**Pull request by jam7**
It is not need to distribute binary packages, so I add source compile methods and update git to 2.13.0.

Tested on armv7l.

### CODE REVIEW

**Comment by thedamian** [comment]
Damn. I always forget.

I think we have issue3s updating GIT, and anything else in the original files that make the initial install.

am I wrong?

**Comment by jam7** [comment]
Thank you for the review.  You are partially wrong.  It was the problem before.  Recently, we modified install.sh to not use .rb file at install.  Install.sh extracts tar files directly.  Therefore, what we need now is to keep the original tar files of git/ruby/libssh2 as is and make new .rb files freely.  :)

**Comment by thedamian** [comment]
@jam7 thank you for the explanations.

I love it! 
I'm going to bring in the tars from dropbox (I think it's YOUR drop box, correct?) into github.

ANY OBJECTION on that?

ANd of course this is approved. I always want GIT updated.

**Comment by jam7** [comment]
@thedamian No objection. 
 git/ssh2/ruby binaries for armv7l are in my dropbox.  Others are in skycocker's?  I'm not sure.

**Pull request merged**
