### PR TITLE
Improve Chromebrew ascii art

### PR DESCRIPTION
**Pull request by uberhacker**

### CODE REVIEW

**Comment by saltedcoffii** [comment]
Unfortunately it doesn't seem to be rendering properly:
```
                       . .
                   ..,:;;;::'..
                 .':lllllllool,.
                ...cl;..... ,::;'.
               .'oc...;::::..0KKo.
               .'od: .:::::, lolc.
             .'lNMMMO ;ooc.,XMMWx;:;.
            .dMMMMMMXkMMMMxoMMMMMMMMO.
            .:O0NMMMMMMMMMM0MMMMMN0Oc.
              .:xdloddddddoXMMMk:x:....
              .xMNOKX0OOOOxcodlcXMN0O0XKc.
              .OMXOKXOOOOOk;ol:OXMK...;N0.
              'XMKOXXOOOOOk:docOKMW,  .kW;
             .cMMKOXXOOOOOOOOOOO0MM;  .lMc.
             .cMM00XKOOOOkkkkkkOOWMl. .cMo.
             .lMWO0XKOOOkkkkkkkkONMo.  ;Wk.
             .oMNO0X0OOkkkkkkkkkOXMd..,oW0'
             .xMNO0X0OOkkkkkkkkkkXMWKXKOx;.
             .0MXOOOOOOkkkkkkkkkOKM0..
             'NMWNXXKK000000KKXNNMMX.
             .;okk0XNWWMMMMWWNKOkdc'.
                .....'cc:cc:''...
 ___  _                               _
 / (_)| |                              ||     | |_    ,_    __   _  _  _    __ |/_   ,_    __  ,  ,  ,
|     |/  |  /  |  /  \_/ |/ |/ |  |_/ |  \_/  |  |_/ /|  |  |\_
 \___/|   |_/   |_/\__/   |  |  |_/|__/\__/    |_/|__/ \_/ \_/
```

**Comment by uberhacker** [comment]
> Unfortunately it doesn't seem to be rendering properly:
> 
> ```
>                        . .
>                    ..,:;;;::'..
>                  .':lllllllool,.
>                 ...cl;..... ,::;'.
>                .'oc...;::::..0KKo.
>                .'od: .:::::, lolc.
>              .'lNMMMO ;ooc.,XMMWx;:;.
>             .dMMMMMMXkMMMMxoMMMMMMMMO.
>             .:O0NMMMMMMMMMM0MMMMMN0Oc.
>               .:xdloddddddoXMMMk:x:....
>               .xMNOKX0OOOOxcodlcXMN0O0XKc.
>               .OMXOKXOOOOOk;ol:OXMK...;N0.
>               'XMKOXXOOOOOk:docOKMW,  .kW;
>              .cMMKOXXOOOOOOOOOOO0MM;  .lMc.
>              .cMM00XKOOOOkkkkkkOOWMl. .cMo.
>              .lMWO0XKOOOkkkkkkkkONMo.  ;Wk.
>              .oMNO0X0OOkkkkkkkkkOXMd..,oW0'
>              .xMNO0X0OOkkkkkkkkkkXMWKXKOx;.
>              .0MXOOOOOOkkkkkkkkkOKM0..
>              'NMWNXXKK000000KKXNNMMX.
>              .;okk0XNWWMMMMWWNKOkdc'.
>                 .....'cc:cc:''...
>  ___  _                               _
>  / (_)| |                              ||     | |_    ,_    __   _  _  _    __ |/_   ,_    __  ,  ,  ,
> |     |/  |  /  |  /  \_/ |/ |/ |  |_/ |  \_/  |  |_/ /|  |  |\_
>  \___/|   |_/   |_/\__/   |  |  |_/|__/\__/    |_/|__/ \_/ \_/
> ```

Huh?

**Comment by saltedcoffii** [comment]
It's not rendering properly again
```
                       . .
                   ..,:;;;::'..
                 .':lllllllool,.
                ...cl;..... ,::;'.
               .'oc...;::::..0KKo.
               .'od: .:::::, lolc.
             .'lNMMMO ;ooc.,XMMWx;:;.
            .dMMMMMMXkMMMMxoMMMMMMMMO.
            .:O0NMMMMMMMMMM0MMMMMN0Oc.
              .:xdloddddddoXMMMk:x:....
              .xMNOKX0OOOOxcodlcXMN0O0XKc.
              .OMXOKXOOOOOk;ol:OXMK...;N0.
              'XMKOXXOOOOOk:docOKMW,  .kW;
             .cMMKOXXOOOOOOOOOOO0MM;  .lMc.
             .cMM00XKOOOOkkkkkkOOWMl. .cMo.
             .lMWO0XKOOOkkkkkkkkONMo.  ;Wk.
             .oMNO0X0OOkkkkkkkkkOXMd..,oW0'
             .xMNO0X0OOkkkkkkkkkkXMWKXKOx;.
             .0MXOOOOOOkkkkkkkkkOKM0..
             'NMWNXXKK000000KKXNNMMX.
             .;okk0XNWWMMMMWWNKOkdc'.
                .....'cc:cc:''...
  ___  _                               _
 / (_)| |                              ||     | |_    ,_    __   _  _  _    __ |/_   ,_    __  ,  ,  ,
|     |/  |  /  |  /  \_/ |/ |/ |  |_/ |  \_/  |  |_/ /|  |  |\_
 \___/|   |_/   |_/\__/   |  |  |_/|__/\__/    |_/|__/ \_/ \_/
                                                                
```

**Comment by uberhacker** [comment]
> It's not rendering properly again
> 
> ```
>                        . .
>                    ..,:;;;::'..
>                  .':lllllllool,.
>                 ...cl;..... ,::;'.
>                .'oc...;::::..0KKo.
>                .'od: .:::::, lolc.
>              .'lNMMMO ;ooc.,XMMWx;:;.
>             .dMMMMMMXkMMMMxoMMMMMMMMO.
>             .:O0NMMMMMMMMMM0MMMMMN0Oc.
>               .:xdloddddddoXMMMk:x:....
>               .xMNOKX0OOOOxcodlcXMN0O0XKc.
>               .OMXOKXOOOOOk;ol:OXMK...;N0.
>               'XMKOXXOOOOOk:docOKMW,  .kW;
>              .cMMKOXXOOOOOOOOOOO0MM;  .lMc.
>              .cMM00XKOOOOkkkkkkOOWMl. .cMo.
>              .lMWO0XKOOOkkkkkkkkONMo.  ;Wk.
>              .oMNO0X0OOkkkkkkkkkOXMd..,oW0'
>              .xMNO0X0OOkkkkkkkkkkXMWKXKOx;.
>              .0MXOOOOOOkkkkkkkkkOKM0..
>              'NMWNXXKK000000KKXNNMMX.
>              .;okk0XNWWMMMMWWNKOkdc'.
>                 .....'cc:cc:''...
>   ___  _                               _
>  / (_)| |                              ||     | |_    ,_    __   _  _  _    __ |/_   ,_    __  ,  ,  ,
> |     |/  |  /  |  /  \_/ |/ |/ |  |_/ |  \_/  |  |_/ /|  |  |\_
>  \___/|   |_/   |_/\__/   |  |  |_/|__/\__/    |_/|__/ \_/ \_/
>                                                                 
> ```

How are you testing this?  Look at the diff.

**Comment by uberhacker** [comment]
How about now?

**Comment by uberhacker** [comment]
```
old:
 ___  _                               _
 / (_)| |                             | |
|     | |_    ,_    __   _  _  _    _ | |   ,_    _
|     |/  |  /  |  /  \_/ |/ |/ |  |/ |/ \_/  |  |/  |  |  |_
 \___/|   |_/   |_/\__/   |  |  |_/|__/\_/    |_/|__/ \/ \/
                                                             
new:
  ___  _                              _
 / (_)| \                             |\
|     | |_    ,_    __  __  _  _   __ |/_  ,_    __ _   _   _
|     |/  |  /  |  /  \/ |/ |/ |  |_/ |  \/  |  |_/ |   |   |\_
 \___/|   |_/   |_/\__/  |  |  |_/|__/\__/   |_/|__/ \_/ \_/

```

**Comment by uberhacker** [comment]
@saltedcoffii: Yay or nay?

**Comment by saltedcoffii** [comment]
if you can get your cursive to format correctly i like it.
i'm not a fan of the italics though

**Comment by uberhacker** [comment]
What do you mean about formatting correctly?  It renders fine.  So you are not a fan of `another:`?

**Comment by uberhacker** [comment]
@saltedcoffii: Is this good enough to merge?

**Comment by uberhacker** [comment]
@saltedcoffii: I made some more tweaks.  I see what you mean.

**Comment by satmandu** [comment]
There are so many options. :)  https://patorjk.com/software/taag/#p=display&f=Small%20Keyboard&t=Chromebrew

**Comment by satmandu** [comment]
Also: https://patorjk.com/software/taag/#p=testall&f=NScript&t=Chromebrew

**Review by satmandu — APPROVED** [review]
LGTM...

**Comment by uberhacker** [comment]
My favorites:
https://patorjk.com/software/taag/#p=display&f=Big%20Money-ne&t=Chromebrew
https://patorjk.com/software/taag/#p=display&f=Doom&t=Chromebrew
https://patorjk.com/software/taag/#p=display&f=Slant&t=Chromebrew
https://patorjk.com/software/taag/#p=display&f=Banner&t=Chromebrew
https://patorjk.com/software/taag/#p=display&f=JS%20Stick%20Letters&t=Chromebrew
https://patorjk.com/software/taag/#p=display&f=Stampatello&t=Chromebrew
https://patorjk.com/software/taag/#p=display&f=Stampatello&t=Chromebrew

**Comment by uberhacker** [comment]
@saltedcoffii: This PR is waiting on your blessing.  Please merge if you think it's ready.

**Comment by saltedcoffii** [comment]
> @saltedcoffii: This PR is waiting on your blessing. Please merge if you think it's ready.

the echo line doesn't look like it's misforming anymore, i grant my blessing :)

**Pull request merged**
