### PR TITLE
Patchelf -> 0.14.3

### PR DESCRIPTION
**Pull request by satmandu**
Works properly:
- [x] x86_64
- [x] armv7;
- [x] i686
### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=patchelf CREW_TESTING=1 crew update
```

### CODE REVIEW

**Comment by saltedcoffii** [comment]
Since we're linking this statically, should we be using musl?

**Comment by satmandu** [comment]
> Since we're linking this statically, should we be using musl?

We don't need to, so it appears. (But good thinking on this... a bunch of recent commits this past month to the patchelf repo indicate tweaks for building with musl!)

**Comment by saltedcoffii** [comment]
why don't we need to?

**Comment by satmandu** [comment]
`patchelf` as built here is already static. I think it's the more complicated programs which have huge problems with building statically with glibc.

**Comment by satmandu** [comment]
(I think generally if you need to pull in other non-libc libraries, then you need to use musl to make a static build.)

**Pull request merged**
