### PR TITLE
Update libssh2 package

### PR DESCRIPTION
**Pull request by JL2210**
Update to 1.8.1

### CODE REVIEW

**Comment by uberhacker** [comment]
I'm confused.  How does git have anything to do with this package?  This openssl 1.1.0 update has opened a Pandora's box of worms (or should I say bugs?).  I would rather wait until a stable version of this package.

**Comment by JL2210** [comment]
This is basically just preparing for the upgrade. If you don't mind, I'd like to keep it open so all the OpenSSL related pull requests can be merged at once.

**Comment by uberhacker** [comment]
OK, but these kinds of updates tend to have a cascading effect to break everything.  If understand correctly, the intention here is to remove the dependency from git?

**Comment by JL2210** [comment]
It's more of a "Kill two birds with one stone" deal, but yes.

**Comment by JL2210** [comment]
Can this be merged? It doesn't break anything.

**Comment by uberhacker** [comment]
Except the install?  Did you forget this is still a dependency in install.sh?  We would also need binaries for all architectures since this is a core package.  If you plan on removing the git dependency, wouldn't we also need an updated git?  All these things would then need to be updated in install.sh.

**Comment by JL2210** [comment]
Can you add binaries, then? It still works with the old OpenSSL.

**Comment by uberhacker** [comment]
See https://github.com/skycocker/chromebrew/pull/3151#issuecomment-464517728.

**Comment by JL2210** [comment]
This enables static archives and paves the way to upgrading OpenSSL to 1.1.1. It's not causing any harm.

**Comment by uberhacker** [comment]
Or so you think.  There must be a reason they haven't released a stable version yet.  Maybe because it's still unstable?

**Comment by JL2210** [comment]
Nah, probably just really sparse release timing.

**Comment by JL2210** [comment]
Stable version was released recently, please merge.

**Comment by uberhacker** [comment]
This is more like it.  I'll try and build the binaries first since this is a core package.

**Comment by skiman6010** [comment]
Good work on the fast update everyone!

**Pull request merged**
