### PR TITLE
Fix ISL compatibility symlink

### LINKED ISSUE #2567: [isl] dangling symlink in package
Hello,

Package isl on arm has a dangling symlink: `/usr/local/lib/libisl.so.15`. That does not seem to create any issues (so far), so just a heads-up.

## Versions and system information
chromebrew: 1.0.3

ChromeOS:
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=4856647
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={AAE972E1-A913-C860-B7AB-BF7F267F199B}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={AAE972E1-A913-C860-B7AB-BF7F267F199B}
CHROMEOS_RELEASE_BOARD=hana-signed-mp-v4keys
CHROMEOS_RELEASE_BRANCH_NUMBER=58
CHROMEOS_RELEASE_BUILDER_PATH=hana-release/R67-10575.58.0
CHROMEOS_RELEASE_BUILD_NUMBER=10575
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=67
CHROMEOS_RELEASE_DESCRIPTION=10575.58.0 (Official Build) stable-channel hana 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=10575.58.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10575.58.0

Model: Lenovo Chromebook N23 Yoga

Architecture: aarch64

### LINKED ISSUE #2569: QB64: 32- and 64-bit BASIC Compiler and IDE
I've been attempting to compile QB64, with little success.

I modified the install script to use `bash setup_build.sh` instead of `./setup_build.sh`, and that fixed some initial errors. But now I keep getting this error, which is obviously related to #2567:
```
/usr/local/libexec/gcc/x86_64-cros-linux-gnu/4.9.4/cc1: error while loading shared libraries: libisl.so.15: cannot open shared object file: No such file or directory
```
Hopefully we can get that fixed, because I'd love to mess around with some of my old programs 😝

(p.s. - there's an SDL version of QB64 as well, in case there are graphical issues in future)

### PR DESCRIPTION
**Pull request by JL2210**
Fixes #2569 
Fixes #2567 
Changes the symlink in the ISL package.
From `libisl.so.15` => `libisl.so.20` to `libisl.so.15` => `libisl.so.19.1.0`

### CODE REVIEW

**Comment by uberhacker** [comment]
Thank you for the PR @JL2210 but we obviously can't merge this without pre-built binaries or it will break the compiler.  Do you want to take a shot at creating the new binaries?  Hopefully, you still have the step-by-step instructions I sent you a few days ago.

**Comment by JL2210** [comment]
Sure. QEMU, here I come.

**Comment by JL2210** [comment]
BTW, QEMU has a new stable version: 3.0.0.

**Comment by uberhacker** [comment]
Sounds like your next project. ;)

**Comment by JL2210** [comment]
@uberhacker: When I try to unzip the .7z file provided by ATB with p7zip, m Chromebook crashes. Any suggestions?

**Comment by uberhacker** [comment]
Sounds like maybe your disk is full?  What is the output of `df -h`?

**Comment by JL2210** [comment]
It crashes at 50%

**Comment by JL2210** [comment]
```
Filesystem               Size  Used Avail Use% Mounted on
/dev/root                1.7G  1.7G   63M  97% /
devtmpfs                 2.0G     0  2.0G   0% /dev
tmp                      2.0G  164K  2.0G   1% /tmp
run                      2.0G  684K  2.0G   1% /run
shmfs                    2.0G   29M  1.9G   2% /dev/shm
/dev/mmcblk0p1            25G   19G  5.0G  79% /mnt/stateful_partition
/dev/mmcblk0p8            12M   28K   12M   1% /usr/share/oem
/dev/mapper/encstateful  7.3G  128M  7.1G   2% /mnt/stateful_partition/encrypted
media                    2.0G     0  2.0G   0% /media
none                     2.0G     0  2.0G   0% /sys/fs/cgroup
imageloader              2.0G     0  2.0G   0% /run/imageloader
tmpfs                    2.0G  4.0K  2.0G   1% /run/arc/oem
tmpfs                    2.0G     0  2.0G   0% /run/arc/sdcard
tmpfs                    2.0G     0  2.0G   0% /run/arc/obb
tmpfs                    2.0G     0  2.0G   0% /run/arc/media
tmpfs                    2.0G     0  2.0G   0% /run/arc/adbd
/dev/fuse                 25G   19G  5.0G  79% /run/arc/sdcard/default/emulated
/dev/fuse                 25G   19G  5.0G  79% /run/arc/sdcard/read/emulated
/dev/fuse                 25G   19G  5.0G  79% /run/arc/sdcard/write/emulated
passthrough              2.0G     0  2.0G   0% /run/arc/media/removable
```

**Comment by uberhacker** [comment]
How big is the .7z file?  Looks like you "only" have 5 gb available.

**Comment by JL2210** [comment]
That's  enough. A lot of times it fails on 40.

**Comment by JL2210** [comment]
The file itself is only 400MB. The file inside is 4.8GB.

**Comment by uberhacker** [comment]
400 mb + 4.8 gb > 5.0 gb

**Comment by JL2210** [comment]
Sorry. I had the broken file still on the fs. 
```
Filesystem               Size  Used Avail Use% Mounted on
/dev/root                1.7G  1.7G   63M  97% /
devtmpfs                 2.0G     0  2.0G   0% /dev
tmp                      2.0G  164K  2.0G   1% /tmp
run                      2.0G  684K  2.0G   1% /run
shmfs                    2.0G   11M  1.9G   1% /dev/shm
/dev/mmcblk0p1            25G   16G  7.9G  67% /mnt/stateful_partition
/dev/mmcblk0p8            12M   28K   12M   1% /usr/share/oem
/dev/mapper/encstateful  7.3G  128M  7.1G   2% /mnt/stateful_partition/encrypted
media                    2.0G     0  2.0G   0% /media
none                     2.0G     0  2.0G   0% /sys/fs/cgroup
imageloader              2.0G     0  2.0G   0% /run/imageloader
tmpfs                    2.0G  4.0K  2.0G   1% /run/arc/oem
tmpfs                    2.0G     0  2.0G   0% /run/arc/sdcard
tmpfs                    2.0G     0  2.0G   0% /run/arc/obb
tmpfs                    2.0G     0  2.0G   0% /run/arc/media
tmpfs                    2.0G     0  2.0G   0% /run/arc/adbd
/dev/fuse                 25G   16G  7.9G  67% /run/arc/sdcard/default/emulated
/dev/fuse                 25G   16G  7.9G  67% /run/arc/sdcard/read/emulated
/dev/fuse                 25G   16G  7.9G  67% /run/arc/sdcard/write/emulated
passthrough              2.0G     0  2.0G   0% /run/arc/media/removable
```

**Comment by uberhacker** [comment]
If space is not the issue then maybe try a fresh crew install?  Are you running Chrome OS release 67 (aka stable)?

**Comment by JL2210** [comment]
Yes. I will.

**Comment by JL2210** [comment]
Though, it worked before.

**Comment by JL2210** [comment]
After stripping my chroot's gcc, here it is.

**Comment by JL2210** [comment]
```
Filesystem               Size  Used Avail Use% Mounted on
/dev/root                1.7G  1.7G   63M  97% /
devtmpfs                 2.0G     0  2.0G   0% /dev
tmp                      2.0G  164K  2.0G   1% /tmp
run                      2.0G  684K  2.0G   1% /run
shmfs                    2.0G   12M  1.9G   1% /dev/shm
/dev/mmcblk0p1            25G   14G  9.4G  60% /mnt/stateful_partition
/dev/mmcblk0p8            12M   28K   12M   1% /usr/share/oem
/dev/mapper/encstateful  7.3G  128M  7.1G   2% /mnt/stateful_partition/encrypted
media                    2.0G     0  2.0G   0% /media
none                     2.0G     0  2.0G   0% /sys/fs/cgroup
imageloader              2.0G     0  2.0G   0% /run/imageloader
tmpfs                    2.0G  4.0K  2.0G   1% /run/arc/oem
tmpfs                    2.0G     0  2.0G   0% /run/arc/sdcard
tmpfs                    2.0G     0  2.0G   0% /run/arc/obb
tmpfs                    2.0G     0  2.0G   0% /run/arc/media
tmpfs                    2.0G     0  2.0G   0% /run/arc/adbd
/dev/fuse                 25G   14G  9.4G  60% /run/arc/sdcard/default/emulated
/dev/fuse                 25G   14G  9.4G  60% /run/arc/sdcard/read/emulated
/dev/fuse                 25G   14G  9.4G  60% /run/arc/sdcard/write/emulated
passthrough              2.0G     0  2.0G   0% /run/arc/media/removable
```
Still doesn't work.

**Comment by uberhacker** [comment]
Dunno what to tell you then.  Maybe the p7zip package needs updated?

**Comment by JL2210** [comment]
@uberhacker, now QEMU fails with `***stack smashing detected. aborting...***`.

**Comment by JL2210** [comment]
Thanks.

**Pull request merged**
