### PR TITLE
	new file:   packages/screen.rb

### PR DESCRIPTION
**Pull request by alexzapatka**
adds gnu screen as a package...  works if you run it as sudo, still trying to get it to work under chronos user... but it is a start.

### CODE REVIEW

**Comment by lyxell** [comment]
This works for me without sudo, what error message do you get?

**Comment by alexzapatka** [comment]
the output i get is this:

`chronos@localhost ~/src/chromebrew/packages $ screen`
`/var/run/utmp: No such file or directory`
`[screen is terminating]`

from what i can tell, it is because the chronos user has not write access to the /var/run directory.  screen is trying to create a socket utmp and it fails.  i have tried different configure options to not use /var/run but every time i get this message.

i am on the latest chromeos beta channel.  acer c720.

**Comment by skycocker** [comment]
@lyxell did you mount your partition rw or change the ownership of `/var/run/utmp` in any way?

**Comment by lyxell** [comment]
@skycocker No, it's on a fresh install.

**Comment by alexzapatka** [comment]
Okay.. let me say 1), I am a bit of an idiot here, 2) there is a bug, but not in screen, but probably in ChromeOS somewhere. 

I have done a bit more debugging/playing and here is what I have found:

On my c720's ChromeOS install there is no utmp file at all.  It doesn't exist.  If I create it per spec, the utmp error at screen start up goes away, but screen still terminates right away.

If I run screen followed by a command as the chronos user, (instead of just screen to get a shell), screen works! (Sort of- I type screen nano, I get nano up.  I can ctrl-a,d and suspend it and then reconnect to it later... but I cannot ctrl-a,c to create another instance of nano on another pty.  And if I run screen bash or screen sh, it terminates right away).

If I run screen as root (sudoku screen) I get a shell prompt, and I can create other virtual windows just fine with ctrl-a,c.  So either there is a bug in ChromeOS somewhere, or there is a permission problem somewhere.  And I have compiled screen using the socket dir as ~/.screen/ and it has not made a difference.  It could be a perm issue with /dev/pty, I'm not sure.  But it only seems to affect the shell functionality. 

Anyway, hope this sheds some light.

**Comment by thedamian** [comment]
So are we good here? is this merg-able?

**Comment by lyxell** [comment]
@thedamian I'm pretty sure it works, but as alexzpatka said, there was an permission issue (not sure if it's still there) in chromeos making the application fail at runtime under certain circumstances.

**Comment by thedamian** [comment]
@lyxell then I don't think we should merge it yet right?

**Comment by lyxell** [comment]
@thedamian I guess it would be a good idea to test it again first, now when a couple of months has passed.

**Comment by alexzapatka** [comment]
This is definitely mergable.  I have been using it since I I was told what was the issue.  One of the prebuilt packages that came with chromebrew is incompatible with screen.  Readline either has issues or is just incompatible.  When I downloaded the latest readline sourve, compiled from scratch, and installed, screen started to work flawlessly.  I have had no issues with all the new chromos versions since then.

**Comment by thedamian** [comment]
DONE! It's merged.

**Pull request merged**
