### PR TITLE
Add x86_64 binaries for dpkg package

### PR DESCRIPTION
**Pull request by JL2210**
Tested on x86_64 :)

### CODE REVIEW

**Comment by uberhacker** [comment]
If you can't create all the binaries, please do not submit a PR.

**Comment by JL2210** [comment]
I can't create the ARM binaries, because I don't have an ARM Chromebook, and I can't create an i686 binary because my USB broke. Why?

**Comment by uberhacker** [comment]
I want to include all the binaries or none.  I'll see if I can create binaries for all architectures.

**Comment by uberhacker** [comment]
Just so you are not in the dark about me reasons for an all or nothing approach, I want to make sure if there are any issues building the binaries for a certain architecture that those are addressed in the source for future builds.

**Comment by JL2210** [comment]
Oh, that's fine.

**Pull request closed without merging**
