### PR TITLE
Added icu4c as a dependency for R package (#1629)

### LINKED ISSUE #1629: shared library: libicuuc missing but required for R
## Description

After running `crew install r`, when running the `R` command, I am getting this error: 

If you executed a specific command:
command being run: ```R```

Output:
```/usr/local/lib64/R/bin/exec/R: error while loading shared libraries: libicuuc.so.60: cannot open shared object file: No such file or directory```

## Versions and system information
crew: `0.4.3`

ChromeOS: ```
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=4505339
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={7B2FC5AC-894A-5702-D00E-62E999F0AE22}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={7B2FC5AC-894A-5702-D00E-62E999F0AE22}
CHROMEOS_RELEASE_BOARD=asuka-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=75
CHROMEOS_RELEASE_BUILDER_PATH=asuka-release/R63-10032.75.0
CHROMEOS_RELEASE_BUILD_NUMBER=10032
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=63
CHROMEOS_RELEASE_DESCRIPTION=10032.75.0 (Official Build) stable-channel asuka 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=10032.75.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10032.75.0```

Model: Dell Chromebook 13

Architecture: `x86_64`

I am not sure if this is a missing dependency? It looks like this package is not already included in chromebrew, but I am not sure if others have been able to use R without this by changing configuration or something?

### PR DESCRIPTION
**Pull request by zacharysang**
Fixes #1629 

## Description
Issue existed where R could not run because of missing libicuuc shared library. This fix adds icu4c as a dependency for R which makes this shared library available

Works properly:
- [x] x86_64
- [ ] aarch64 (untested)

### CODE REVIEW

**Comment by uberhacker** [comment]
Thank you for the update @zacharysang.  Can you please remove the binaries and bump the version?  Also, this is minor but you could simplify the following line:
```
- if `uname -m`.strip == 'x86_64'
+ if ARCH == 'x86_64'
```
Thanks

**Comment by zacharysang** [comment]
Hey, I've bumped the least significant version and simplified that one line, but am unsure what you mean by removing the binaries?

**Comment by uberhacker** [comment]
The following section should be removed.
```
 binary_url ({
     aarch64: 'https://dl.bintray.com/chromebrew/chromebrew/r-3.4.3-chromeos-armv7l.tar.xz',
      armv7l: 'https://dl.bintray.com/chromebrew/chromebrew/r-3.4.3-chromeos-armv7l.tar.xz',
        i686: 'https://dl.bintray.com/chromebrew/chromebrew/r-3.4.3-chromeos-i686.tar.xz',
      x86_64: 'https://dl.bintray.com/chromebrew/chromebrew/r-3.4.3-chromeos-x86_64.tar.xz',
   })
   binary_sha256 ({
     aarch64: '49a5b66353b19c4078daa3081819348f391949dfaea74b25a4a08c15fe6b0d58',
      armv7l: '49a5b66353b19c4078daa3081819348f391949dfaea74b25a4a08c15fe6b0d58',
        i686: 'b3ef1c5ee0c69f8da1dda0292299df1ffc6692c63198a87fe7add6a8bcecd84c',
      x86_64: '997022827cf2709da1c76ab9ffbefcec6f5be21df2a72b1c33c2a797a77dcead',
   })
```
For the version, you should not change the least significant digit.  Instead, do something like below:
```
- version '3.4.3'
+ version '3.4.3-1'
```
Thanks

**Comment by zacharysang** [comment]
@uberhacker Do I need to do anything to replace these binaries?

**Comment by uberhacker** [comment]
@zacharysang: Don't worry about the binaries.  I'll include this package in the next batch.

**Comment by uberhacker** [comment]
The docs are located at https://github.com/skycocker/chromebrew/tree/master/tools.  You need an account on bintray and all uploads require an api key.  If you are interested, I can send you an invite to join.

**Comment by zacharysang** [comment]
Thanks for this! I am just interested in reading about it for now. Thanks for the offer though :)

**Pull request merged**
