### PR TITLE
Fix pulseaudio to avoid dependency loop

### PR DESCRIPTION
**Pull request by uberhacker**
This fixes the dependency loop issue @JL2210.

### CODE REVIEW

**Comment by JL2210** [comment]
Thanks :)

**Comment by JL2210** [comment]
Did you check if there were bindings to alsa_plugins in pulseaudio? Should you rebuild the binaries?

**Comment by uberhacker** [comment]
I think it's fine for now.  Can you test if pulseaudio kills your sound again?

**Comment by JL2210** [comment]
It's working now. I think it was either the codecs that were messing with my sound, or the fact that my Chromebook was so full of junk that it needed a Powerwash.

**Comment by uberhacker** [comment]
After taking out the dependency, the build no longer has alsa bindings so I just made it a build dependency in order to prevent the dependency loop.  This should be ready to merge @skiman6010.

**Comment by JL2210** [comment]
Wouldn't that still cause a dependency loop if you're trying to build from source?

**Comment by uberhacker** [comment]
It builds fine after fresh Chromebrew install.  No dependency looping.

**Comment by JL2210** [comment]
Also, a binary is still linked to a library whether the library is there or not, so... rebuild.
Take this for example:
```
chronos@localhost ~/Downloads $ cat a.c
extern int lol(int argc, char **argv);

int main(int argc, char **argv)
{
        lol(argc,argv);
        return 0;
}
chronos@localhost ~/Downloads $ cat liba.c
#include <stdio.h>

int lol(int argc, char **argv)
{
        printf("%s", argv[1]);
        return 0;
}
chronos@localhost ~/Downloads $ ldd a 
        linux-vdso.so.1 (0x00007ffe539c8000)
        liba.so => ***not found***
        libc.so.6 => /usr/local/lib64/libc.so.6 (0x00007c861b5e7000)
        /lib64/ld-linux-x86-64.so.2 (0x00007c861b992000)
chronos@localhost ~/Downloads $ ldd liba.so
        linux-vdso.so.1 (0x00007ffd0bfd9000)
        libc.so.6 => /usr/local/lib64/libc.so.6 (0x00007fcac48a3000)
        /usr/local/lib64/ld-linux-x86-64.so.2 (0x00007fcac4c4e000)
chronos@localhost ~/Downloads $ ./a
./a: error while loading shared libraries: liba.so: cannot open shared object file: No such file or directory
```

**Comment by uberhacker** [comment]
No need to rebuild.  The binary will be the same.

**Comment by JL2210** [comment]
OK.

**Pull request merged**
