### PR TITLE
Update golang package

### PR DESCRIPTION
**Pull request by idvoretskyi**
Updated golang package to the latest version.

### CODE REVIEW

**Comment by thedamian** [comment]
You have to update the sha1sum as well

Here it is:
09232AC0E76635CC9E0A1F33A81BF03AE9CB9DB5

**Comment by idvoretskyi** [comment]
@thedamian done, thank you.

**Comment by thedamian** [comment]
@idvoretskyi  Looks perfect now. I'll test it when I get home but I'm pretty sure it's ready to merge. 

P.S. I'm don't have any kind of authority of course, but it looks good to me.

**Comment by idvoretskyi** [comment]
@thedamian please, provide your updates. Thank you!

**Comment by seriv** [comment]
First, the build process for golang >= 1.5.x requires having go1.4.x for bootstrapping.
Also, sha1sum is compared by the 'crew' with case-sensitive '==' operator, the value proposed by @theadmin will not match.

**Comment by thedamian** [comment]
@idvoretskyi unfortunately I can't provide a test since I'm getting the segment fault with the crew command. I think this was introduced my a chrome update (I'm still on 51) or with playing with ldconfig

2) as for the sha since I copied it from a windows utility and all that is wrong is that it's in upper case that can be fixed quickly or by running the sha1sum command on a Linux machine.

3) there's no way the "all.build" command uses go Lang to build go lang... Are you sure?

**Comment by idvoretskyi** [comment]
Closed due to the comments above - have to be improved. Unfortunately, I can do that not now.

**Pull request closed without merging**
