### PR TITLE
libcurl -> 7.78.0

### PR DESCRIPTION
**Pull request by satmandu**
- Just an update of non-static libcurl
- needs armv7l, i686 builds

Works properly:

- [x] armv7l
- [x] i686
- [x] x86_64

### CODE REVIEW

**Comment by uberhacker** [comment]
Are the arm and i686 builds coming later?

**Comment by satmandu** [comment]
Not doing i686 builds any more... Will get a armv7l build on there
tomorrow...

**Comment by satmandu** [comment]
FYI this may now depend upon https://github.com/skycocker/chromebrew/pull/6129

**Comment by satmandu** [comment]
This should be good to merge?

**Comment by uberhacker** [comment]
I held off because of the libssh dependency.  Wanted to make sure that was added first.

**Pull request merged**
