### PR TITLE
Update python27 from 2.7.13-2 to 2.7.14

### PR DESCRIPTION
**Pull request by uberhacker**

### CODE REVIEW

**Comment by cstrouse** [comment]
Fails to build on Samsung Chromebook Plus (aarch64).

```bash
(cd /usr/local/tmp/crew/dest/usr/local/share/man/man1; ln -s python2.1 python.1)
if test "xinstall" != "xno"  ; then \
        case install in \
                upgrade) ensurepip="--upgrade" ;; \
                install|*) ensurepip="" ;; \
        esac; \
        LD_LIBRARY_PATH=/usr/local/tmp/crew/Python-2.7.14.tar.xz.dir/Python-2.7.14:/usr/local/lib ./python -E -m ensurepip \
                $ensurepip --root=/usr/local/tmp/crew/dest/ ; \
fi
Traceback (most recent call last):
  File "/usr/local/tmp/crew/Python-2.7.14.tar.xz.dir/Python-2.7.14/Lib/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/tmp/crew/Python-2.7.14.tar.xz.dir/Python-2.7.14/Lib/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/tmp/crew/Python-2.7.14.tar.xz.dir/Python-2.7.14/Lib/ensurepip/__main__.py", line 4, in <module>
    ensurepip._main()
  File "/usr/local/tmp/crew/Python-2.7.14.tar.xz.dir/Python-2.7.14/Lib/ensurepip/__init__.py", line 142, in _main
    import argparse
  File "/usr/local/tmp/crew/Python-2.7.14.tar.xz.dir/Python-2.7.14/Lib/argparse.py", line 86, in <module>
    import copy as _copy
  File "/usr/local/tmp/crew/Python-2.7.14.tar.xz.dir/Python-2.7.14/Lib/copy.py", line 52, in <module>
    import weakref
  File "/usr/local/tmp/crew/Python-2.7.14.tar.xz.dir/Python-2.7.14/Lib/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
make: *** [Makefile:920: install] Error 1
python27 failed to install: `make DESTDIR=/usr/local/tmp/crew/dest install` exited with 2
```

**Comment by cstrouse** [comment]
That fixes the _remove_dead_weakref error but now _ctypes fails to build.

**Comment by uberhacker** [comment]
I don't have any install issues on x86_64, i686 or armv7l.  Could this be another aarch64 specific issue?  In any event, I hate how this package installs.  I'll continue to work on it.

**Comment by cstrouse** [comment]
Do you have both Python versions installed when you try to upgrade one?

**Comment by uberhacker** [comment]
Yeah, it works fine.  I didn't notice any install issues.  Just retested on armv7l just to make sure.

**Comment by thedamian** [comment]
are we good to go? That chromebook plus is a HOT seller. 
(I got the pro which you don't have worry about, but everyone's getting the plus!)

**Comment by uberhacker** [comment]
@thedamian: We should hold off until we can figure out what's the deal with `-L#{CREW_PREFIX}/lib`.  We might need `-L#{CREW_LIB_PREFIX}` instead.  I'll do some more testing and then I'll let you know.
Thanks

**Comment by uberhacker** [comment]
The new Pixelbook is out now also.

**Comment by uberhacker** [comment]
@thedamian: I think this is ready now.  Go ahead and merge when you get a chance.

**Pull request merged**
