### PR TITLE
Some Adds and Fixes

### PR DESCRIPTION
**Pull request by beliefless-dogmasless**
Hy,

Some Adds and Fixes.

### CODE REVIEW

**Comment by uberhacker** [comment]
Wow, this is an epic commit @beliefless-dogmasless!  I really appreciate your effort.  Can you please remove the homepage url from the description in all packages?  We also need the homepage to accurately locate the correct project page.  Please do not include any urls with `download` or `releases` in the path or domain.  Also, we really need to concentrate on getting the `gtk3` package issue resolved since so many of these packages have this dependency.  Once we get all the "foundation" packages to compile without errors, then we can merge these.

**Comment by beliefless-dogmasless** [comment]
@uberhacker
"remove the homepage url from the description in all packages? "

...'I've already done that', but that "bloody github" seems to have hiccups, sometimes. I'm doing 'it again'.

- "we really need to concentrate on getting the gtk3 package issue resolved"
I "still" 'try to understand', why some software launch and others don't:

Geany: cannot open display
Could not parse arguments: Cannot open display:

and why 'even I have not installed weston', and some packages launch themselves.

**Comment by uberhacker** [comment]
Try creating a whole new branch.  It's probably conflicting with your previous branch.  You really should not be using the master branch anyway.  That should be kept as pristine as possible so you can sync with the upstream master branch.  Branching is a basic fundamental concept that should be used often in git.

**Comment by beliefless-dogmasless** [comment]
- Changes 'made' 'in addresses'.

- You 'already' 'told' me about, creating a branch, you mean 'what' by that ?

**Comment by beliefless-dogmasless** [comment]
I 'just saw' that:
https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/

So, I create, a branch, from the master branch, then I "pull the requests" "from that" ?

**Comment by uberhacker** [comment]
The basic workflow should work like this if you started from scratch:
1. Fork this repo into your own Github project
2. Clone the forked repo locally
3. Add a remote to your local repo that points back at this project
4. For each new PR, create a separate branch from master
5. Make changes and commit locally
6. Push your changes up to your own Github project using this separate PR branch
7. Submit a PR to this project from your own Github project

The equivalent commands in code (assuming you already forked this repo):
```
$ git clone git@github.com:beliefless-dogmasless/chromebrew.git
$ cd chromebrew
$ git remote add chromebrew git@githsgit@github.com:skycocker/chromebrew.gitub.com:skycocker/chromebrew.git
$ git checkout --branch my-new-pr-branch (you can call this anything you like)
... changes ...
$ git add -A
$ git commit -m "Message describing your changes"
$ git push beliefless-dogmasless my-new-pr-branch
See step 7. above.
```
When you want to work on a new PR:
```
$ cd /path/to/chromebrew
$ git checkout master
$ git pull chromebrew master
$ git checkout --branch ...
```

**Comment by beliefless-dogmasless** [comment]
I'm gonna try to meditate/and understand it, fully, for the next time.

**Comment by uberhacker** [comment]
If you follow these steps, you will avoid many potential conflicts.

**Comment by beliefless-dogmasless** [comment]
Just to notice, I figured out, that applications, need to 'be compiled with gtk3 option", otherwise with 2.24(gtk), they won't start.

autogen.sh --enable-gtk3
or if no autogen:
configure --enable-gtk3

**Comment by uberhacker** [comment]
What about https://github.com/skycocker/chromebrew/issues/1974?  We need that issue resolved or nothing that includes `gtk3` as a dependency will work.

**Comment by beliefless-dogmasless** [comment]
I 'must say I haven't upgraded' crew 'since the last "few days", I powerashed the chromebook this weekend and had to install it 'again'. Now, I'm gonna do some backup of usr/local.
I will check with the update, and see "that issue" [ https://github.com/skycocker/chromebrew/issues/1974 ]

**Comment by lovedheart** [comment]
@beliefless-dogmasless you don't need to powerash the chromebook.  You need just 

**#!/bin/bash
sudo dev_install --reinstall -y
curl -Ls git.io/vddgY | bash**

**Comment by beliefless-dogmasless** [comment]
Yes, I know lovedheart, but I was trying 'to put/activate again' 'portage'(from gentoo), in chromeos, and it completely messed up 'the system'.

**Comment by uberhacker** [comment]
@beliefless-dogmasless: @lovedheart is correct.  Don't worry about the portage stuff.  Every Chromebook that I've used has had trouble rebuilding that.  You can just ignore and even `Ctrl + C` on the first download attempt.

**Comment by beliefless-dogmasless** [comment]
@uberhacker:
I don't give up, totally the idea, not 'the first time' I tried, and some others, are trying to do the same. It was on the 'stupid idea' of google to remove a package manager, it makes 'no sense', but the dvpt of google makes 'no sense'.

**Comment by uberhacker** [comment]
@beliefless-dogmasless: I would suggest you close this PR also and submit each package update as a separate PR.

**Comment by uberhacker** [comment]
Closing due to inactivity.

**Pull request closed without merging**
