### PR TITLE
Add moreutils package

### PR DESCRIPTION
**Pull request by uberhacker**
moreutils is a growing collection of the unix tools that nobody thought to write long ago when unix was young.

chronic: runs a command quietly unless it fails
combine: combine the lines in two files using boolean operations
errno: look up errno names and descriptions
ifdata: get network interface info without parsing ifconfig output
ifne: run a program if the standard input is not empty
isutf8: check if a file or standard input is utf-8
lckdo: execute a program with a lock held
mispipe: pipe two commands, returning the exit status of the first
parallel: run multiple jobs at once
pee: tee standard input to pipes
sponge: soak up standard input and write to a file
ts: timestamp standard input
vidir: edit a directory in your text editor
vipe: insert a text editor into a pipe
zrun: automatically uncompress arguments to command

See https://joeyh.name/code/moreutils/.

### CODE REVIEW

**Comment by thedamian** [comment]
Talk to be @uberhacker 

what am I doing wrong. Exited with the latest error

moreutils_0.60.orig.tar.xz         100%[================================================================>]  77.50K  --.-KB/s    in 0.05s   

2017-06-18 22:08:17 (1.49 MB/s) - 'moreutils_0.60.orig.tar.xz' saved [79360/79360]

Archive downloaded
Unpacking archive, this may take a while...
gcc (GCC) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
make -C is_utf8/
cc -O2 -g -Wall    ifdata.c   -o ifdata
cc -O2 -g -Wall    ifne.c   -o ifne
cc -O2 -g -Wall    pee.c   -o pee
make[1]: Entering directory `/usr/local/tmp/crew/moreutils_0.60.orig.tar.xz.dir/moreutils-0.60/is_utf8'
gcc -O3 -Wextra -Wall -ansi -Wstrict-prototypes   -c -o main.o main.c
gcc -O3 -Wextra -Wall -ansi -Wstrict-prototypes   -c -o is_utf8.o is_utf8.c
cc -O2 -g -Wall    sponge.c   -o sponge
cc -O2 -g -Wall    mispipe.c   -o mispipe
gcc -O3 -Wextra -Wall -ansi -Wstrict-prototypes -o isutf8 main.o is_utf8.o
make[1]: Leaving directory `/usr/local/tmp/crew/moreutils_0.60.orig.tar.xz.dir/moreutils-0.60/is_utf8'
cp is_utf8/isutf8 .
cc -O2 -g -Wall    lckdo.c   -o lckdo
cc -O2 -g -Wall    parallel.c   -o parallel
In file included from /usr/local/include/unistd.h:25:0,
                 from lckdo.c:10:
/usr/local/include/features.h:148:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^
echo '#include <errno.h>' > dump.c
cc -E -dD dump.c | awk '/^#define E/ { printf "{\"%s\",%s},\n", $2, $2 }' > errnos.h
rm -f dump.c
xmllint --noout --valid sponge.docbook
pod2man --center=" " --release="moreutils" vidir > vidir.1;
/usr/local/bin/perl: relocation error: /usr/local/bin/perl: symbol __get_cpu_features, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
make: *** [vidir.1] Error 127
make: *** Waiting for unfinished jobs....
xsltproc --param man.authors.section.enabled 0 /usr/local/docbook/manpages/docbook.xsl sponge.docbook
make: xsltproc: Command not found
make: *** [sponge.1] Error 127
moreutils failed to install: `make -j4` exited with 2

**Comment by uberhacker** [comment]
@thedamian: It looks like maybe the `libxslt` package is a needed dependency.  The command `xsltproc` is missing.  That is your issue.  Sorry, I should have checked after a powerwash.

**Comment by uberhacker** [comment]
Confirmed.  The `libxslt` package is definitely a needed dependency.  It's nice we have all these nice commands that can help us out. :)
```
$ crew whatprovides xsltproc
libxslt: /usr/local/bin/xsltproc
libxslt: /usr/local/share/doc/libxslt-1.1.28/html/xsltproc.html
libxslt: /usr/local/share/doc/libxslt-1.1.28/html/xsltproc2.html
libxslt: /usr/local/share/man/man1/xsltproc.1

Total found: 4
```
I'll push up another commit and add the `depends_on 'libxslt'` line.  In the meantime, can you please confirm the package installs without needing any other dependencies.
Thanks

**Comment by thedamian** [comment]
That was it

Note: Writing lckdo.1
Note: Writing errno.1
Preconfiguring package...
mkdir -p /usr/local/tmp/crew/dest/usr/local/bin
install -s isutf8 ifdata ifne pee sponge mispipe lckdo parallel errno /usr/local/tmp/crew/dest/usr/local/bin
install vidir vipe ts combine zrun chronic /usr/local/tmp/crew/dest/usr/local/bin
mkdir -p /usr/local/tmp/crew/dest/usr/local/man/man1
install sponge.1 vidir.1 vipe.1 isutf8.1 ts.1 combine.1 ifdata.1 ifne.1 pee.1 zrun.1 chronic.1 mispipe.1 lckdo.1 parallel.1 errno.1 /usr/local/tmp/crew/dest/usr/local/man/man1
Installing...
**# Moreutils installed!**

**Pull request merged**
