### PR TITLE
Node Updates, OpenSSL 1.02f, Ruby 2.3.7, and Readline Error fixed

### PR DESCRIPTION
**Pull request by thedamian**
I saw @zoltanradics 's https://github.com/skycocker/chromebrew/pull/194 pull request and realized we could not only fix node_stable sha1 signature (which I'm trying to ignore since the name changes in the node project)  BUT Also update all the Node versions to the most recent.

### CODE REVIEW

**Comment by thedamian** [comment]
Confirimed to work and updated to 6.3.1

this is the end of the installation:

installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/BSD-x86_64/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/linux64-s390x/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/linux-x32/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/VC-WIN32/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/zconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/zlib.h
Now to get npm -g working you should type this
sudo chown -R chronos /usr/local/lib/node_modules
Installing...
Node_current installed!

**Comment by lyxell** [comment]
Please, next time, split multiple issues/features into multiple pull requests. You're making it really hard to figure out what you're trying to achieve and why.

**Comment by thedamian** [comment]
I would LOVE that. I'll look into that @lyxell but if you can point to to where to do that.

**Comment by lyxell** [comment]
@thedamian 
https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell
https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging
https://help.github.com/articles/using-pull-requests/

**Comment by thedamian** [comment]
Done. I will spend lunch time splitting this into different pull requests as y should be.

Thank you. I've been wanting to do this for a while.

**Comment by thedamian** [comment]
@lyxell this is going to be a pain.
What am I suppose to do.

Essentially there are
1) node updates (3 files)
2) changes to exiting packages (2 files)
3) new packages (3 files)

I feel I can do a hacky way and do a brand new pull on my device. then copy and paste the changes from this pull and make a new branch each time so that they're all organized.

is that what you're suggesting/ or is there a way to do it from the existing changes here.

the 8 files changes aren't that hard to confirm and to figure out from what I see.

**Comment by thedamian** [comment]
crap. All I did is end up creating another pull request.

Ok. I'm going to leave it as it is. if it's too complicated people can pull from these files

**Comment by thedamian** [comment]
closing as I branched the changes to make it easier.

**Comment by lyxell** [comment]
@thedamian Looks like you figured it out, great!

**Comment by thedamian** [comment]
I hacked it. But it worked out. And I agree it's better separated like this.

**Comment by thedamian** [comment]
P.s. @lycell I of course did it like you mentioned with branches from those links you sent me so thank you.

**Pull request closed without merging**
