### PR TITLE
Add rtws package

### PR DESCRIPTION
**Pull request by uberhacker**
Something made especially for @satmandu. :)

### CODE REVIEW

**Comment by satmandu** [comment]
Rubocop also does this...

**Comment by uberhacker** [comment]
Well then, where is the rubocop package?

**Comment by cstrouse** [comment]
Are we doing gem wrappers?

**Comment by satmandu** [comment]
I'm not sure that we need to do a rubocop package? Why create a package when ```gem install rubocop``` will suffice?

The only reason I can see for doing that would be to prepackage a .rubocop.yml file

And I think that should be part of the core install. eg. : ~/.rubocop.yml

```
# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

AllCops:
  NewCops: enable

Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - separator
  EnforcedColonStyle:
    - separator

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/FrozenStringLiteralComment:
  Enabled: false
```

**Pull request closed without merging**
