### PR TITLE
Update dbus from 1.13.4 to 1.13.12

### PR DESCRIPTION
**Pull request by uberhacker**
Tested on all architectures.

### CODE REVIEW

**Comment by vincowl** [comment]
Why not applying @JL2210 solution to solve the #3591 dealing with dbus troubles in codium ? Solution was adding `ln -sf /var/run/dbus /usr/local/var/run` in `~/.bashrc`. Maybe we could add it as an install command or a postinstall message ?

**Comment by uberhacker** [comment]
Definitely don't want to add that command to `~/.bashrc`.  It makes more sense to add a line in the install section of this package since it's a one-off thing.

**Comment by JL2210** [comment]
No, /usr/local/var is nuked on shutdown, at least on my system.

**Comment by uberhacker** [comment]
In any event, that doesn't solve the issue because requests to dbus still fail:
```
[main 2019-10-28T04:01:56.364Z] update#setState checking for updates
[main 2019-10-28T04:01:56.367Z] RequestService#request https://vscodium.now.sh/api/update/linux-x64/stable/88f15d17dca836346e787762685a40bb5cce75a8
[main 2019-10-28T04:01:56.518Z] update#setState available for download
[main 2019-10-28T04:01:56.752Z] menubarService#updateMenubar 1
[22277:1027/230156.829972:ERROR:bus.cc(394)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[22277:1027/230156.841278:ERROR:bus.cc(394)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[main 2019-10-28T04:02:16.074Z] update#checkForUpdates, state =  available for download
[main 2019-10-28T04:02:28.291Z] update#downloadUpdate, state =  available for download
[main 2019-10-28T04:02:28.333Z] update#setState idle
LaunchProcess: failed to execvp:

xdg-open

[main 2019-10-28T04:02:28.565Z] menubarService#updateMenubar 1
[22277:1027/230228.635576:ERROR:bus.cc(394)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[22277:1027/230228.643217:ERROR:bus.cc(394)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
```

**Comment by vincowl** [comment]
Same error here : 
```shell
$ codium --verbose
[25969:1028/122420.621473:ERROR:gl_surface_glx.cc(424)] glxQueryVersion failed
[25969:1028/122420.621628:ERROR:gl_initializer_x11.cc(157)] GLSurfaceGLX::InitializeOneOff failed.
[25969:1028/122420.675777:ERROR:viz_main_impl.cc(236)] Exiting GPU process due to errors during initialization
[main 2019-10-28T11:24:20.862Z] Starting VS Code
[main 2019-10-28T11:24:20.874Z] from: /usr/local/share/VSCodium-linux-x64/resources/app
[main 2019-10-28T11:24:20.879Z] args: { _: [], verbose: true, diff: undefined }
[main 2019-10-28T11:24:20.891Z] Resolving machine identifier...
[main 2019-10-28T11:24:20.894Z] Resolved machine identifier: 71fcfe91-e3b8-4d0a-9013-d9436a5c394c (trueMachineId: undefined)
[main 2019-10-28T11:24:20.972Z] update#setState idle
[main 2019-10-28T11:24:20.994Z] [storage state.vscdb] open(/home/chronos/user/.config/VSCodium/User/globalStorage/state.vscdb, retryOnBusy: true)
[main 2019-10-28T11:24:20.997Z] lifecycle (main): phase changed (value: 2)
[main 2019-10-28T11:24:21.010Z] windowsManager#open
[25014:1028/122421.677543:ERROR:bus.cc(394)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[main 2019-10-28T11:24:21.758Z] lifecycle (main): phase changed (value: 3)
[25014:1028/122421.856429:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.
```

**Comment by skiman6010** [comment]
This is fine.

**Pull request merged**
