### PR TITLE
Update gtk3.rb

### PR DESCRIPTION
**Pull request by lovedheart**
Need this patch quickly! @uberhacker

### CODE REVIEW

**Comment by uberhacker** [comment]
LoL, this is the exact same fix I proposed in #2131 but after thinking about it awhile, I think there is a better way.  Try this:
```
  def self.install
    system "pip install six"  # for installation process
     system "make", "DESTDIR=#{CREW_DEST_DIR}", "install"
+    system "mkdir -p #{CREW_DEST_PREFIX}/share/glib-2.0/schemas"
+    system "glib-compile-schemas #{CREW_DEST_PREFIX}/share/glib-2.0/schemas"
    system "pip uninstall --yes six"
  end

- def self.postinstall
-    system "glib-compile-schemas #{CREW_DEST_PREFIX}/share/glib-2.0/schemas"   # generate gschemas.compiled
- end
```

**Comment by lovedheart** [comment]
This is better. I got error by previous fix

**Comment by uberhacker** [comment]
Would it make sense to include system "glib-compile-schemas #{CREW_DEST_PREFIX}/share/glib-2.0/schemas" in the glib package instead?

**Comment by uberhacker** [comment]
We'll need new binaries and the version bumped also, correct?

**Comment by lovedheart** [comment]
doing it. I do not bump the version

**Comment by uberhacker** [comment]
Keep in mind that if somebody has already installed gtk3 and you don't bump the version, they will not have the changes detected.

**Pull request merged**
