### PR TITLE
lib/package.rb: Exclude `buildessential` dependency on some packages which have prebuilt binary as source

### LINKED ISSUE #6917: core: Depends on `crew_profile_base` depends on `buildessential`
```
└───┬─core
    ├─────brotli
    ├─────bz2
    ├─────c_ares
    ├─────ca_certificates
    ├───┬─crew_profile_base
    │   └───┬─buildessential
    │       ├─────glibc
    │       ├─────gmp
    │       ├─────mpfr
```

### PR DESCRIPTION
**Pull request by supechicken**
Fixes #6917 

Tested on `x86_64`

### Changes
- Added a flag named `no_compile_needed` at `lib/package.rb`, also appended it on some packages with scripts/official prebuilt binary as the source.

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/supechicken/chromebrew.git CREW_TESTING_BRANCH=allow_without_buildessential CREW_TESTING=1 crew update
```

### CODE REVIEW

**Comment by satmandu** [comment]
These are the relevant files:
```
chronos@rpi4b-armv7l /usr/local/lib/crew/packages $ grep CREW_NOT_STRIP *
arduino_ide.rb:ENV['CREW_NOT_STRIP'] = 'true'
arduino_ide.rb:ENV['CREW_NOT_STRIP'] = ''
balena_etcher.rb:    ENV['CREW_NOT_STRIP'] = '1'
cpu_x.rb:    prev = ENV['CREW_NOT_STRIP']
cpu_x.rb:    ENV['CREW_NOT_STRIP'] = '1'
cpu_x.rb:    ENV['CREW_NOT_STRIP'] = prev
krita.rb:    ENV['CREW_NOT_STRIP'] = '1'
natron.rb:  @strip = ENV['CREW_NOT_STRIP']
natron.rb:  ENV['CREW_NOT_STRIP'] = '1'
natron.rb:  ENV['CREW_NOT_STRIP'] = @strip
opera.rb:    ENV['CREW_NOT_STRIP'] = '1'
packer.rb:    ENV['CREW_NOT_STRIP'] = '1'
udeler.rb:    prev = ENV['CREW_NOT_STRIP']
udeler.rb:    ENV['CREW_NOT_STRIP'] = '1'
udeler.rb:    ENV['CREW_NOT_STRIP'] = prev
```

**Comment by supechicken** [comment]
> Can you also add `no_compile_needed` to the `strip_dir` logic in `crew` so if `no_compile_needed` is set it acts like `CREW_NOT_STRIP` is set too? (Actually, I think most situations with CREW_NOT_STRIP should be handled by `no_compile_needed`.)

Done

**Comment by satmandu** [comment]
just need to rebase to master...

**Comment by satmandu** [comment]
`crew deps -t core | less` shows that this resolves the issue.

**Pull request merged**
