### PR TITLE
Add xterm pre-built binaries

### PR DESCRIPTION
**Pull request by uberhacker**
Depends on #2521.

### CODE REVIEW

**Comment by JL2210** [comment]
How does this depend on #2521? It works with xinit and my wayland modifications. Try it.

**Comment by JL2210** [comment]
If anything, could you edit it and add `depends_on 'xwayland'` and `depends_on 'xinit'`?

**Comment by uberhacker** [comment]
Dude, it depends on either but there were no dependencies when you added the package which, as it turns out, was not considered originally.

**Comment by JL2210** [comment]
Sorry. Could you edit that for me, please?

**Comment by uberhacker** [comment]
No need.  The `depends_on 'sommelier'` includes xwayland as a dependency already.

**Comment by JL2210** [comment]
OK. True. If anything, this should be a dependency of xinit. Next up, gnome-session! lol

**Pull request merged**
