### PR TITLE
crew: Add `autoremove` command

### LINKED ISSUE #4572: Chromebrew has no system to remove unused dependencies
Chromebrew doesn't know if a dependency is unused and there's no system to remove unused dependencies. For example, I installed `rsync`. It called a dependency `xxhash`, however when running `crew remove rsync` it doesn't uninstall `xxhash`. It would greatly increase the usability of chromebrew if this feature was added, either with automatic unused dependency removals or with something like `crew remove --unused` (`crew remove -u`). There should also be a way to indicate to chromebrew whether a package is wanted, similar to portage's `--deselect` option or apt's `apt-mark`, for example `crew mark rsync --auto` or `crew mark xxhash --manual`. Installing a package when it's already installed should also mark a package that isn't manually installed as manually installed. Maybe even showing what's manually and automatically installed would be useful, for example `crew list auto` and `crew list manual`
I'm happy to clarify what I mean if I don't make sense.

### PR DESCRIPTION
**Pull request by supechicken**
Add `autoremove` command for auto removing unused dependencies.  Fixes #4572.

### CODE REVIEW

**Comment by uberhacker** [comment]
Nice!  We'll need to add the command to README.md also.

**Comment by saltedcoffii** [comment]
Fixes #1918

**Comment by satmandu** [comment]
Let's get this done!

**Comment by supechicken** [comment]
> Nice! We'll need to add the command to README.md also.

Done :)

**Comment by supechicken** [comment]
## Working
- [x] All unused dependencies installed **after** this update (so that a new key called `is_dep` will be saved in `device.json`, used to determine if that package is installed as a dependency)

I will test it in a fresh crew install later

## Run the following to test this pull request
```shell
CREW_TESTING_REPO=https://github.com/supechicken/chromebrew.git \
CREW_TESTING_BRANCH=auto_remove \
CREW_TESTING=1 \
crew update
```

**Comment by satmandu** [comment]
Can you give an example package insall to show how this works?

**Comment by uberhacker** [comment]
Also, we'll need to bump the version in `lib/const.rb`.

**Comment by uberhacker** [comment]
Add to `@cmds = ["build", "const", "deps", "download", "files", "help", "install", "list", "postinstall", "reinstall", "remove", "search", "update", "upgrade", "whatprovides"]` too?

**Comment by supechicken** [comment]
> Can you give an example package insall to show how this works?

- For example, a package has been removed now
`crew remove chrome`
- Some of its dependencies like `nspr` is no longer needed and remains
- If we run `crew autoremove` now:
```shell
chronos@localhost / $ crew autoremove
The following packages also need to be REMOVED: 
nspr 
Do you agree? [Y/n]
```

**Comment by supechicken** [comment]
> Add to `@cmds = ["build", "const", "deps", "download", "files", "help", "install", "list", "postinstall", "reinstall", "remove", "search", "update", "upgrade", "whatprovides"]` too?

Done

**Comment by uberhacker** [comment]
Can we also add?
```
def help(pkgName)
  case pkgName
  when "autoremove"
```

**Comment by uberhacker** [comment]
@supechicken: After you add `crew help autoremove`, I can merge this PR.

**Comment by supechicken** [comment]
> Can we also add?
> 
> ```
> def help(pkgName)
>   case pkgName
>   when "autoremove"
> ```

Done

**Comment by uberhacker** [comment]
Bump crew version in `lib/const.rb`?

**Review by saltedcoffii — APPROVED** [review]

**Comment by uberhacker** [comment]
Thanks for the bump @saltedcoffii. :)

**Pull request merged**
