### PR TITLE
New package 'file' and dependencies fix for 'nano'

### PR DESCRIPTION
**Pull request by 0x5c**
The `nano` package depends on `libmagic` witch is not included in chromebrew. This pull request adds the `libmagic` package and adds it to `nano`'s dependencies.

Fixes issue #131

### CODE REVIEW

**Comment by thedamian** [comment]
Why isn't the package called file? Or using maybe a more official distribution file?

Maybe http://pkgs.fedoraproject.org/lookaside/extras/file/file-5.28.tar.gz/3f7771424aa855f32094b49571e19b33/file-5.28.tar.gz

Also really? Nano needs this and no one had contributed this already? I've had nano running on my chromebook for a year! What changed?

**Comment by 0x5c** [comment]
@thedamian nano wont compile on i686 systems without libmagic (part of `file`). The name, however, is simply for compatibility with Ruby , `fule.rb` being part of Ruby and `File` being already defined internally within Ruby.

**Comment by thedamian** [comment]
So x64 platforms don't need it but 32bit ones do? Strange, you sure?

hey! I'm no linux expert but the package should be name at least with the name within it. no just LibMagic even if that's the parent or creator.

I have plenty of projects here that add "_stable" or "_dev" to the file name not to override the original or in your case because of a ruby conflix

**Comment by 0x5c** [comment]
I am not exactly sure that it is a problem with all 32bit installs, the build used in #131 being from the same source than mine. It might be a problem with ArnoldTheBat's build (any versions). 

For the name, I tried many combinations with file (file_.rb, FilePack < Package,...) but Ruby seems to be very pricky about internal definitions.

**Comment by thedamian** [comment]
I don't like the name LibMagic for the File project. May I suggest "Filepkg" or "Filecmd" as you suggested in the past

I've updated nano in the master to 2.7.1
Can you try installing that?

I don't see ANY dependancies on anything other than ncurses
http://mybookworld.wikidot.com/compile-nano-from-source

Let me know how it goes. if it works WITHOUT file then we'll just close this pull request.

**Comment by minektur** [comment]
I  resubmitted my pull request for adding a 'file' command  - the package
can't be named 'file' because packages can't be named the same as ruby
builtin objects - it is named 'filecmd' but it installs /usr/local/bin/file

**Comment by thedamian** [comment]
We now have the Filecmd package in our master repo.

Can you now uninstall your file package. And try to install nano without your libmaster package?

**Comment by thedamian** [comment]
Just confirmed the requirement on libmagic isn't needed for x86 - 32bit nano installation. 
(just installed it on my CR-48 right after installing crew from scratch)

**Pull request closed without merging**
