### PR TITLE
Change crew to use same logic for zip and tar

### PR DESCRIPTION
**Pull request by jam7**
This PR is originally created to compile lshw #400 as we discussed in #394.  This PR will replace #399.

This PR has relations to #276 and #284 also.  I refactor crew carefully, so I think I'm not breaking #276.  But who knows, please test this PR carefully.  Thanks.

I tested on X86_64 using following scenarios.

- lshw #400, as a test of tar file containing files at top  (EDIT: need modification after https://github.com/skycocker/chromebrew/pull/443/commits/0c435ec6dd56fae1df3ffbf3086415e7ed723b66)
- perl, as a test of binary package
- automake and m4 as a test of multiple package installation at once
- Makefile.zip #276 as a test of zip file without directories inside
- a.zip #276 as a test of zip file with top directory

### CODE REVIEW

**Comment by lyxell** [comment]
@jam7 @cstrouse Can we merge this?

**Comment by jam7** [comment]
@lyxell I think so. :)

It's stable here on both ARM and X86_64.

**Comment by cstrouse** [comment]
I'm unable to build lshw using your branch.

```bash
chronos@localhost /usr/local/lib/crew/packages $ crew install lshw
Found lshw, version B.02.18
Found lshw, version B.02.18
No precompiled binary available for your platform, downloading source...
--2017-01-31 12:48:10--  http://www.ezix.org/software/files/lshw-B.02.18.tar.gz
Resolving www.ezix.org... 104.28.6.39, 104.28.7.39
Connecting to www.ezix.org|104.28.6.39|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2322176 (2.2M) [application/x-gzip]
Saving to: 'lshw-B.02.18.tar.gz'

lshw-B.02.18.tar.gz                   100%[======================================================================>]   2.21M   666KB/s    in 3.7s    

2017-01-31 12:48:14 (620 KB/s) - 'lshw-B.02.18.tar.gz' saved [2322176/2322176]

Archive downloaded
Unpacking archive, this may take a while...
gcc (GCC) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
/usr/local/lib/ruby/2.0.0/fileutils.rb:125:in `chdir': No such file or directory - src (Errno::ENOENT)
        from /usr/local/lib/ruby/2.0.0/fileutils.rb:125:in `cd'
        from /usr/local/lib/crew/packages/lshw.rb:9:in `build'
        from /usr/local/bin/crew:225:in `block in build_and_preconfigure'
        from /usr/local/bin/crew:223:in `chdir'
        from /usr/local/bin/crew:223:in `build_and_preconfigure'
        from /usr/local/bin/crew:344:in `install'
        from /usr/local/bin/crew:269:in `resolveDependenciesAndInstall'
        from /usr/local/bin/crew:442:in `<main>'
```

**Comment by jam7** [comment]
@cstrouse Please modify `FileUtils.chdir("src")` to `FileUtils.chdir("lshw-B.02.18/src")`.

I think extracting all files as is is better as what @minektur did.

For example, lshw tar file contains below.
```
lshw-B.02.18/    lshw.spec
```
So, it is possible to chdir lshw-B.02.18 at crew program side for this case.  However, if we have archive files something like below, what should we do?
```
Makefile     src/
```
Check #284 for more details.

**Comment by jam7** [comment]
@cstrouse Does above explanation make sense?  Please let me know whether you think merging this is OK.

**Comment by cstrouse** [comment]
@jam7 yes it makes sense. I'll update my lshw package shortly. I found another scenario to handle that was odd as well; see lsof (http://ftp.mirrorservice.org/sites/lsof.itap.purdue.edu/pub/tools/unix/lsof/lsof_4.89.tar.bz2).

**Comment by jam7** [comment]
@cstrouse Thank you for new example.  I uses lsof daily, but never noticed its source tar file structure.  :)
It's nice this PR makes crew work with lsof too.

**Comment by jam7** [comment]
Rebased to resolve conflicts in #488

**Comment by jam7** [comment]
I'm not sure why this PR is not merged yet.  Maybe need more aggressive test?

So, I compiled all packages as much as I can with this PR on ARM to test this PR.  I find two problems related to this PR, so add fixes for them.  Please let me know if you need more tests or reviews.  Thanks.

**Pull request merged**
