### PR TITLE
gnupg.rb : update to version 2.2.2

### PR DESCRIPTION
**Pull request by duckunix**
--- a/packages/gnupg.rb
+++ b/packages/gnupg.rb
@@ -3,9 +3,9 @@ require 'package'
 class Gnupg < Package
    description 'GnuPG is a complete and free implementation of the
    OpenPGP standard as defined by RFC4880 (also known as PGP).'
       homepage 'https://gnupg.org/'
       -  version '2.2.1'
       -  source_url 'https://gnupg.org/ftp/gcrypt/gnupg/gnupg-2.2.1.tar.bz2'
       -  source_sha256 '34d70cd65b9c95f3f2f90a9f5c1e0b6a0fe039a8d685e2d66d69c33d1cbf62fb'
       +  version '2.2.2'
       +  source_url 'https://gnupg.org/ftp/gcrypt/gnupg/gnupg-2.2.2.tar.bz2'
       +  source_sha256 'bfb62c7412ceb3b9422c6c7134a34ff01a560f98eb981c2d96829c1517c08197'

	   binary_url ({
	      })

### CODE REVIEW

**Comment by uberhacker** [comment]
Thank you for the contribution @duckunix!  As soon as we can test this on all the architectures, we'll get it merged.

**Comment by cstrouse** [comment]
Works on Samsung Chromebook Plus (aarch64) with all tests passing.

**Comment by uberhacker** [comment]
Installs fine on Hisense C11 (armv7l).  However, I'm not sure how concerned we should be about this message?
```
$ gpg
gpg: NOTE: THIS IS A DEVELOPMENT VERSION!
gpg: It is only intended for test purposes and should NOT be
gpg: used in a production environment or with production keys!
gpg: directory '/home/chronos/user/.gnupg' created
gpg: keybox '/home/chronos/user/.gnupg/pubring.kbx' created
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
gpg: Go ahead and type your message ...
```

**Comment by cstrouse** [comment]
The wikipedia entry for GnuPG says that the modern 2.1.* and 2.2.* line has replaced the 2.0.* stable. It's probably fine.

```
As of August 2016, there are three actively maintained branches of GnuPG:

"Modern" (2.1 / 2.2), containing the latest developments, with numerous new features, such as elliptic curve cryptography; it replaced the "stable" (2.0) branch with the release of GnuPG 2.2.0 on August 28, 2017.[15] It was initially released on November 6, 2014.[9]
"Stable" (2.0), stable version for general use, initially released on November 13, 2006.[16] This branch is announced to reach end-of-life December 31, 2017.[17]
"Classic" (1.4), older standalone version, most suitable for older or embedded platforms. Initially released on December 16, 2004.[18]
```

**Comment by duckunix** [comment]
@uberhacker - I was getting that on the 2.2.1 version as well on my Acer C720.  I do not get it with the same version of gnupg under ArchLinux, so I am assuming there is a build flag somewhere to turn it off.

**Comment by uberhacker** [comment]
Hey @duckunix: Is this something you want to investigate and report back?  If you push another commit, I'll assume the answer is yes. :)

**Comment by cstrouse** [comment]
I've looked at the source and various distro's packaging and there doesn't seem to be a build flag. It picks up on a few things from the environment in which it's compiled to determine if it's a development version or not. I'm working on a fix. There are also some common build options that we're not using but probably should be so I'm adding those as well.

**Comment by cstrouse** [comment]
Ok, so this is because of a problem with their `autogen.sh`. It always sets the `development_version` variable as beta in `configure.ac` unless you run it from within git.

**Comment by duckunix** [comment]
Okay, I tracked down where the scary message was coming from.  It seems that autogen.sh was returning something not quite to m4's liking, and decide that the build was a development version.

I feel that the call to autogen.sh is not need as we are pulling from a release tarball.

Tested build on x86_64 (Acer C720) & armv7l (HP Chromebook 11 G1).

**Pull request merged**
