### PR TITLE
Add libmng package

### PR DESCRIPTION
**Pull request by uberhacker**
A PNG-like Image Format Supporting Multiple Images, Animation and Transparent JPEG.  See http://www.libpng.org/pub/mng/.

Tested on:
- [x] aarch64
- [x] armv7l
- [x] i686
- [x] x86_64

### CODE REVIEW

**Comment by JL2210** [comment]
May I ask what this is needed for?

**Comment by uberhacker** [comment]
It's a dependency of something else I'm working on atm.

**Comment by JL2210** [comment]
What would that be? Could I help?

**Comment by JL2210** [comment]
Nice.

**Pull request merged**
