### PR TITLE
Update Code package (again)

### LINKED ISSUE #3126: Code package problems on armv7l
EDIT: this issue was originally for a problem with computing dependencies for the `code` package, but a fix has since been applied. There are some more issues described in this thread that have not been fixed, please look through the thread before dismissing it as not helpful. Most of these issues appear to be armv7l related, but they may still apply to you anyway.

## Description
i'm trying to install vs code.
when doing
```shell
crew install code
```
nothing happens for a long time (literally half an hour) and it finally fails:

Output:
```shell
~ [ crew install code                                                                                                                       ] 11:10 AM
code: Visual Studio Code is a source code editor developed by Microsoft for Windows, Linux and macOS.
https://code.visualstudio.com/
version 1.30.1-1
Traceback (most recent call last):
        12679: from /usr/local/bin/crew:988:in `<main>'
        12678: from /usr/local/bin/crew:919:in `install_command'
        12677: from /usr/local/bin/crew:919:in `each'
        12676: from /usr/local/bin/crew:923:in `block in install_command'
        12675: from /usr/local/bin/crew:612:in `resolve_dependencies_and_install'
        12674: from /usr/local/bin/crew:669:in `resolve_dependencies'
        12673: from /usr/local/bin/crew:663:in `expand_dependencies'
        12672: from /usr/local/bin/crew:657:in `push_dependencies'
         ... 12667 levels...
            4: from /usr/local/lib/ruby/2.5.0/find.rb:49:in `block (2 levels) in find'
            3: from /usr/local/bin/crew:148:in `block in search'
            2: from /usr/local/bin/crew:109:in `set_package'
            1: from /usr/local/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/usr/local/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:123:in `rescue in require': stack level too deep (SystemStackError)
```

## Versions and system information
chromebrew: `crew --version`
1.1.2
ChromeOS: `cat /etc/lsb-release`
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={2FC0F0CF-1A55-DF3F-73E6-517389444085}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={2FC0F0CF-1A55-DF3F-73E6-517389444085}
CHROMEOS_RELEASE_BOARD=nyan_big-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=113
CHROMEOS_RELEASE_BUILDER_PATH=nyan_big-release/R71-11151.113.0
CHROMEOS_RELEASE_BUILD_NUMBER=11151
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=71
CHROMEOS_RELEASE_DESCRIPTION=11151.113.0 (Official Build) stable-channel nyan_big 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=11151.113.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=11151.113.0
Model: acer chromebook 13

Architecture: `uname -m`
armv7l
## Addtional information
i had tried to install it before but everything on my machine was massively outdated. it didn't fail that way before updating though.

i have read #3106 but have no idea how to use it (if that's even possible and/or advisable)

### PR DESCRIPTION
**Pull request by JL2210**
Fixes #3126?

### CODE REVIEW

**Comment by JL2210** [comment]
Open to suggestions.

**Comment by uberhacker** [comment]
Can you create a pre-built binary and see if it works?

**Comment by JL2210** [comment]
I installed it. It works fine, and the files are found by 'crew files
code'. You should be able to create binaries, no problem. Sadly, my battery
is dead right now, so I'll have to let it charge before I can do anything.
This is good, though.

**Comment by uberhacker** [comment]
Don't you have a power adapter?

**Comment by JL2210** [comment]
It's not long enough to use comfortably while it's plugged in.

**Comment by JL2210** [comment]
This should be good to merge.

**Pull request merged**
