### PR TITLE
Add perl_xml_parser package

### PR DESCRIPTION
**Pull request by uberhacker**
Perl XML::Parser - A perl module for parsing XML documents.  See https://metacpan.org/pod/XML::Parser.

### CODE REVIEW

**Comment by cstrouse** [comment]
Installs and works with example code from CPAN docs on Samsung Chromebook Plus (ARMv8).

**Comment by cstrouse** [comment]
Fails to build/install on x864_64 without adding `expat` as a dependency.

**Comment by uberhacker** [comment]
Good catch.  We actually need perl as a dependency also.  Duh...right?

**Comment by cstrouse** [comment]
Works on Samsung Chromebook Plus (aarch64) and Samsung Chromebook 3 (x86_64).

**Pull request merged**
