### PR TITLE
Discuss: Installation errors can leave chromebrew in an inconsistent state

### PR DESCRIPTION
**Pull request by dmcaulay**
Chromebrew currently ignores `build` and `install` errors returned from `Kernel.system`. This is an issue, because it tells the user that the package has installed successfully. However, when the user tries to use the package they will see that installation failed, but not know where to look.

This commit adds some error checking around `Kernel.system`. It was the simplest solution I could come up with. I can rename `Package.system` to `Package.system!` if you want it to be a little clearer. I can also replace `system` everywhere so errors outside of `Package.build` and `Package.install` will raise errors. Or I can do something completely different. Let me know.

### CODE REVIEW

**Comment by skycocker** [comment]
This looks like a good starting point to me, I'll just have to set up a VM to tak a look at this. I'll let you know when I'll do it.

**Comment by ryanmjacobs** [comment]
Hey @skycocker, how do you setup a VM for Chrome OS? Just wondering, because it seems like a good way to test out stuff.

**Comment by skycocker** [comment]
That's a good question. I've tried the precompiled builds but they don't work at all on my virtualbox. I'm trying to compile ChromeOS myself but it takes a lot of time and always something goes wrong; I'll do it eventually once I have a lot of free time at once.

**Comment by skycocker** [comment]
@dmcaulay merged, but you can't run .uniq! and rely on the result - http://stackoverflow.com/questions/2102252/why-does-uniq-return-nil-if-there-are-no-duplicates 

Fixed already. Thanks! :)

**Pull request merged**
