### PR TITLE
Update curl from 7.61.0 to 7.64.0

### PR DESCRIPTION
**Pull request by uberhacker**
Tested on all architectures.

### CODE REVIEW

**Comment by superloach** [comment]
Apparently this causes issues with libmetalink, at least on ARM32.

**Comment by uberhacker** [comment]
@superloach:  I have noticed this also.  It seems to be problematic on packages that have curl as a dependency.  What package did you notice this issue?

**Comment by superloach** [comment]
Someone on the Discord attempting to run the crew installer.

**Comment by uberhacker** [comment]
Can you please provide more details (ie. architecture, install or reinstall, etc)?  If this relates to #3174, please comment on that thread.

**Comment by superloach** [comment]
Never mind, #3174 is the same one.

**Pull request merged**
