### PR TITLE
Update ruby to version 2.2.4

### PR DESCRIPTION
**Pull request by Tivoli**

### CODE REVIEW

**Comment by skycocker** [comment]
I'm afraid this won't be so easy - there needs to be a working binary, since it will be needed for chromebrew to work at all. This way, it would never install for the first time.

**Comment by Tivoli** [comment]
@skycocker Hmm, ok, the current one doesn't work atm which is why I did the update.

**Comment by skycocker** [comment]
@Tivoli is it because of the cpu architecture other than x86_64 and i686?

**Comment by Tivoli** [comment]
@skycocker nope, it was a sha1sum that didn't match with the compiled one, the x86_64.

**Comment by thedamian** [comment]
So the issue is a "chicken and egg" (like they say here)

Everything needs ruby to start, BUT we'd like to update the package easily with the latest ruby. 

OK. So how about creating a package called "ruby-latest" that can easily be kept up to date with the latest ruby. or simply have the initial ruby scripts and binary have one version (say the 2.0 we have there now) BUT the ruby.rb file has the latest and greatest.

I overwrote my /usr/local/lib/crew/packages/ruby.rb  with this pull request and (since I already have crew installed and working) I now successfully have 2.2.4p230 installed 
(did a $ ruby --version to find the version)

So the your pull request has everything setup correctly ONCE you have crew working flawlessly on your laptop.

I have the x64 chrome (it's a chromebook pixel) so I can confirm it works AFTER everything is installed correctly.

**Comment by skycocker** [comment]
It would be a good idea to keep the ruby as binary I guess, so you don't spend your whole life on updating basic crew packages right after installing it - keep in mind chromebooks don't have too much computing power. But we can make a ruby-224 package file instead. @Tivoli?

**Comment by thedamian** [comment]
@Tivoli
Can I suggest again the package be called "ruby-latest" so it can be independently updated in the future again?

**Comment by Tivoli** [comment]
@skycocker @thedamian Updated with a ruby-latest package and fixed the sha1sum for the x86_64 binary.

**Comment by skycocker** [comment]
Fine for me. Thanks for all the great work!

**Comment by thedamian** [comment]
@Tivoli and I see you new  https://github.com/skycocker/chromebrew/pull/133 and that fixes the issue I ran into. Looks great!

**Pull request merged**
