### PR TITLE
Update go from 1.9 to 1.9.1

### PR DESCRIPTION
**Pull request by cstrouse**
This is a bugfix and maintenance release.

Tested as working on XE500C13-K01US.

### CODE REVIEW

**Comment by uberhacker** [comment]
Thanks for the update @cstrouse.  Can we clean the build and install sections up a bit?  We could change `#{CREW_PREFIX}/lib` to `#{CREW_LIB_PREFIX}` and `#{CREW_DEST_DIR}#{CREW_PREFIX}` to `#{CREW_DEST_PREFIX}`.

**Comment by cstrouse** [comment]
Does this make sense even though `go_bootstrap` is installing binaries there which aren't actually libraries and so probably don't belong under `/usr/local/lib` or `/usr/local/lib64`?

**Comment by uberhacker** [comment]
That makes me think that maybe we shouldn't be installing binaries in `/usr/local/lib`?  Is that where they belong?  What happens if you take `/usr/local/lib` out of the library search path `LD_LIBRARY_PATH` environment variable on a x86_64 build?  Does it install and execute without error?

**Comment by uberhacker** [comment]
@cstrouse: I'm thinking we should install go in `/usr/local/share` instead of `/usr/local/lib` and move all the stuff installed in `$HOME` to there as well.  Thoughts?

**Comment by maazghani** [comment]
Could the default golang installation path `/usr/local` work here? Source: [Golang documentation](https://golang.org/doc/install#tarball)

Resulting `$GOROOT` would be `/usr/local/go`.

**Comment by uberhacker** [comment]
@maazghani: While I would normally agree with the official documentation, in this case I think they're "wrong". :)  IMHO, I think the `/usr/local` directory should only include subdirectories such as bin, lib, include, share, etc. and not be "cluttered".  Most projects install in `/usr/local/share` and go should be no different in order to keep things organized.

**Comment by uberhacker** [comment]
@cstrouse: Any update on this PR?

**Comment by cstrouse** [comment]
They've rev'd to 1.9.2 in the meantime. The holdup has been that it doesn't build properly on aarch64. I've been unable to get it to build and am thinking of having it use the official ARM binaries for the time being. Any objections?

**Comment by thedamian** [comment]
@cstrouse binaries sound better than compiling it if it works. If you do that, my friend, then I'll merge it!

**Comment by uberhacker** [comment]
@thedamian: I can take this PR over and generate the binaries if you like.  Do you have an aarch64 system you can test?

**Comment by thedamian** [comment]
No @uberhacker I don't.
So if you're taking this over I think I should merge it and you'd make the changes?
I'd suggest a quick fix is just get the old version of the binary for the aarch64 people. so at least they have an installable build.

I'll wait for your answer before I merge.

**Comment by uberhacker** [comment]
@thedamian: Go ahead and merge this.  I think we have an update anyway but the changes here are minimal and don't affect the current situation we are in with this package anyway.

**Comment by thedamian** [comment]
merged

**Pull request merged**
