### PR TITLE
Add include option in make for libpstat

### LINKED ISSUE #1334: Unable to install libpstat on x86_64
```
$ crew install libpstat
libpstat: Library for getting information about running processes
https://github.com/jcnelson/libpstat
version 030f37
No precompiled binary available for your platform, downloading source...
######################################################################## 100.0%
Archive downloaded
Unpacking archive, this may take awhile...
gcc (GCC) 4.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
cc -Wall -g -fPIC -std=c99 -o "/usr/local/tmp/crew/030f37a9d22ef3b8be839d487c97759e6126c30f.tar.gz.dir/libpstat-030f37a9d22ef3b8be839d487c97759e6126c30f/build/tools/pstat.o" -I. -I/usr/local/tmp/crew/030f37a9d22ef3b8be839d487c97759e6126c30f.tar.gz.dir/libpstat-030f37a9d22ef3b8be839d487c97759e6126c30f/build -I/usr/local/tmp/crew/030f37a9d22ef3b8be839d487c97759e6126c30f.tar.gz.dir/libpstat-030f37a9d22ef3b8be839d487c97759e6126c30f/build/include/pstat -c "tools/pstat.c" -D_THREAD_SAFE -D__STDC_FORMAT_MACROS -D_LINUX
cc -Wall -g -fPIC -std=c99 -o "/usr/local/tmp/crew/030f37a9d22ef3b8be839d487c97759e6126c30f.tar.gz.dir/libpstat-030f37a9d22ef3b8be839d487c97759e6126c30f/build/libpstat.o" -I. -I/usr/local/tmp/crew/030f37a9d22ef3b8be839d487c97759e6126c30f.tar.gz.dir/libpstat-030f37a9d22ef3b8be839d487c97759e6126c30f/build -I/usr/local/tmp/crew/030f37a9d22ef3b8be839d487c97759e6126c30f.tar.gz.dir/libpstat-030f37a9d22ef3b8be839d487c97759e6126c30f/build/include/pstat -c "libpstat.c" -D_THREAD_SAFE -D__STDC_FORMAT_MACROS -D_LINUX
cc -Wall -g -fPIC -std=c99 -o "/usr/local/tmp/crew/030f37a9d22ef3b8be839d487c97759e6126c30f.tar.gz.dir/libpstat-030f37a9d22ef3b8be839d487c97759e6126c30f/build/os/common.o" -I. -I/usr/local/tmp/crew/030f37a9d22ef3b8be839d487c97759e6126c30f.tar.gz.dir/libpstat-030f37a9d22ef3b8be839d487c97759e6126c30f/build -I/usr/local/tmp/crew/030f37a9d22ef3b8be839d487c97759e6126c30f.tar.gz.dir/libpstat-030f37a9d22ef3b8be839d487c97759e6126c30f/build/include/pstat -c "os/common.c" -D_THREAD_SAFE -D__STDC_FORMAT_MACROS -D_LINUX
cc -Wall -g -fPIC -std=c99 -o "/usr/local/tmp/crew/030f37a9d22ef3b8be839d487c97759e6126c30f.tar.gz.dir/libpstat-030f37a9d22ef3b8be839d487c97759e6126c30f/build/os/linux.o" -I. -I/usr/local/tmp/crew/030f37a9d22ef3b8be839d487c97759e6126c30f.tar.gz.dir/libpstat-030f37a9d22ef3b8be839d487c97759e6126c30f/build -I/usr/local/tmp/crew/030f37a9d22ef3b8be839d487c97759e6126c30f.tar.gz.dir/libpstat-030f37a9d22ef3b8be839d487c97759e6126c30f/build/include/pstat -c "os/linux.c" -D_THREAD_SAFE -D__STDC_FORMAT_MACROS -D_LINUX
In file included from tools/pstat.h:24:0,
                 from tools/pstat.c:22:
./libpstat.h:26:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
In file included from libpstat.c:22:0:
libpstat.h:26:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
make: *** [Makefile:131: /usr/local/tmp/crew/030f37a9d22ef3b8be839d487c97759e6126c30f.tar.gz.dir/libpstat-030f37a9d22ef3b8be839d487c97759e6126c30f/build/libpstat.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:131: /usr/local/tmp/crew/030f37a9d22ef3b8be839d487c97759e6126c30f.tar.gz.dir/libpstat-030f37a9d22ef3b8be839d487c97759e6126c30f/build/tools/pstat.o] Error 1
In file included from os/common.h:24:0,
                 from os/common.c:22:
./libpstat.h:26:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
make: *** [Makefile:131: /usr/local/tmp/crew/030f37a9d22ef3b8be839d487c97759e6126c30f.tar.gz.dir/libpstat-030f37a9d22ef3b8be839d487c97759e6126c30f/build/os/common.o] Error 1
In file included from os/common.h:24:0,
                 from os/linux.h:26,
                 from os/linux.c:25:
./libpstat.h:26:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
make: *** [Makefile:131: /usr/local/tmp/crew/030f37a9d22ef3b8be839d487c97759e6126c30f.tar.gz.dir/libpstat-030f37a9d22ef3b8be839d487c97759e6126c30f/build/os/linux.o] Error 1
libpstat failed to install: `make -j8` exited with 2
```

### PR DESCRIPTION
**Pull request by uberhacker**
Fixes #1334.

### CODE REVIEW

**Comment by cstrouse** [comment]
Are you sure this is the right fix for the issue? I fixed it by modifying the LIBDIR path in the Makefile to point to /usr/local/lib64 instead of /usr/local/lib and it worked fine on my x86_64 machine. Or do we perhaps need both fixes?

**Comment by uberhacker** [comment]
Probably should have both fixes including setting PREFIX as well.

**Comment by uberhacker** [comment]
Do the latest changes fix your issue in https://github.com/skycocker/chromebrew/issues/1334#issuecomment-340293771?

**Comment by cstrouse** [comment]
The updated version works properly on Samsung Chromebook Plus (ARMv8) and Samsung Chromebook 3 (x86_64).

**Pull request merged**
