### PR TITLE
Update crew to explain multiple argument handling

### PR DESCRIPTION
**Pull request by uberhacker**
Also updated comments for clarity.

### CODE REVIEW

**Comment by jam7** [comment]
Thank you for updating help message.  But you modified it's behavior also without explanations.  Can you explain why you did?  You are merging modifications a lot in a single PR without explanations, so reviewing is really difficult.

1. `crew search` accepts multiple arguments like below before this PR.
```
$ crew search make man
(i) automake: Automake is a tool for automatically generating Makefile.in files compliant with the GNU Coding Standards.
(i) cmake: CMake is an open-source, cross-platform family of tools designed to build, test and package software.
(i) make: GNU Make is a tool which controls the generation of executables and other non-source files of a program from the program's source files.
(i) help2man: help2man produces simple manual pages from the '--help' and '--version' output of other commands.
(i) mandb: mandb is used to initialise or manually update index database caches that are usually maintained by man.
manpages: The Linux man-pages project documents the Linux kernel and C library interfaces that are employed by user-space programs.
(i) pixman: Pixman is a low-level software library for pixel manipulation, providing features such as image compositing and trapezoid rasterization.
txt2man: Txt2man converts flat ASCII text to man page format.
```
2. `crew whatprovides` also accepts multiple arguments like below before this PR.
```
$ crew whatprovides liblcms libsoxr
jdk8: /usr/local/lib64/jdk8/jre/lib/amd64/liblcms.so
lcms: /usr/local/lib/liblcms2.a
lcms: /usr/local/lib/liblcms2.la
lcms: /usr/local/lib/liblcms2.so
lcms: /usr/local/lib/liblcms2.so.2
lcms: /usr/local/lib/liblcms2.so.2.0.8

Total found: 6
libsoxr: /usr/local/lib/libsoxr-lsr.so
libsoxr: /usr/local/lib/libsoxr-lsr.so.0
libsoxr: /usr/local/lib/libsoxr-lsr.so.0.1.9
libsoxr: /usr/local/lib/libsoxr.so
libsoxr: /usr/local/lib/libsoxr.so.0
libsoxr: /usr/local/lib/libsoxr.so.0.1.1
libsoxr: /usr/local/share/doc/libsoxr/LICENCE
libsoxr: /usr/local/share/doc/libsoxr/NEWS
libsoxr: /usr/local/share/doc/libsoxr/README
libsoxr: /usr/local/share/doc/libsoxr/examples/1-single-block.c
libsoxr: /usr/local/share/doc/libsoxr/examples/1a-lsr.c
libsoxr: /usr/local/share/doc/libsoxr/examples/2-stream.C
libsoxr: /usr/local/share/doc/libsoxr/examples/3-options-input-fn.c
libsoxr: /usr/local/share/doc/libsoxr/examples/4-split-channels.c
libsoxr: /usr/local/share/doc/libsoxr/examples/5-variable-rate.c
libsoxr: /usr/local/share/doc/libsoxr/examples/README
libsoxr: /usr/local/share/doc/libsoxr/examples/examples-common.h

Total found: 17
```

**Comment by uberhacker** [comment]
Oh, I didn't realize that docopt uses the ellipsis for multiple arguments.  Now I know.  PR updated. Thanks

**Comment by uberhacker** [comment]
I changed `#{__FILE__}` to `crew` since it expands to `/usr/local/bin/crew` which is not necessary and makes it more difficult to understand.

**Comment by uberhacker** [comment]
Any reason there is a delay on getting this merged?  The help will confuse users in the current state.

**Comment by jam7** [comment]
I reviewed your code once and pointed out problems.  Your code is too complicated and detailed.  So, I appreciate if other collaborators review this PR again to make it sure there is no problem.  Thanks.

**Comment by lyxell** [comment]
This looks good to me now, but there's still conflicts.

**Comment by uberhacker** [comment]
Resolved!

**Comment by uberhacker** [comment]
No conflicts...yet.

**Comment by jam7** [comment]
@uberhacker I saw your message https://github.com/skycocker/chromebrew/pull/963#issuecomment-326781699 with kind of suprise.  Well, I really really appreciate if you separate this PR into following four parts.

1. Update help messages
2. Update comments
3. Update DOC constant variable
4. Modify crew behavior like removing unnecessary if.

**Comment by uberhacker** [comment]
Go ahead and merge #963 and I'll fix the merge conflicts.

**Comment by jam7** [comment]
I'm not talking about the order.  I'm talking about the difficulties of your PR review.  You combine whatever you want, but it exhausts reviewers very much.  I'm really happy that you know how to separate them.

**Comment by uberhacker** [comment]
I'm talking about the order.  If his gets merged first then I need to resolve merge conflicts.  If mine gets merged first then he needs to resolve merge conflicts.  I thought it might be easier for him if he split his PR to make it easier to resolve merge conflicts.  You know 4. is not modifying crew behavior in any way, right?

**Comment by uberhacker** [comment]
Closing in favor of a new simplified PR without merge conflicts.

**Pull request closed without merging**
