### PR TITLE
Add Wireshark

### PR DESCRIPTION
**Pull request by satmandu**
- Adds `wireshark` 3.6.0
- Adds dependency `libmaxminddb`
- Updates `c_ares` to 1.18.1
- Build depends upon fixed `asciidoctor` in https://github.com/skycocker/chromebrew/pull/6422

Works properly:
- [x] x86_64
- [x] armv7l
- [ ] i686 ? (built w/o gui)

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=wireshark CREW_TESTING=1 crew update
```

### CODE REVIEW

**Comment by uberhacker** [comment]
Has i686 been tested?

**Comment by uberhacker** [comment]
I get segfaults on i686.
```
$ captype
Segmentation fault (core dumped)
$ capinfos
Segmentation fault (core dumped)
```

**Comment by satmandu** [comment]
Doing another rebuild of i686... looks like there is some leakage from newer libraries.

**Comment by satmandu** [comment]
Putting this under the python3.10 PR, since it needs libffi...

**Comment by satmandu** [comment]
Merged into https://github.com/skycocker/chromebrew/pull/6295 since it depends upon `libffi` and it doesn't make sense to make two closely spaced releases before and after the `libffi` update.

**Pull request closed without merging**
