### PR TITLE
ARM support (tested on c100pa)

### PR DESCRIPTION
**Pull request by jam7**
Hi, this is a pull request for full ARM support including gcc, glibc, ruby, python, git, etc.
I'm using pre-compiled gcc taken from http://davy.nyacom.net/cros-arm-dev.html under author's permission.
Others are compiled by myself using this gcc. 

All of above are available on https://github.com/jam7/chromebrew also for the ease of access.

In addion, regarding to recent discuss on the board.  I know #185, but I haven't had time to test it.  I modified package.rb to avoid SHORTARCH conflicts, so I hope almost all source compile packages work on ARM too.

Have a fun.  And thank you for the great effort to release and update chrombrew.  👍

### CODE REVIEW

**Comment by thedamian** [comment]
Incredible work @jam7 
I haven't been able to test it (don't have an arm chromebook) but fantastic work.

**Comment by jam7** [comment]
Thank you.  Thanks for the suggestion too.  Fixed OWNER in install.sh.

**Comment by jam7** [comment]
This pull request has a problem, so I'm going to close this pull request once.

The problem is it requires symbolic link from ~/Downloads/tool to /usr/local to use pre-compiled gcc.  However this slows chrome when users try to download something.  Chrome searches everything under Downloads directly including links and it takes forever.

If you don't care such a problem, please use it as is.

**Comment by thedamian** [comment]
WOW! that didn't sound like that bad of a problem to have. And it was some fantastic work Jam7. Too bad you took it away. 

The "issue" sounds easy to "fix" and not that bad to live with.

**Comment by jam7** [comment]
Thedaian,

I was thinking if anyone have an interest and want to live with "issue", they can download stuff from above site.  So, I didn't think deleting branch meant taking it off.  I've just restored deleted branch.

**Comment by jam7** [comment]
Hi, I've reduced the number of files being referenced from ~/Download/tools.  So, now it's not so much slow chrome downloading stuff.  Therefore, I reopen it.

**Comment by thedamian** [comment]
@jam7 thanks for that. This contribution is amazing. Glad it's back!

**Comment by thedamian** [comment]
@jam7 

I LOOOVE this pull request, but will have to look carefully to make sure it's not going to break anything. Have you done some serious testing on it? have you tried pulling from a X86 device with these changes? 

Tell me why and I'll merge it. (just let me catch up with the merges like my merge that fixes node)

**Comment by lyxell** [comment]
Nice work, I'll try this out when I get home. Would it be possible to put the toolchain directly under `/usr/local` instead of doing the symlinking?

**Comment by jam7** [comment]
@thedamian thanks.  I haven't tested it for some concrete target yet.  I compiled binary packages in this pull request using it, so it is kinda test.  I don't have any x86 devices, so it may fails although I tried to avoid any influence.

On the other hand, there are few test failures in perl and ruby and python make test.  How do you treat them?

**Comment by jam7** [comment]
@lyxell thanks.  I would like to do so, but haven't compiled toolchains by myself well.  In these few days, I was working on docker to try your new tool-chains since it looks very cool.  Is there any news about that?

**Comment by lyxell** [comment]
@jam7 I haven't been working on them for a while, they still lack full c++ support, but it shouldn't be too hard to get them working. I'll look into it, and test this pull request out as well.

**Comment by bfayers** [comment]
Currently resetting my samsung XE303C12 so i can have a clean platform to test this.

**Comment by bfayers** [comment]
All is good so far, currently have "crew install python27" running, so hopefully I will land up with a usable python.

**Comment by bfayers** [comment]
No worries! I got it to build w/ SSL Support. Requires install openssl_devel (which i did my pulling openssl_devel.rb and putting it in my packages folder, changing around some settings to a different version then using crew to install that) then you have to modify (in python source) Modules/Setup.dist uncomment line starting SSL and make it `SSL=/usr/local/include/openssl` then modify (again source) setup.py line 792 add new line with contents: `'/usr/local/include/',`  then just do ./configure (all the arguments from the .rb file) 

Sorry if this is really badly formatted these are just super quick instructions.

**Comment by thedamian** [comment]
I think also the python package (at least in x86) has the SSL fix (with the openssl_dev requirement in the package)

Just FYI.

Again. I'm not merging this ONLY because I haven't had a chance to merge it into my local report and try to install with THESE changes, but with a x86 device.

**Comment by bfayers** [comment]
@jam7 Last time i tried to put @lyxell 's toolchains in /usr/local it didnt work, there wasn't enough space which i assume is the reason for the symlinking.

**Comment by jam7** [comment]
@bfayers thank you for your try.  I'm happy that hear you it works well.

The precompiled python (3.3.2) for ARM also doesn't support ssl.  I don't have x86 device, so I cannot check other precompiled pythons.  Does anyone know how about others?

**Comment by bfayers** [comment]
Unsure about the others, pretty sure it doesn't though. Could change that...

**Comment by bfayers** [comment]
When/if this is merged ill be happy to try to make as many of the packages in crew available in arm. ones that build themselves will be left until last. again, only when this is merged / when its confirmed going to be merged.

**Comment by thedamian** [comment]
@jam7 amazing PR. I'll try it on by wiping CR-48 tomorrow. but I'll take @bfayers word.

that's a LOT of reverting to do if it fails ;-)

what an amziing PR

**Comment by bfayers** [comment]
Woo! Time to put binaries in for some packages :P

**Comment by lyxell** [comment]
Great work!

**Pull request merged**
