### PR TITLE
Update git from 2.20.1 to 2.21.0

### PR DESCRIPTION
**Pull request by uberhacker**
Tested on all architectures.

### CODE REVIEW

**Comment by JL2210** [comment]
Can we have this wait until I'm able to statically build?

**Comment by skiman6010** [comment]
@jl2210 How long do you need?

**Comment by uberhacker** [comment]
This has merge conflicts anyway.

**Comment by JL2210** [comment]
@skiman6010 Depends on how frustrating Git wants to be today :).

**Comment by uberhacker** [comment]
Reopened to fix immediate install issue.

**Comment by uberhacker** [comment]
Fixes #3230.

**Comment by skiman6010** [comment]
@uberhacker does this need to be merged now?

**Comment by JL2210** [comment]
This changes way too many packages.

**Comment by skiman6010** [comment]
What are you talking about? It updated git.

**Comment by JL2210** [comment]
Look: https://github.com/skycocker/chromebrew/commit/030a562a62a9f5791a85bdef034953e822e38db6
Showing **11 changed files** with **163 additions** and **169 deletions**.

**Comment by JL2210** [comment]
Never mind, it's fine. I was looking at the combined merge commit.

**Pull request merged**
