### PR TITLE
Add `zlibpkg` dep to Emacs.

### PR DESCRIPTION
**Pull request by ryanpcmcquen**
It fails to compile otherwise.

### CODE REVIEW

**Comment by cstrouse** [comment]
zlibpkg is installed as part of a fresh chromebrew installation.

**Comment by ryanpcmcquen** [comment]
I am hoping that this will get merged: https://github.com/skycocker/chromebrew/pull/529

In which case, `zlibpkg` will _not_ be part of a fresh install.

**Comment by cstrouse** [comment]
It is failing to compile for me after a fresh install but for a different reason.
screenshot 2017-02-21 at 11 57 43 am

**Comment by ryanpcmcquen** [comment]
If you are on `beta` or `dev`, this should fix it: https://github.com/skycocker/chromebrew/pull/533

**Comment by jam7** [comment]
Currently zlibpkg is installed by install.sh, so not having zlibpkg dependency doesn't cause problems.

However, it's possible to remove zlibpkg by hand.  #529 also changes to not install zlibpkg by default.  And anyway emacs requires zlibpkg.  So, adding such dependencies don't cause any trouble.  I prefer to add such dependencies whenever we notice it.

**Comment by ryanpcmcquen** [comment]
Any update here? #529 was merged so we really should merge this, it is broken right now.

**Comment by ryanpcmcquen** [comment]
@lyxell will you take a look at this?

**Pull request merged**
