### PR TITLE
New package: systemd

### PR DESCRIPTION
**Pull request by supechicken**
The systemd System and Service Manager

Tested on `x86_64`

### CODE REVIEW

**Comment by satmandu** [comment]
Oh wow.

**Comment by satmandu** [comment]
Wait... How are you running/starting systemd? There should probably be documentation on how you get this to actually run on ChromeOS since you can't be running systemd as the init process.

**Comment by uberhacker** [comment]
Yeah, this is definitely a bold move.  I was thinking recently it would also be nice to have a boot process manager and this would be a good start in that direction.

**Comment by supechicken** [comment]
> Wait... How are you running/starting systemd? There should probably be documentation on how you get this to actually run on ChromeOS since you can't be running systemd as the init process.

I am not trying to replace the system systemd at this moment :)  (must remount rootfs as rw to do it) (or GRUB?)  The purpose of
this package for me is the `libsystemd` part

**Pull request closed without merging**
