### PR TITLE
Update OpenSSL package

### PR DESCRIPTION
**Pull request by JL2210**
System provides older version for backwards compat. We can fix and propose upstream any source changes needed.

### CODE REVIEW

**Comment by uberhacker** [comment]
I don't think this is a good idea.  Please test on some packages that require it like irssi, php, ruby and tcpdump and report back the results.  Since this is a core package we'll need working binaries also.

**Comment by JL2210** [comment]
Don't worry. All those packages have OpenSSL 1.1 support by now, and there's no binary incompatibility. If this and #3149 are merged, the core packages should be able to be linked statically, which would reduce packages needed during install to the minimum of just Git and Ruby.

**Comment by uberhacker** [comment]
Doesn't ruby still have a gcc dependency or did you figure out how to remove it?  Still doesn't hurt to test.

**Comment by JL2210** [comment]
That's my point: static linking **should** remove any external dependencies from the binary (a.k.a. `libssh2`, `libiconv`, and `gcc`).

**Comment by JL2210** [comment]
Ruby works fine after upgrading.

**Comment by JL2210** [comment]
And any newer PHP version (i.e not 5 or anything 7.2 or below) should compile and work just fine with this.
There also shouldn't be any issue with the binaries as long as the system still has openssl 1.0.

**Comment by uberhacker** [comment]
Sorry, but this breaks everything.  I cannot compile php with this version of openssl.

**Comment by uberhacker** [comment]
@skiman6010: Please do NOT merge this.  It is not ready yet.

**Comment by skiman6010** [comment]
Haha don't tell me what to do @uberhacker. I merge what I want.

**Pull request closed without merging**
