### PR TITLE
Add openssl again to fix tmux

### LINKED ISSUE #83: Tmux no longer installs
Looks like there are missing headers with the built in Openssl, which causes Tmux to not install anymore.

```
/bin/bash ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I./compat -I./include -I./include    -g -O2 -Wall -fno-strict-aliasing -pthread -MT bufferevent_openssl.lo -MD -MP -MF .deps/bufferevent_openssl.Tpo -c -o bufferevent_openssl.lo bufferevent_openssl.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./compat -I./include -I./include -g -O2 -Wall -fno-strict-aliasing -pthread -MT bufferevent_openssl.lo -MD -MP -MF .deps/bufferevent_openssl.Tpo -c bufferevent_openssl.c  -fPIC -DPIC -o .libs/bufferevent_openssl.o
bufferevent_openssl.c:60:25: fatal error: openssl/bio.h: No such file or directory
 #include <openssl/bio.h>
                         ^
compilation terminated.
make[2]: *** [bufferevent_openssl.lo] Error 1
make[2]: Leaving directory `/usr/local/tmp/crew/libevent-2.0.21-stable'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/usr/local/tmp/crew/libevent-2.0.21-stable'
make: *** [all] Error 2
libevent failed to install: `make` exited with 2
```

### PR DESCRIPTION
**Pull request by lyxell**
Adding the old openssl package, this should resolve #83.

### CODE REVIEW

**Comment by lyxell** [comment]
Looks like I missed issue #65, don't merge this until tested.

**Comment by thedamian** [comment]
TEST: PASSED

open ssl installed successfully.

Output: 
openssl-1.0.1e-chromeos-x86_64.tar 100%[=================================================================>]   3.28M  3.65MB/s   in 0.9s   
..............
2016-01-16 21:34:05 (3.65 MB/s) - 'openssl-1.0.1e-chromeos-x86_64.tar.gz' saved [3436167/3436167]
Archive downloaded
Unpacking archive, this may take a while...
Installing...
Openssl installed!

Don't know about the issue with tmux. but at least openssh.rb should be included

**Comment by thedamian** [comment]
TMUX TEST: PASSED

I'm on a x64 chromebook and did a 
$ crew install tmux

Output:
.....
/bin/mkdir -p /usr/local/tmp/crew//dest/usr/local/share/man/man1
/usr/bin/install -c -m 644 ./tmux.1.mdoc \
        /usr/local/tmp/crew//dest/usr/local/share/man/man1/tmux.1
make[2]: Leaving directory `/usr/local/tmp/crew/tmux-1.9a'
make[1]: Nothing to be done for `install-data-am'.
make[1]: Leaving directory `/usr/local/tmp/crew/tmux-1.9a'
Installing...
Tmux installed!

**Comment by skycocker** [comment]
@lyxell merged, thanks :) 
@thedamian thanks for the testing! it's really valuable for I guess everyone :)

**Pull request merged**
