### PR TITLE
Update tests/README.md

### PR DESCRIPTION
**Pull request by uberhacker**
Updated instructions based on my experience attempting to run tests.

### CODE REVIEW

**Comment by cstrouse** [comment]
It might be a good idea to add in some information about what the tests do and how they're intended to be integrated into the packaging workflow.

**Comment by uberhacker** [comment]
@yancouto: Did you want to chime in here and add some feedback?

**Comment by yancouto** [comment]
> It might be a good idea to add in some information about what the tests do

You mean some comments in each test explaining what it tests for? That would be good. I can create a PR to explain my no_cycle test.

> and how they're intended to be integrated into the packaging workflow

You mean saying something like `You should run these tests before submitting any Pull Request to make sure everything is working correctly.` in the README?

What I think is a better idea is to run the tests automatically using travis (like I said [here](https://github.com/skycocker/chromebrew/pull/963#issuecomment-326431863)), but I don't have permissions to do this.

**Comment by cstrouse** [comment]
Agreed that running the tests via a CI system is ideal.

I stand by adding some additional docs to the tests as being a good idea though regardless of when/if/how we automate things as they clarify your intent with the tests, the types of issues they're design to uncover, when in the package creation/maintenance/debugging process they're useful to be ran, etc.

Make it easy for someone to know why to run them, when to run them, and how to run them. Anything we can do to make testing easier and more understandable for people new to the project is a win.

**Comment by yancouto** [comment]
Is #1363 what you suggested? Sadly it conflicts with this PR.

**Comment by uberhacker** [comment]
@yancouto: No worries.  I'll just close this PR.  You are welcome to add the suggestions here in your PR.

**Pull request closed without merging**
