### PR TITLE
Update yarn from 1.12.0 to 1.12.1

### PR DESCRIPTION
**Pull request by uberhacker**

### CODE REVIEW

**Comment by JL2210** [comment]
No binaries?

**Comment by uberhacker** [comment]
Not needed.  It takes seconds to install.  Amazing that an app this powerful is this simple.

**Comment by JL2210** [comment]
I could see that. Meson, with what an incredible build system it is, takes less than a minute to compile and install, even though it has to precompile the .py files into Python bytecode!

**Comment by skiman6010** [comment]
Meson is incredible.

**Pull request merged**
