### PR TITLE
Update bash_completion instructions to improve clarity

### PR DESCRIPTION
**Pull request by uberhacker**

### CODE REVIEW

**Comment by jam7** [comment]
Not sure what you are trying to fix.  What error message you get?

**Comment by uberhacker** [comment]
Take a look at the PR title.

**Comment by jam7** [comment]
Hmm, did you see their homepage, https://github.com/scop/bash-completion?  It's identical what this package shows.  And it worked when I tested.

I guess that you miss typed in your .bashrc.

**Comment by uberhacker** [comment]
The fact that I mistyped should tell you something.  It's easy to miss the final message.  I have updated the instructions to match the project page and colorized to make it stand out visually.  Is that better?

**Comment by jam7** [comment]
Ya.  Now I understand what you want to do.  I'll review and merge soon.

**Comment by uberhacker** [comment]
By the way, thank you for adding this package @richard-fisher, it is a welcome addition.

**Pull request merged**
