### PR TITLE
Add Mesa

### PR DESCRIPTION
**Pull request by flyingP0tat0**
Next step towards #889.
Depends on #930 and #961.

OpenGL on Chromebooks! 🎉

### CODE REVIEW

**Comment by yancouto** [comment]
libXfixes has missing dependencies.

I checked the configure file, and the compilation worked when I added the dependencies 'fixesproto', 'xproto', 'xextproto' and 'libx11'.

After that everything compiled correctly 😄

**Comment by flyingP0tat0** [comment]
@yancouto Thank you!

**Comment by flyingP0tat0** [comment]
@jam7 I think this one is ready?

**Comment by jam7** [comment]
Thanks.  I'll try them tomorrow.  Sorry for reviewing others.

2017-08-06 18:46 GMT+09:00 Jan Baudisch <notifications@github.com>:

**Comment by flyingP0tat0** [comment]
@jam7 No worries. Thank you for keeping this repo alive!

**Pull request merged**
