### PR TITLE
Ruby -> 3.1.0

### PR DESCRIPTION
**Pull request by satmandu**
- New ruby version

Works properly in container:
- [x] x86_64
- [x] i686
- [x] armv7l

Tested & works properly on hardware:
- [x] x86_64
- [x] i686
- [ ] armv7l

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=ruby_31 CREW_TESTING=1 crew update
```

testing errors `x86_64`: 
```
1)
Process.setpriority sets the scheduling priority for a specified process FAILED
Expected [19, 0, 19] == [19, 0, 20]
to be truthy but was false
/usr/local/tmp/crew/ruby.20211226015242.dir/ruby-3.1.0/spec/ruby/core/process/setpriority_spec.rb:11:in `block (3 levels) in <top (required)>'
/usr/local/tmp/crew/ruby.20211226015242.dir/ruby-3.1.0/spec/ruby/core/process/setpriority_spec.rb:3:in `<top (required)>'

2)
Process.setpriority sets the scheduling priority for a specified process group FAILED
Expected [19, 0, 19] == [19, 0, 20]
to be truthy but was false
/usr/local/tmp/crew/ruby.20211226015242.dir/ruby-3.1.0/spec/ruby/core/process/setpriority_spec.rb:25:in `block (4 levels) in <top (required)>'
/usr/local/tmp/crew/ruby.20211226015242.dir/ruby-3.1.0/spec/ruby/core/process/setpriority_spec.rb:3:in `<top (required)>'

3)
RbConfig::CONFIG ['STRIP'] exists and can be executed FAILED
Expected #<Process::Status: pid 61088 exit 1>.success?
to be truthy but was false
/usr/local/tmp/crew/ruby.20211226015242.dir/ruby-3.1.0/spec/ruby/library/rbconfig/rbconfig_spec.rb:85:in `block (3 levels) in <top (required)>'
/usr/local/tmp/crew/ruby.20211226015242.dir/ruby-3.1.0/spec/ruby/library/rbconfig/rbconfig_spec.rb:4:in `<top (required)>'

4)
Socket.getnameinfo using IPv6 using a 3 element Array as the first argument using NI_NUMERICHOST as the flag returns an Array containing the numeric hostname and service name ERROR
SocketError: getaddrinfo: No address associated with hostname
/usr/local/tmp/crew/ruby.20211226015242.dir/ruby-3.1.0/spec/ruby/library/socket/socket/getnameinfo_spec.rb:111:in `getnameinfo'
/usr/local/tmp/crew/ruby.20211226015242.dir/ruby-3.1.0/spec/ruby/library/socket/socket/getnameinfo_spec.rb:111:in `block (6 levels) in <top (required)>'
/usr/local/tmp/crew/ruby.20211226015242.dir/ruby-3.1.0/spec/ruby/library/socket/socket/getnameinfo_spec.rb:65:in `<top (required)>'

Finished in 109.482565 seconds

3817 files, 30890 examples, 129050 expectations, 3 failures, 1 error, 0 tagged
make: *** [uncommon.mk:863: yes-test-spec] Error 1
```
testing errors `armv7l`:
```


  1) Failure:
TestReadline#test_interrupt_in_other_thread [/usr/local/tmp/crew/ruby.20211226045425.dir/ruby-3.1.0/test/readline/test_readline.rb:585]:
Unknown failure with exit status #<Process::Status: pid 45499 exit 1>
Log: ** START **Readline::VERSION is 8.1.
#<Thread:0xf4fe47d8 /usr/local/tmp/interrupt_in_other_thread20211226-35718-uuvcfx:9 run> terminated with exception (report_on_exception is true):
/usr/local/tmp/interrupt_in_other_thread20211226-35718-uuvcfx:13:in `readline': stack level too deep (SystemStackError)
	from /usr/local/tmp/interrupt_in_other_thread20211226-35718-uuvcfx:13:in `block in <main>'
/usr/local/tmp/interrupt_in_other_thread20211226-35718-uuvcfx:13:in `readline': stack level too deep (SystemStackError)
	from /usr/local/tmp/interrupt_in_other_thread20211226-35718-uuvcfx:13:in `block in <main>'

Killed by timeout
----

Finished tests in 7916.050461s, 2.7075 tests/s, 346.9148 assertions/s.
21433 tests, 2746195 assertions, 1 failures, 0 errors, 52 skips
```
testing errors `i686`: 
```
Finished tests in 3500.609432s, 6.1252 tests/s, 785.7155 assertions/s.
21442 tests, 2750483 assertions, 0 failures, 0 errors, 47 skips
```

### CODE REVIEW

**Comment by satmandu** [comment]
Rebuilding for `i686` to try to get around `stack-protector` issues...

**Comment by satmandu** [comment]
@uberhacker Could you tell me if this works on `armv7l`? I can test on the other hardware...

**Comment by uberhacker** [comment]
irb seems to be working fine but unable to execute `cycle_test` from the tests directory.
```
$ ruby cycle_test 
<internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- file (LoadError)
Did you mean?  fiddle
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from cycle_test:6:in `<main>'
```

**Comment by satmandu** [comment]
Let us hold off until `3.1.1` then...

**Comment by satmandu** [comment]
> irb seems to be working fine but unable to execute `cycle_test` from the tests directory.
> ```
> $ ruby cycle_test 
> <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- file (LoadError)
> Did you mean?  fiddle
>         from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
>         from cycle_test:6:in `<main>'
> ```
> 

Maybe we just ignore that error...

**Comment by satmandu** [comment]
building new binaries, and also rebuilding libffi, since there were errors with that ruby was complaining about on i686.

**Comment by satmandu** [comment]
updated builds. @saltedcoffii do these work for you?

**Pull request merged**
