### PR TITLE
Add wine package

### PR DESCRIPTION
**Pull request by flyingP0tat0**

### CODE REVIEW

**Comment by finwo** [comment]
Has this been tested on platforms other than amd64?

**Comment by flyingP0tat0** [comment]
No, it has not. I only have a x86_64 chromebook.

**Comment by lyxell** [comment]
The `--enable-win64` will likely break installation on other architectures, I'll wait with merging this until it's tested on arm/aarch64.

**Comment by flyingP0tat0** [comment]
Yes, I already thought about that. Should I make two sperate packages? (something like wine and wine64)

**Comment by flyingP0tat0** [comment]
@lyxell Yes, I already thought about that. Should I make two sperate packages? (something like wine and wine64)

**Comment by lyxell** [comment]
If the --enable-win64 flag really is needed for x86_64, a case switch inside wine.rb determining what to do for the specific architectures would be needed.

**Comment by flyingP0tat0** [comment]
I deleted my wine branch, will create a new pull request.

**Pull request closed without merging**
