### PR TITLE
readline & python27 updated

### PR DESCRIPTION
**Pull request by thedamian**

### CODE REVIEW

**Comment by ZelectroKarZ** [comment]
Well why didn't you tell me earlier? Can I merge this code into my fork?

**Comment by thedamian** [comment]
What are you referring to? And did you mean to add a smiley face at the end of that?

**Comment by ZelectroKarZ** [comment]
No. I said I wanted to merge your code into my release...

**Comment by thedamian** [comment]
@ZelectroKarZ you are welcome to merge anything I have into your release.
if @skycocker were to merge some of these releases you wouldn't have to. but until then you are very welcome to.

**Comment by thedamian** [comment]
merged

**Pull request merged**
