### PR TITLE
Remove need for wget

### PR DESCRIPTION
**Pull request by saltedcoffii**
For a while I've wondered why we had `wget` in our core packages list since we have curl.
This removes wget from the core package list and removes the requirement for the package in that list entirely.

### CODE REVIEW

**Comment by saltedcoffii** [comment]
Alright, ready to merge, works on x86_64

**Comment by satmandu** [comment]
Looks like you missed some.
```
grep wget * | grep -v wget.rb
buildessential.rb:  depends_on 'wget' # in some cases, patches might be required and can be downloaded using wget
dr.rb:    system 'wget -O dr/dr https://github.com/Ewpratten/dr/releases/download/2.0-cros/dr'
iniparser.rb:    system 'wget', 'https://github.com/ndevilla/iniparser/commit/a249509544972d60f5077bfde554af480bd82594.patch'
js78.rb:    system('wget', '--continue', '--no-check-certificate', patch_url, '-O', 'unzippatches.tar.xz')
nmon.rb:    system 'wget http://downloads.sourceforge.net/project/nmon/lmon16g.c'
wp_cli.rb:    system "wget https://github.com/wp-cli/wp-cli/releases/download/v#{version}/wp-cli-#{version}.phar"
wput.rb:  description 'wput is a command line file upload tool, the opposite of wget'
```

**Comment by saltedcoffii** [comment]
> Looks like you missed some.

I got those in this PR

**Comment by satmandu** [comment]
@saltedcoffii  You need `wp_cli.rb`

**Review by satmandu — APPROVED** [review]

**Comment by uberhacker** [comment]
Bump buildessentials version?

**Pull request merged**
