### PR TITLE
Upgrade openssl from 1.0.2j to 1.0.2k

### LINKED ISSUE #415: Cannot install OpenSSL (needed for Vim), "No such file 'openssl-1.0.2j.tar.gz'."
Hi,

I just installed Chromebrew to use Vim on my Dell Chromebook 13. I got the followning error when trying to install openssl:

```
Found openssl, version 1.0.2j
No precompiled binary available for your platform, downloading source...
--2017-01-27 12:53:32--  ftp://openssl.org/source/openssl-1.0.2j.tar.gz
           => 'openssl-1.0.2j.tar.gz'
Resolving openssl.org... 194.97.150.234
Connecting to openssl.org|194.97.150.234|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /source ... done.
==> SIZE openssl-1.0.2j.tar.gz ... done.

==> PASV ... done.    ==> RETR openssl-1.0.2j.tar.gz ... 
No such file 'openssl-1.0.2j.tar.gz'.

Checksum mismatch :/ try again
```

I've tried a number of times, every time with the same results.

Other information:

- Chromebrew: HEAD is now at 5650208
- Chrome Version 55.0.2883.105 (64-bit)
- Platform 8872.76.0 (Official Build) stable-channel lulu
- ARC Version 3617689

Please let me know if I can provide any further information to help debug this issue.

### PR DESCRIPTION
**Pull request by uberhacker**
Resolves #415 and #424.

### CODE REVIEW

**Comment by uberhacker** [comment]
I just noticed this PSA on the project home page so we probably should upgrade:
```
26-Jan-2017OpenSSL 1.0.2k is now available, including bug and security fixes
```

**Comment by uberhacker** [comment]
Hey guys,.
Can we please git this merged soon?  It breaks every package install that has this as a dependency currently.
Thanks

**Comment by cstrouse** [comment]
+1

**Comment by dihuta** [comment]
I have this issue today.
==> PASV ... done.    ==> RETR openssl-1.0.2k.tar.gz ... 
No such file 'openssl-1.0.2k.tar.gz'.

**Comment by uberhacker** [comment]
Hey @dihuta: PR #688 should fix this issue.

**Comment by dihuta** [comment]
Hi @uberhacker 
Could you help me how to update to PR #688?
Thank you.

**Comment by dihuta** [comment]
I edited the file, it works well now.
Thank you.

**Comment by uberhacker** [comment]
Hi @dihuta:
The easiest way would be to edit the file directly in the shell.  See below:
```
$ nano /usr/local/lib/crew/packages/openssl.rb
```
Change:
```
-  source_url 'ftp://openssl.org/source/openssl-1.0.2k.tar.gz'
+  source_url 'https://www.openssl.org/source/openssl-1.0.2k.tar.gz'
```
Then save and exit and attempt to install the package that has the openssl dependency or try and install the openssl package by itself.
```
$ crew install openssl
```

**Comment by uberhacker** [comment]
@dihuta: jinx LoL

**Pull request merged**
