### PR TITLE
Add pre-built binaries for fakeroot, nano and wireless_tools

### PR DESCRIPTION
**Pull request by uberhacker**

### CODE REVIEW

**Comment by JL2210** [comment]
Sorry about the `fakeroot` URL. It was late at night and I was tired.

**Comment by uberhacker** [comment]
No problem.  These things usually aren't missed with proper testing. :)

**Comment by JL2210** [comment]
For some odd reason, I as able to install it. Or, maybe that was nano.

**Comment by uberhacker** [comment]
I appreciate your efforts and all these new packages!  Once you get set up on the i686 VM, try and take a shot at building the pre-built binaries and upload to bintray.com.  This should help with your testing also.  If you can install from the pre-built binaries, it proves you have actually tested the package(s).

**Comment by JL2210** [comment]
Yeah. BTW, your `install.sh` PR is still not merged yet. I know you're against it, but could you double check your work and commit directly to the repository? I can't do anything on the i686 VM if that's not merged.

**Comment by uberhacker** [comment]
I won't merge my own commits but what you can do is checkout my PR branch and install.  That should work and you could help test and approve this PR.

**Comment by JL2210** [comment]
Good idea!

**Comment by uberhacker** [comment]
Try this:
```
wget -q -O - https://raw.githubusercontent.com/uberhacker/chromebrew/fix-broken-git-i686/install.sh | bash
```

**Pull request merged**
