### PR TITLE
Add R package

### LINKED ISSUE #228: Add R to the list of packages?
Is there any way to install [R](https://www.r-project.org/) with Chromebrew? Thanks! :)

### PR DESCRIPTION
**Pull request by lyxell**
Fixes #228, tested on ARM.

### CODE REVIEW

**Comment by thedamian** [comment]
Looks good!

Merged.

**Comment by danilofreire** [comment]
Thanks for your work! However, the code doesn't seem to work on my Lenovo N22. Error messages: https://gist.github.com/danilofreire/a15aaba8463180afa5921edf48042160

Any suggestions? Thanks again :)

**Comment by lyxell** [comment]
@danilofreire Oh yeah, you're totally right. The ARM toolchain has a Fortran compiler included while the x86 ones hasn't, I'll figure out a solution.

**Comment by BobbyBobster** [comment]
@lyxell Have you found anything yet? I have tried to manually install g95 and gfortran on my Toshiba Chromebook 2 but could not get those to work. 

Is there a possibility of including gfortran in the version of gcc that can be downloaded via Chromebrew?

Thanks in advance.

**Comment by riceshrug** [comment]
bump. acer cb131, can't install (build) r due to fortran dependancy:

configure: error: No F77 compiler found
r failed to install: `./configure --with-x=no` exited with 1

**Pull request merged**
