### PR TITLE
Add reload_constants command

### PR DESCRIPTION
**Pull request by uberhacker**
Also reduces clutter in packages.

### CODE REVIEW

**Comment by satmandu** [comment]
Does it make sense to use this as a `crew reload` command?

Don't the variables get reloaded based upon current env variables every time one runs crew?

**Comment by uberhacker** [comment]
Does this work?
```
$ export CREW_NOT_STRIP='1'
$ crew const CREW_NOT_STRIP
```
If so, then we don't need the `crew reload` command.

**Comment by satmandu** [comment]
> Does this work?
> ```
> $ export CREW_NOT_STRIP='1'
> $ crew const CREW_NOT_STRIP
> ```
> If so, then we don't need the `crew reload` command.

**Comment by uberhacker** [comment]
We don't need it.  I'll remove.

**Pull request merged**
