### PR TITLE
Added bind version 9.10.4 and Subversion 1.9.5 (with dependencies)

### PR DESCRIPTION
**Pull request by ntchambers**
This currently works on x86_64. I don't have access to any other chromebook arch, but I don't see any reason why it wouldn't work.

### CODE REVIEW

**Comment by minektur** [comment]
Is there any reason you have to specify the arch on the build line? It
would make life easier if it could autodetect.... It might do it
automatically... Or there are some packages that handle multiple
architectures....

Any chance?

**Comment by ntchambers** [comment]
No. My apologies. I added it for some initial testing and forgot to remove it. Its updated with a proper build script.

**Comment by ntchambers** [comment]
On my quest to package swift, I ended up making packages for apr, apr-util, and svn (which depends on the former too) and have added them to this pull request.

**Comment by jam7** [comment]
Nice.  All of them works fine on armv7l too.

**Pull request merged**
