### PR TITLE
Add libblockdev package

### PR DESCRIPTION
**Pull request by Zopolis4**
## Description
Adds the libblockdev package (part of the same larger package as #6766).

- Also updated `gpgme`

## Additional information
Depends on #6775 

Works properly:
- [x] armv7l
- [x] x86_64
- [ ] i686 (dependency does not build for this arch)

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/Zopolis4/chromebrew.git CREW_TESTING_BRANCH=libblockdev CREW_TESTING=1 crew update
```
---

### CODE REVIEW

**Comment by satmandu** [comment]
Build fails:
```
libtool: link: (cd ".libs" && rm -f "libbd_dm.so.2" && ln -s "libbd_dm.so.2.0.0" "libbd_dm.so.2")
libtool: link: (cd ".libs" && rm -f "libbd_dm.so" && ln -s "libbd_dm.so.2.0.0" "libbd_dm.so")
libtool: link: ( cd ".libs" && rm -f "libbd_dm.la" && ln -s "../libbd_dm.la" "libbd_dm.la" )
make[3]: Leaving directory '/usr/local/tmp/crew/libblockdev.20220304173257.dir/libblockdev-2.26/src/plugins'
make[2]: *** [Makefile:1251: all-recursive] Error 1
make[2]: Leaving directory '/usr/local/tmp/crew/libblockdev.20220304173257.dir/libblockdev-2.26/src/plugins'
make[1]: *** [Makefile:431: all-recursive] Error 1
make[1]: Leaving directory '/usr/local/tmp/crew/libblockdev.20220304173257.dir/libblockdev-2.26/src'
make: *** [Makefile:508: all-recursive] Error 1
libblockdev failed to build: `CFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=gold" CXXFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=gold" FCFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=gold" FFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=gold" LDFLAGS="-flto" bash -c make -j4` exited with 2
```

**Comment by Zopolis4** [comment]
> Build fails:
> ```
> libtool: link: (cd ".libs" && rm -f "libbd_dm.so.2" && ln -s "libbd_dm.so.2.0.0" "libbd_dm.so.2")
> libtool: link: (cd ".libs" && rm -f "libbd_dm.so" && ln -s "libbd_dm.so.2.0.0" "libbd_dm.so")
> libtool: link: ( cd ".libs" && rm -f "libbd_dm.la" && ln -s "../libbd_dm.la" "libbd_dm.la" )
> make[3]: Leaving directory '/usr/local/tmp/crew/libblockdev.20220304173257.dir/libblockdev-2.26/src/plugins'
> make[2]: *** [Makefile:1251: all-recursive] Error 1
> make[2]: Leaving directory '/usr/local/tmp/crew/libblockdev.20220304173257.dir/libblockdev-2.26/src/plugins'
> make[1]: *** [Makefile:431: all-recursive] Error 1
> make[1]: Leaving directory '/usr/local/tmp/crew/libblockdev.20220304173257.dir/libblockdev-2.26/src'
> make: *** [Makefile:508: all-recursive] Error 1
> libblockdev failed to build: `CFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=gold" CXXFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=gold" FCFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=gold" FFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=gold" LDFLAGS="-flto" bash -c make -j4` exited with 2
> ```

What architecture? I can't really see an obvious error here, do you have buildessential installed? I can't really think of anything else that would cause a mysterious failure.

**Comment by satmandu** [comment]
```
/bin/bash ../../libtool  --tag=CC   --mode=link x86_64-cros-linux-gnu-gcc -I/usr/local/include/glib-2.0 -I/usr/local/lib64/glib-2.0/include  -I/usr/local/include/blkid -I/usr/local/include/nss -I/usr/local/include/nspr -Wall -Wextra -Werror -O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=gold -std=gnu99 -L./../utils/ -version-info 2:0:0 -Wl,--no-undefined -flto -o libbd_crypto.la -rpath /usr/local/lib64 libbd_crypto_la-crypto.lo ./../utils/libbd_utils.la -lglib-2.0 -lcryptsetup -lssl3 -lsmime3 -lnss3 -lnssutil3 -lplds4 -lplc4 -lnspr4 -lblkid -lvolume_key 
mv -f .deps/libbd_vdo_la-vdo.Tpo .deps/libbd_vdo_la-vdo.Plo
/bin/bash ../../libtool  --tag=CC   --mode=link x86_64-cros-linux-gnu-gcc -I/usr/local/include/glib-2.0 -I/usr/local/lib64/glib-2.0/include  -Wall -Wextra -Werror  -O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=gold -std=gnu99 -L./../utils/ -version-info 2:0:0 -Wl,--no-undefined -flto -o libbd_dm.la -rpath /usr/local/lib64 libbd_dm_la-dm.lo libbd_dm_la-check_deps.lo ./../utils/libbd_utils.la -lglib-2.0 -ldevmapper -ludev -ldmraid 
/bin/grep: /usr/local/lib64/libgpgme.la: No such file or directory
/usr/local/bin/sed: can't read /usr/local/lib64/libgpgme.la: No such file or directory
libtool:   error: '/usr/local/lib64/libgpgme.la' is not a valid libtool archive
make[3]: *** [Makefile:902: libbd_crypto.la] Error 1
make[3]: *** Waiting for unfinished jobs....
```
Looks like you need a `gpgme` dep...

**Comment by Zopolis4** [comment]
Added, try building again?

**Comment by satmandu** [comment]
Built binaries for this and updated the `gpgme` dependency and added that here too.

**Comment by satmandu** [comment]
(sorry to overwrite your changes... I was already building.)

**Review by satmandu — APPROVED** [review]

**Pull request merged**
