### PR TITLE
Add cron package

### PR DESCRIPTION
**Pull request by uberhacker**
Gotta have it.

### CODE REVIEW

**Comment by thedamian** [comment]
How did we NOT have this package before. AWESOME!

**Comment by thedamian** [comment]
Damn! On my Chromebook pixel (intel 64bit i5)

I ended the error with this:

In file included from /usr/local/include/sys/syscall.h:31:0,
                 from /usr/local/include/syscall.h:1,
                 from random.c:81:
random.c: In function ‘fill_random_bytes_syscall’:
random.c:525:16: error: ‘__NR_getrandom’ undeclared (first use in this function)
  ret = syscall(SYS_getrandom, seed, size, flags);
                ^
random.c:525:16: note: each undeclared identifier is reported only once for each function it appears in
random.c: At top level:
cc1: warning: unrecognized command line option "-Wno-self-assign" [enabled by default]
cc1: warning: unrecognized command line option "-Wno-constant-logical-operand" [enabled by default]
cc1: warning: unrecognized command line option "-Wno-parentheses-equality" [enabled by default]
cc1: warning: unrecognized command line option "-Wno-tautological-compare" [enabled by default]
make: *** [random.o] Error 1
make: *** Waiting for unfinished jobs....
ruby failed to install: `make -j4` exited with 2

Where do I look for a log of wher this issue is.

**Comment by uberhacker** [comment]
Hey @thedamian: Thanks for taking a look at this.  Did the patch apply without errors?  You might check `tail /var/log/messages`.

**Comment by thedamian** [comment]
I'll double check this code again. Can you re-submit it. Sorry. I didn't mean to revert it and remove it from the package list.

It didn't install on my box, but maybe it's the same dependency as moreutils.rb? 

if this code now works then we know the same dependency (does that make sense?

place resubmit it and I'l check again. (Currently system it's installing my node updates to make sure MY PR is ok)

**Comment by thedamian** [comment]
@uberhacker No go. Same results. Here's my results from tail --lines=1000 /var/log/messages


2017-06-19T00:48:41.907265-04:00 INFO periodic_scheduler[17661]: cleanup_logs: job completed
2017-06-19T00:48:56.326533-04:00 NOTICE temp_metrics[17751]: Throttling (temps: 1:38:7:38:9:67:): 1801000 800000 1150 0 0x180aa00dd8088 # no throttling
2017-06-19T00:49:06.430413-04:00 NOTICE temp_metrics[17852]: Throttling (temps: 1:38:7:39:9:65:): 1801000 800000 1150 0 0x180aa00dd8080 # cap pkg to 16W
2017-06-19T00:50:39.336914-04:00 CRIT kernel: [10970.504405] CPU1: Package power limit notification (total events = 8590)
2017-06-19T00:50:39.336931-04:00 CRIT kernel: [10970.504407] CPU0: Package power limit notification (total events = 8590)
2017-06-19T00:50:39.336934-04:00 CRIT kernel: [10970.504412] CPU2: Package power limit notification (total events = 8590)
2017-06-19T00:50:39.336941-04:00 CRIT kernel: [10970.504414] CPU3: Package power limit notification (total events = 8590)
2017-06-19T00:50:39.347922-04:00 INFO kernel: [10970.515311] CPU1: Package power limit normal
2017-06-19T00:50:39.347938-04:00 INFO kernel: [10970.515313] CPU2: Package power limit normal
2017-06-19T00:50:39.347940-04:00 INFO kernel: [10970.515314] CPU3: Package power limit normal
2017-06-19T00:50:39.347946-04:00 INFO kernel: [10970.515315] CPU0: Package power limit normal
2017-06-19T00:50:40.757972-04:00 WARNING debugd[1207]: Failed to open procfs entry of process 18313
2017-06-19T00:50:40.759457-04:00 WARNING debugd[1207]: Failed to open uid map file /proc/18313/uid_map for process 18313
2017-06-19T00:50:40.759489-04:00 WARNING debugd[1207]: Invalid pid 18313, operation not allowed




ERROR NOW::

                ^
../.././ext/psych/yaml/emitter.c: At top level:
cc1: warning: unrecognized command line option "-Wno-constant-logical-operand"
cc1: warning: unrecognized command line option "-Wno-parentheses-equality"
cc1: warning: unrecognized command line option "-Wno-tautological-compare"
compiling ../.././ext/psych/yaml/writer.c
compiling ../.././ext/psych/yaml/scanner.c
../.././ext/psych/yaml/scanner.c: In function ‘yaml_parser_decrease_flow_level’:
../.././ext/psych/yaml/scanner.c:1189:23: warning: variable ‘dummy_key’ set but not used [-Wunused-but-set-variable]
     yaml_simple_key_t dummy_key;    /* Used to eliminate a compiler warning. */
                       ^
../.././ext/psych/yaml/scanner.c: At top level:
cc1: warning: unrecognized command line option "-Wno-constant-logical-operand"
cc1: warning: unrecognized command line option "-Wno-parentheses-equality"
cc1: warning: unrecognized command line option "-Wno-tautological-compare"
compiling ../.././ext/psych/yaml/dumper.c
compiling ../.././ext/psych/yaml/api.c
../.././ext/psych/yaml/api.c: In function ‘yaml_document_delete’:
../.././ext/psych/yaml/api.c:1121:7: warning: variable ‘context’ set but not used [-Wunused-but-set-variable]
     } context;
       ^
../.././ext/psych/yaml/api.c: At top level:
cc1: warning: unrecognized command line option "-Wno-constant-logical-operand"
cc1: warning: unrecognized command line option "-Wno-parentheses-equality"
cc1: warning: unrecognized command line option "-Wno-tautological-compare"
compiling ../.././ext/psych/yaml/reader.c
linking shared-object psych.so
installing default psych libraries
make[2]: Leaving directory '/usr/local/tmp/crew/ruby-2.4.1.tar.xz.dir/ruby-2.4.1/ext/psych'
make[2]: Entering directory '/usr/local/tmp/crew/ruby-2.4.1.tar.xz.dir/ruby-2.4.1/ext/pty'
compiling pty.c
linking shared-object pty.so
installing default pty libraries
make[2]: Leaving directory '/usr/local/tmp/crew/ruby-2.4.1.tar.xz.dir/ruby-2.4.1/ext/pty'
make[2]: Entering directory '/usr/local/tmp/crew/ruby-2.4.1.tar.xz.dir/ruby-2.4.1/ext/racc/cparse'
compiling cparse.c
linking shared-object racc/cparse.so
make[2]: Leaving directory '/usr/local/tmp/crew/ruby-2.4.1.tar.xz.dir/ruby-2.4.1/ext/racc/cparse'
make[2]: Entering directory '/usr/local/tmp/crew/ruby-2.4.1.tar.xz.dir/ruby-2.4.1/ext/rbconfig/sizeof'
compiling sizes.c
linking shared-object rbconfig/sizeof.so
make[2]: Leaving directory '/usr/local/tmp/crew/ruby-2.4.1.tar.xz.dir/ruby-2.4.1/ext/rbconfig/sizeof'
make[2]: Entering directory '/usr/local/tmp/crew/ruby-2.4.1.tar.xz.dir/ruby-2.4.1/ext/readline'
compiling readline.c
linking shared-object readline.so
make[2]: Leaving directory '/usr/local/tmp/crew/ruby-2.4.1.tar.xz.dir/ruby-2.4.1/ext/readline'
make[2]: Entering directory '/usr/local/tmp/crew/ruby-2.4.1.tar.xz.dir/ruby-2.4.1/ext/ripper'
compiling ripper.c
Assembler messages:
Fatal error: can't create ripper.o: No such file or directory
make[2]: *** [Makefile:285: ripper.o] Error 1
make[2]: Leaving directory '/usr/local/tmp/crew/ruby-2.4.1.tar.xz.dir/ruby-2.4.1/ext/ripper'
make[1]: *** [exts.mk:245: ext/ripper/all] Error 2
make[1]: Leaving directory '/usr/local/tmp/crew/ruby-2.4.1.tar.xz.dir/ruby-2.4.1'
make: *** [uncommon.mk:220: build-ext] Error 2
ruby failed to install: `make -j4` exited with 2

Again, it could very well be me.

**Pull request merged**
