### PR TITLE
Add manpages

### LINKED ISSUE #27: Could we get Man-pages?
Okay, this may not be a chromebrew specific issue, 
But I was looking for a way to install man pages into crosh...

I checked out the following man-pages, and I've installed the manuals from below
https://www.kernel.org/doc/man-pages/

however, I haven't been able to find the actual man 'reader' binary, or source code...

Any ideas?

### PR DESCRIPTION
**Pull request by lyxell**
This pull request adds support for `man`, however, chromeos has some environment variables set per default, among them is `PAGER=/usr/bin/less`, so, in order to use the `man` command, one first has to `unset PAGER`. I'm not sure whether there is a way to solve this.

Fixes #27

### CODE REVIEW

**Comment by bfayers** [comment]
You could add ```unset PAGER``` to ~/.bashrc like this in self.install : ```system "sed -i '$ a unset PAGER' ~/.bashrc"``` OR you could put it in /etc/environment like this: ```system "sed -i '$ a PAGER=/usr/local/bin/less' /etc/environment"```

**Comment by lyxell** [comment]
Yeah, I guess, but I'd prefer to not fiddle with the users files, and `/etc/environment` is mounted read-only. I think it would be better to print instructions and let the users do it manually in the way they prefer.

**Comment by thedamian** [comment]
@lyxell why not do both?
Just a suggestion. 

I mean why not DO it and then WARN WITH A BIG WARNING, that you did it. 

that way no one is missing the change by mistake. 

Can you do one of both,and I'll merge it asap.

**Comment by lyxell** [comment]
Doing that would be bad practice and hostile against the users. I've added a message letting the user take actions themselves.

**Comment by bfayers** [comment]
Works! if the unset PAGER is done.

**Comment by lyxell** [comment]
We don't have write access to `/usr/bin`.

**Comment by thedamian** [comment]
@lyxell

I don't agree with hoping the user sees the comment and does something after the crew install package but you do nothing but excellent work here so how can I not merged this great pull.

**Pull request merged**
