### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sajjaadf**
Add the new Fixes Plus New Patch1

### CODE REVIEW

**Comment by uberhacker** [comment]
Can you please reduce the size of the Chromebrew image?  It's a bit on the large side. :)  See https://github.com/sajjaadf/chromebrew-Dev/tree/patch-1.

**Comment by uberhacker** [comment]
Also, what happened to the Discord logo?

**Comment by JL2210** [comment]
I wouldn't necessarily say GUI apps are working.

**Comment by sajjaadf** [comment]
Okay okay
[image: Picture]
Sajjaad Farzad
About Me
<https://about.me/sajjaadf?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>

**Comment by sajjaadf** [comment]
The image wont appear on my computer
[image: Picture]
Sajjaad Farzad
About Me
<https://about.me/sajjaadf?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>

**Pull request closed without merging**
