### PR TITLE
Fix mixed triple issue

### PR DESCRIPTION
**Pull request by saltedcoffii**
Chromebrew has had the weirdest problem that I originally noticed a few months ago but didn't know what it was. Sometimes chromebrew's host triplet is what it should be: `#{ARCH}-cros-linux-gnu`. Other times, it's `#{ARCH}-pc-linux-gnu`.

This fix allows newly compiled packages to properly identify the current triplet being used and, if need be, cross compile. This fix will only cause compiling packages to cross compile if the `--build` is different than `--host`.

I've made this change and compiled multiple packages, including core packages, and I noticed no problems (except with glibc, however that's an unrelated issue that occurs without this change, relevant issue here: #5398)

After merging this, it would be prudent to recompile binaries for `binutils`, `gcc` and potentially `llvm`.

### CODE REVIEW

**Comment by uberhacker** [comment]
I'm confused why we would need to recompile binaries if the host and target are the same.  Also, if you are going to introduce a new constant, that should also be added to `crew` so `crew const` can return the value.  That means bumping the crew version as well.

**Comment by saltedcoffii** [comment]
For some reason, they aren't. Sometimes autotools configure scripts will find `#{ARCH}-cros-linux-gnu` as the build machine and host (because it was passed these arguments), so it won't cross compile. But because the triple is actually `#{ARCH}-pc-linux-gnu`, and it's not cross compiling (because the passed --build and --host are the same) it will compile with the triple `#{ARCH}-pc-linux-gnu`. Watch a configure script that hasn't been passed these arguments (run outside of chromebrew most likely) and you'll see what I'm talking about. Hopefully that makes sense.

**Comment by saltedcoffii** [comment]
Also would you mind updating crew? I don't wanna break anything.

**Comment by satmandu** [comment]
@saltedcoffii modified `crew` and `CREW_VERSION` for you.

**Pull request merged**
