### PR TITLE
Allow for SHA-256, update ruby_latest and Oracle JDK8

### PR DESCRIPTION
**Pull request by bmorris22**
Brought the more secure SHA-2 class to crew, allowing new packages to be verified with sha-256 and old packages to be migrated. Updated ruby_latest the the newest stable version of Ruby 2.3 and added Oracle's JDK 8u91,

### CODE REVIEW

**Comment by thedamian** [comment]
Great pull. Great additions.

Now I tried to upgrade ruby and people were complaining because this would cause the version in the packages to automatically higher than what they already have installed without them knowing. So in this case we might want to add something to the install.sh to warn the user of this.

**Comment by bmorris22** [comment]
I didn't think about that. What if I created a ruby-2.3 package and just updated this to 2.2.5?

**Comment by bmorris22** [comment]
What we need is an rvm or rbenv package

**Comment by thedamian** [comment]
@bmorris22 

Well what do you think? I created a node_stable and because no now calls their most up to date version (as opposed to their TLS version) they call it CURRENT. now I have to keep up to date TWO versions.

I know this is a different issue, but maybe we SHOULD have just a message in the install.sh to let the user knows.

with the updates in chrome os new crew is giving me segment failt with every call but so is a bunch of other methods, so there are a couple of things that will need to be rebuilt and upgraded.

**Comment by bmorris22** [comment]
I'm getting the same error! As soon as I get home, I'm going to submit an issue report.

**Comment by thedamian** [comment]
@bmorris22 this pull works perfectly!

I had to format my chromebook pixel because of the segment fail issue (which is on something else) I installed the crew with the normal install.sh 

AND THEN I updated the crew, package.rb and ruby_latest.rb from THIS pull.

then I installed ruby_latest flawlessly. 

But everything here looks perfectly. I haven't tried JDK yet but I will but I don't see any issues with the rest and you just updated the version of JDK and added your SHA256 (which worked in ruby_latest just fine)

**Comment by bmorris22** [comment]
Thanks! Yeah, I've been busy the past two days, but I have to format my Acer Chromebook too. I'd really like to dive into this readline problem tomorrow.

**Comment by thedamian** [comment]
@bmorris22
Damn! I'm scared of this. If you don't mind I'll test this out on my chromebook before testing it. 

I'm worried that people will get the latest version of packages with the sha256 and since they used their old version of the crew app it won't know what to do.

I think we'll have to pause of this for later (my oppinion) please tell me why I'm wrong.

**Comment by bmorris22** [comment]
I'll close this. Are there any active forks of this repo?

**Pull request closed without merging**
