### PR TITLE
Update vim from 8.1.2225 to 8.1.2234

### PR DESCRIPTION
**Pull request by cstrouse**
Tested on ARM.

### CODE REVIEW

**Comment by uberhacker** [comment]
Update gvim also?

**Comment by uberhacker** [comment]
@cstrouse: Can you please include the gvim update with this PR.  Then it will be good to merge.  Actually, since it's already been a few days, a newer release is available. :)

**Comment by cstrouse** [comment]
Just updated to the new release for all three vim packages.

**Comment by uberhacker** [comment]
Excellent!  Thank you!

**Pull request merged**
