### PR TITLE
Update jdk8 from 8u131 to 8u144

### LINKED ISSUE #966: jdk8 without javac
Hi I've been ignoring it for a while but now 
I would need javac and it's missing from the 
package recently. It used to be included 
some months ago and it worked perfectly.

### PR DESCRIPTION
**Pull request by uberhacker**
Resolves #966.

### CODE REVIEW

**Comment by jam7** [comment]
It fails on armv7l.
```
$ crew install jdk8
...
jdk1.8.0_144/release
jdk1.8.0_144/src.zip
cp: cannot stat 'jre/plugin/': No such file or directory
jdk8 failed to install: `cp -r jre/plugin/ /usr/local/tmp/crew/dest/usr/local` exited with 1
```
Do we really need to perform below?
```
+      system "cp -r db/bin/ #{CREW_DEST_DIR}/usr/local"
 +      system "cp -r db/lib/ #{CREW_DEST_DIR}/usr/local"
 +      system "cp -r include/ #{CREW_DEST_DIR}/usr/local"
 +      system "cp -r jre/bin/ #{CREW_DEST_DIR}/usr/local"
 +      system "cp -r jre/lib/ #{CREW_DEST_DIR}/usr/local"
 +      system "cp -r jre/plugin/ #{CREW_DEST_DIR}/usr/local"
```
For example `cp -r db/bin ...` copies all following files directly into `local/bin`.
```
$ ls db/bin
NetworkServerControl      derby_common.bat  setEmbeddedCP.bat       setNetworkServerCP.bat  stopNetworkServer.bat
NetworkServerControl.bat  ij                setNetworkClientCP      startNetworkServer      sysinfo
dblook                    ij.bat            setNetworkClientCP.bat  startNetworkServer.bat  sysinfo.bat
dblook.bat                setEmbeddedCP     setNetworkServerCP      stopNetworkServer
```

**Comment by uberhacker** [comment]
@jam7: What happens if you remove the `jre/plugin/` line?  I think we can probably safely not include the files in this folder on other architectures also.  What is wrong with including the `db/bin` executables?

**Comment by jam7** [comment]
Removing that line will solve this problem.

I'm not sure why we need `db`, `include` and `jre` stuff.  In this PR, you added `db/bin`, `db/lib`, `include`, `jre/bin`, `jre/lib` and `jre/plugin` as a target of `cp -r` command.  It increase the number of programs installed.  If all of them are necessary, it's OK.  I just don't understand the needs.  Please explain or point release note or something.

**Comment by uberhacker** [comment]
We don't need everything, but when you start excluding java libraries, epic fail crashes occur.  The `jre/bin` directory is actually the most important as it includes the main java executables.  Try removing stuff and you will quickly understand what I mean.

**Comment by jam7** [comment]
@uberhacker those files are identical files.
```
$ cd jdk1.8.0_144
$ for i in jre/bin/*; do cmp bin/`basename $i` $i; done
$
```
How about modifying it like below?  I modified [official installation guide](https://docs.oracle.com/javase/8/docs/technotes/guides/install/linux_jdk.html#BJFJJEFG_) to match chromebrew environment.
```
    system "mkdir -p #{CREW_DEST_DIR}#{CREW_LIB_PREFIX}/jdk8"
    FileUtils.cd('jdk1.8.0_144') do
      system "rm -f src.zip"
      system "cp -r * #{CREW_DEST_DIR}#{CREW_LIB_PREFIX}/jdk8"
    end
    system "mkdir -p #{CREW_DEST_DIR}#{CREW_PREFIX}/bin"
    FileUtils.cd("#{CREW_DEST_DIR}#{CREW_PREFIX}/bin") do
      system "ln -s ../../../#{CREW_LIB_PREFIX}/jdk8/bin/* ."
    end
```
This will create LIB/jdk8 directory and install everything there except source code.  Then, make a symbolic link for LIB/jdk8/bin/* commands from /usr/local/bin for the ease of use.

**Comment by uberhacker** [comment]
@jam7: I will test your solution this evening.  Thanks

**Comment by uberhacker** [comment]
@jam7: I tested your suggestion and it works great!  I have pushed up a new commit.

**Pull request merged**
