### PR TITLE
Discord and Slack Logos

### PR DESCRIPTION
**Pull request by superloach**
Added proper logos for Slack and Discord, with links to both.
Chat is synced between services by 30 lines of Python I wrote! 😝

Like so:
<a href="https://join.slack.com/t/chromebrew/shared_invite/enQtNDA2MTQ5ODQ3NDc2LTA0ZmJlMGFmNmZhOTYwNDE3ZDY0NDA0MWI0OTE3MzJkYTQxN2UxMWQ1YTEzOWFmNTliMGM4NDZjYzY2NjczZGE" target="_blank">image</a><a href="https://discord.gg/QRrzBXN" target="_blank">image</a>

### CODE REVIEW

**Comment by superloach** [comment]
For some reason the rich diff doesn't load the images right, but you can check [the actual branch](https://github.com/superloach/chromebrew/blob/chat_logos/README.md) if you want.

**Comment by uberhacker** [comment]
Nice!

**Comment by skiman6010** [comment]
Looks much better than my implementation! Thanks @superloach!

**Comment by superloach** [comment]
No problem! I'm going to be working a bit more on speed and accuracy for the link, so don't worry if it goes down sometimes in the next few days.

**Pull request merged**
