### PR TITLE
Update python packages

### PR DESCRIPTION
**Pull request by uberhacker**
- Add six dependency to all relevant packages

Tested updated python27 and python3 (including pip/pip3) on:
- [x] armv7l
- [x] i686
- [x] x86_64

### CODE REVIEW

**Comment by JL2210** [comment]
@uberhacker: Six already depends on python2.7 and python3, so any Python dependencies can be removed.

**Comment by JL2210** [comment]
Aka, `mate_desktop`

**Comment by uberhacker** [comment]
Good call!  I like the way you think.

**Comment by JL2210** [comment]
Wait, if you have `mate_desktop`, and you have `sommelier` and `xinit`, does that mean you can have a working desktop environment in crew?

**Comment by uberhacker** [comment]
There is only one way you can find out. :)

**Comment by JL2210** [comment]
@uberhacker, you put it way better than I could have. @thedamian, have you seen the code package?

**Comment by uberhacker** [comment]
If it helps any, I will accept full responsibility if this breaks anything. :)

**Comment by JL2210** [comment]
And I'll help. I'm glad you're back. Did you get meltdown and spectre resolved at work? 😆

**Pull request merged**
