### PR TITLE
Add memory lower limit for using pixz for package compression

### PR DESCRIPTION
**Pull request by satmandu**
- Fixes issue with `pixz` failing to compress on systems with less ram
- Solution is to just avoid using `pixz` for compression on such systems.

Works properly:
- [x] x86_64
- [x] armv7l
- [x] i686

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=pixz_ram_check CREW_TESTING=1 crew update
```

### CODE REVIEW

**Comment by saltedcoffii** [comment]
can you show an example of pixz failing on a computer with less ram? i haven't had an issue with that building on actual hardware (4GB of RAM)

**Comment by uberhacker** [comment]
Bump version in `lib/const.rb`?

**Comment by uberhacker** [comment]
> can you show an example of pixz failing on a computer with less ram? i haven't had an issue with that building on actual hardware (4GB of RAM)

I imagine this depends on the size of the file being compressed too.  I was having trouble with large files with only 2 gb of ram.

**Comment by satmandu** [comment]
version bumped

**Comment by satmandu** [comment]
> can you show an example of pixz failing on a computer with less ram? i haven't had an issue with that building on actual hardware (4GB of RAM)

I can lower the limit to 4Gb... what do you see from `%x(free).split(" ")[7]` on your system @saltedcoffii ?

On low ram systems, pixz just fails. See https://github.com/vasi/pixz/issues/97

**Comment by satmandu** [comment]
@saltedcoffii As long as your ram is > `3999500`, which I just set the max to, pixz may be fine?

**Comment by saltedcoffii** [comment]
I'd be happy if chromebrew emitted a warning letting the user know that RAM is too low to compress using pixz, that pixz can be forced using an environment variable, and that chromebrew is falling back to xz.

**Comment by uberhacker** [comment]
If pixz requires more that 4 gb of ram, you can disable with an architecture conditional.  32-bit systems can only physically address 4 gb max.

**Comment by satmandu** [comment]
Honestly, since I don't have time to implement the individual file decompression stuff with pixz I was planning on, I think it best to just limit this here. I think doing something like zstd for compression might be much better anyways, and I think zstd might handle low memory situations better anyways...

For decompression of course it doesn't matter.

**Comment by satmandu** [comment]
> If pixz requires more that 4 gb of ram, you can disable with an architecture conditional. 32-bit systems can only physically address 4 gb max.

Yes, but when running in a container on a `x86_64` system, the i686 apps are PAE aware, and can throw 4Gb at each process, so it is the total ram available which matters.

**Comment by uberhacker** [comment]
> > If pixz requires more that 4 gb of ram, you can disable with an architecture conditional. 32-bit systems can only physically address 4 gb max.
> 
> Yes, but when running in a container on a `x86_64` system, the i686 apps are PAE aware, and can throw 4Gb at each process, so it is the total ram available which matters.

But you are talking about Docker containers.  We probably should be making decisions based on Chromebook hardware instead.

**Comment by satmandu** [comment]
> 
> But you are talking about Docker containers. We probably should be making decisions based on Chromebook hardware instead.

We're talking about building packages. Since most packages are being generated in containers that should take priority. Decompression is of course not an issue at all on any hardware.

**Comment by uberhacker** [comment]
> > But you are talking about Docker containers. We probably should be making decisions based on Chromebook hardware instead.
> 
> We're talking about building packages. Since most packages are being generated in containers that should take priority. Decompression is of course not an issue at all on any hardware.

I kind of disagree since there are those who have a Chromebook as their only option and a failure on a large build will be disappointing and confusing.

**Comment by uberhacker** [comment]
What if we replace pixz with something else as discussed in the Slack channel?

**Comment by saltedcoffii** [comment]
like with tarlz?

**Comment by satmandu** [comment]
> I kind of disagree since there are those who have a Chromebook as their only option and a failure on a large build will be disappointing and confusing.

Oh yes, I agree with you here.  On ChromeOS hardware `crew` should never break due to insufficient hardware. This is why I think we should try to be safe and not present options _to the end-user_ which may result in breakage for them.

**Comment by satmandu** [comment]
> like with tarlz?

I think at the moment my problem with tarlz is that we are already using xz, which is also a lzma derived compression format. 

I don't see any major benefits from the switch?

**Comment by satmandu** [comment]
Resolved by https://github.com/skycocker/chromebrew/pull/6703

**Pull request closed without merging**
