### PR TITLE
add sommelier binaries

### PR DESCRIPTION
**Pull request by satmandu**
Can only verify on my own system.

Works properly:
- [x] x86_64

### CODE REVIEW

**Comment by uberhacker** [comment]
Can we change the SCALE environment variable to 1 instead of 0.5?  My screen is huge at 0.5.

**Comment by satmandu** [comment]
> Can we change the SCALE environment variable to 1 instead of 0.5? My screen is huge at 0.5.

Maybe it would be better to have local customization options? maybe by sourcing a  ```.sommelier.env.default``` before sourcing a ```.sommelier.env``` and only populating the former?

Alternately we could also just not populate the .sommelier.env at all and just have bash variable defaults...

```SCALE=1``` works great on my slate device, but my device also has a hidpi monitor...

**Comment by uberhacker** [comment]
Sounds like more of a hassle than it's worth.  I don't know why SCALE was changed from 1 but all my Chromebook screens are out of whack with 0.5.

**Comment by satmandu** [comment]
@uberhacker are any of your chromebooks hidpi?

**Comment by satmandu** [comment]
sommelier in crostini has two sets of sommelier instances to handle hidpi and non-hidpi.

**Comment by uberhacker** [comment]
I grepped for hidpi in /etc/lsb-release on all my Chromebooks and didn't find anything.  Should we have a conditional in sommelier.rb for this?

**Comment by satmandu** [comment]
That's not how they do it. See this from inside crostini. Note the LOW_DENSITY bits.
```
satadru@penguin:~$ pgrep -fa sommelier
243 /opt/google/cros-containers/bin/../lib/ld-linux-x86-64.so.2 --library-path /opt/google/cros-containers/bin/../lib --inhibit-rpath  /opt/google/cros-containers/bin/sommelier.elf -X --x-display=0 --sd-notify=READY=1 --no-exit-with-child --x-auth=/home/satadru/.Xauthority /bin/sh -c systemctl --user set-environment DISPLAY=${DISPLAY};                     systemctl --user set-environment XCURSOR_SIZE=${XCURSOR_SIZE};                     systemctl --user import-environment SOMMELIER_VERSION;                     touch /home/satadru/.Xauthority;                     xauth -f /home/satadru/.Xauthority add :0 . $(xxd -l 16 -p /dev/urandom);                     . /etc/sommelierrc
247 /opt/google/cros-containers/bin/../lib/ld-linux-x86-64.so.2 --library-path /opt/google/cros-containers/bin/../lib --inhibit-rpath  /opt/google/cros-containers/bin/sommelier.elf --master --sd-notify=READY=1 --socket=wayland-0 /bin/sh -c systemctl --user set-environment WAYLAND_DISPLAY=${WAYLAND_DISPLAY};                     systemctl --user import-environment SOMMELIER_VERSION
254 /opt/google/cros-containers/bin/../lib/ld-linux-x86-64.so.2 --library-path /opt/google/cros-containers/bin/../lib --inhibit-rpath  /opt/google/cros-containers/bin/sommelier.elf --master --sd-notify=READY=1 --socket=wayland-1 /bin/sh -c systemctl --user set-environment WAYLAND_DISPLAY_LOW_DENSITY=${WAYLAND_DISPLAY};                     systemctl --user import-environment SOMMELIER_VERSION
255 /opt/google/cros-containers/bin/../lib/ld-linux-x86-64.so.2 --library-path /opt/google/cros-containers/bin/../lib --inhibit-rpath  /opt/google/cros-containers/bin/sommelier.elf -X --x-display=1 --sd-notify=READY=1 --no-exit-with-child --x-auth=/home/satadru/.Xauthority /bin/sh -c systemctl --user set-environment DISPLAY_LOW_DENSITY=${DISPLAY};                     systemctl --user set-environment XCURSOR_SIZE_LOW_DENSITY=${XCURSOR_SIZE};                     systemctl --user import-environment SOMMELIER_VERSION;                     touch /home/satadru/.Xauthority;                     xauth -f /home/satadru/.Xauthority add :1 . $(xxd -l 16 -p /dev/urandom);                     . /etc/sommelierrc
satadru@penguin:~$ pgrep -fa sommelier
243 /opt/google/cros-containers/bin/../lib/ld-linux-x86-64.so.2 --library-path /opt/google/cros-containers/bin/../lib --inhibit-rpath  /opt/google/cros-containers/bin/sommelier.elf -X --x-display=0 --sd-notify=READY=1 --no-exit-with-child --x-auth=/home/satadru/.Xauthority /bin/sh -c systemctl --user set-environment DISPLAY=${DISPLAY};                     systemctl --user set-environment XCURSOR_SIZE=${XCURSOR_SIZE};                     systemctl --user import-environment SOMMELIER_VERSION;                     touch /home/satadru/.Xauthority;                     xauth -f /home/satadru/.Xauthority add :0 . $(xxd -l 16 -p /dev/urandom);                     . /etc/sommelierrc
247 /opt/google/cros-containers/bin/../lib/ld-linux-x86-64.so.2 --library-path /opt/google/cros-containers/bin/../lib --inhibit-rpath  /opt/google/cros-containers/bin/sommelier.elf --master --sd-notify=READY=1 --socket=wayland-0 /bin/sh -c systemctl --user set-environment WAYLAND_DISPLAY=${WAYLAND_DISPLAY};                     systemctl --user import-environment SOMMELIER_VERSION
254 /opt/google/cros-containers/bin/../lib/ld-linux-x86-64.so.2 --library-path /opt/google/cros-containers/bin/../lib --inhibit-rpath  /opt/google/cros-containers/bin/sommelier.elf --master --sd-notify=READY=1 --socket=wayland-1 /bin/sh -c systemctl --user set-environment WAYLAND_DISPLAY_LOW_DENSITY=${WAYLAND_DISPLAY};                     systemctl --user import-environment SOMMELIER_VERSION
255 /opt/google/cros-containers/bin/../lib/ld-linux-x86-64.so.2 --library-path /opt/google/cros-containers/bin/../lib --inhibit-rpath  /opt/google/cros-containers/bin/sommelier.elf -X --x-display=1 --sd-notify=READY=1 --no-exit-with-child --x-auth=/home/satadru/.Xauthority /bin/sh -c systemctl --user set-environment DISPLAY_LOW_DENSITY=${DISPLAY};                     systemctl --user set-environment XCURSOR_SIZE_LOW_DENSITY=${XCURSOR_SIZE};                     systemctl --user import-environment SOMMELIER_VERSION;                     touch /home/satadru/.Xauthority;                     xauth -f /home/satadru/.Xauthority add :1 . $(xxd -l 16 -p /dev/urandom);                     . /etc/sommelierrc
```

**Comment by uberhacker** [comment]
@satmandu: Can we change `SCALE=0.5` to `SCALE=1` on line 92?  This will require new binaries also.

**Comment by satmandu** [comment]
@uberhacker Modified default scale to 1 and put all values into ~/.sommelier-default.env with an optional ~/.sommelier.env being read thereafter.

Binaries added too.

**Pull request merged**
