### PR TITLE
Fix upgrade of rsync binary breaking crew

### PR DESCRIPTION
**Pull request by satmandu**
- otherwise, we cannot upgrade `rsync`
- Fixed by not checking the output of the `rsync` command if `rsync` isn't available.
- Adds rebuild of `rsync` command against fixed `popt`

Works properly:
- [x] x86_64
- [x] i686
- [x] armv7l

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=rsync_essential CREW_TESTING=1 crew update ; crew upgrade
```

### CODE REVIEW

**Comment by uberhacker** [comment]
Where is rsync used in the upgrade process?  Should we be using it?

**Comment by uberhacker** [comment]
Why am I seeing @supechicken's changes in this PR?

**Comment by satmandu** [comment]
I just merged master...

**Comment by satmandu** [comment]
Ok this is fixed now!

**Comment by uberhacker** [comment]
Still seeing @supechicken's changes even after a refresh.

**Comment by satmandu** [comment]
I'll make a new PR....

**Comment by uberhacker** [comment]
Something was definitely out of sync.

**Pull request closed without merging**
