### PR TITLE
Update Checkinstall package

### PR DESCRIPTION
**Pull request by JL2210**
Fix switched locale and configuration directories
Moves programs from /usr/local/sbin to /usr/local/bin
Patch doesn't edit documentation

### CODE REVIEW

**Comment by JL2210** [comment]
Don't worry. I did this time.

**Comment by JL2210** [comment]
I created a perfectly valid working binary of Checkinstall from this package.

**Comment by uberhacker** [comment]
What I want to get away from in the future is PRs that have multiple commits after the fact.  If you start submitting PRs that are fully tested and don't require much correction on my part, this will help build your credibility. :)

**Comment by JL2210** [comment]
Got it. I'll make sure to check and double check.

**Pull request merged**
