### PR TITLE
Strip binaries but not compressed archives

### PR DESCRIPTION
**Pull request by uberhacker**
This fixes the issue in #848.

### CODE REVIEW

**Comment by jam7** [comment]
Nice notice.  I'll check details soon.  Thanks.

**Comment by jam7** [comment]
Thank you for your insight.  It's identify the source of problem.

However, this PR does solve the problem if and only if zip file is not hard or soft linked to binary file.  Because, checking name solves the problem from zip file side, but doesn't from binary file side.  So, I'm still looking for better solution about this.  Maybe we can check elf format size and actual file size...

**Comment by uberhacker** [comment]
The best solution, IMHO, would be to identify only the relevant binary files that need stripped and operate on those only.  However, identifying the gamut of possible binary files that need stripped is likely not attainable, so excluding files that shouldn't be stripped may be the only feasible option.

**Comment by jam7** [comment]
@uberhacker You are thinking problem differently.  Think about situation like below:
```
$ touch a b
$ zip test.zip a b
...
$ echo 'main() {puts("hello");}' > hello.c
$ gcc hello.c
...
$ cat a.out test.zip > binary
$ chmod a+x binary
$ ln binary library.zip
$ ./binary
hello
$ unzip -l library.zip 
Archive:  library.zip
warning [library.zip]:  8600 extra bytes at beginning or within zipfile
  (attempting to process anyway)
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2017-08-13 23:11   a
        0  2017-08-13 23:11   b
---------                     -------
        0                     2 files
```
It's what dropbox provides.  It is a signle file.  Therefore, it is impossible to strip only newbinary.

This PR works for `dropbox.rb` situation.  The reason is this `dropbox.rb` copies `dropbox` and `library.zip` separately by using `cp -r` for copying contents.  It's the reason I'm looking for better solution.

**Comment by uberhacker** [comment]
I guess I'm confused why you think library.zip is symlinked.  I was able to extract the contents fine from the source_url downloaded tarball.

**Comment by jam7** [comment]
It is actually hard-link to dropbox like below.  I've never said it is a symbolic-link, though.
```
$ crew download dropbox
$ tar tvf  /usr/local/tmp/crew/dropbox-lnx.x86_64-30.4.22.tar.gz|grep library
hrwxr-xr-x releng/releng        0 2017-07-12 12:48 .dropbox-dist/dropbox-lnx.x86_64-30.4.22/library.zip link to .dropbox-dist/dropbox-lnx.x86_64-30.4.22/dropbox
```

**Comment by jam7** [comment]
Not sure which library.zip you are talking about.  It is ELF format binary file at the beginning.
```
$ file library.zip
library.zip: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.15, BuildID[sha1]=4993d9df69a7bd249187d38df9a6fd8431293cc7, stripped
$ od -c library.zip |head
0000000 177   E   L   F 002 001 001  \0  \0  \0  \0  \0  \0  \0  \0  \0
0000020 002  \0   >  \0 001  \0  \0  \0  \0   `   E  \0  \0  \0  \0  \0
0000040   @  \0  \0  \0  \0  \0  \0  \0     022   O  \0  \0  \0  \0  \0
0000060  \0  \0  \0  \0   @  \0   8  \0  \t  \0   @  \0 036  \0 035  \0
0000100 006  \0  \0  \0 005  \0  \0  \0   @  \0  \0  \0  \0  \0  \0  \0
0000120   @  \0   @  \0  \0  \0  \0  \0   @  \0   @  \0  \0  \0  \0  \0
0000140 370 001  \0  \0  \0  \0  \0  \0 370 001  \0  \0  \0  \0  \0  \0
0000160  \b  \0  \0  \0  \0  \0  \0  \0 003  \0  \0  \0 004  \0  \0  \0
0000200   8 002  \0  \0  \0  \0  \0  \0   8 002   @  \0  \0  \0  \0  \0
0000220   8 002   @  \0  \0  \0  \0  \0 034  \0  \0  \0  \0  \0  \0  \0
$ unzip -l library.zip |head
Archive:  library.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
     3265  06-27-2017 14:53   __main__.pyc
      257  07-12-2017 12:46   __main__dropbox__.pyc
    15857  06-27-2017 14:33   BaseHTTPServer.pyc
    20929  06-27-2017 14:33   ConfigParser.pyc
    16849  06-27-2017 14:33   Cookie.pyc
    14065  06-27-2017 14:33   HTMLParser.pyc
      113  10-25-2015 04:41   PyQt5/__init__.pyc
```

**Comment by jam7** [comment]
Well, it is required to copy linked file to different separated files, but this works with `dropbox.rb`.  I'm merging this.  Maybe we can find better solution later.

**Comment by jam7** [comment]
Just an additional info.  It is possible to check whether a file is already stripped or not by `objdump -t library.zip|head|grep "no symbols"`, but this is not perfect too...

**Pull request merged**
