### PR TITLE
Add cups package

### LINKED ISSUE #10: cups package
A cups package would be a nice addition if cups can work on chromeos.  It should.

### PR DESCRIPTION
**Pull request by uberhacker**
CUPS is the standards-based, open source printing system developed by Apple Inc. for macOS® and other UNIX®-like operating systems. CUPS uses the Internet Printing Protocol (IPP) to support printing to local and network printers.  See https://www.cups.org/.  Resolves #10.

### CODE REVIEW

**Comment by JL2210** [comment]
If you don't mind, I'd like to use the stable version. I've had some issues with the unstable.

**Comment by JL2210** [comment]
Also, `depends_on 'libjpeg'`

**Comment by uberhacker** [comment]
What were the issues?  This package has a complex build.

**Comment by JL2210** [comment]
No it doesn't. In my case, I've been using the stable version and it's a simple `./configure  && make && make install` process.

**Comment by JL2210** [comment]
Well, now that I see yours, I realize that's what it is. Could you still by chance use stable? I am making a new package, `hplip`, that doesn't seem to recognize the beta.

**Comment by uberhacker** [comment]
Fair enough.  I didn't like the fact that they hardcoded some paths in the configure script.  It's something that really grinds my gears.  https://www.youtube.com/watch?v=CkK0z2ALU_4

**Comment by JL2210** [comment]
Neither did I.

**Comment by JL2210** [comment]
Sed is a real lifesaver with things like that.

**Pull request merged**
