### PR TITLE
[libxml2] Update to 2.9.9

### PR DESCRIPTION
**Pull request by vincowl**

### CODE REVIEW

**Comment by uberhacker** [comment]
I'm going to hold off on this until I get a chance to generate binaries since this is a core package.

**Comment by uberhacker** [comment]
I appreciate all the updates @vincowl!  I'm usually a bit hesitant to update libraries but I'm willing to take the risk for progress. :)

**Comment by vincowl** [comment]
I fully agree but I have too much errors linked to graphical libs and thus need to upgrade to see if it helps. While I am at it, sharing it is costless.

**Comment by uberhacker** [comment]
But the contribution is priceless. ;)

**Pull request merged**
