### PR TITLE
Fixes the issue with crosh hanging when sommelier is installed

### PR DESCRIPTION
**Pull request by JL2210**
Pretty self explanatory.

### CODE REVIEW

**Comment by Ewpratten** [comment]
Any chance that this could be used to change desktop environments?

**Comment by JL2210** [comment]
No.

**Comment by JL2210** [comment]
Maybe run a separate one inside a window.

**Comment by JL2210** [comment]
It's basically like Crouton Integration, except you can't minimize it.

**Comment by JL2210** [comment]
@dososboicwen

**Comment by JL2210** [comment]
Now, with Xwayland and Xinit, then you could, but you need a desktop environment first.

**Pull request merged**
