### PR TITLE
Remove need for sudo

### PR DESCRIPTION
**Pull request by uberhacker**
This is a reissue of PR #176.  Installs cleanly on a power washed Chromebook with specs below:
```
Version 56.0.2924.110 (64-bit)
Platform 9000.91.0 (Official Build) stable-channel kip
Firmware Google_Kip.5216.227.78
```
Hopefully, this will take less than 8 months to get merged into master. :)

### CODE REVIEW

**Comment by uberhacker** [comment]
@minektur @lyxell @jam7 @thedamian @cstrouse Anything wrong with this PR?

**Comment by thedamian** [comment]
last time the amazing @minektur it failed when I tried it.

https://github.com/skycocker/chromebrew/pull/176

what did you do differently?

**Comment by uberhacker** [comment]
Hey @thedamian: Thanks for looking into this.  I basically just updated the code to be compatible with the latest crew command.  Since there have been some changes to crew recently, it looks like it needs to be updated again.  I can update it if you promise it doesn't sit in the queue another 6 months. :)

**Comment by thedamian** [comment]
@uberhacker Yes. I promise to test it right away when you've updated it and I promise to check it in once it installs from my CR-48 powerwashed

**Pull request closed without merging**
