### PR TITLE
Add perl_algorithm_diff, perl_digest_md5, perl_parallel_forkmanager, perl_regexp_common packages

### PR DESCRIPTION
**Pull request by JL2210**
Helps along #3153

### CODE REVIEW

**Comment by uberhacker** [comment]
This is definitely overkill.  What do you think @davidberard98?  I want you to get the credit for adding this package.

**Comment by JL2210** [comment]
I didn't actually add the Cloc package in this PR, just the dependencies for it. @davidberard98 can have as much credit as he wants for the package; after all, he is the one who wrote it.

**Comment by JL2210** [comment]
Besides, all the package managers out there that I can think of also have these packages.

**Comment by JL2210** [comment]
How exactly is this a work in progress? This can be merged and the specific packages work just fine.

**Comment by uberhacker** [comment]
Well, I could merge these but since the cloc package is still a wip, it would be useless if he doesn't decide to go this route.

**Comment by JL2210** [comment]
Let's just merge it. These may be useful some time in the future, anyway.

**Comment by uberhacker** [comment]
I'm hesitant.

**Comment by JL2210** [comment]
It's no big deal. At least they won't break anything.

**Comment by uberhacker** [comment]
We can submit this again if these packages are needed in the future.

**Comment by JL2210** [comment]
Or we could just merge it because there's no reason not to.

**Comment by JL2210** [comment]
Except that `Parallel::ForkManager` requires `Moo::Role`. I'll add that.

**Comment by JL2210** [comment]
There's a HUGE dependency tree for `Moo::Role`... This will take a while.

**Pull request closed without merging**
