### PR TITLE
Add autoconf build dependency to Weston

### PR DESCRIPTION
**Pull request by lzmartinico**
## Description
Adds a build dependency to prevent Weston installation from failing

### CODE REVIEW

**Comment by uberhacker** [comment]
@lzmartinico: Thank you for the update but we already include autoconf in Chromebrew "core" so no need to include it here since it is added in a standard install already.

**Comment by lzmartinico** [comment]
@uberhacker my local version of Chromebrew (0.4.3) did not come with autoconf installed

**Comment by uberhacker** [comment]
@lzmartinico: Did you try `crew update` followed by `crew upgrade` yet?  If that doesn't fix it, try:
```
$ sudo dev_install --reinstall -y
$ curl -Ls git.io/vddgY | bash
```
I'm guessing you haven't updated in awhile.

**Comment by lzmartinico** [comment]
Yes that's right, I hadn't updated in a while, but there was no indication I hadn't. Homebrew by default updates whenever a new installation is started if the last update was not too recent, maybe Chromebrew should have the same behaviour? Otherwise, I think there might be some merit in preserving dependencies added in recent versions of core crew.

**Pull request closed without merging**
