### PR TITLE
Update ruby from 2.5.3 to 2.6.3

### PR DESCRIPTION
**Pull request by uberhacker**
Tested on all architectures.  This update provides a self-healing wrapper script around ruby that makes sure crew still works if any of the runtime dependency packages are removed.  In fact, any of the core packages can be removed and crew will continue to work.  You can't remove ruby without requiring a fresh Chromebrew install, however.  A future PR is in the plans to make it possible to remove the ruby package and still keep the crew command working.

### CODE REVIEW

**Comment by JL2210** [comment]
Whoa! I do not approve. Just disable stack smashing protection.

**Comment by uberhacker** [comment]
Dude, that doesn't work.  I disapprove your suggestion.

**Comment by JL2210** [comment]
Configure with stack_protector=no and tell me it doesn't work again.

**Comment by JL2210** [comment]
If that doesn't work, try *at least* packaging `libssp` with the `ruby` package.

**Comment by JL2210** [comment]
But I really don't want to force a download, nor the overhead of a shell script, on unsuspecting users.

**Comment by uberhacker** [comment]
You are missing the point.  The only reason you want to remove stack protection is so you can get rid of the gcc dependency.  That is not a good enough reason to take an important feature away.  The overhead of the shell script is minimal.  This is a package manager, not some executable that needs maximum performance.  There is more method to the madness here.  I want to be able to switch gcc versions without breaking crew and this solution fits the bill.

**Comment by uberhacker** [comment]
I have an idea how to package libssp.  I think that is a better approach to be able to switch gcc versions.

**Pull request closed without merging**
