### PR TITLE
Add cloc package

### PR DESCRIPTION
**Pull request by davidberard98**
Added cloc package; this is a script which counts the number of lines of code in a directory

Moved to a different branch.

### CODE REVIEW

**Comment by JL2210** [comment]
@uberhacker 👍?

**Comment by JL2210** [comment]
Is there a testsuite of some sort or any configuration that may be needed?

**Comment by JL2210** [comment]
It looks like you could use the `Makefile` in the `Unix/` directory to build, test, and install this.

**Comment by JL2210** [comment]
May I suggest this?
```
  def self.build
    Dir.chdir('Unix') do
      system 'make'
    end
  end

  def self.install
    Dir.chdir('Unix') do
      system 'make', "DESTDIR=#{CREW_DEST_DIR}", 'install'
    end
  end

  def self.check
    Dir.chdir('Unix') do
      system 'make', 'test'
    end
  end
```

**Comment by uberhacker** [comment]
This won't work @JL2210.  If you read the INSTALL, the Unix directory is for distros with package managers and the cloc executable there needs external dependencies.  Try it and find out yourself.

**Comment by JL2210** [comment]
So Chromebrew **isn't** a package manager?

**Comment by JL2210** [comment]
We should be able to package them. I don't see why not.

**Comment by uberhacker** [comment]
Dude, they're not going to have instructions for building on Chromebrew.  Think about that for a moment.

**Comment by JL2210** [comment]
They're just regular Perl packages, just like any other `perl_*` package (including `perl_io_socket_ssl`).

**Comment by uberhacker** [comment]
And that is exactly why make doesn't work.  Are you going to try it?  Obviously, you don't believe me.

**Comment by JL2210** [comment]
Sources:
https://cpan.metacpan.org/authors/id/T/TY/TYEMQ/Algorithm-Diff-1.1903.tar.gz
https://cpan.metacpan.org/authors/id/A/AB/ABIGAIL/Regexp-Common-2017060201.tar.gz
https://cpan.metacpan.org/authors/id/G/GA/GAAS/Digest-MD5-2.55.tar.gz
https://cpan.metacpan.org/authors/id/Y/YA/YANICK/Parallel-ForkManager-2.02.tar.gz

**Comment by uberhacker** [comment]
You don't need to go to that extent to package this thing.

**Comment by JL2210** [comment]
They honestly shouldn't be that hard.

**Comment by JL2210** [comment]
@uberhacker How's that?

**Comment by davidberard98** [comment]
Sorry for the delay; thanks for looking into this.

However, as far as I can tell, it seems like these dependencies aren't actually required when using this perl file for cloc.  It will install these dependencies in a temporary directory on startup if they aren't already installed
https://github.com/AlDanial/cloc#regexpcommon-digestmd5-win32autoglob-algorithmdiff-

Additionally, grepping through the file it appears that most the source code for the dependencies is included in the cloc file.

**Comment by JL2210** [comment]
Yes, but we should be able to package those, too; after all, we are a
package manager. In fact, I have already pushed a PR with the dependencies.

**Comment by uberhacker** [comment]
We could do that but it's total overkill.  @davidberard98 is correct.  The perl dependencies aren't needed with the cloc executable.  If we really want to package like other package managers, we only need the command and manpage.  Here is the output of files installed from the Debian version of the cloc package:
```
$ dpkg -L cloc
/usr/bin/cloc
/usr/share/doc/cloc/changelog.Debian.gz
/usr/share/doc/cloc/changelog.gz
/usr/share/doc/cloc/copyright
/usr/share/man/man1/cloc.1.gz
```

**Comment by JL2210** [comment]
How exactly is it "total overkill"? For one, these could well be needed for other packages, and for another, I don't think that installing those in a temporary directory is any better than packaging them.

**Comment by uberhacker** [comment]
The cloc executable is over 13k lines of perl code that includes all the dependencies already.

**Comment by JL2210** [comment]
Yes, and the stripped-down `cloc` executable is more modular and allows for different versions of dependencies.

**Comment by uberhacker** [comment]
@davidberard98: Have you decided how you want to proceed with this package?  Monolithic or modular?  That is the question.

**Comment by uberhacker** [comment]
Closed due to inactivity.

**Pull request closed without merging**
