### PR TITLE
Static Musl Curl -> 7.79.1

### PR DESCRIPTION
**Pull request by satmandu**
Supersedes work in https://github.com/skycocker/chromebrew/pull/6051
Needs https://github.com/skycocker/chromebrew/pull/6064 and https://github.com/skycocker/chromebrew/pull/6062 (but only to build).

- If curl build fails on a symbol not being found, just first rebuild the musl package with that resource.
- includes a static libcurl which can be used to build other things (like git)

Builds/Works properly (in container):
- [x] x86_64
- [x] armv7l
- [x] i686

**Needs testing on all platforms before merge!**

Tested on actual hardware:
- [x] x86_64
- [x] armv7l
- [x] i686

image

### CODE REVIEW

**Comment by uberhacker** [comment]
Unfortunately, on i686, I get:
```
$ curl -V
Segmentation fault (core dumped)
```
I'll try a build with all the musl packages and report back.

**Comment by uberhacker** [comment]
The i686 build fails with:
```
configure: using LIBS: /usr/local/musl/lib/libkrb5support.a  /usr/local/musl/lib/libgssapi_krb5.a /usr/local/musl/lib/libkrb5.a  /usr/local/musl/lib/libk5crypto.a /usr/local/musl/lib/libcom_err.a       -l:libresolv.a       -l:libm.a       -l:libbrotlicommon-static.a       -l:libbrotlidec-static.a       -l:libzstd.a       -l:libz.a       -l:libssl.a       -l:libcrypto.a       -l:libsasl2.a       -l:libnghttp2.a       -l:libpthread.a       -l:libncursesw.a       -l:libtinfow.a       -l:libcares.a       -l:libunistring.a       -l:libidn2.a       -l:libssh.a     -L/usr/local/musl/lib
configure: LIBS note: LIBS should only be used to specify libraries (-lname).
configure: WARNING: Continuing even with errors mentioned immediately above this line.
checking for a BSD-compatible install... /usr/bin/install -c
checking for gcc... /usr/local/musl/bin/i686-linux-musl-gcc
checking whether the C compiler works... no
configure: error: in `/usr/local/tmp/crew/curl.20210813012131.dir/curl-7.78.0':
configure: error: C compiler cannot create executables
See `config.log' for more details
curl failed to build: `PATH=/usr/local/musl/bin:/home/chronos/user/.cargo/bin:/usr/local/pkg/bin:/usr/local/pkg/sbin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/local/libexec/busybox/bin:/usr/local/libexec/busybox/sbin         CC='/usr/local/musl/bin/i686-linux-musl-gcc'         CXX='/usr/local/musl/bin/i686-linux-musl-g++'         LD=/usr/local/musl/bin/i686-linux-musl-ld.gold         CFLAGS='-B/usr/local/musl/include -flto -pipe -O3 -ffat-lto-objects -fipa-pta -fno-semantic-interposition -fdevirtualize-at-ltrans  -fno-stack-protector -fcommon'         CXXFLAGS='-B/usr/local/musl/include -flto -pipe -O3 -ffat-lto-objects -fipa-pta -fno-semantic-interposition -fdevirtualize-at-ltrans  -fno-stack-protector -fcommon'         CPPFLAGS='-I/usr/local/musl/include -DCURL_STATICLIB -DNGHTTP2_STATICLIB'         LDFLAGS='-L/usr/local/musl/lib -flto -static'     LIBS='/usr/local/musl/lib/libkrb5support.a  /usr/local/musl/lib/libgssapi_krb5.a /usr/local/musl/lib/libkrb5.a  /usr/local/musl/lib/libk5crypto.a /usr/local/musl/lib/libcom_err.a       -l:libresolv.a       -l:libm.a       -l:libbrotlicommon-static.a       -l:libbrotlidec-static.a       -l:libzstd.a       -l:libz.a       -l:libssl.a       -l:libcrypto.a       -l:libsasl2.a       -l:libnghttp2.a       -l:libpthread.a       -l:libncursesw.a       -l:libtinfow.a       -l:libcares.a       -l:libunistring.a       -l:libidn2.a       -l:libssh.a     -L/usr/local/musl/lib'     CURL_LIBRARY_PATH=/usr/local/musl/lib     ./configure --prefix=/usr/local/musl     --libdir=/usr/local/musl     --disable-dependency-tracking     --disable-imap     --disable-ldap     --disable-ldaps     --disable-maintainer-mode     --disable-rtsp     --disable-shared     --enable-ares     --enable-ipv6     --enable-static     --enable-unix-sockets     --with-brotli=/usr/local/musl     --with-ca-bundle=/usr/local/etc/ssl/certs/ca-certificates.crt     --with-ca-fallback     --with-ca-path=/usr/local/etc/ssl/certs     --with-gssapi=/usr/local/musl     --with-libidn2=/usr/local/musl     --with-libssh=/usr/local/musl     --with-nghttp2=/usr/local/musl     --with-openssl=/usr/local/musl     --without-librtmp     --with-zlib=/usr/local/musl     ` exited with 77
```

**Comment by satmandu** [comment]
Ok that's interesting, because I didn't build that gcc.... but this is in a way good news, because it leads me to believe that something else is going on here. What does `/usr/local/musl/bin/i686-linux-musl-gcc -dumpversion` give you?

I'm going to guess you are getting a segfault with that...

**Comment by uberhacker** [comment]
Surprisingly, I get:
```
$ /usr/local/musl/bin/i686-linux-musl-gcc -dumpversion
10.2.1
$ /usr/local/musl/bin/gcc -dumpversion
10.2.1
```

**Comment by satmandu** [comment]
Can you run this for me on i686, so I can compare the cpu options on hardware vs in my VM?

`gcc -march=native -E -v - </dev/null 2>&1 | grep cc1`

**Comment by satmandu** [comment]
Also post the config.log of the failed compile, so we can see where it thinks the compiler is failing?

**Comment by uberhacker** [comment]
```
$ cat configure.log 
--------------------
./configure --prefix=/usr/local/musl --static
Thu Aug 12 21:13:14 CDT 2021
=== ztest14631.c ===
extern int getchar();
int hello() {return getchar();}
===
/usr/local/musl/bin/i686-linux-musl-gcc -c ztest14631.c
cc1: fatal error: ztest14631.c: No such file or directory
compilation terminated.
... using /usr/local/musl/bin/i686-linux-musl-gcc

Checking for obsessive-compulsive compiler options...
=== ztest14631.c ===
int foo() { return 0; }
===
/usr/local/musl/bin/i686-linux-musl-gcc -c -B/usr/local/musl/include -flto -pipe -O3 -ffat-lto-objects -fipa-pta -fno-semantic-interposition -fdevirtualize-at-ltrans -fno-stack-protector -fcommon ztest14631.c
cc1: fatal error: ztest14631.c: No such file or directory
compilation terminated.
(exit code 1)
Compiler error reporting is too harsh for ./configure (perhaps remove -Werror).
** ./configure aborting.
--------------------
```

**Comment by uberhacker** [comment]
```
$ gcc -march=native -E -v - </dev/null 2>&1 | grep cc1
 /usr/local/libexec/gcc/i686-cros-linux-gnu/11/cc1 -E -quiet -v - -march=bonnell -mmmx -mno-popcnt -msse -msse2 -msse3 -mssse3 -mno-sse4.1 -mno-sse4.2 -mno-avx -mno-avx2 -mno-sse4a -mno-fma4 -mno-xop -mno-fma -mno-avx512f -mno-bmi -mno-bmi2 -mno-aes -mno-pclmul -mno-avx512vl -mno-avx512bw -mno-avx512dq -mno-avx512cd -mno-avx512er -mno-avx512pf -mno-avx512vbmi -mno-avx512ifma -mno-avx5124vnniw -mno-avx5124fmaps -mno-avx512vpopcntdq -mno-avx512vbmi2 -mno-gfni -mno-vpclmulqdq -mno-avx512vnni -mno-avx512bitalg -mno-avx512bf16 -mno-avx512vp2intersect -mno-3dnow -mno-adx -mno-abm -mno-cldemote -mno-clflushopt -mno-clwb -mno-clzero -mcx16 -mno-enqcmd -mno-f16c -mno-fsgsbase -mfxsr -mno-hle -msahf -mno-lwp -mno-lzcnt -mmovbe -mno-movdir64b -mno-movdiri -mno-mwaitx -mno-pconfig -mno-pku -mno-prefetchwt1 -mno-prfchw -mno-ptwrite -mno-rdpid -mno-rdrnd -mno-rdseed -mno-rtm -mno-serialize -mno-sgx -mno-sha -mno-shstk -mno-tbm -mno-tsxldtrk -mno-vaes -mno-waitpkg -mno-wbnoinvd -mno-xsave -mno-xsavec -mno-xsaveopt -mno-xsaves -mno-amx-tile -mno-amx-int8 -mno-amx-bf16 -mno-uintr -mno-hreset -mno-kl -mno-widekl -mno-avxvnni --param l1-cache-size=24 --param l1-cache-line-size=64 --param l2-cache-size=512 -mtune=bonnell -dumpbase -
```

**Comment by satmandu** [comment]
ok that gives me these options: 
```
-march=bonnell -mmmx -msse -msse2 -msse3 -mssse3 -mcx16 -mfxsr -msahf -mmovbe --param l1-cache-size=24 --param l1-cache-line-size=64 --param l2-cache-size=512 -mtune=bonnell
```

Maybe I could try compiling with those?

**Comment by uberhacker** [comment]
```
$ /usr/local/musl/libexec/gcc/i686-linux-musl/10.2.1/cc1 -version
bash: /usr/local/musl/libexec/gcc/i686-linux-musl/10.2.1/cc1: No such file or directory
```

**Comment by satmandu** [comment]
> ```
> $ /usr/local/musl/libexec/gcc/i686-linux-musl/10.2.1/cc1 -version
> GNU C17 (GCC) version 10.2.1 20210227 (i686-linux-musl)
>         compiled by GNU C version 10.2.1 20210227, GMP version 6.2.1, MPFR version 4.1.0, MPC version 1.2.1, isl version none
> GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
> cc1: fatal error: stdout: No such file or directory
> compilation terminated.
> ```

So GCC isn't broken... But there's something else going on? Huh.

Any chance you can get me remote access to an i686 machine?

**Comment by satmandu** [comment]
@uberhacker Can you see if this new i686 build of curl works?

**Comment by uberhacker** [comment]
Unfortunately, still doesn't work.  Output below:
```
configure: using LIBS: /usr/local/musl/lib/libkrb5support.a  /usr/local/musl/lib/libgssapi_krb5.a /usr/local/musl/lib/libkrb5.a  /usr/local/musl/lib/libk5crypto.a /usr/local/musl/lib/libcom_err.a       -l:libresolv.a       -l:libm.a       -l:libbrotlicommon-static.a       -l:libbrotlidec-static.a       -l:libzstd.a       -l:libz.a       -l:libssl.a       -l:libcrypto.a       -l:libsasl2.a       -l:libnghttp2.a       -l:libpthread.a       -l:libncursesw.a       -l:libtinfow.a       -l:libcares.a       -l:libunistring.a       -l:libidn2.a       -l:libssh.a     -L/usr/local/musl/lib
configure: LIBS note: LIBS should only be used to specify libraries (-lname).
configure: WARNING: Continuing even with errors mentioned immediately above this line.
checking for a BSD-compatible install... /usr/bin/install -c
checking for gcc... /usr/local/musl/bin/i686-linux-musl-gcc
checking whether the C compiler works... no
configure: error: in `/usr/local/tmp/crew/curl.20210819144219.dir/curl-7.78.0':
configure: error: C compiler cannot create executables
See `config.log' for more details
curl failed to build: `PATH=/usr/local/musl/bin:/home/chronos/user/.cargo/bin:/usr/local/pkg/bin:/usr/local/pkg/sbin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/local/libexec/busybox/bin:/usr/local/libexec/busybox/sbin         CC='/usr/local/musl/bin/i686-linux-musl-gcc'         CXX='/usr/local/musl/bin/i686-linux-musl-g++'         LD=/usr/local/musl/bin/i686-linux-musl-ld.gold         CFLAGS='-B/usr/local/musl/include -flto -pipe -O3 -ffat-lto-objects -fipa-pta -fno-semantic-interposition -fdevirtualize-at-ltrans  -fno-stack-protector -fcommon'         CXXFLAGS='-B/usr/local/musl/include -flto -pipe -O3 -ffat-lto-objects -fipa-pta -fno-semantic-interposition -fdevirtualize-at-ltrans  -fno-stack-protector -fcommon'         CPPFLAGS='-I/usr/local/musl/include -DCURL_STATICLIB -DNGHTTP2_STATICLIB'         LDFLAGS='-L/usr/local/musl/lib -flto -static'     LIBS='/usr/local/musl/lib/libkrb5support.a  /usr/local/musl/lib/libgssapi_krb5.a /usr/local/musl/lib/libkrb5.a  /usr/local/musl/lib/libk5crypto.a /usr/local/musl/lib/libcom_err.a       -l:libresolv.a       -l:libm.a       -l:libbrotlicommon-static.a       -l:libbrotlidec-static.a       -l:libzstd.a       -l:libz.a       -l:libssl.a       -l:libcrypto.a       -l:libsasl2.a       -l:libnghttp2.a       -l:libpthread.a       -l:libncursesw.a       -l:libtinfow.a       -l:libcares.a       -l:libunistring.a       -l:libidn2.a       -l:libssh.a     -L/usr/local/musl/lib'     CURL_LIBRARY_PATH=/usr/local/musl/lib     ./configure --prefix=/usr/local/musl     --libdir=/usr/local/musl/lib     --disable-dependency-tracking     --disable-imap     --disable-ldap     --disable-ldaps     --disable-maintainer-mode     --disable-rtsp     --disable-shared     --enable-ares     --enable-ipv6     --enable-static     --enable-unix-sockets     --with-brotli=/usr/local/musl     --with-ca-bundle=/usr/local/etc/ssl/certs/ca-certificates.crt     --with-ca-fallback     --with-ca-path=/usr/local/etc/ssl/certs     --with-gssapi=/usr/local/musl     --with-libidn2=/usr/local/musl     --with-libssh=/usr/local/musl     --with-nghttp2=/usr/local/musl     --with-openssl=/usr/local/musl     --without-librtmp     --with-zlib=/usr/local/musl     ` exited with 77
```
Also included the config.log.  See attachment. 
[config.log](https://github.com/skycocker/chromebrew/files/7016690/config.log)

**Comment by satmandu** [comment]
@uberhacker Can you try this new i686 build from the older container...

**Comment by uberhacker** [comment]
Unfortunately, i686 still segfaults:
```
$ crew reinstall curl
curl: Command line tool and library for transferring data with URLs.
Performing pre-flight checks...
Precompiled binary available, downloading...
##################################################################################################################################### 100.0%
Curl archive downloaded.
Unpacking 'tpxz' archive using 'tar', this may take a while...
Removing since upgrade or reinstall...
Package curl isn't installed.
Performing pre-install...
Performing install...
Performing post-install for curl...
Curl installed!
$ curl -V
Segmentation fault (core dumped)
```

**Comment by satmandu** [comment]
Alas.

**Comment by uberhacker** [comment]
Works on i686!
```
$ curl -V
curl 7.79.1 (i686-pc-linux-gnu) libcurl/7.79.1 OpenSSL/3.0.0 zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 c-ares/1.17.2 libidn2/2.3.2 libssh/0.9.6/openssl/zlib nghttp2/1.45.1
Release-Date: 2021-09-22
Protocols: dict file ftp ftps gopher gophers http https mqtt pop3 pop3s scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets zstd
```

**Pull request merged**
