### PR TITLE
ruby update to 2.7.2

### PR DESCRIPTION
**Pull request by satmandu**
Compiles and runs with LibreSSL 3.1.4

Works properly:
- [x] x86_64

### CODE REVIEW

**Comment by satmandu** [comment]
Here's my output with this doing a ```crew build ruby``` (as opposed to a ```crew install ruby``` - which works.)

```
make[1]: Leaving directory '/usr/local/tmp/crew/ruby-2.7.2.tar.xz.dir/ruby-2.7.2'
making enc
make[1]: Entering directory '/usr/local/tmp/crew/ruby-2.7.2.tar.xz.dir/ruby-2.7.2'
make[1]: Nothing to be done for 'enc'.
make[1]: Leaving directory '/usr/local/tmp/crew/ruby-2.7.2.tar.xz.dir/ruby-2.7.2'
making trans
make[1]: Entering directory '/usr/local/tmp/crew/ruby-2.7.2.tar.xz.dir/ruby-2.7.2'
make[1]: Nothing to be done for './enc/trans'.
make[1]: Leaving directory '/usr/local/tmp/crew/ruby-2.7.2.tar.xz.dir/ruby-2.7.2'
making encs
make[1]: Entering directory '/usr/local/tmp/crew/ruby-2.7.2.tar.xz.dir/ruby-2.7.2'
make[1]: Nothing to be done for 'encs'.
make[1]: Leaving directory '/usr/local/tmp/crew/ruby-2.7.2.tar.xz.dir/ruby-2.7.2'
Generating RDoc documentation

No newer files.

  Files:      0

  Classes:    0 (0 undocumented)
  Modules:    0 (0 undocumented)
  Constants:  0 (0 undocumented)
  Attributes: 0 (0 undocumented)
  Methods:    0 (0 undocumented)

  Total:      0 (0 undocumented)
    0.00% documented

  Elapsed: 0.0s

Fiber count: 10000 (skipping)    
PASS all 1409 tests
exec ./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems "./bootstraptest/runner.rb" --ruby="ruby --disable-gems"   ./KNOWNBUGS.rb
2020-10-05 14:37:34 -0400
Driver is ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-gnu]
Target is ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-gnu]

KNOWNBUGS.rb  PASS 0
No tests, no problem

test succeeded
Run options: "--ruby=./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems"

# Running tests:

Finished tests in 2.644454s, 86.5963 tests/s, 189.0750 assertions/s.                                            
229 tests, 500 assertions, 0 failures, 0 errors, 0 skips

ruby -v: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-gnu]
config.status: creating ruby-runner.h
making mjit_build_dir.so
Gem::Indexer tests are being skipped.  Install builder gem.
generate_index tests are being skipped.  Install builder gem.
Run options: "--ruby=./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems" --excludes-dir=./test/excludes --name=!/memory_leak/

# Running tests:

Leaked file descriptor: DRbTests::TestDRbTCP#test_immediate_close: 10 : #<IO:fd 10>                                         
Leaked file descriptor: DRbTests::TestDRbTCP#test_immediate_close: 11
[ 5757/21030] TestAutoload#test_autoload_fork = 1.53 s                                                                                                                          
  1) Failure:
TestAutoload#test_autoload_fork [/usr/local/tmp/crew/ruby-2.7.2.tar.xz.dir/ruby-2.7.2/test/ruby/test_autoload.rb:378]:
[ruby-core:86410] [Bug #14634].
Expected #<MiniTest::Assertion: Expected #<Process::Status: pid 14192 SIGABRT (signal 6) (core dumped)> to be success?.> to be nil.

  2) Failure:
TestAutoload#test_autoload_fork [/usr/local/tmp/crew/ruby-2.7.2.tar.xz.dir/ruby-2.7.2/tool/lib/zombie_hunter.rb:6]:
Expected [[14193, #<Process::Status: pid 14193 SIGABRT (signal 6) (core dumped)>],
 [14194, #<Process::Status: pid 14194 SIGABRT (signal 6) (core dumped)>]] to be empty.

[ 5842/21030] TestBeginEndBlock#test_internal_errinfo_at_exit = 0.51 s                                
  3) Failure:
TestBeginEndBlock#test_internal_errinfo_at_exit [/usr/local/tmp/crew/ruby-2.7.2.tar.xz.dir/ruby-2.7.2/test/ruby/test_beginendblock.rb:175]:
Expected #<Process::Status: pid 14275 SIGABRT (signal 6) (core dumped)> to not be signaled?.

[11672/21030] TestIO#test_copy_stream_socket7 = 1.17 s                                                                                               
  4) Failure:
TestIO#test_copy_stream_socket7 [/usr/local/tmp/crew/ruby-2.7.2.tar.xz.dir/ruby-2.7.2/test/ruby/test_io.rb:947]:
Expected #<Process::Status: pid 16914 SIGABRT (signal 6) (core dumped)> to be success?.

[12311/21030] TestJIT#test_compile_insn_opt_invokebuiltin_delegate_leave                                      
/usr/local/tmp/crew/ruby-2.7.2.tar.xz.dir/ruby-2.7.2/test/ruby/test_jit.rb:606: warning: 'opt_invokebuiltin_delegate_leave' insn is not included in the script. Actual insns are: opt_invokebuiltin_delegate leave
[14473/21030] TestProcess#test_process_detach = 1.80 s                                                                   
  5) Failure:
TestProcess#test_process_detach [/usr/local/tmp/crew/ruby-2.7.2.tar.xz.dir/ruby-2.7.2/test/ruby/test_process.rb:2274]:
Expected #<Process::Status: pid 20840 SIGABRT (signal 6) (core dumped)> to be success?.

[14488/21030] TestProcess#test_signals_work_after_exec_fail = 8.63 s 
  6) Failure:
TestProcess#test_signals_work_after_exec_fail [/usr/local/tmp/crew/ruby-2.7.2.tar.xz.dir/ruby-2.7.2/test/ruby/test_process.rb:2354]:
Expected #<Process::Status: pid 20858 SIGABRT (signal 6) (core dumped)> to be success?.

[14502/21030] TestProcess#test_threading_works_after_exec_fail = 1.86 s       
  7) Failure:
TestProcess#test_threading_works_after_exec_fail [/usr/local/tmp/crew/ruby-2.7.2.tar.xz.dir/ruby-2.7.2/test/ruby/test_process.rb:2390]:
Expected #<Process::Status: pid 20916 SIGABRT (signal 6) (core dumped)> to be success?.

[16785/21030] TestRand#test_fork_shuffle = 3.20 s                                                                               
  8) Failure:
TestRand#test_fork_shuffle [/usr/local/tmp/crew/ruby-2.7.2.tar.xz.dir/ruby-2.7.2/test/ruby/test_rand.rb:432]:
#<Process::Status: pid 20994 SIGABRT (signal 6) (core dumped)>.
Expected #<Process::Status: pid 20994 SIGABRT (signal 6) (core dumped)> to be success?.

[16792/21030] TestRand#test_rand_reseed_on_fork = 1.42 s          
  9) Failure:
TestRand#test_rand_reseed_on_fork [/usr/local/tmp/crew/ruby-2.7.2.tar.xz.dir/ruby-2.7.2/test/ruby/test_rand.rb:462]:
[ruby-core:41209]
pid 21007 killed by SIGABRT (signal 6) (core dumped)

[19813/21030] TestThread#test_blocking_mutex_unlocked_on_fork = 3.11 s                                                                                               
 10) Failure:
TestThread#test_blocking_mutex_unlocked_on_fork [/usr/local/tmp/crew/ruby-2.7.2.tar.xz.dir/ruby-2.7.2/test/ruby/test_thread.rb:1200]:
[ruby-core:55102] [Bug #8433].
<false> expected but was
<nil>.

[19815/21030] TestThread#test_fork_in_thread = 12.21 s                          
 11) Failure:
TestThread#test_fork_in_thread [/usr/local/tmp/crew/ruby-2.7.2.tar.xz.dir/ruby-2.7.2/test/ruby/test_thread.rb:1220]:
[ruby-core:62070] [Bug #9751]
pid 22418 killed by SIGABRT (signal 6) (core dumped).
Expected #<Process::Status: pid 22418 SIGABRT (signal 6) (core dumped)> to not be signaled?.


[19816/21030] TestThread#test_fork_while_locked = 12.83 s       
 12) Failure:
TestThread#test_fork_while_locked [/usr/local/tmp/crew/ruby-2.7.2.tar.xz.dir/ruby-2.7.2/test/ruby/test_thread.rb:1231]:
[ruby-core:85940] [Bug #14578].
Expected #<Process::Status: pid 22453 SIGABRT (signal 6) (core dumped)> to be success?.

 13) Failure:
TestThread#test_fork_while_locked [/usr/local/tmp/crew/ruby-2.7.2.tar.xz.dir/ruby-2.7.2/tool/lib/zombie_hunter.rb:6]:
Expected [[22530, #<Process::Status: pid 22530 SIGABRT (signal 6) (core dumped)>],
 [22529, #<Process::Status: pid 22529 SIGABRT (signal 6) (core dumped)>]] to be empty.

Finished tests in 611.778829s, 34.3621 tests/s, 4447.0548 assertions/s.                                                  
21022 tests, 2720614 assertions, 13 failures, 0 errors, 72 skips

ruby -v: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-gnu]
make: *** [uncommon.mk:782: yes-test-all] Aborted (core dumped)
ruby failed to build: `TMPDIR=/usr/local/tmp make check` exited with 2
```

**Comment by uberhacker** [comment]
Thank you for the feedback @satmandu.  I have mixed feelings about the validity of tests.  Passing tests give a false sense of confidence whereas failed tests might not be a big deal.  That said, there are a lot of different ways to test ruby.  Do you have any clues how to solve these failed tests?

**Comment by satmandu** [comment]
No idea at all. I'm not a ruby dev, and crew seems to run fine with the newer release. If these tests aren't important, maybe they should be disabled in the recipe/script so ```crew build ruby``` works?

**Comment by uberhacker** [comment]
Fixed in #4392.

**Pull request closed without merging**
