### PR TITLE
(UPDATE/FIX) Python27 SSL Stuff

### PR DESCRIPTION
**Pull request by bfayers**
Quick rundown of changes.
- Add openssl_devel as a dependency
- Change source_url to a **slightly** modified source so Python27 builds with SSL support
- Changed source_sha1 to match the new source_url
- Added installation of pip at the end.
- Changed version number (in crew) to 2.7.12-1 so people can just run crew update

pip For All!
Enjoy
-bfayers

### CODE REVIEW

**Comment by bfayers** [comment]
Removed pip stuff as it ran before python was finished installing. users can get-pip themselves.

**Comment by bfayers** [comment]
Summary after bugs smashed out:
- Added openssl_devel as dependency
- Change source url to a **slightly** modified source so that python is looking in the correct folders for ssl
- Change sha1 to match
- Changed version number in crew to 2.7.12-1

Enjoy your snakes
-bfayers

**Comment by thedamian** [comment]
I have this fixed on my chromebook pixel and I don't remember how. I think all I did was put the requirements of openssl_devel

Why not try just installing the very of ruby directly from the source and see if the dependancy fixes it. I needed python to have SSL for another project and I think I solved it by just that dependancy.

**Comment by bfayers** [comment]
Closing. Will reopen at a later date when confirmed required.

**Pull request closed without merging**
