### PR TITLE
Update subversion from 1.9.7 to 1.9.12

### PR DESCRIPTION
**Pull request by cstrouse**
Update package and remove dependencies included in core. Tested on ARM.

### CODE REVIEW

**Comment by uberhacker** [comment]
I didn't think anybody was using this anymore. :)

**Comment by cstrouse** [comment]
There are some projects that still use SVN like WordPress that I need it for.

**Comment by uberhacker** [comment]
WordPress needs to "git" with the program.

**Comment by JL2210** [comment]
https://www-us.apache.org/dist/subversion/subversion-1.12.2.tar.bz2 is the latest. You might consider updating your update.

**Pull request merged**
