### PR TITLE
Update binary versions in install.sh

### LINKED ISSUE #1624: Can't install Chromebrew - Checksums don't match
Hi,

I am using an ARM Chromebook, and some hours ago I started to get problems when trying to crew install any application. After downloading the binaries, Chromebrew threw a checksum error. I figured that something could be wrong with my Chromebrew, so I nuked my /usr/local folder and tried to install Chromebrew from zero again. But when I try to do it, I get this error:

> wget -q -O - https://raw.github.com/skycocker/chromebrew/master/install.sh | bash
> Password: 
> Creating new device.json...
> Downloading ruby...
> ######################################################################## 100.0%
> Verifying ruby...
> ruby-2.4.1-chromeos-armv7l.tar.xz: FAILED
> sha256sum: WARNING: 1 computed checksum did NOT match
> Verification failed, something may be wrong with the ruby download.

Why do I keep getting this warnings about the checksums?

Thanks,

Nicolás.

### PR DESCRIPTION
**Pull request by uberhacker**
Fixes #1624.

### CODE REVIEW

**Comment by nicolascolla** [comment]
> Downloading libssh2...
> ######################################################################## 100.0%
> Verifying libssh2...
> libssh2-1.8.0-chromeos-armv7l.tar.xz: FAILED
> sha256sum: WARNING: 1 computed checksum did NOT match
> Verification failed, something may be wrong with the libssh2 download.

**Comment by uberhacker** [comment]
@nicolascolla: What is your architecture and system specs?

**Comment by nicolascolla** [comment]
I'm using a CTL J4+ (4GB RAM). Its architechture is armv7l and it uses a Quad Core Arm 1.8 Ghz RK3288 (Rockchip) processor.

**Comment by uberhacker** [comment]
Have you tried pulling the changes in this PR?  It uses a different location for libssh2.

**Comment by nicolascolla** [comment]
@uberhacker since I'm new to Github, I thought that maybe I had downloaded the old version of the script, so I have downloaded the script and changed manually the lines of this pull request. But I still get the same error.

**Comment by uberhacker** [comment]
I just tried a fresh install on an armv7l system and it worked fine.  Have you tried more than once?

**Comment by nicolascolla** [comment]
This is really weird. If I download the tar.xz file manually and check the sha256sum on the terminal I get the same checksum that is specified on this pull request (6fa84296583273dd9e749a2c54cb1cf688a7dab032e2528de5944a4d9777f037). But still, when running the script, I get that error.

I have checked my script again and it is identical to the one on this PR.

**Comment by uberhacker** [comment]
You could try a powerwash.  I know that is extreme but if you start fresh, that may help.

**Comment by nicolascolla** [comment]
Ok, so I tried deleting the entire /usr/local folder and now it works like a charm. It seems like something installed there was causing the error. Thanks a lot for your help.

**Comment by uberhacker** [comment]
No problem.  Glad you got it sorted!

**Comment by slickplaid** [comment]
> Chromebrew installed successfully and package lists updated.
These changes worked beautifully for me on a fresh pixelbook install. Thanks for the quick fixes.

**Pull request merged**
