### PR TITLE
Rebuild curl binaries against libressl

### LINKED ISSUE #3640: [php7] Unable to build from source
May affect other packages that depend on curl as well.
```
checking for cURL support... yes
checking for libcurl.pc... using default path
checking for cURL 7.15.5 or greater... 7.66.0
checking for SSL support in libcurl... yes
checking how to run the C preprocessor... cc -E
checking for openssl support in libcurl... no
checking for gnutls support in libcurl... no
checking for curl_easy_perform in -lcurl... no
configure: error: There is something wrong. Please check config.log for more information.
php7 failed to build: `./configure --prefix=/usr/local --docdir=/usr/local/doc --infodir=/usr/local/info --libdir=/usr/local/lib --localstatedir=/usr/local/tmp --mandir=/usr/local/share/man --sbindir=/usr/local/bin --with-config-file-path=/usr/local/etc --with-libdir=lib --with-freetype-dir=/usr/local/include/freetype2/freetype --with-pcre-regex=/usr/local/lib --with-jpeg-dir=/usr/local/lib --with-kerberos=/usr/local/lib --with-png-dir=/usr/local/lib --with-webp-dir=/usr/local/lib --with-xpm-dir=/usr/local/lib --enable-exif --enable-fpm --enable-ftp --enable-mbstring --enable-opcache --enable-pcntl --enable-shared --enable-shmop --enable-sockets --enable-zip --with-bz2 --with-curl --with-gd --with-gettext --with-gmp --with-libzip --with-mysqli --with-openssl --with-pcre-regex --with-pdo-mysql --with-pear --with-readline --with-tidy --with-unixODBC --with-xsl --with-zlib` exited with 1
```

### PR DESCRIPTION
**Pull request by uberhacker**
Fixes #3640.  Tested on all architectures.

### CODE REVIEW

**Comment by cstrouse** [comment]
Works on ARM.

**Comment by JL2210** [comment]
Hmm... Didn't I suggest this?

**Comment by uberhacker** [comment]
Didn't I submit a PR?  What is your point?

**Comment by JL2210** [comment]
Well, yeah. I suggested to include the rebuilds in the PR. Doesn't matter
much now, anyway.

**Pull request merged**
