### PR TITLE
Sqlite -> 3.10 -=*=- Node -> 4.2.4 -=*=- Node_stable (5.4.1) -=*=- JDK8 download url fix (again) -=*=- faddee's GCC fix to install.sh

### PR DESCRIPTION
**Pull request by thedamian**
- SqLite to version 3.10 - (needed this version for a project I'm working on)
- NodeJS package renamed to Node to change it to the Node new naming convertion (nodejs will make people think it's the old version of node)
- Node package upgraded to the official LTS (4.2.4)
- Node_stable package added for node's official "STABLE" branch (v5.4.1)
- Fixed a JDK8 link mix up (I created the problem. I'm fixing it)
- Added @faddee 's fix for GCC (linked as CC also) to the install.sh

### CODE REVIEW

**Comment by thedamian** [comment]
Anyone know how to split these.

I'm ok with any of these not going in, except for JDK8 which I screwed up the link on my dropbox and want to fix that.

I'm ok with just THAT change going in.

**Comment by lyxell** [comment]
It looks good to me.

**Comment by thedamian** [comment]
Thank you @lyxell 
I think it's important that others test what we're checking in. 

I appreciate that.

**Comment by thedamian** [comment]
Added @faddee 's amazing link of GCC.

I agree with skycoker that it should be a config thing, but when doing an NPM install of a crypo library if I didn't have faddee's change It wasn't working.

Just to be clear. This "CONFIG" change @skycocker  was talking about. would it be PER project? Because this NPM package I wouldn't be able to change.

**Comment by skycocker** [comment]
I guess the chromebrew development goes too fast to try to keep it as it was and the cc symlink is now necessary. @thedamian, could you just close this bracket so I can merge this? https://github.com/skycocker/chromebrew/pull/137/files#diff-3fbb47e318cd8802bd325e7da9aaabe8R106

**Comment by thedamian** [comment]
Hey skycocker. 

I don't see the missing bracket. Tell me in which file?

**Comment by skycocker** [comment]
@thedamian merged. Thanks! :)

**Comment by thedamian** [comment]
@skycocker I wish these were separate PR so that you could choose what goes in and what doesn't 

The symlink is just my suggestion because I don't know how to do it any other way other than how @faddee suggested which worked for me when I had trouble with an mpm package I needed.

**Pull request merged**
