### PR TITLE
Update build_cross_gcc script to use crew specific variables for versions

### PR DESCRIPTION
**Pull request by uberhacker**
Also added some validation and input constraints.  It definitely needs work.  I have been unable to build for any architecture successfully yet.  My hangup is always here:
```
make[1]: Nothing to be done for 'install-target'.
make[1]: Leaving directory '/media/tmp/build-binutils'
Makefile:610: arch/i686-cros-linux/Makefile: No such file or directory
make: *** No rule to make target 'arch/i686-cros-linux/Makefile'.  Stop.
```
@JL2210: Please look at this when you get a chance and try to debug.

Thanks

For reference: https://gcc.gnu.org/install/specific.html

### CODE REVIEW

**Comment by JL2210** [comment]
No way! What happened to my old PR?

**Comment by uberhacker** [comment]
It got tidied up a bit. :)

**Comment by JL2210** [comment]
I'll make some changes. It doesn't need the crew command.

**Comment by uberhacker** [comment]
The crew command makes sure the versions are the same as the latest packages.  We need to simulate the current Chromebrew environment as closely as we can.

**Comment by JL2210** [comment]
It requires 3 arguments. The target, the arch type, such as x86 or arm64, and the kernel version.

**Comment by uberhacker** [comment]
The kernel version is not necessary.  We can get that from the linuxheaders package version.

**Comment by JL2210** [comment]
Except that you don't have the source for linuxheaders. Can you close this and I'll go off of yours?

**Comment by JL2210** [comment]
Notice `cross`, not `cros`.

**Comment by JL2210** [comment]
BTW, glibc223 fails to compile with this. That's why I switched to 228.

**Comment by uberhacker** [comment]
Closing to let @JL2210 fix it better.

**Comment by uberhacker** [comment]
The `cros` means "Chrome OS` and is totally arbitrary.

**Comment by JL2210** [comment]
`cross`, not `cros`.

**Comment by uberhacker** [comment]
Like I said, the value is arbitrary and only there so gcc considers it a "valid" architecture.

**Comment by JL2210** [comment]
OK. yeah. It doesn't really matter. BTW, I was talking about the name of the script.

**Comment by JL2210** [comment]
The versions I use are newer and they all work very well with each other. I have an updated script that uses a newer version of everything except glibc and the kernel version.

**Pull request closed without merging**
