### PR TITLE
Update filezilla from 3.38.1 to 3.39.0

### PR DESCRIPTION
**Pull request by uberhacker**
Tested on:
- [x] aarch64
- [x] armv7l
- [x] i686
- [x] x86_64

### CODE REVIEW

**Comment by JL2210** [comment]
Darn. I was going to do this, too.

**Comment by uberhacker** [comment]
If you are "looking" for things to do, the code package is still dead in the water.  That really should be a high priority right now.  Lots of users want to use code.

**Comment by JL2210** [comment]
And dead in the water it will stay. That program is probably broken. After
all, it was written by the company that created Windows.

**Comment by sajjaadf** [comment]
Use sublime its better

-- SajjaadF

**Pull request merged**
