### PR TITLE
Update sommelier from 1382ce0 to 1382ce08

### PR DESCRIPTION
**Pull request by uberhacker**
Add --scale option to sommelierd and improve the pid detection in the scripts.

Tested on:
- [x] aarch64
- [x] armv7l
- [x] i686
- [x] x86_64

### CODE REVIEW

**Comment by JL2210** [comment]
Just a note, the scale would be different on Chromebooks with different DPIs. You might not set that variable.

**Comment by uberhacker** [comment]
Leaving it unset produces the same problem.  At least now they know the option is available if they want to change it or not.  They also don't need to change the script.  They can change the environment variable in `~/.bashrc`.

**Comment by JL2210** [comment]
Fair enough. A suggestion: Maybe you could add a note in the postinstall about that.

**Comment by uberhacker** [comment]
It would have to be just one line.  The current post install message is almost using up the entire viewable screen already.

**Comment by JL2210** [comment]
Maybe install a `bashrc.tmp` file in `/usr/local/tmp` and ask users to `cat /usr/local/tmp/bashrc.tmp >> ~/.bashrc`?

**Comment by JL2210** [comment]
That would save space in the postinstall.

**Comment by uberhacker** [comment]
The thing is, I want users to see what they're appending to `~/.bashrc` and understand what it means.  If you hide it, then they don't see and understand.

**Comment by JL2210** [comment]
Have them first `cat /usr/local/tmp/bashrc.tmp`?

**Pull request merged**
