### PR TITLE
wget => 1.21.3

### PR DESCRIPTION
**Pull request by supechicken**
### Changes
- Updated to `1.21.3`
- Remove unnecessary dependencies
- Switch from `gnutls` to `openssl`
- Replace `libiconv` error with a warning

Tested on `x86_64`

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/supechicken/chromebrew.git CREW_TESTING_BRANCH=wget CREW_TESTING=1 crew update
```

### CODE REVIEW

**Comment by satmandu** [comment]
build fails on i686:
```
make  all-am
make[3]: Entering directory '/usr/local/tmp/crew/wget.20220302175601.dir/wget-1.21.3/lib'
  CC       libgnu_a-openat-proc.o
  CC       libgnu_a-base32.o
  CC       libgnu_a-basename-lgpl.o
  CC       libgnu_a-binary-io.o
In file included from /usr/local/include/string.h:630,
                 from ./string.h:41,
                 from basename-lgpl.c:25:
./string.h:1080:1: error: expected identifier or '(' before '__extension__'
 1080 | _GL_FUNCDECL_SYS (strndup, char *,
      | ^~~~~~~~~~~~~~~~
make[3]: *** [Makefile:3301: libgnu_a-basename-lgpl.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /usr/local/include/string.h:630,
                 from ./string.h:41,
                 from openat-proc.c:30:
./string.h:1080:1: error: expected identifier or '(' before '__extension__'
 1080 | _GL_FUNCDECL_SYS (strndup, char *,
      | ^~~~~~~~~~~~~~~~
make[3]: *** [Makefile:3273: libgnu_a-openat-proc.o] Error 1
In file included from /usr/local/include/string.h:630,
                 from ./string.h:41,
                 from base32.c:53:
./string.h:1080:1: error: expected identifier or '(' before '__extension__'
 1080 | _GL_FUNCDECL_SYS (strndup, char *,
      | ^~~~~~~~~~~~~~~~
make[3]: *** [Makefile:3287: libgnu_a-base32.o] Error 1
make[3]: Leaving directory '/usr/local/tmp/crew/wget.20220302175601.dir/wget-1.21.3/lib'
make[2]: *** [Makefile:2773: all] Error 2
make[2]: Leaving directory '/usr/local/tmp/crew/wget.20220302175601.dir/wget-1.21.3/lib'
make[1]: *** [Makefile:1754: all-recursive] Error 1
make[1]: Leaving directory '/usr/local/tmp/crew/wget.20220302175601.dir/wget-1.21.3'
make: *** [Makefile:1706: all] Error 2
wget failed to build: `CFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=gold" CXXFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=gold" FCFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=gold" FFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=gold" LDFLAGS="-flto" bash -c make -j4` exited with 2
```

**Comment by uberhacker** [comment]
FWIW, I tried to revert to the previous dependencies and the i686 build has the same error.

**Comment by supechicken666** [comment]
[Binaries for all architectures (build with `clang+lld`)](https://github.com/skycocker/chromebrew/files/8203599/Archive.zip)

**Comment by satmandu** [comment]
Added a package + binaries which work for all architectures.

**Pull request merged**
