### PR TITLE
add c89 and c99 executables to gcc11

### PR DESCRIPTION
**Pull request by saltedcoffii**
The POSIX Single UNIX Specification, Version 2 requires the c89 executable to compile ANSI C programs.
The POSIX Open Group Base Specifications, Issue 6 requires the c99 executable to compile C99 programs.

This pull request adds both executables to gcc11. I honestly don't think we need to recompile the binaries. We just need to extract the already existing binaries, put the scripts in their proper places with 0755 permissions and retarball and compress them.

```
CREW_TESTING_REPO=https://github.com/saltedcoffii/chromebrew.git CREW_TESTING_BRANCH=c89\&c99 CREW_TESTING=1 crew update
```

### CODE REVIEW

**Comment by satmandu** [comment]
I think @uberhacker just added functionality to add files properly from post-install...

Also, this is essentially the same as the file from debian, no?

**Comment by satmandu** [comment]
Ubuntu c89:
```
#! /bin/sh

# Call the appropriate C compiler with options to accept ANSI/ISO C
# The following options are the same (as of gcc-2.95):
#       -ansi
#       -std=c89
#       -std=iso9899:1990

extra_flag=-std=c89

for i; do
    case "$i" in
        -ansi|-std=c89|-std=iso9899:1990)
            extra_flag=
            ;;
        -std=*)
            echo >&2 "`basename $0` called with non ANSI/ISO C option $i"
            exit 1
            ;;
    esac
done

exec gcc $extra_flag ${1+"$@"}
```

**Comment by saltedcoffii** [comment]
I probably should have put it in the original message, but these scripts are from archlinux.

**Comment by satmandu** [comment]
Can you put this in the postinstall so that we don't have to rebuild this? (And use the logic @uberhacker setup to add the files to the filelist.)

**Comment by saltedcoffii** [comment]
I'll make binaries.

**Comment by satmandu** [comment]
Also, FYI, a generic`crew` modification to allow uncompressing and recompressing packages would be useful too. Something along the lines of extracting a given package to destroot, and then repackaging it (and generating the appropriate filelist and dlist files too, and also running the steps to compress the contents.)  This way you could programmatically compress older packages already built with a different compression format, which might be nice for batch processing older package files.

**Comment by saltedcoffii** [comment]
https://github.com/saltedcoffii/chromebrew/releases/tag/v0.4

**Comment by satmandu** [comment]
Also, please don't put ampersands in your branch names. :)

**Comment by saltedcoffii** [comment]
> Also, please don't put ampersands in your branch names. :)

Of course, why?

**Comment by satmandu** [comment]
They are hard to make work with the command line since they need eacaping.

**Pull request merged**
