### PR TITLE
Mesa -> 21.2.5

### PR DESCRIPTION
**Pull request by satmandu**
- This is built upon the Python 3.10 PR, so please don't merge before that is merged.

Works properly:
- [x] x86_64

Builds properly:
- [x] x86_64
- [x] armv7l
- [x] i686 (needs build)

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=mesa2124 CREW_TESTING=1 crew update
```

### CODE REVIEW

**Comment by uberhacker** [comment]
My i686 build failed as shown below:
```
[2073/2073] Linking target src/intel/vulkan/libvulkan_intel.so
samu: job failed: c++  -o src/intel/vulkan/libvulkan_intel.so src/intel/vulkan/libvulkan_intel.so.p/anv_gem.c.o -flto -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -Wl,-soname,libvulkan_intel.so -Wl,--whole-archive src/intel/vulkan/libanv_common.a src/intel/vulkan/libanv_per_hw_ver70.a src/intel/vulkan/libanv_per_hw_ver75.a src/intel/vulkan/libanv_per_hw_ver80.a src/intel/vulkan/libanv_per_hw_ver90.a src/intel/vulkan/libanv_per_hw_ver110.a src/intel/vulkan/libanv_per_hw_ver120.a src/intel/vulkan/libanv_per_hw_ver125.a src/vulkan/util/libvulkan_util.a -Wl,--no-whole-archive src/intel/compiler/libintel_compiler.a src/util/libmesa_util.a src/util/format/libmesa_format.a src/intel/dev/libintel_dev.a src/intel/isl/libisl.a src/intel/isl/libisl_per_hw_ver40.a src/intel/isl/libisl_per_hw_ver50.a src/intel/isl/libisl_per_hw_ver60.a src/intel/isl/libisl_per_hw_ver70.a src/intel/isl/libisl_per_hw_ver75.a src/intel/isl/libisl_per_hw_ver80.a src/intel/isl/libisl_per_hw_ver90.a src/intel/isl/libisl_per_hw_ver110.a src/intel/isl/libisl_per_hw_ver120.a src/intel/isl/libisl_per_hw_ver125.a src/intel/isl/libisl_tiled_memcpy.a src/intel/isl/libisl_tiled_memcpy_sse41.a src/intel/blorp/libblorp.a src/vulkan/wsi/libvulkan_wsi.a src/util/libxmlconfig.a src/compiler/libcompiler.a src/intel/perf/libintel_perf.a src/intel/common/libintel_common.a src/compiler/nir/libnir.a -Wl,--build-id=sha1 -Wl,-Bsymbolic -Wl,--gc-sections -pthread -ldl -lm /usr/local/lib/libdrm.so /usr/local/lib/libxcb-dri3.so /usr/local/lib/libwayland-client.so /usr/local/lib/libXrandr.so /usr/local/lib/libz.so /usr/local/lib/libexpat.so /usr/local/lib/libzstd.so /usr/local/lib/libunwind.so /usr/local/lib/libxcb.so /usr/local/lib/libX11-xcb.so /usr/local/lib/libX11.so /usr/local/lib/libxcb-present.so /usr/local/lib/libxcb-sync.so /usr/local/lib/libxcb-randr.so /usr/local/lib/libxshmfence.so -Wl,--end-group
../src/intel/compiler/brw_fs.cpp: In member function ‘dump_instruction’:
../src/intel/compiler/brw_fs.cpp:8296:1: error: unrecognizable insn:
 8296 | }
      | ^
(insn 632 631 633 72 (set (reg:SF 246 [ _297 ])
        (reg:SF 20 xmm0)) "../src/util/half_float.h":86:35 -1
     (nil))
during RTL pass: vregs
../src/intel/compiler/brw_fs.cpp:8296:1: internal compiler error: in extract_insn, at recog.c:2770
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
lto-wrapper: fatal error: c++ returned 1 exit status
compilation terminated.
/usr/local/bin/ld: fatal error: lto-wrapper failed
collect2: error: ld returned 1 exit status
samu: job failed: c++  -o src/gallium/targets/dri/libgallium_dri.so src/gallium/targets/dri/libgallium_dri.so.p/target.c.o -flto -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -Wl,-soname,libgallium_dri.so '-Wl,-rpath,$ORIGIN/../../../mapi/shared-glapi' -Wl,-rpath-link,/usr/local/tmp/crew/mesa.20211024233812.dir/builddir/src/mapi/shared-glapi src/gallium/frontends/dri/libdri.a src/util/libmesa_util.a src/util/format/libmesa_format.a src/mesa/libmesa_gallium.a src/mesa/libmesa_common.a src/compiler/glsl/libglsl.a src/compiler/glsl/glcpp/libglcpp.a src/compiler/nir/libnir.a src/compiler/libcompiler.a src/mesa/libmesa_sse41.a src/mesa/drivers/dri/common/libdricommon.a src/mesa/drivers/dri/common/libmegadriver_stub.a src/gallium/auxiliary/libgalliumvl.a src/gallium/auxiliary/libgallium.a src/mapi/shared-glapi/libglapi.so.0.0.0 src/gallium/auxiliary/pipe-loader/libpipe_loader_static.a src/loader/libloader.a src/util/libxmlconfig.a src/gallium/winsys/sw/null/libws_null.a src/gallium/winsys/sw/wrapper/libwsw.a src/gallium/winsys/sw/dri/libswdri.a src/gallium/winsys/sw/kms-dri/libswkmsdri.a src/gallium/drivers/llvmpipe/libllvmpipe.a src/gallium/drivers/softpipe/libsoftpipe.a src/gallium/winsys/kmsro/drm/libkmsrowinsys.a src/gallium/drivers/svga/libsvga.a src/gallium/winsys/svga/drm/libsvgadrm.a src/gallium/drivers/virgl/libvirgl.a src/gallium/winsys/virgl/drm/libvirgldrm.a src/gallium/winsys/virgl/common/libvirglcommon.a src/gallium/winsys/virgl/vtest/libvirglvtest.a src/gallium/drivers/swr/libmesaswr.a src/gallium/drivers/lima/liblima.a src/gallium/winsys/lima/drm/liblimawinsys.a src/panfrost/shared/libpanfrost_shared.a src/gallium/drivers/zink/libzink.a -Wl,--build-id=sha1 -Wl,--gc-sections -Wl,--version-script /usr/local/tmp/crew/mesa.20211024233812.dir/src/gallium/targets/dri/dri.sym -Wl,--dynamic-list /usr/local/tmp/crew/mesa.20211024233812.dir/src/gallium/targets/dri/../dri-vdpau.dyn /usr/local/lib/libdrm.so -lLLVM-12 -pthread /usr/local/lib/libexpat.so /usr/local/lib/libz.so -lm /usr/local/lib/libzstd.so -ldl /usr/local/lib/libunwind.so -lLLVM-12 -lsensors -lLLVM-12 -lLLVM-12 /usr/local/lib/libvulkan.so -Wl,--end-group
../src/mesa/main/uniform_query.cpp: In function ‘_mesa_get_uniform’:
../src/mesa/main/uniform_query.cpp:727:1: error: unrecognizable insn:
  727 | }
      | ^
(insn 288 287 289 48 (set (reg:SF 388 [ _482 ])
        (reg:SF 20 xmm0)) "../src/util/half_float.h":86:35 -1
     (nil))
during RTL pass: vregs
../src/mesa/main/uniform_query.cpp:727:1: internal compiler error: in extract_insn, at recog.c:2770
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
lto-wrapper: fatal error: c++ returned 1 exit status
compilation terminated.
/usr/local/bin/ld: fatal error: lto-wrapper failed
collect2: error: ld returned 1 exit status
samu: job failed: c++  -o src/mesa/drivers/dri/libmesa_dri_drivers.so  -flto -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -Wl,-soname,libmesa_dri_drivers.so -Wl,--whole-archive src/mesa/drivers/dri/i915/libi915.a src/mesa/drivers/dri/i965/libi965.a src/mesa/drivers/dri/radeon/libr100.a src/mesa/drivers/dri/r200/libr200.a src/mesa/drivers/dri/nouveau/libnouveau_vieux.a -Wl,--no-whole-archive '-Wl,-rpath,$ORIGIN/../../../mapi/shared-glapi' -Wl,-rpath-link,/usr/local/tmp/crew/mesa.20211024233812.dir/builddir/src/mapi/shared-glapi src/mesa/drivers/dri/common/libmegadriver_stub.a src/mesa/drivers/dri/common/libdricommon.a src/util/libmesa_util.a src/util/format/libmesa_format.a src/mapi/shared-glapi/libglapi.so.0.0.0 src/mesa/libmesa_classic.a src/mesa/libmesa_common.a src/compiler/glsl/libglsl.a src/compiler/glsl/glcpp/libglcpp.a src/compiler/nir/libnir.a src/compiler/libcompiler.a src/mesa/libmesa_sse41.a src/util/libxmlconfig.a src/mesa/drivers/dri/i965/libi965_per_hw_ver40.a src/mesa/drivers/dri/i965/libi965_per_hw_ver45.a src/mesa/drivers/dri/i965/libi965_per_hw_ver50.a src/mesa/drivers/dri/i965/libi965_per_hw_ver60.a src/mesa/drivers/dri/i965/libi965_per_hw_ver70.a src/mesa/drivers/dri/i965/libi965_per_hw_ver75.a src/mesa/drivers/dri/i965/libi965_per_hw_ver80.a src/mesa/drivers/dri/i965/libi965_per_hw_ver90.a src/mesa/drivers/dri/i965/libi965_per_hw_ver110.a src/intel/dev/libintel_dev.a src/intel/isl/libisl.a src/intel/isl/libisl_per_hw_ver40.a src/intel/isl/libisl_per_hw_ver50.a src/intel/isl/libisl_per_hw_ver60.a src/intel/isl/libisl_per_hw_ver70.a src/intel/isl/libisl_per_hw_ver75.a src/intel/isl/libisl_per_hw_ver80.a src/intel/isl/libisl_per_hw_ver90.a src/intel/isl/libisl_per_hw_ver110.a src/intel/isl/libisl_per_hw_ver120.a src/intel/isl/libisl_per_hw_ver125.a src/intel/isl/libisl_tiled_memcpy.a src/intel/isl/libisl_tiled_memcpy_sse41.a src/intel/compiler/libintel_compiler.a src/intel/blorp/libblorp.a src/intel/perf/libintel_perf.a src/intel/common/libintel_common.a -Wl,--build-id=sha1 -Wl,-Bsymbolic -Wl,--gc-sections /usr/local/lib/libdrm.so -lm -pthread -ldl /usr/local/lib/libz.so /usr/local/lib/libexpat.so /usr/local/lib/libzstd.so /usr/local/lib/libunwind.so /usr/local/lib/libdrm_intel.so /usr/local/lib/libdrm_radeon.so /usr/local/lib/libdrm_nouveau.so -Wl,--end-group
../src/mesa/main/uniform_query.cpp: In function ‘_mesa_get_uniform’:
../src/mesa/main/uniform_query.cpp:727:1: error: unrecognizable insn:
  727 | }
      | ^
(insn 288 287 289 48 (set (reg:SF 388 [ _482 ])
        (reg:SF 20 xmm0)) "../src/util/half_float.h":86:35 -1
     (nil))
during RTL pass: vregs
../src/mesa/main/uniform_query.cpp:727:1: internal compiler error: in extract_insn, at recog.c:2770
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
lto-wrapper: fatal error: c++ returned 1 exit status
compilation terminated.
/usr/local/bin/ld: fatal error: lto-wrapper failed
collect2: error: ld returned 1 exit status
samu: subcommands failed
mesa failed to build: `samu -C builddir` exited with 1
```

**Comment by satmandu** [comment]
@uberhacker Please see if this build works?

**Comment by uberhacker** [comment]
On i686 with the latest changes, I get:
```
Downloading source...
Initialized empty Git repository in /usr/local/tmp/crew/mesa.20211106054219.dir/.git/
remote: Enumerating objects: 8727, done.
remote: Counting objects: 100% (8727/8727), done.
remote: Compressing objects: 100% (7787/7787), done.
remote: Total 8727 (delta 1875), reused 3520 (delta 661), pack-reused 0
Receiving objects: 100% (8727/8727), 26.65 MiB | 3.34 MiB/s, done.
Resolving deltas: 100% (1875/1875), done.
From https://gitlab.freedesktop.org/mesa/mesa
 * tag               mesa-21.2.5 -> FETCH_HEAD
Updating files: 100% (8414/8414), done.
HEAD is now at d152999 VERSION: bump for 21.2.5 release
Repository downloaded.
Building from source, this may take a while...
Rename all *.la files to *.la_tmp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
mesa failed to build: `curl -OLf https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/13273.patch` exited with 60
```
Your i686 binary seems fine, however.

**Comment by uberhacker** [comment]
Apparently, libcurl is a build dependency since installing that package fixes the certificate issue.

**Comment by satmandu** [comment]
If the binary is ok can we merge this?

**Pull request closed without merging**
