### PR TITLE
Add poppler package

### PR DESCRIPTION
**Pull request by uberhacker**
Poppler is a PDF rendering library based on the xpdf-3.0 code base. See https://poppler.freedesktop.org/.

### CODE REVIEW

**Comment by cstrouse** [comment]
Works on Samsung Chromebook Plus (aarch64).

**Comment by cstrouse** [comment]
I can't get it to build properly on the Samsung Chromebook 3 (x86_64).  I've tried reinstalling `glib` from source as well as doing a fresh install of Chromebrew with no luck.

```bash
/bin/sed: can't read /usr/local/lib/libglib-2.0.la: No such file or directory
libtool:   error: '/usr/local/lib/libglib-2.0.la' is not a valid libtool archive
make[3]: *** [Makefile:957: libpoppler.la] Error 1
make[3]: Leaving directory '/usr/local/tmp/crew/poppler-0.59.0.tar.xz.dir/poppler-0.59.0/poppler'
make[2]: *** [Makefile:862: all] Error 2
make[2]: Leaving directory '/usr/local/tmp/crew/poppler-0.59.0.tar.xz.dir/poppler-0.59.0/poppler'
make[1]: *** [Makefile:653: all-recursive] Error 1
make[1]: Leaving directory '/usr/local/tmp/crew/poppler-0.59.0.tar.xz.dir/poppler-0.59.0'
make: *** [Makefile:536: all] Error 2
poppler failed to install: `make -j2` exited with 2
```

**Comment by uberhacker** [comment]
It seems like it should be looking in `/usr/local/lib64` instead of `/usr/local/lib`.  Does `libglib-2.0.1a` exist in `/usr/local/lib64`?

**Comment by cstrouse** [comment]
Yes it exists. Are the two sed lines perhaps not having the desired effect?

**Comment by uberhacker** [comment]
The only way you would get it installed in `/usr/local/lib64` is on a x86_64 system.  Not sure how it crept into the aarch64 system.

**Comment by cstrouse** [comment]
Seems my system was broken. Powerwash fixed things.

**Pull request merged**
