### PR TITLE
Update Readline package

### PR DESCRIPTION
**Pull request by JL2210**
Updates readline package to 6.3p8-2 and uses new versioning scheme seen in readline 7.0p5.

### CODE REVIEW

**Comment by JL2210** [comment]
Oh shoot. Let me fix this for a minute...

**Comment by uberhacker** [comment]
In case you didn't know already, this is a core package.  We need the pre-built binaries before we can merge this, otherwise, it gets compiled on every new install.

**Comment by JL2210** [comment]
Done.

**Comment by JL2210** [comment]
Oh. Can you copy my work into one of your branches and go from there?

**Comment by uberhacker** [comment]
I can but when you make changes to your PR after the fact, it makes me lose confidence that you have actually tested this to make sure it doesn't have any cascading bad effects.

**Comment by JL2210** [comment]
I have, and it compiled fine. I accidentally omitted the leading section of the old `readline` package that had the system libraries override the libraries provided by the package. Wouldn't it be better for me to catch it and fix it then for you to have to do the same?

**Pull request merged**
