### PR TITLE
Restore aws package

### PR DESCRIPTION
**Pull request by uberhacker**
- Update aws2 package description, homepage, license and source_url
- Tested on all architectures

### CODE REVIEW

**Comment by satmandu** [comment]
Should we be using `--single-version-externally-managed` on these to avoid screwing up python's internal package database?

That's what debian uses. See https://salsa.debian.org/python-team/packages/pygments/-/blob/debian/master/debian/rules

**Comment by saltedcoffii** [comment]
After I separate the repository, I'll add back and clean up all the python packages. I don't think we should be using pip to install packages anymore.

**Comment by satmandu** [comment]
> After I separate the repository, I'll add back and clean up all the python packages. I don't think we should be using pip to install packages anymore.

As long as we can still use pip... We should never be entirely dependent upon packagers to get an update of we need one.

**Comment by saltedcoffii** [comment]
We can, we just shouldn't. It's not a breaking issue so this PR is fine to stay merged.

**Pull request merged**
