### PR TITLE
change method names to conform to ruby conventions

### PR DESCRIPTION
**Pull request by mattddowney**
See:
https://github.com/bbatsov/ruby-style-guide#snake-case-symbols-methods-vars

Should probably make variable names conform to this as well, but that is for another day.

### CODE REVIEW

**Comment by thedamian** [comment]
Ill try it on ny box and would like others to try this too hut doesnt this fall under "if it aint broken....."

**Comment by mattddowney** [comment]
Lots of manual testing going on. Any ideas for some test automation?

**Comment by minektur** [comment]
Maybe we could do something with cloudready - automated vm cloning, automated deploying, etc... but it would be a lot of work.

We now support 3 platforms... I think among the regular contributors we have pretty good coverage of platforms...

What we could maybe do is have a 2-stage release process. a "Beta" where we push stuff, and all can test, and then weekly, or monthly releases or something...  This would fit with our desire to have binaries hosted and release-tagged on github.

**Comment by jam7** [comment]
@mattddowney Hi, is it possible to rebase this PR to the latest one?  I think modifying crew like this way is very important.

**Pull request closed without merging**
