### PR TITLE
change method names to conform to ruby style guidelines

### PR DESCRIPTION
**Pull request by mattddowney**
Reopening as discussed here:
https://github.com/skycocker/chromebrew/pull/310

### CODE REVIEW

**Comment by mattddowney** [comment]
@jam7

**Comment by lyxell** [comment]
Thanks, great PR! Could you remove the temporary file created by your text editor though?

**Comment by mattddowney** [comment]
Whoops, deleted

**Comment by jam7** [comment]
@mattddowney Nice, thank you.  I really like this.  Works fine on armv7l.

**Pull request merged**
