### PR TITLE
Change library location of gnuc_lib for clc++ script

### PR DESCRIPTION
**Pull request by uberhacker**
Tested on:
- [x] x86_64

### CODE REVIEW

**Comment by skiman6010** [comment]
Whoops I swore I merged this already, but I guess I didn't push the big, green button...

**Comment by JL2210** [comment]
@uberhacker You forgot to change the binary URL and the version!

**Comment by uberhacker** [comment]
No, it wasn't necessary since only the x86_64 version changed and that binary was updated.  No need to recompile the i686 and armv7l versions.  Besides, this package requires an overnight task to compile the binaries.  You are welcome to compile from source to see what I mean.

**Comment by JL2210** [comment]
True, but people using the current version won't see it in `crew update && crew upgrade`.

**Comment by uberhacker** [comment]
But if they run `crew update`, it will update silently.  No big deal.

**Comment by JL2210** [comment]
What I'm saying is that unless people use `crew remove llvm && crew install llvm`, they won't see the effects of this update. It won't update or upgrade automatically because the version hasn't changed.

**Comment by uberhacker** [comment]
If anybody does have this problem, then the simple fix is to have them `crew upgrade llvm`.  No biggie.

**Comment by JL2210** [comment]
Therefore, the `clc` and `clc++` scripts won't work. Big deal.

**Comment by JL2210** [comment]
If you don't bump the version number, IT WON'T UPGRADE.

**Comment by JL2210** [comment]
```
chronos@localhost / $ crew update
crew upgrade
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 7 (delta 3), reused 4 (delta 3), pack-reused 0
Unpacking objects: 100% (7/7), done.
From https://github.com/skycocker/chromebrew
 * branch              master     -> FETCH_HEAD
   179700ca..aa961a7d  master     -> origin/master
HEAD is now at aa961a7d Merge pull request #2749 from uberhacker/update-llvm-package
Package lists, crew, and library updated.
Checking for package updates...

glfw could be updated from 0.1.0 to 3.2.1-1

Run `crew upgrade` to update all packages or `crew upgrade <package1> [<package2> ...]` to update specific packages.
```

**Comment by uberhacker** [comment]
Only the clc++ script is affected.  It will upgrade. It will just do it silently.

**Comment by JL2210** [comment]
Look at my comment. It won't. That is my point.

**Comment by uberhacker** [comment]
Don't worry about it.  We will work around any problems users may encounter.

**Comment by JL2210** [comment]
Workarounds?

**Pull request merged**
