### PR TITLE
flatseal => 1.7.5

### PR DESCRIPTION
**Pull request by saltedcoffii**
works on x86_64. needs binaries.

### CODE REVIEW

**Comment by satmandu** [comment]
I'm having trouble updating js78... which is a dep for this...

**Comment by satmandu** [comment]
WIP package:

```
require 'package'

class Js78 < Package
  description 'Spidermonkey is a javaScript interpreter with libraries from Mozilla — Version 78'
  @_ver = '78.15.0'
  version @_ver
  license 'MPL-2.0'
  compatibility 'all'
  source_url "https://archive.mozilla.org/pub/firefox/releases/#{@_ver}esr/source/firefox-#{@_ver}esr.source.tar.xz"
  source_sha256 'a4438d84d95171a6d4fea9c9f02c2edbf0475a9c614d968ebe2eedc25a672151'

  binary_url({
    aarch64: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/js78/78.13.0_armv7l/js78-78.13.0-chromeos-armv7l.tpxz',
     armv7l: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/js78/78.13.0_armv7l/js78-78.13.0-chromeos-armv7l.tpxz',
     x86_64: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/js78/78.13.0_x86_64/js78-78.13.0-chromeos-x86_64.tpxz'
  })
  binary_sha256({
    aarch64: 'c411fce679ebaf36c0f5eb24232499da3902b34561a62555cdb38a0832ca8647',
     armv7l: 'c411fce679ebaf36c0f5eb24232499da3902b34561a62555cdb38a0832ca8647',
     x86_64: '1f95140b994a39b9a2d71f08099e3d4c0f34f5487e2ee24b54e991026c31bc20'
  })

  depends_on 'autoconf213' => :build
  depends_on 'rust' => :build
  depends_on 'llvm' => :build
  depends_on 'nspr'

  @rust_default_host = case ARCH
                       when 'aarch64', 'armv7l'
                         'armv7-unknown-linux-gnueabihf'
                       else
                         "#{ARCH}-unknown-linux-gnu"
                       end

  def self.patch
    # Ubuntu patches
    # http://changelogs.ubuntu.com/changelogs/pool/main/m/mozjs78/mozjs78_78.13.0-1/changelog
    patch_url = 'http://archive.ubuntu.com/ubuntu/pool/main/m/mozjs78/mozjs78_78.15.0-2.debian.tar.xz'
    patch_sha256 = '37c2dcdd20a68d994c00e75577fc2755c4873a23eef78d42659d0042432faf53'

    system "curl -Ls #{patch_url} -o unzippatches.tar.xz"
    unless Digest::SHA256.hexdigest(File.read('./unzippatches.tar.xz')) == patch_sha256
      abort 'Checksum mismatch :/ try again'
    end
    system('tar', '-xf', 'unzippatches.tar.xz')

    system('for i in `cat debian/patches/series`; do  patch -p 1 < debian/patches/$i; done')

    # Arch Patches
    # patch2_url = 'https://github.com/archlinux/svntogit-packages/raw/packages/js78/trunk/0002-Bug-1667736-Update-packed_simd-to-compile-on-Rust-1..patch'
    # patch2_sha256 = 'ad3dd149651d76c1c3de2dc71d3fb3361181a1add75ff095df7bfba88a4e4ad6'
    # system('curl', '-Lf', patch2_url, '-o', '0002-Bug-1667736-Update-packed_simd-to-compile-on-Rust-1..patch')
    # unless Digest::SHA256.hexdigest(File.read('./0002-Bug-1667736-Update-packed_simd-to-compile-on-Rust-1..patch')) == patch2_sha256
    #  abort 'Checksum mismatch :/ try again'
    # end
    # system('patch -p 1 < ./0002-Bug-1667736-Update-packed_simd-to-compile-on-Rust-1..patch')
    
    # Python 3.10 fixes
    system "sed -i s,collections.Sequence,collections.abc.Sequence,g python/mozbuild/mozbuild/util.py"
    system "sed -i 's/Iterable, OrderedDict/OrderedDict/' python/mozbuild/mozbuild/backend/configenvironment.py"
    system "sed -i '/from collections import OrderedDict/a from collections.abc import Iterable' python/mozbuild/mozbuild/backend/configenvironment.py"
    system "sed -i 's/collections import defaultdict, MutableSequence/collections import defaultdict/' testing/mozbase/manifestparser/manifestparser/filters.py"
    system "sed -i '/from collections import defaultdict/a from collections.abc import MutableSequence' testing/mozbase/manifestparser/manifestparser/filters.py"
    system "sed -i 's/collections import Iterable/collections.abc import Iterable/' python/mozbuild/mozbuild/makeutil.py"
    
    # Rust 1.56+ patch from netbsd at http://cvsweb.netbsd.org/bsdweb.cgi/~checkout~/pkgsrc/www/seamonkey/patches/patch-third__party_rust_packed__simd_src_lib.rs
    @packed_simd_patch = <<~PACKED_SIMD_PATCH_EOF   
      #--- third_party/rust/packed_simd/src/lib.rs.orig	2021-08-08 13:02:00.000000000 +0000
      #+++ third_party/rust/packed_simd/src/lib.rs
      #@@ -199,8 +199,9 @@
       #//!   Numeric casts are not very "precise": sometimes lossy, sometimes value
       #//!   preserving, etc.

      #+#![cfg_attr(const_generics, feature(const_generics))]
      #+#![cfg_attr(not(const_generics), feature(adt_const_params))]
       ##![feature(
      #-    const_generics,
           #repr_simd,
           #rustc_attrs,
           #platform_intrinsics,
      --- third_party/rust/packed_simd/src/lib.rs.orig     2021-09-28 10:05:02.000000000 +0000
      +++ third_party/rust/packed_simd/src/lib.rs   2021-12-11 23:28:12.698937467 +0000
      @@ -200,6 +200,7 @@
       //!   preserving, etc.

       #![cfg_attr(use_const_generics, feature(const_generics))]
      +#![cfg_attr(not(const_generics), feature(adt_const_params))]
       #![cfg_attr(use_const_generics, allow(incomplete_features, clippy::from_over_into))]
       #![feature(
           repr_simd,
    PACKED_SIMD_PATCH_EOF
    #File.write('packed_simd.patch', @packed_simd_patch)
    #system 'patch -Np0 -i packed_simd.patch'
    system "sed -i '/packed_simd/d' Cargo.toml"
    system "sed -i '/libudev-sys/a packed_simd = { version = \"0.3.6\", package = \"packed_simd_2\" }' Cargo.toml"
  end

  def self.build
    FileUtils.mkdir_p 'obj'
    Dir.chdir 'obj' do
      system '../js/src/configure --help'
      # error: Cannot set `RUSTC_BOOTSTRAP=1` from build script of `packed_simd v0.3.4 (https://github.com/hsivonen/packed_simd?rev=0917fe780032a6bbb23d71be545f9c1834128d75#0917fe78)`.
      # note: Crates cannot set `RUSTC_BOOTSTRAP` themselves, as doing so would subvert the stability guarantees of Rust for your project.
      # help: If you're sure you want to do this in your project, set the environment variable `RUSTC_BOOTSTRAP=packed_simd` before running cargo instead.
      ENV['RUSTC_BOOTSTRAP'] = 'packed_simd,encoding_rs'
      system "CFLAGS='-stdlib=libc++' \
            RUSTFLAGS='-Clinker-plugin-lto' \
            RUSTUP_HOME='#{CREW_PREFIX}/share/rustup' \
            CARGO_HOME='#{CREW_PREFIX}/share/cargo' \
            AUTOCONF=#{CREW_PREFIX}/bin/autoconf-2.13 \
            CC=clang \
            CXX='clang++' \
            AR=llvm-ar NM=llvm-nm RANLIB=llvm-ranlib \
            LDFLAGS='-lreadline -ltinfo' \
            ../js/src/configure --prefix=#{CREW_PREFIX} \
            --libdir=#{CREW_LIB_PREFIX} \
            --disable-debug \
            --disable-debug-symbols \
            --disable-jemalloc \
            --disable-strip \
            --enable-hardening \
            --enable-linker=lld \
            --enable-lto=thin \
            --enable-optimize \
            --enable-readline \
            --enable-release \
            --enable-rust-simd \
            --enable-shared-js \
            --enable-stdcxx-compat \
            --with-intl-api \
            --without-system-icu \
            --with-system-nspr \
            --with-system-zlib"
      system 'make'
    end
  end

  def self.install
    Dir.chdir 'obj' do
      system "make DESTDIR=#{CREW_DEST_DIR} install"
      FileUtils.rm Dir.glob("#{CREW_DEST_LIB_PREFIX}/*.ajs")
    end
  end
end
```

**Comment by saltedcoffii** [comment]
Alright @satmandu let's just wait until the new version of `js78` is done.

**Comment by satmandu** [comment]
@saltedcoffii I haven't had a chance to get js78 fixed. Do you want to give it a shot?

**Comment by satmandu** [comment]
Currently trying this:
```
require 'package'

class Js78 < Package
  description 'Spidermonkey is a javaScript interpreter with libraries from Mozilla — Version 78'
  @_ver = '78.15.0'
  version @_ver
  license 'MPL-2.0'
  compatibility 'all'
  source_url "https://archive.mozilla.org/pub/firefox/releases/#{@_ver}esr/source/firefox-#{@_ver}esr.source.tar.xz"
  source_sha256 'a4438d84d95171a6d4fea9c9f02c2edbf0475a9c614d968ebe2eedc25a672151'

  binary_url({
    aarch64: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/js78/78.13.0_armv7l/js78-78.13.0-chromeos-armv7l.tpxz',
     armv7l: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/js78/78.13.0_armv7l/js78-78.13.0-chromeos-armv7l.tpxz',
     x86_64: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/js78/78.13.0_x86_64/js78-78.13.0-chromeos-x86_64.tpxz'
  })
  binary_sha256({
    aarch64: 'c411fce679ebaf36c0f5eb24232499da3902b34561a62555cdb38a0832ca8647',
     armv7l: 'c411fce679ebaf36c0f5eb24232499da3902b34561a62555cdb38a0832ca8647',
     x86_64: '1f95140b994a39b9a2d71f08099e3d4c0f34f5487e2ee24b54e991026c31bc20'
  })

  depends_on 'autoconf213' => :build
  depends_on 'rust' => :build
  depends_on 'llvm' => :build
  depends_on 'nspr'

  @rust_default_host = case ARCH
                       when 'aarch64', 'armv7l'
                         'armv7-unknown-linux-gnueabihf'
                       else
                         "#{ARCH}-unknown-linux-gnu"
                       end

  def self.patch
    # Ubuntu patches
    # http://changelogs.ubuntu.com/changelogs/pool/main/m/mozjs78/mozjs78_78.13.0-1/changelog
    patch_url = 'http://archive.ubuntu.com/ubuntu/pool/main/m/mozjs78/mozjs78_78.15.0-2.debian.tar.xz'
    patch_sha256 = '37c2dcdd20a68d994c00e75577fc2755c4873a23eef78d42659d0042432faf53'

    system "curl -Ls #{patch_url} -o unzippatches.tar.xz"
    unless Digest::SHA256.hexdigest(File.read('./unzippatches.tar.xz')) == patch_sha256
      abort 'Checksum mismatch :/ try again'
    end
    system('tar', '-xf', 'unzippatches.tar.xz')

    system('for i in `cat debian/patches/series`; do  patch -Np1 -i debian/patches/$i; done')

    # Arch Patches
    # patch2_url = 'https://github.com/archlinux/svntogit-packages/raw/packages/js78/trunk/0002-Bug-1667736-Update-packed_simd-to-compile-on-Rust-1..patch'
    # patch2_sha256 = 'ad3dd149651d76c1c3de2dc71d3fb3361181a1add75ff095df7bfba88a4e4ad6'
    # system('curl', '-Lf', patch2_url, '-o', '0002-Bug-1667736-Update-packed_simd-to-compile-on-Rust-1..patch')
    # unless Digest::SHA256.hexdigest(File.read('./0002-Bug-1667736-Update-packed_simd-to-compile-on-Rust-1..patch')) == patch2_sha256
    #  abort 'Checksum mismatch :/ try again'
    # end
    # system('patch -p 1 < ./0002-Bug-1667736-Update-packed_simd-to-compile-on-Rust-1..patch')
    
    # Python 3.10 fixes
    system "sed -i s,collections.Sequence,collections.abc.Sequence,g python/mozbuild/mozbuild/util.py"
    system "sed -i 's/Iterable, OrderedDict/OrderedDict/' python/mozbuild/mozbuild/backend/configenvironment.py"
    system "sed -i '/from collections import OrderedDict/a from collections.abc import Iterable' python/mozbuild/mozbuild/backend/configenvironment.py"
    system "sed -i 's/collections import defaultdict, MutableSequence/collections import defaultdict/' testing/mozbase/manifestparser/manifestparser/filters.py"
    system "sed -i '/from collections import defaultdict/a from collections.abc import MutableSequence' testing/mozbase/manifestparser/manifestparser/filters.py"
    system "sed -i 's/collections import Iterable/collections.abc import Iterable/' python/mozbuild/mozbuild/makeutil.py"
    
    # Rust 1.56+ patch from netbsd at http://cvsweb.netbsd.org/bsdweb.cgi/~checkout~/pkgsrc/www/seamonkey/patches/patch-third__party_rust_packed__simd_src_lib.rs
    @packed_simd_patch = <<~PACKED_SIMD_PATCH_EOF   
      #--- third_party/rust/packed_simd/src/lib.rs.orig	2021-08-08 13:02:00.000000000 +0000
      #+++ third_party/rust/packed_simd/src/lib.rs
      #@@ -199,8 +199,9 @@
       #//!   Numeric casts are not very "precise": sometimes lossy, sometimes value
       #//!   preserving, etc.

      #+#![cfg_attr(const_generics, feature(const_generics))]
      #+#![cfg_attr(not(const_generics), feature(adt_const_params))]
       ##![feature(
      #-    const_generics,
           #repr_simd,
           #rustc_attrs,
           #platform_intrinsics,
      --- third_party/rust/packed_simd/src/lib.rs.orig     2021-09-28 10:05:02.000000000 +0000
      +++ third_party/rust/packed_simd/src/lib.rs   2021-12-11 23:28:12.698937467 +0000
      @@ -200,6 +200,7 @@
       //!   preserving, etc.

       #![cfg_attr(use_const_generics, feature(const_generics))]
      +#![cfg_attr(not(const_generics), feature(adt_const_params))]
       #![cfg_attr(use_const_generics, allow(incomplete_features, clippy::from_over_into))]
       #![feature(
           repr_simd,
    PACKED_SIMD_PATCH_EOF
    #File.write('packed_simd.patch', @packed_simd_patch)
    #system 'patch -Np0 -i packed_simd.patch'
    system "sed -i '/packed_simd/d' Cargo.toml"
    system "sed -i '/libudev-sys/a packed_simd = { version = \"0.3.4\", package = \"packed_simd_2\", git = \"https://github.com/glandium/packed_simd.git\",rev=\"8d3eafcb5c28551d1d0f6bbc13970779cd0cb79b\" }' Cargo.toml"
    # system "sed -i 's,packed_simd =,packed_simd_2 =,g' Cargo.toml"
    # system "sed -i 's,https://github.com/hsivonen/packed_simd,https://github.com/glandium/packed_simd.git,g' Cargo.toml"
    # system "sed -i 's,07d285ba65d9a4e3b9d76eacbf4c6489e125127d,8d3eafcb5c28551d1d0f6bbc13970779cd0cb79b,g' Cargo.toml"
    # system "sed -i '/# Excluded crates/i [dependencies]\\\npacked_simd = { version = \"0.3.6\", package = \"packed_simd_2\" }' Cargo.toml"
    system "cargo update -p packed_simd"
  end

  def self.build
    FileUtils.mkdir_p 'obj'
    Dir.chdir 'obj' do
      system '../js/src/configure --help'
      # error: Cannot set `RUSTC_BOOTSTRAP=1` from build script of `packed_simd v0.3.4 (https://github.com/hsivonen/packed_simd?rev=0917fe780032a6bbb23d71be545f9c1834128d75#0917fe78)`.
      # note: Crates cannot set `RUSTC_BOOTSTRAP` themselves, as doing so would subvert the stability guarantees of Rust for your project.
      # help: If you're sure you want to do this in your project, set the environment variable `RUSTC_BOOTSTRAP=packed_simd` before running cargo instead.
      ENV['RUSTC_BOOTSTRAP'] = 'packed_simd,encoding_rs'
      system "CC=gcc CXX=g++ \
            RUSTFLAGS='-Clto=thin' \
            RUSTUP_HOME='#{CREW_PREFIX}/share/rustup' \
            CARGO_HOME='#{CREW_PREFIX}/share/cargo' \
            LDFLAGS='-lreadline -ltinfo' \
            ../js/src/configure --prefix=#{CREW_PREFIX} \
            --libdir=#{CREW_LIB_PREFIX} \
            --disable-debug \
            --disable-debug-symbols \
            --disable-jemalloc \
            --disable-strip \
            --enable-hardening \
            --enable-optimize \
            --enable-readline \
            --enable-release \
            --enable-rust-simd \
            --enable-shared-js \
            --enable-stdcxx-compat \
            --with-intl-api \
            --without-system-icu \
            --with-system-nspr \
            --with-system-zlib"
      system 'make'
    end
  end

  def self.install
    Dir.chdir 'obj' do
      system "make DESTDIR=#{CREW_DEST_DIR} install"
      FileUtils.rm Dir.glob("#{CREW_DEST_LIB_PREFIX}/*.ajs")
    end
  end
end
```

**Comment by satmandu** [comment]
gave up on js78. Trying to build `js91` thus:
```
require 'package'

class Js91 < Package
  description 'Spidermonkey is a javaScript interpreter with libraries from Mozilla — Version 91'
  @_ver = '91.4.1'
  version @_ver
  license 'MPL-2.0'
  compatibility 'all'
  source_url "https://archive.mozilla.org/pub/firefox/releases/#{@_ver}esr/source/firefox-#{@_ver}esr.source.tar.xz"
  source_sha256 '75e98daf53c5aea19d711a625d5d5e6dfdc8335965d3a19567c62f9d2961fc75'

  depends_on 'autoconf213' => :build
  depends_on 'rust' => :build
  depends_on 'llvm' => :build
  depends_on 'nspr'

  @rust_default_host = case ARCH
                       when 'aarch64', 'armv7l'
                         'armv7-unknown-linux-gnueabihf'
                       else
                         "#{ARCH}-unknown-linux-gnu"
                       end

  def self.patch
    # Python 3.10 fixes
    system 'sed -i s,collections.Sequence,collections.abc.Sequence,g python/mozbuild/mozbuild/util.py'
    system "sed -i 's/Iterable, OrderedDict/OrderedDict/' python/mozbuild/mozbuild/backend/configenvironment.py"
    system "sed -i '/from collections import OrderedDict/a from collections.abc import Iterable' python/mozbuild/mozbuild/backend/configenvironment.py"
    system "sed -i 's/collections import defaultdict, MutableSequence/collections import defaultdict/' testing/mozbase/manifestparser/manifestparser/filters.py"
    system "sed -i '/from collections import defaultdict/a from collections.abc import MutableSequence' testing/mozbase/manifestparser/manifestparser/filters.py"
    system "sed -i 's/collections import Iterable/collections.abc import Iterable/' python/mozbuild/mozbuild/makeutil.py"
  end

  def self.build
    @mozconfig = <<~MOZCONFIG_EOF
      ac_add_options --disable-debug
      ac_add_options --disable-debug-symbols
      ac_add_options --disable-jemalloc
      ac_add_options --disable-strip
      ac_add_options --enable-application=js
      ac_add_options --enable-hardening
      ac_add_options --enable-optimize
      ac_add_options --enable-optimize
      ac_add_options --enable-readline
      ac_add_options --enable-release
      ac_add_options --enable-rust-simd
      ac_add_options --enable-shared-js
      ac_add_options --enable-stdcxx-compat
      ac_add_options --libdir=#{CREW_LIB_PREFIX}
      ac_add_options --prefix=#{CREW_PREFIX}
      ac_add_options --with-intl-api
      ac_add_options --without-system-icu
      ac_add_options --with-system-nspr
      ac_add_options --with-system-zlib
      mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/obj
    MOZCONFIG_EOF
    File.write('.mozconfig', @mozconfig)
    FileUtils.mkdir_p 'obj'
    Dir.chdir 'obj' do
      # error: Cannot set `RUSTC_BOOTSTRAP=1` from build script of `packed_simd v0.3.4 (https://github.com/hsivonen/packed_simd?rev=0917fe780032a6bbb23d71be545f9c1834128d75#0917fe78)`.
      # note: Crates cannot set `RUSTC_BOOTSTRAP` themselves, as doing so would subvert the stability guarantees of Rust for your project.
      # help: If you're sure you want to do this in your project, set the environment variable `RUSTC_BOOTSTRAP=packed_simd` before running cargo instead.
      ENV['RUSTC_BOOTSTRAP'] = 'packed_simd,encoding_rs'
      system "CFLAGS='-fcf-protection=none' \
            CXXFLAGS='-fcf-protection=none' \
            CC=gcc CXX=g++ \
            RUSTFLAGS='-Clto=thin' \
            RUSTUP_HOME='#{CREW_PREFIX}/share/rustup' \
            CARGO_HOME='#{CREW_PREFIX}/share/cargo' \
            LDFLAGS='-lreadline -ltinfo' \
            MACH_USE_SYSTEM_PYTHON=1 \
            MOZCONFIG=../.mozconfig \
            ../mach build"
    end
  end

  def self.install
    Dir.chdir 'obj' do
      system "MOZCONFIG=../.mozconfig ../mach DESTDIR=#{CREW_DEST_DIR} install"
      FileUtils.rm Dir.glob("#{CREW_DEST_LIB_PREFIX}/*.ajs")
    end
  end
end
```

**Comment by satmandu** [comment]
There's a different branch of gjs that builds with mozjs-91, so I'm seeing if that compiles too...

**Comment by satmandu** [comment]
@saltedcoffii please see if these binaries work. They require the js91 and gjs in https://github.com/skycocker/chromebrew/pull/6187

**Comment by satmandu** [comment]
@saltedcoffii This should be good to go since https://github.com/skycocker/chromebrew/pull/6187 got merged. Please check to see that the binaries work? This now has binaries for all architectures.

**Comment by saltedcoffii** [comment]
Binaries work for me!

**Pull request merged**
