### PR TITLE
downloader: Fallback to `curl` if an error is raised by `securerandom`

### LINKED ISSUE #6996: Chromebrew fails to start because of Ruby.
## Description
When running Chromebrew (crew) on ChromeOS, Ruby fails with urandom error, and Chromebrew does not execute.

If you executed a specific command:
```shell
chronos@localhost / $ crew
```

Output:
```
/usr/local/lib/ruby/3.1.0/securerandom.rb:75:in `urandom': failed to get urandom (RuntimeError)
        from /usr/local/lib/ruby/3.1.0/securerandom.rb:75:in `singleton class'
        from /usr/local/lib/ruby/3.1.0/securerandom.rb:42:in `<module:SecureRandom>'
        from /usr/local/lib/ruby/3.1.0/securerandom.rb:41:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/lib/ruby/3.1.0/resolv.rb:8:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/lib/ruby/3.1.0/resolv-replace.rb:4:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/lib/crew/lib/downloader.rb:5:in `<top (required)>'
        from /usr/local/bin/crew:15:in `require_relative'
        from /usr/local/bin/crew:15:in `<main>'
```

## Versions and system information
***
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={5615D466-EF74-FCD0-46EA-D7F60416B3CD}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={5615D466-EF74-FCD0-46EA-D7F60416B3CD}
CHROMEOS_RELEASE_BOARD=peach_pi-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=100
CHROMEOS_RELEASE_BUILDER_PATH=peach_pi-release/R75-12105.100.0
CHROMEOS_RELEASE_BUILD_NUMBER=12105
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=75
CHROMEOS_RELEASE_DESCRIPTION=12105.100.0 (Official Build) stable-channel peach_pi 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=12105.100.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=12105.100.0
***

## Additional information
Chromebrew will output `Chromebrew should not be run as root.` if executing `sudo crew`.
I removed crew manually by using `rm -rf /usr/local/bin`
I don't want to delete my installed apps.
This issue also happened when running `crew upgrade` when Chromebrew still worked.
I also have a crouton chroot with Ubuntu 20.04 LTS with XFCE.

Also, how do I add labels on my issue?

### PR DESCRIPTION
**Pull request by supechicken**
Fix #6996 #6854

### CODE REVIEW

**Comment by satmandu** [comment]
Did you test this?

**Comment by supechicken** [comment]
> Did you test this?

Tested on `x86_64` but I cannot test the rescue logic

**Comment by uberhacker** [comment]
Take a character off and it will force the rescue logic.  `require 'securerando'`

**Comment by satmandu** [comment]
(FYI I have successfully rebuilt containers with this update.)

**Pull request merged**
