### PR TITLE
Update inetutils package

### PR DESCRIPTION
**Pull request by uberhacker**
- Add ncurses dependency
- Disable traceroute

### CODE REVIEW

**Comment by thedamian** [comment]
All look good (especially the ncurses requirements if it's needed) 
but why the disable of traceroute?

**Comment by uberhacker** [comment]
That is a good question.  The traceroute installed from this package is just a stub file that is not executable.  The same is true with whois.  That is why we have separate packages.  I'm guessing the maintainers did this so they would not interfere with the executables installed from the main package manager.  In our case, Chrome OS does not install these executables out-of-the-box.

**Comment by jam7** [comment]
Is it possible to hear more about why you want to disable `traceroute`?  I'm not sure what you meant by `stub file`.  `traceroute` command itself is built by inetutils but +rx flags are disabled on previous `inetutils.rb`.

**Comment by uberhacker** [comment]
The `traceroute` included in this package is an older version and currently doesn't install with execute permissions.  Since we already have a `traceroute` package (more updated version), hence why it was disabled.

**Comment by jam7** [comment]
I see your point.  I'll check more detail later.  Thanks.

**Pull request merged**
