### PR TITLE
Update e2fsprogs and krb5 packages

### LINKED ISSUE #5877: libcom_err.so.3 missing
## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.

## Description
I cannot start codium it just complains like this:

```shell
chronos@localhost ~ $ codium
/usr/local/VSCodium-linux-x64/bin/../codium: error while loading shared libraries: libcom_err.so.3: cannot open shared object file: No such file or directory
```

## Versions and system information
chromebrew: 1.11.1

ChromeOS: 
```shell
chronos@localhost ~ $ cat /etc/lsb-release
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7360525
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={5A3AB642-2A67-470A-8F37-37E737A53CFC}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={5A3AB642-2A67-470A-8F37-37E737A53CFC}
CHROMEOS_RELEASE_BOARD=coral-signed-mp-v19keys
CHROMEOS_RELEASE_BRANCH_NUMBER=41
CHROMEOS_RELEASE_BUILDER_PATH=coral-release/R91-13904.41.0
CHROMEOS_RELEASE_BUILD_NUMBER=13904
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=91
CHROMEOS_RELEASE_DESCRIPTION=13904.41.0 (Official Build) stable-channel coral 
CHROMEOS_RELEASE_KEYSET=mp-v19
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=13904.41.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13904.41.0
```

Model: Asus CBS 514-1H

Architecture: x86_64

### PR DESCRIPTION
**Pull request by uberhacker**
Fixes #5877.  Tested on all architectures.

### CODE REVIEW

**Comment by satmandu** [comment]
The pre-compiled codium binary is dependent upon libcom_err.a being built by krb5 instead of e2fsprogs, but many packages are now built with libcom_err.so.2, which is provided by e2fsprogs.

Note also that major distributions like debian/ubuntu distribute libcomerr from e2fsprogs as well. See https://packages.ubuntu.com/bionic/libcom-err2

Wouldn't a more robust solution be to just compile codium from source so it doesn't have this dependency?

**Comment by satmandu** [comment]
Also, it appears that the simplest fix would be to do this:

```
Dir.chdir "#{CREW_LIB_PREFIX}" do
  unless File.exist?('libcom_err.so.3')
    FileUtils.ln_s 'libcom_err.so.2','libcom_err.so.3' if File.exist?('libcom_err.so.2')

end
```

Creating the symlink appears to keep `codium` from complaining. :)

Maybe that could be added to the codium post install in https://github.com/skycocker/chromebrew/pull/5882 so we don't create unnecessary symlinks?

**Comment by uberhacker** [comment]
The symlink solution doesn't work.  That was the first thing I tried.  Specially, what packages require libcom_err.so.2?

**Comment by uberhacker** [comment]
You are welcome to try to build codium from source.  Not a nimble task.

**Comment by satmandu** [comment]
codium is starting for me with the symlink. What do you see?
image

**Comment by satmandu** [comment]
image

**Comment by satmandu** [comment]
Here's what is using libcom_err.so.2 on my system so far:
```
chronos@localhost /usr/local/lib64 $ for i in * ; do file $i | grep -q "LSB shared object" && readelf -d
 $i  | (grep -q "libcom_err.so.2" && echo $i) ; done
libcom_err.so.2.1
libext2fs.so.2.4
libgssapi_krb5.so.2.2
libgssrpc.so.4.2
libkadm5clnt_mit.so.12.0
libkadm5srv_mit.so.12.0
libkdb5.so.10.0
libkrad.so.0.0
libkrb5.so.3.3
readelf: Error: 'libpython*.so*': No such file
libsasl2.so.3.0.0
libss.so.2.0
libssh.so.4.8.6
libtirpc.so.3.0.0
```

```
chronos@localhost /usr/local/bin $ for i in * ; do file $i | grep -q "dynamically linked" && readelf -d 
$i  | (grep -q "libcom_err.so.2" && echo $i) ; done
chattr
gss-client
kadmin
kdestroy
kinit
klist
kpasswd
ksu
kswitch
ktutil
kvno
lsattr
sclient
sim_client
uuclient
```

**Comment by uberhacker** [comment]
Shouldn't we be symlinking `libcom_err.so.3` to `libcom_err.so.2` and not the other way around?

**Comment by uberhacker** [comment]
How about this idea?  Why not remove `libcom_err.so` from `e2fsprogs` and use from `krb5` instead?  That way we have both `libcom_err.so.2` and `libcom_err.so.3` but provided by separate packages.  I don't understand why they include versions when they compile.  The compiler should look for `libcom_err.so` and not have the specific version embedded in the binary.

**Comment by satmandu** [comment]
That doesn't work because you either need the headers for building with the com_err  from krb5 or from e2fs.

See the files that debian provides for their comerr-dev package:
```
dpkg -L comerr-dev
/.
/usr
/usr/bin
/usr/bin/compile_et
/usr/include
/usr/include/et
/usr/include/et/com_err.h
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libcom_err.a
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/com_err.pc
/usr/share
/usr/share/doc
/usr/share/doc/comerr-dev
/usr/share/doc/comerr-dev/com_err.texi.gz
/usr/share/doc/comerr-dev/copyright
/usr/share/doc/comerr-dev/examples
/usr/share/doc/comerr-dev/examples/ext2_err.et
/usr/share/doc/comerr-dev/examples/ss_err.et
/usr/share/doc/comerr-dev/html-info
/usr/share/doc/comerr-dev/html-info/com_err.html
/usr/share/doc-base
/usr/share/doc-base/comerr-manual
/usr/share/et
/usr/share/et/et_c.awk
/usr/share/et/et_h.awk
/usr/share/info
/usr/share/info/com_err.info.gz
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/compile_et.1.gz
/usr/share/man/man3
/usr/share/man/man3/com_err.3.gz
/usr/include/com_err.h
/usr/lib/x86_64-linux-gnu/libcom_err.so
/usr/share/doc/comerr-dev/changelog.Debian.gz
```
and
```
dpkg -L libcom-err2
/.
/lib
/lib/x86_64-linux-gnu
/lib/x86_64-linux-gnu/libcom_err.so.2.1
/usr
/usr/share
/usr/share/doc
/usr/share/doc/libcom-err2
/usr/share/doc/libcom-err2/changelog.Debian.gz
/usr/share/doc/libcom-err2/copyright
/lib/x86_64-linux-gnu/libcom_err.so.2
```

But I still think both libraries are mostly binary-compatible... 

e2fsutils has `libcom_err.so.2` and krb5 has `libcom_err.so.3` which is why I was suggesting making a symlink from 
 `libcom_err.so.2`  to  `libcom_err.so.3` .

I'll look at a codium compile when I get a chance later...

**Pull request closed without merging**
