### PR TITLE
[fribidi] Has a wrong source address

### PR DESCRIPTION
**Pull request by beliefless-dogmasless**
Hy,

The Source file is not right.

### CODE REVIEW

**Comment by uberhacker** [comment]
Thank you for the update @beliefless-dogmasless!  It looks like you have 2 files.  Please sync with the updated master branch locally and push another commit so you only include the `fribidi` package changes.  Also, you will need to update the version to match the source:
```
- version '0.19.7-1'
+ version '1.0.1'
```
Thanks

**Comment by beliefless-dogmasless** [comment]
I haven't change(look to) the binaries, but compiling(source), I noticed the address was dead, had that one instead.

**Comment by uberhacker** [comment]
If you can remove all the binary references also that would be appreciated.

**Comment by beliefless-dogmasless** [comment]
Done.

**Comment by uberhacker** [comment]
I'm still seeing the extra `pavuk` package.  I think this package is already in the master branch.  Please remove and resubmit.

**Comment by beliefless-dogmasless** [comment]
You're right, excuse me, I have not 'updated the master branch'.[I don't even know 'how to do it'].

**Comment by uberhacker** [comment]
Follow these steps:
```
$ cd /path/to/chromebrew/source
$ git checkout master
$ git pull origin master (or crew update)
$ git push origin master
```
I think that should fix it.

**Comment by beliefless-dogmasless** [comment]
Thanks, I will 'try that', the next time:
I deleted the fork, and fork it 'again'.

**Comment by uberhacker** [comment]
If you create a new branch any time you need to make changes and leave the master branch untainted, it will make this process much more manageable.  Don't be afraid to create branches.  That is the power of git.

**Comment by beliefless-dogmasless** [comment]
"If you create a new branch any time you need to make changes and leave the master branch untainted, it will make this process much more manageable. Don't be afraid to create branches. That is the power of git."
Ok, Thanks For the Tip.

**Pull request closed without merging**
