### PR TITLE
Update pango from 1.40.0 to 1.40.9

### PR DESCRIPTION
**Pull request by uberhacker**

### CODE REVIEW

**Comment by jam7** [comment]
Compile error like below.
```
pangofc-font.c: In function 'pango_fc_shape_engine_get_type':
pangofc-font.c:315:1: warning: 'pango_engine_shape_get_type' is deprecated (declared at ../pango/pango-engine.h:238) [-Wdeprecated-declarations]
 G_DEFINE_TYPE (PangoFcShapeEngine, pango_fc_shape_engine, PANGO_TYPE_ENGINE_SHAPE);
 ^
  CC       pangoft2.lo
pangofc-shape.c:30:19: fatal error: hb-ft.h: No such file or directory
 #include <hb-ft.h>
                   ^
compilation terminated.
make[4]: *** [Makefile:1222: pangofc-shape.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
pangoft2.c: In function 'pango_ft2_font_real_lock_face':
pangoft2.c:436:3: warning: 'pango_ft2_font_get_face' is deprecated (declared at pangoft2.c:177): Use 'pango_fc_font_lock_face' instead [-Wdeprecated-declarations]
   return pango_ft2_font_get_face ((PangoFont *)font);
   ^
pangoft2.c: In function 'pango_ft2_get_unknown_glyph':
pangoft2.c:512:3: warning: 'pango_ft2_font_get_face' is deprecated (declared at pangoft2.c:177): Use 'pango_fc_font_lock_face' instead [-Wdeprecated-declarations]
   FT_Face face = pango_ft2_font_get_face (font);
   ^
In file included from /usr/local/include/freetype2/freetype/fterrors.h:188:0,
                 from pangoft2.c:542:
/usr/local/include/freetype2/freetype/fterrdef.h: In function '_pango_ft2_ft_strerror':
/usr/local/include/freetype2/freetype/fterrdef.h:234:3: warning: initializer-string for array of chars is too long
   FT_ERRORDEF_( DEF_In_Glyf_Bytecode,                        0x9C,
   ^
/usr/local/include/freetype2/freetype/fterrdef.h:234:3: warning: (near initialization for 'ft_errors[75].msg')
make[4]: Leaving directory '/usr/local/tmp/crew/pango-1.40.9.tar.xz.dir/pango-1.40.9/pango'
make[3]: *** [Makefile:1304: all-recursive] Error 1
make[3]: Leaving directory '/usr/local/tmp/crew/pango-1.40.9.tar.xz.dir/pango-1.40.9/pango'
make[2]: *** [Makefile:1046: all] Error 2
make[2]: Leaving directory '/usr/local/tmp/crew/pango-1.40.9.tar.xz.dir/pango-1.40.9/pango'
make[1]: *** [Makefile:565: all-recursive] Error 1
```
I guess pango required freetype enabled harfbuzz since this error is caused by `hb-ft`.  So, I think some dependencies are needed to be added to harfbuzz.

We could compile this before since pango requires freetype before harfbuzz.  However, you remove them and hidden problem appears.  If you want to optimize dependencies path, please test them more aggressively.  Thanks.

**Comment by jam7** [comment]
@uberhacker Can you fix harfbuzz to include `freetype` and maybe `fontconfig`?  Thanks.

**Comment by jam7** [comment]
BTW, to test the correctness of dependency paths, perform something like below.
```
$ crew remove freetype
$ crew remove fontconfig
$ crew isntall harfbuzz
$ crew install pango
```

**Comment by uberhacker** [comment]
Dude, they're dependencies of cairo.  We don't need them there.  I compiled fine without.

**Comment by jam7** [comment]
You don't have errors since you already installed `freetype` and `fontconfig` when you install `harfbuzz`.
Try command lines I explained above.  You will see errors.

**Comment by uberhacker** [comment]
I'm not understanding.  Package harfbuzz needs no dependencies to compile.

**Comment by jam7** [comment]
As I said `pango` requires `freetype` enabled `harfbuzz`.  `harfbuzz` doesn't require `freetype`, but it add features to support `freetype` if it is installed.  You can see below at harfbuzz compile time.
```
config.status: executing libtool commands
configure:

Build configuration:

Unicode callbacks (you want at least one):
        Builtin (UCDN):         true
        Glib:                   true
        ICU:                    true

Font callbacks (the more the better):
        FreeType:               true

Tools used for command-line utilities:
        Cairo:                  false
        Fontconfig:             false

Additional shapers (the more the better):
        Graphite2:              false

Platform shapers (not normally needed):
        CoreText:               false
        Uniscribe:              false
        DirectWrite:            false

Other features:
        Documentation:          no
        GObject bindings:       false
        Introspection:          false
```
Pango requires at least `freetype` for `harfbuzz`.  So, please add `depends_on 'freetype'` in harfbuzz.rb to solve this problem.  Thanks.

**Comment by jam7** [comment]
Well, there is a pending dependency correction for harfbuzz anyway,  So, I've add dependency discussed about there.

**Pull request merged**
