### PR TITLE
Add info and refresh commands

### PR DESCRIPTION
**Pull request by uberhacker**
- The crew info command describes a package
  - The crew refresh command rebuilds the package metadata
  - Update README.md to include the new commands

This PR offers a complete solution to #332.  The package metadata is updated with the `crew update` command as well.

### CODE REVIEW

**Comment by jam7** [comment]
Is doing something like below not enough?  I'm not sure why we need to build json database.
```
when "info"
  search @pkgName, true
  puts @pkg.description
  puts @pkg.homepage
```

**Comment by lyxell** [comment]
I agree with @jam7 here

**Comment by uberhacker** [comment]
Agreed but after thinking about it a bit, why don't we just enhance the `crew search` command?

**Comment by uberhacker** [comment]
Replaced by #720.

**Pull request closed without merging**
