### PR TITLE
Update gptfdisk package

### PR DESCRIPTION
**Pull request by JL2210**
Update to latest version, remove packages that are included in core, remove unneeded hack with newer version.

Use more ruby during install phase and use `FileUtils.glob` for filename-matching.

### CODE REVIEW

**Comment by uberhacker** [comment]
What happened to fixparts?

**Comment by uberhacker** [comment]
If install works like I think it does, you shouldn't need `FileUtils.mkdir_p ...`.

**Comment by JL2210** [comment]
`fixparts` is in there. `install` does *not* work like you think it does.

**Comment by uberhacker** [comment]
Where is the manpage?

**Comment by JL2210** [comment]
It's included in the glob `*.8.gz`.

**Pull request merged**
