### PR TITLE
[New Package] polari

### PR DESCRIPTION
**Pull request by saltedcoffii**
Builds, segfaults for unknown reason when running. I don't know JavaScript and can't debug this error.

### CODE REVIEW

**Comment by uberhacker** [comment]
Any reason this PR was labeled Draft?  It looks good to me.

**Comment by saltedcoffii** [comment]
Because it segfaults when trying to run it and I don't know why.

**Comment by satmandu** [comment]
I couldn't get polari working several weeks ago, which is why I abandoned the underlying dep PRs I was working on. Please don't merge this until you have a working build on your end. You might have better luck with running this via flatpak...

**Comment by uberhacker** [comment]
We really shouldn't create a PR until it is ready.

**Comment by satmandu** [comment]
Also, can we stop adding sommelier as a required build dep?  If it works fine using wayland, (as many gtk apps should) then there is no reason to insist that one also install sommelier.

Just setting ```GDK_BACKEND=wayland``` is often enough.

**Comment by uberhacker** [comment]
@satmandu: I don't think the average user is aware of these environment variables.  Does it make sense to create a wrapper script to set the correct values like we've done in other packages?

**Comment by satmandu** [comment]
Maybe? depends upon i686?

**Comment by satmandu** [comment]
@uberhacker Also, we are talking about the average user who has learned to jump through the hoops to put their Chromebook into dev mode? 

(I'd suggest making wayland the default for apps which can handle it.)

**Comment by uberhacker** [comment]
Well, they can figure out from README.md.  I doubt many users will understand how to set environment variables unless it's scripted or documented somewhere.

**Comment by saltedcoffii** [comment]
No :(

**Pull request closed without merging**
