### PR TITLE
Add qt package

### PR DESCRIPTION
**Pull request by uberhacker**
Qt is a comprehensive cross-platform framework and toolkit that helps you create and build native applications and user interfaces for all the screens of your end user.  See https://info.qt.io/download-qt-for-application-development.

Guys, I think this is the first gui app installable via crew and the coolest thing is it lets you create cross-platform gui apps. :)

### CODE REVIEW

**Comment by flyingP0tat0** [comment]
There is no way this would work in the current situation, as we have no X11.
Have you tried to install it?

**Comment by uberhacker** [comment]
@flyingP0tat0: Dude, it totally works.  I have tested it and all the static libraries necessary to get it working are embedded into the package.  For what it's worth, this emulates a RedHat environment and only works on x86_64 and i686 systems.

**Comment by flyingP0tat0** [comment]
Well, I tested it on my x86_64 HP Chromebook 13 G1 and it did not work because of missing `libx`.

**Comment by flyingP0tat0** [comment]
Are you sure you have not compiled any libraries for that before?

**Comment by uberhacker** [comment]
OK, so it installs on CloudReady since the libX11 library files exist.  I just tried it on my HP Chromebook and the libX11 libraries don't exist.  So you are right about that.  However, now that I know it works with CloudReady, I'm thinking X11 is very possible.

**Comment by flyingP0tat0** [comment]
Yes it may be. But I guess the tricky thing is, that Chrome OS uses some sort of Wayland-Port, if i remember correctly. So after installing libX11, it wont find any display, X-org-server is needed. Which probably also won't work given the Wayland thing. So we will probably need Weston. I am trying that out right now, but that will take some time.

**Comment by thedamian** [comment]
This would be revolutionary but I agree with flyingP0tat0 in that I don't know if this will work, and we might just get Xlib working first. since THAT will make EVERYTHING work on chrome!

**Comment by flyingP0tat0** [comment]
@thedamian The issue is way bigger than just getting libX11, there is a lot to be done. I will open a new issue to keep track of getting all of this to work on Chrome OS.

**Comment by thedamian** [comment]
do do we close this PR without merging?

**Comment by uberhacker** [comment]
Yes, but there is a glimmer of hope for gui apps since I could install this in CloudReady.

**Comment by JL2210** [comment]
Hey, @uberhacker, open this again and merge it.

**Comment by sajjaadf** [comment]
Please

**Comment by uberhacker** [comment]
@sajjaadf: Been there, done that.  Please try to install the latest qt and submit an issue if you have any trouble.

**Comment by sajjaadf** [comment]
Later Today
is it Crew Install qt?

**Comment by uberhacker** [comment]
Yes, `crew install qt`.  The command to execute after installed is `qtcreator`.

**Comment by sajjaadf** [comment]
Thanks, Btw See my The issue with creating Gui App store and Link apps to
the icon. I'm working on it.

>

**Comment by sajjaadf** [comment]
And Android Studio?

**Comment by uberhacker** [comment]
I did.  Thank you for adding the issues.  Nice to see interest in improving Chromebrew.

**Pull request closed without merging**
