### PR TITLE
Add NGINX Webserver (Version 1.11.6)

### PR DESCRIPTION
**Pull request by bfayers**
This doesn't have any binaries in it in but the build from source works.

### CODE REVIEW

**Comment by thedamian** [comment]
@bfayers LOVE this merge.

BUT...I think the last two lines need their quotes escaped or else it won't work 

I'm talking about these two lines. Correct me if i'm wrong but I think you'll have issues with these lines.
+    system "sed -i '$ a alias startnginx="sudo nginx"' ~/.bashrc"
+    system "sed -i '$ a alias stopnginx="sudo pkill nginx"' ~/.bashrc"

**Comment by thedamian** [comment]
Even after manually escaping the double quotes with the \ key I still get the following error:

./configure: error: the HTTP rewrite module requires the PCRE library.
You can either disable the module by using --without-http_rewrite_module
option, or install the PCRE library into the system, or build the PCRE library
statically from the source with nginx by using --with-pcre=<path> option.

So it's not ready to merge.

this was on a 32bit x86 machine (the original chromebook CR-48) and with crew installed just minutes before installing this package.

**Comment by bfayers** [comment]
I guess I had PCRE from something else.

**Comment by bfayers** [comment]
@thedamian Could you try nginx again? I've added PCRE as a package and as a dependency in nginx

**Comment by thedamian** [comment]
Yes. It works perfectly.

BUT... ;-)

You have to escape the quotes (put the \ key in front of the " in the middle of the "sed..." lines.

Also, why use your version of pcre?

Here: I didn't know you were going to fix it this fast so I many my own pcre.rb package but haven't merged it.

Please look at it and let me know what you think:
https://github.com/thedamian/chromebrew/blob/new-packages/packages/pcre.rb

I'm using the suggestions from this post:
http://www.linuxfromscratch.org/blfs/view/7.6/general/pcre.html

I'll merge it regardless of the pcre fix, but you do have to fix the quotes by escaping them.

**Comment by bfayers** [comment]
Oh, its not my own PCRE. I just downloaded it from their sourceforge and re-uploaded it since i've not got wget to work nice with sourceforge.

**Comment by thedamian** [comment]
Excellent work! Nginx is awesome and it works flawlessly on my chromebook now.

MERGED!

**Comment by bfayers** [comment]
Thank you!

**Pull request merged**
