### PR TITLE
[WIP] Support custom user CREW_PREFIX

### PR DESCRIPTION
**Pull request by dragon788**
The `${VAR:-/some/path}` will use the path on the right side if the variable on the left side is null or empty (ie if the user didn't set it).

I tested this on my machine as I wanted to set the prefix to `/usr/local/.chromebrew` to prevent it from getting wiped by `dev_install --uninstall` per #536 and #429 though it may require some work on #877 to remove symlinks only if they were created by Chromebrew (if it would attempt to symlink a binary into `/usr/local/bin` only if it didn't already exist).

### CODE REVIEW

**Comment by dragon788** [comment]
Some caveats, the install script gets crew in the requested spot, but there are many places paths to config files or other bits appears to be hardcoded or incorrectly assembled. I'll be working through these as I get time, as I'd really like to have Chromebrew and Linuxbrew working nicely side by side in addition to the native ChromeOS `dev_install` packages.

**Comment by jam7** [comment]
It might be possible to solve the path problem by opposite way.  First, we change to use `/usr/local/.chromebrew` as the default place to install and compile everything.  Then, we can install everything into `/usr/local` if users want to stick `/usr/local`.  In this way, we can make a symbolic link from `/usr/local/.chromebrew` to `/usr/local` to avoid those path problem.

This requires drastic changes, though...

**Comment by jam7** [comment]
LGTM.  Is it OK to merge this one?  I appreciate hear something from other collaborators and owner.  Thanks.

**Comment by uberhacker** [comment]
@dragon788: Thank you for submitting this PR.  I agree with this concept in theory but in order for it to actually work, we need to update every package to configure via `--prefix=#{CREW_PREFIX}`.  Right now, that is not the case.  I would like to eventually modify the crew command to do this automagically along with `--libdir=#{CREW_LIB_PREFIX}` if these configure options are not provided in the `def self.build` section of the package.  I just haven't figured out how to do it elegantly yet.  Obviously, we would like the ability to override the auto-configured options and we also need to consider cases where "non-standard" configure scripts are used.  A prime example is PR #1121 which is a total PITA to compile.

**Comment by dragon788** [comment]
Does crew support reporting its current prefix with `crew prefix` similar to how brew's is available via `brew prefix`? That could make testing some of these things easier.

**Comment by spoelstraethan** [comment]
@uberhacker I just ran into it today where CREW_PREFIX wasn't being honored by the Ruby and other Bootstrap packages in spite of this PR being merged, have you made any progress on updating crew to handle fixing this for all packages to use the path specified by the user in .bashrc or exported in the command line? It may also be good to capture the value to an env file (which I think the installer does).

**Pull request merged**
