### PR TITLE
Add store.js

### PR DESCRIPTION
**Pull request by sajjaadf**
For crew store

### CODE REVIEW

**Comment by uberhacker** [comment]
What are we supposed to do with this and how do you plan on keeping this updated with the 900+ packages we have currently?

**Comment by JL2210** [comment]
1. LibreOffice isn't even a package.
2. This is not the right way to abstract packages.
3. Along with those reasons, it's not functional.

**Comment by sajjaadf** [comment]
true, but can we put it here for now?

**Comment by sajjaadf** [comment]
as a replacement for berri-co.me/js.js for the thing?

**Comment by sajjaadf** [comment]
> What are we supposed to do with this and how do you plan on keeping this updated with the 900+ packages we have currently?

Its only for GUI and important packages

**Comment by sajjaadf** [comment]
is that a good idea?

**Comment by sajjaadf** [comment]
I thought libreoffice was a package

**Comment by sajjaadf** [comment]
it installs and runs on my crew

**Comment by JL2210** [comment]
@sajjaadf Let me give you the right way to do this.
Create a shell script that downloads all the Chromebrew packages.
Abstract the `homepage` variable from aforementioned packages.
Create images from `homepage` URLs.
Upload aforementioned images and create JavaScript file with commands in it.

**Comment by sajjaadf** [comment]
weird

**Comment by sajjaadf** [comment]
okay fine

**Comment by JL2210** [comment]
Can I have `libreoffice.rb` from `/usr/local/lib/crew/packages`?

**Comment by sajjaadf** [comment]
sure

**Comment by sajjaadf** [comment]
I think I found it on uberhackers GitHub fork of chrome brew

**Comment by sajjaadf** [comment]
```ruby
require 'package'

class Libreoffice < Package
  description 'LibreOffice is a powerful office suite - its clean interface and feature-rich tools help you unleash your creativity and enhance your productivity.'
  homepage 'https://www.libreoffice.org/'
  version '6.1.3.2'
  source_url 'https://download.documentfoundation.org/libreoffice/src/6.1.3/libreoffice-6.1.3.2.tar.xz'
  source_sha256 'd46f38f6c48c6d2338fb97c6d0fae9b43802f9849b50817b3bcf9910f1708f44'

  binary_url ({
  })
  binary_sha256 ({
  })

  depends_on 'ant'
  depends_on 'boost'
  depends_on 'cppunit'
  depends_on 'cups'
  depends_on 'curl'
  depends_on 'dbus_glib'
  depends_on 'glm'
  depends_on 'gst_plugins_base'
  depends_on 'gtk2'
  depends_on 'gtk3'
  depends_on 'hunspell'
  depends_on 'lcms'
  depends_on 'libatomic_ops'
  depends_on 'openldap'
  depends_on 'poppler'
  depends_on 'sane_backends'
  depends_on 'unixodbc'
  depends_on 'sommelier'

  def self.build
    system './autogen.sh',
           "--prefix=#{CREW_PREFIX}",
           "--libdir=#{CREW_LIB_PREFIX}",
           '--without-junit',
           #'--with-system-altlinuxhyph',
           #'--with-system-apache-commons'
           '--with-system-apr',
           #'--with-system-bluez',
           '--with-system-boost',
           '--with-system-bzip2',
           '--with-system-cairo',
           #'--with-system-clucene',
           #'--with-system-coinmp',
           #'--with-system-cppunit',
           '--with-system-curl',
           '--with-system-epoxy',
           '--with-system-expat',
           #'--with-system-glm',
           #'--with-system-gpgmepp',
           #'--with-system-graphite',
           #'--with-system-harfbuzz',
           #'--with-system-headers',
           '--with-system-hunspell',
           '--with-system-icu',
           '--with-system-icu-for-build=yes',
           '--with-system-jpeg',
           '--with-system-lcms2',
           #'--with-system-libabw',
           '--with-system-libatomic_ops',
           #'--with-system-libcdr',
           #'--with-system-libcmis',
           #'--with-system-libebook',
           #'--with-system-libeot',
           #'--with-system-libepubgen',
           #'--with-system-libetonyek',
           #'--with-system-libexttextcat',
           #'--with-system-libfreehand',
           #'--with-system-liblangtag'
           #'--with-system-libmspub',
           #'--with-system-libmwaw',
           #'--with-system-libnumbertext',
           #'--with-system-libodfgen',
           #'--with-system-libpagemaker',
           '--with-system-libpng',
           #'--with-system-libqxp',
           #'--with-system-librevenge',
           #'--with-system-libs',
           #'--with-system-libstaroffice',
           #'--with-system-libvisio',
           #'--with-system-libwpd',
           #'--with-system-libwpg',
           #'--with-system-libwps',
           '--with-system-libxml',
           #'--with-system-libzmf',
           #'--with-system-lpsolve',
           #'--with-system-mdds',
           #'--with-system-mythes',
           #'--with-system-neon',
           #'--with-system-nss',
           '--with-system-odbc',
           '--with-system-openldap',
           '--with-system-openssl',
           #'--with-system-orcus',
           '--with-system-poppler',
           #'--with-system-redland',
           '--with-system-sane',
           '--with-system-serf',
           '--with-system-ucpp',
           #'--with-system-xmlsec',
           '--with-system-zlib',
           '--with-x'
    system 'make'
  end

  def self.install
    system "make", "DESTDIR=#{CREW_DEST_DIR}", "install"
  end
end

**Comment by sajjaadf** [comment]
https://github.com/uberhacker/chromebrew/blob/add-libreoffice-package/packages/libreoffice.rb

**Comment by uberhacker** [comment]
Dude, this is a wip and definitely not complete.  If you got it to install, I would be amazed.

**Pull request closed without merging**
