### PR TITLE
Most is not an essential package.

### PR DESCRIPTION
**Pull request by saltedcoffii**

### CODE REVIEW

**Comment by uberhacker** [comment]
I would argue less is more but more or less most is best. :)

**Comment by satmandu** [comment]
As a person who was taught to use vi in the '80s as a child, I'm going to laugh if this leads to a PR stating “Emacs is not an essential package.”

**Comment by uberhacker** [comment]
Emacs is not even useful when it's installed. :laughing:

**Comment by saltedcoffii** [comment]
https://en.wikipedia.org/wiki/Editor_war

**Comment by saltedcoffii** [comment]
I guess the reason I wanted to get rid of most is because its not necessary to build packages like buildessential, and has more dependencies and is bigger than less. Most is kinda "extra" for a core package. It would be like installing exa by default under the argument that it's better than ls (it is).

**Comment by uberhacker** [comment]
Probably not worth the effort but if you really insist on removing it, you will need to also do the following:
```
Alternatively, you could use most.  Why settle for less, right?
echo "crew install most"
echo \"export PAGER='most'\" >> ~/.bashrc && . ~/.bashrc
```
And then remove `most` and `slang` from `tools/core_packages.txt`.

My guess is as soon as we do this, we'll need to start including `depends_on 'slang'` in some packages. :-D

**Comment by saltedcoffii** [comment]
We could add slang to the core package list, or just make the change, get bugs and update package dependencies.

**Comment by uberhacker** [comment]
Like I said, probably not worth the effort. :wink:

**Comment by saltedcoffii** [comment]
Alright

**Comment by uberhacker** [comment]
Closing with this:
_"Emacs is a great operating system; it just lacks a good editor"_

**Pull request closed without merging**
