### PR TITLE
Update ffcall from 1.10-1 to 2.0

### LINKED ISSUE #1315: [ffcall] Fails to build on ARMv8
I just picked up the Samsung Chromebook Plus tonight and noticed that `ffcall` fails to install properly.

```
chronos@localhost /usr/local/lib/crew/packages $ crew install ffcall
ffcall: Foreign function call is a collection of four libraries which can be used to build foreign function call interfaces in embedded interpreters.
http://www.haible.de/bruno/packages-ffcall-README.html
version 1.10-1
No precompiled binary available for your platform, downloading source...
######################################################################## 100.0%
Archive downloaded
Unpacking archive, this may take awhile...
gcc (GCC) 4.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
checking whether make sets $(MAKE)... yes
configure: creating ./config.status
config.status: creating Makefile
configure: configuring in avcall
configure: running /bin/bash './configure' --prefix=/usr/local  '--prefix=/usr/local' 'CFLAGS= -fPIC' --cache-file=/dev/null --srcdir=.
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ANSI C... none needed
checking how to run the C preprocessor... gcc -E
checking for egrep... grep -E
checking whether gcc needs -traditional... no
checking whether using GNU C... yes
checking for underscore in external names... no
checking for ranlib... ranlib
checking whether make sets $(MAKE)... yes
checking for a BSD compatible install... /usr/bin/install -c
checking how to copy files... cp -p
checking how to make hard links... ln
checking build system type... ./../autoconf/config.guess: line 1380: /tmp/cgLpHx5i/dummy: Permission denied
./../autoconf/config.guess: unable to guess system type

This script, last modified 2004-03-03, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

    ftp://ftp.gnu.org/pub/gnu/config/

If the version you run (./../autoconf/config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2004-03-03

uname -m = aarch64
uname -r = 4.4.70-11386-g8271523ecf43
uname -s = Linux
uname -v = #1 SMP PREEMPT Sun Oct 15 17:38:26 PDT 2017

/usr/bin/uname -p = ARMv8 Processor rev 4 (v8l)
/bin/uname -X     = 

hostinfo               = 
/bin/universe          = 
/usr/bin/arch -k       = 
/bin/arch              = 
/usr/bin/oslevel       = 
/usr/convex/getsysinfo = 

UNAME_MACHINE = aarch64
UNAME_RELEASE = 4.4.70-11386-g8271523ecf43
UNAME_SYSTEM  = Linux
UNAME_VERSION = #1 SMP PREEMPT Sun Oct 15 17:38:26 PDT 2017
configure: error: cannot guess build type; you must specify one
configure: error: /bin/bash './configure' failed for avcall
ffcall failed to install: `./configure --prefix=/usr/local CFLAGS=" -fPIC"` exited with 1
```

### PR DESCRIPTION
**Pull request by cstrouse**
This is a maintenance and bugfix release.

Closes #1315. Tested as working on Samsung Chromebook Plus (ARMv8)

### CODE REVIEW

**Comment by uberhacker** [comment]
The update looks good.  Did you test the clisp package which has this as a dependency?

**Comment by cstrouse** [comment]
What's the right way to specify the build type to configure? It complains that it's not able to guess the build type.

**Comment by uberhacker** [comment]
That's a good question.  Based on the error message, it appears to be a permission issue:
```
checking build system type... ./../autoconf/config.guess: line 1380: /tmp/cgLpHx5i/dummy: Permission denied
./../autoconf/config.guess: unable to guess system type
```
You might try a different directory that is writable/executable, if possible.

**Comment by cstrouse** [comment]
I've tried specifying `TMPDIR=#{CREW_PREFIX}/tmp` and while it fixes the complaint about permissions it still fails stating that it's unable to guess the build type.

```

config.guess timestamp = 2010-04-03

uname -m = aarch64
uname -r = 4.4.70-11386-g8271523ecf43
uname -s = Linux
uname -v = #1 SMP PREEMPT Sun Oct 15 17:38:26 PDT 2017

/usr/bin/uname -p = ARMv8 Processor rev 4 (v8l)
/bin/uname -X     = 

hostinfo               = 
/bin/universe          = 
/usr/bin/arch -k       = 
/bin/arch              = 
/usr/bin/oslevel       = 
/usr/convex/getsysinfo = 

UNAME_MACHINE = aarch64
UNAME_RELEASE = 4.4.70-11386-g8271523ecf43
UNAME_SYSTEM  = Linux
UNAME_VERSION = #1 SMP PREEMPT Sun Oct 15 17:38:26 PDT 2017
configure: error: cannot guess build type; you must specify one
clisp failed to install: `./configure TMPDIR=/usr/local/tmp --prefix=/usr/local --libdir=/usr/local/lib --disable-static --with-pic --with-ffcall --with-readline` exited with 1
```

**Comment by uberhacker** [comment]
Can you try something like `--arch=#{ARCH}`?

**Comment by cstrouse** [comment]
@uberhacker There's a set of patches in the Arch Linux ARM PKGBUILD but I haven't been able to get it working on ARMv8 and don't know ARM assembler to work on it. Closing this issue as it's been resolved.

**Comment by cstrouse** [comment]
Oops, hasn't been merged yet. The Clisp issues will have to be tackled separately.

**Comment by uberhacker** [comment]
If I merge this now then clisp will be broken, right?  Should I wait until you get the clisp issue resolved and a new PR is in the queue so I can merge both at the same time?

**Comment by cstrouse** [comment]
Clisp works fine with the updated ffcall on the other platforms. Clisp has never worked properly to my knowledge on ARMv8.

**Comment by uberhacker** [comment]
OK, I'll go ahead and merge this then.

**Pull request merged**
