### PR TITLE
Adding more documentation to tests

### PR DESCRIPTION
**Pull request by yancouto**
As @cstrouse suggested in #1220. Is this fine? Anything still needs better explaining?

### CODE REVIEW

**Comment by yancouto** [comment]
@uberhacker Any suggestions?

**Comment by uberhacker** [comment]
@yancouto: I agree with @cstrouse.  I definitely think there is value in having local tests for new packages and updates.  You might take a look at #997 and #1307.  Also, the suggestions in #1220.
Thanks

**Comment by cstrouse** [comment]
Thanks @yancouto that's a great improvement. Thanks for your help in both developing the first testing and for improving the documentation along with @uberhacker.

**Comment by uberhacker** [comment]
@yancouto: Yes, this is a huge improvement and we really appreciate your efforts.  Is it possible to explain where the tests should be run (like which directory)?  Also, I'm thinking it might make sense if you swapped the order of the `Preparing new tests` and `How to run tests` sections.  If you can provide a complete example test suite, that would be even better.
Thanks

**Comment by yancouto** [comment]
> Is it possible to explain where the tests should be run (like which directory)?

Done.

> Also, I'm thinking it might make sense if you swapped the order of the Preparing new tests and How to run tests sections.

I don't think so, if this README is for newcomers, they should worry more about running the tests than creating new. But if you wish, I can change it.

> If you can provide a complete example test suite, that would be even better.

What do you mean exactly? There is an example test in the README.
Or do you mean creating more real tests?

**Comment by uberhacker** [comment]
I just thought it might be helpful to provide a complete set of tests as an example to explain how a practical test suite should be generated.  Also, I was thinking if you rearranged the order chronologically, it might be a bit easier to understand.  Kind of more like a step-by-step guide.

**Comment by yancouto** [comment]
Ok, switched the sections.

I'll not create more tests for now though, I have no good ideas, that one was because of the problem we had.

**Comment by uberhacker** [comment]
OK, I'll merge this for now.  We can add more content later as we get more familiar with writing tests.

**Pull request merged**
