### PR TITLE
[New Package] telegram (official static version)

### PR DESCRIPTION
**Pull request by saltedcoffii**
this is the telegram binaries provided on the https://desktop.telegram.org website.

### CODE REVIEW

**Comment by saltedcoffii** [comment]
this should hold over the x86 users until we're able to get #4902 sorted out

**Comment by uberhacker** [comment]
This is a duplicate of #4902.

**Comment by uberhacker** [comment]
Sommelier doesn't work on i686 either (at least on my system).

**Comment by saltedcoffii** [comment]
> Sommelier doesn't work on i686 either (at least on my system).
oh good to know. I'll see if i can get telegram from the source figured out

**Pull request closed without merging**
