### PR TITLE
Add crew search -i and -a options

### PR DESCRIPTION
**Pull request by uberhacker**
-i = List all installed packages
  -a = List all available packages

### CODE REVIEW

**Comment by lyxell** [comment]
I don't really see the use case for this
```bash
crew search | grep '(i)'
crew search | grep -v '(i)'
```

**Comment by uberhacker** [comment]
Which would you rather type?  `crew search -i` or `crew search | grep '(i)'`.  Always naysayers. :)

**Comment by lyxell** [comment]
Personally I think there's a greater value in keeping the code base small and manageable, but that's just my opinion.

**Comment by uberhacker** [comment]
Not every user is going to know how to pipe to grep but point taken.

**Pull request closed without merging**
