### PR TITLE
JDK to u131 -  Node to 6.11.0 - Node_Current to 8.1.0 - Inetutils Package (for telnet, BBS TIME!) added

### PR DESCRIPTION
**Pull request by thedamian**
Just updating Java, and Node to all the current versions.

NOTE: In Java I was able to find the x86 and 64x official links from oracle (instead of dropbox) but I couldn't find the ones for arm, so actually arm is back at 8u22 until I can find the links.

### CODE REVIEW

**Comment by thedamian** [comment]
I will change node and node_current to pull from the binaries. 

I think I was trying to make it easy for me by having everyone compile from code but BOY does my Google Pixel get hot when THAT'S happening, and it probably takes a good half an hour on my i5 1.8Ghz CPU so I can't even think how long it takes on an arm or x86 machine.

**Comment by lyxell** [comment]
The -m64 flag looks problematic to me

**Comment by thedamian** [comment]
@lyxell yeah. that's why I didn't automatically merge it. I needed it for my Pixel (with intel i5) so I'm guessing it's a 64bit version.

So, do I do one of these so that I can run -m64 on 64bit lines?

case ARCH
    when "x86_64" || "aarch64"

**Comment by lyxell** [comment]
I don't think it is possible to use -m64 on aarch64. According to GCC documentation "The 64-bit environment sets int to 32 bits and long and pointer to 64 bits and generates code for AMD's x86-64 architecture". Also, aarch64 uses armv7-gcc, which is 32 bit.

**Comment by thedamian** [comment]
when I tried to upgrade node on my box using crew the -m64 was the only thing that allow it and didn't give me the errors with some libraries. 

My box is the intel i5 (google pixel) so maybe only x64 intel needs it?

I'd have to try it without it to see what the error was and report it.

**Pull request merged**
