### PR TITLE
Update Xorg server

### PR DESCRIPTION
**Pull request by JL2210**
Removes the Xwayland package as xorg_server contains
the Xwayland binary. Enables more features and X servers.
Uses xorg_server instead of xwayland in `libsdl`, `libsdl2`, `libwmf`, `sommelier`, and `xinit`.

### CODE REVIEW

**Comment by uberhacker** [comment]
Does this fix the dependency loop issue?  That should be the highest priority fix right now.

**Comment by JL2210** [comment]
Yes. I can confirm that.

**Comment by uberhacker** [comment]
Great!  Can you compile mesa without errors?  That would be the next priority fix.  Currently, I cannot compile that on x86_64. :confused:

**Comment by JL2210** [comment]
The problem is demonstrated in this diagram:
```
xwayland -> xinit -> xterm -> sommelier -> xwayland
```

**Comment by JL2210** [comment]
I pushed a PR to fix Mesa. It's a matter of undoing a patch that fixes LLVM 6. For some reason, that patch broke LLVM 7.

**Comment by JL2210** [comment]
See #3060.

**Pull request merged**
