### PR TITLE
Update tk from 8.6.8 to 8.6.9

### PR DESCRIPTION
**Pull request by uberhacker**
Tested on all architectures.

### CODE REVIEW

**Comment by cstrouse** [comment]
I just installed this on ARM and while it installs it doesn't work properly.
```
chronos@localhost /usr/local/lib/crew/packages $ tclsh8.6 
% package require Tk
couldn't load file "/usr/local/lib/libtk8.6.so": libXft.so.2: cannot open shared object file: No such file or directory
```

```
chronos@localhost /usr/local/lib/crew/packages $ wish
wish: error while loading shared libraries: libXft.so.2: cannot open shared object file: No such file or directory
```

**Comment by uberhacker** [comment]
Good catch.  I have updated the dependency to xorg_lib instead of libx11.  This should pick up libxft and libxscrnsaver.

**Comment by cstrouse** [comment]
I haven't done anything with Chromebrew since GUI stuff was added. How do you get $DISPLAY set so that Tk things will launch?

**Comment by uberhacker** [comment]
@cstrouse: You need to install and run sommelier via `crew install sommelier`.  Make sure you carefully follow the postinstall instructions so sommelier starts after a reboot.  This should allow you to test `tkdiff`.

**Comment by cstrouse** [comment]
If this requires sommelier why is it not in the dependency list?

**Comment by uberhacker** [comment]
It doesn't need sommelier to build.  You would need sommelier if you wanted to run an app like tkdiff, however.

**Pull request merged**
