### PR TITLE
Add a CI bot for updating readme packages

### PR DESCRIPTION
**Pull request by supechicken**
Let’s hire a bot for doing that automatically:)

Tested on my fork

### CODE REVIEW

**Comment by uberhacker** [comment]
This is interesting but I'm not following what it actually does during the update.

**Comment by supechicken** [comment]
At every commit pushes, it will check modified/added files and add them to `Recently updated/Latest Package` table in readme

**Comment by uberhacker** [comment]
How do you tell the difference between recently updated and latest packages?

**Comment by supechicken** [comment]
> How do you tell the difference between recently updated and latest packages?

By running `git diff-tree`, we can get the path of modified/added file and status  (added/modified) to know whatever they new package or updated.

Also in `README.md`, I added some comments for helping the script find the part of new/recently update packages

**Comment by saltedcoffii** [comment]
I'd also love to see the bot check for package updates, automatically update them and make a PR. That wud save us so much time :P

**Pull request closed without merging**
