### PR TITLE
Upgrade protobuf to v3.5.1

### PR DESCRIPTION
**Pull request by lovedheart**

### CODE REVIEW

**Comment by uberhacker** [comment]
Thank you for the update @lovedheart!  Does this resolve #1926?

**Comment by lovedheart** [comment]
I have not tested x86

**Comment by uberhacker** [comment]
Does it compile without the `system './autogen.sh'` line?  We also don't need the dependencies since they're now part of Chromebrew "core".

**Comment by lovedheart** [comment]
It needs "./autogen.sh"

**Pull request merged**
