### PR TITLE
Added ranger filemanager

### PR DESCRIPTION
**Pull request by revebla**

### CODE REVIEW

**Comment by uberhacker** [comment]
Hey @revebla: Thank you for this package.  It looks interesting and I'm a die-hard vim user.  We are now including description and homepage metadata in all packages.  Please add the following lines below `class Ranger < Package` and commit:
```
description 'A VIM-inspired filemanager for the console.'
homepage 'http://ranger.nongnu.org/'
```
Thanks

**Comment by uberhacker** [comment]
I also noticed on the homepage of the project it mentions a few dependencies.  You might want to include the following lines above the `def self.build` line, powerwash and then attempt a test to see if the package installs cleanly:
```
depends_on 'ncurses'
depends_on 'less'
depends_on 'python'
```
From the project homepage:
```
Dependencies

Python (tested with version 2.7, 3.1, 3.2, 3.3, 3.4) with support for ncurses and (optionally) wide-unicode.
A pager (less by default)
```
Thanks

**Comment by revebla** [comment]
Thanks for being patient :) Looks like it all works for me post powerwash!

**Comment by thedamian** [comment]
Love the testing. Love the comments. and how can I argue with "works after powerwash" 

Can't get better than that. it's now merged

**Comment by uberhacker** [comment]
Good job on this page @revebla.  Really liking ranger!

**Pull request merged**
