### PR TITLE
gdb -> 11.1

### PR DESCRIPTION
**Pull request by satmandu**
Works properly:
- [x] x86_64
- [x] armv7l
- [x] i686 (@uberhacker please check?)

### CODE REVIEW

**Comment by uberhacker** [comment]
On i686, I get:
```
$ gdb
Segmentation fault (core dumped)
$ gdbserver
Segmentation fault (core dumped)
```
I'm guessing all of these failed rebuilds are due to one or more of the recent dependency updates missing something.

**Comment by satmandu** [comment]
> On i686, I get:
> 
> ```
> $ gdb
> Segmentation fault (core dumped)
> $ gdbserver
> Segmentation fault (core dumped)
> ```
> 
> I'm guessing all of these failed rebuilds are due to one or more of the recent dependency updates missing something.

But what is missing though? bisecting that is a pain...

**Comment by uberhacker** [comment]
The i686 build is failing as shown below:
```
  CXX    gdbsupport/common-utils-ipa.o
  CXX    gdbsupport/errors-ipa.o
  CXX    gdbsupport/format-ipa.o
  CXX    gdbsupport/print-utils-ipa.o
  CXX    gdbsupport/rsp-low-ipa.o
  CXX    gdbsupport/safe-strerror-ipa.o
  CXX    gdbsupport/tdesc-ipa.o
  CXX    linux-amd64-ipa.o
  CXX    linux-x86-tdesc-ipa.o
  CXX    regcache-ipa.o
  CXX    remote-utils-ipa.o
  CXX    tdesc-ipa.o
  CXX    tracepoint-ipa.o
../../gdbserver/linux-amd64-ipa.cc: In function ‘const target_desc* get_ipa_tdesc(int)’:
../../gdbserver/linux-amd64-ipa.cc:201:14: error: ‘amd64_linux_read_description’ was not declared in this scope; did you mean ‘i386_linux_read_description’?
  201 |       return amd64_linux_read_description (X86_XSTATE_SSE_MASK, true);
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |              i386_linux_read_description
../../gdbserver/linux-amd64-ipa.cc: In function ‘void initialize_low_tracepoint()’:
../../gdbserver/linux-amd64-ipa.cc:282:3: error: ‘amd64_linux_read_description’ was not declared in this scope; did you mean ‘i386_linux_read_description’?
  282 |   amd64_linux_read_description (X86_XSTATE_SSE_MASK, true);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   i386_linux_read_description
make[2]: *** [Makefile:528: linux-amd64-ipa.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/usr/local/tmp/crew/gdb.20210801232213.dir/gdb-10.2/build/gdbserver'
make[1]: *** [Makefile:9365: all-gdbserver] Error 2
make[1]: *** Waiting for unfinished jobs....
libtooldir=`/bin/bash ./libtool --config | /usr/local/bin/sed -n -e 's/^objdir=//p'`; \
if [ -f $libtooldir/libbfd.a ]; then \
  cp $libtooldir/libbfd.a libbfd.tmp; \
  ranlib libbfd.tmp; \
  /bin/bash ../../bfd/../move-if-change libbfd.tmp libbfd.a; \
else true; fi
touch stamp-lib
make[4]: Leaving directory '/usr/local/tmp/crew/gdb.20210801232213.dir/gdb-10.2/build/bfd'
make[3]: Leaving directory '/usr/local/tmp/crew/gdb.20210801232213.dir/gdb-10.2/build/bfd'
make[2]: Leaving directory '/usr/local/tmp/crew/gdb.20210801232213.dir/gdb-10.2/build/bfd'
make[1]: Leaving directory '/usr/local/tmp/crew/gdb.20210801232213.dir/gdb-10.2/build'
make: *** [Makefile:854: all] Error 2
gdb failed to build: `make V=0 -j8` exited with 2
```

**Comment by satmandu** [comment]
> The i686 build is failing as shown below:
> ```
>   CXX    gdbsupport/common-utils-ipa.o
>   CXX    gdbsupport/errors-ipa.o
>   CXX    gdbsupport/format-ipa.o
>   CXX    gdbsupport/print-utils-ipa.o
>   CXX    gdbsupport/rsp-low-ipa.o
>   CXX    gdbsupport/safe-strerror-ipa.o
>   CXX    gdbsupport/tdesc-ipa.o
>   CXX    linux-amd64-ipa.o
>   CXX    linux-x86-tdesc-ipa.o
>   CXX    regcache-ipa.o
>   CXX    remote-utils-ipa.o
>   CXX    tdesc-ipa.o
>   CXX    tracepoint-ipa.o
> ../../gdbserver/linux-amd64-ipa.cc: In function ‘const target_desc* get_ipa_tdesc(int)’:
> ../../gdbserver/linux-amd64-ipa.cc:201:14: error: ‘amd64_linux_read_description’ was not declared in this scope; did you mean ‘i386_linux_read_description’?
>   201 |       return amd64_linux_read_description (X86_XSTATE_SSE_MASK, true);
>       |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
>       |              i386_linux_read_description
> ../../gdbserver/linux-amd64-ipa.cc: In function ‘void initialize_low_tracepoint()’:
> ../../gdbserver/linux-amd64-ipa.cc:282:3: error: ‘amd64_linux_read_description’ was not declared in this scope; did you mean ‘i386_linux_read_description’?
>   282 |   amd64_linux_read_description (X86_XSTATE_SSE_MASK, true);
>       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
>       |   i386_linux_read_description
> make[2]: *** [Makefile:528: linux-amd64-ipa.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[2]: Leaving directory '/usr/local/tmp/crew/gdb.20210801232213.dir/gdb-10.2/build/gdbserver'
> make[1]: *** [Makefile:9365: all-gdbserver] Error 2
> make[1]: *** Waiting for unfinished jobs....
> libtooldir=`/bin/bash ./libtool --config | /usr/local/bin/sed -n -e 's/^objdir=//p'`; \
> if [ -f $libtooldir/libbfd.a ]; then \
>   cp $libtooldir/libbfd.a libbfd.tmp; \
>   ranlib libbfd.tmp; \
>   /bin/bash ../../bfd/../move-if-change libbfd.tmp libbfd.a; \
> else true; fi
> touch stamp-lib
> make[4]: Leaving directory '/usr/local/tmp/crew/gdb.20210801232213.dir/gdb-10.2/build/bfd'
> make[3]: Leaving directory '/usr/local/tmp/crew/gdb.20210801232213.dir/gdb-10.2/build/bfd'
> make[2]: Leaving directory '/usr/local/tmp/crew/gdb.20210801232213.dir/gdb-10.2/build/bfd'
> make[1]: Leaving directory '/usr/local/tmp/crew/gdb.20210801232213.dir/gdb-10.2/build'
> make: *** [Makefile:854: all] Error 2
> gdb failed to build: `make V=0 -j8` exited with 2
> ```



`uname -a` ?

**Comment by satmandu** [comment]
Looks like GCC is actually thinking you are on `x86_64`?

**Comment by uberhacker** [comment]
```
$ arch
i686
$ uname -a
Linux i686 4.15.0-151-generic #157-Ubuntu SMP Fri Jul 9 23:07:57 UTC 2021 x86_64 GNU/Linux
```
Docker is only simulating the hardware via qemu, apparently.

**Comment by uberhacker** [comment]
Still unable to build with the same error even after new builds of boost and source_highlight.

**Comment by satmandu** [comment]
I wonder if this is a qemu artifact?

**Comment by satmandu** [comment]
Opening this for review again...

**Comment by uberhacker** [comment]
Was anything changed since the last time it was tested?

**Comment by satmandu** [comment]
> Was anything changed since the last time it was tested?

Rebuilt to remove libcurl dependency.

**Comment by satmandu** [comment]
@uberhacker Could we get a i686 build when you get a chance?

**Comment by uberhacker** [comment]
Confirmed working on i686.

**Pull request merged**
