### PR TITLE
Supporting #1585, again.  update 42 packages.

### PR DESCRIPTION
**Pull request by duckunix**
Supports #1585 

## Description

- bind - update to 9.11.2
- cmatrix - update to 1.2
- coreutils - update to 8.29
- erlang - update to 20.2
- fish - update to 2.7.1
- gifsicle - update to 1.90
- gnupg - update to 2.2.4
- gnutls - update to 3.6.1
- gpgme - update to 1.10.0
- gzsize - update to 1.2
- help2man - update to 1.47.5
- imagemagick - update to 7.0.7-18
- jsonc - update to 0.13-20171207
- lcms - update to 2.2.9
- libcheck - update to 0.12.0
- libsdl2 - update to 2.0.7
- libunbound - update to 1.6.7
- ibwayland - update to 1.14.0
- bwebp - update to 0.6.1
- lvm2 - update to 2.02.177
- manpages - update to 4.14
- mdp - update to 1.0.11
- memcached - update to 1.5.4
- mutt - update to 1.9.2
- ninja - update to 1.8.2
- nodebrew - update to 0.9.8
- nvm - update to 0.33.8
- od1n - update to 2.5
- pagemon - update to 0.01.11
- pciutils - update to 3.5.6
- pinentry - update to 1.1.0
- protobuf - update to 3.5.1
- sfk - update to 1.8.9
- strace - update to 4.20
- stressng - update to 0.09.07
- stunnel - update to 5.44
- tinycc - update to 0.9.27
- tmux - update to 2.6
- wget - update to 1.19.2
- xe - update to 0.11
- xxhash - update to 0.6.4
- zsh - update to 5.4.2

## Notes
Again, builds on x86_64, but not tested past that.

### CODE REVIEW

**Comment by uberhacker** [comment]
@duckunix: This is an epic PR and I really appreciate the effort.  I was hoping to fix packages that need abstracted install directories such as ones that only have a simple `./configure` line without any options or `./configure --prefix=/usr/local`.  I know this is a lot of work, but can you please fix these with something like `./configure --prefix=#{CREW_PREFIX} --libdir=#{CREW_LIB_PREFIX}`?  You don't need the `--libdir` option if the package doesn't install any library files.  The `--libdir` option is especially important on `x86_64` architecture since the default `LD_LIBRARY_PATH` environment variable is set to `/usr/local/lib64` and if libraries are installed in `/usr/local/lib` instead, it can create issues when the system attempts to locate these files.  Hopefully, that makes sense.
Thanks

**Comment by uberhacker** [comment]
It also looks like you have some conflicting files.  Please pull from the latest master and these conflicts can be resolved.

**Comment by duckunix** [comment]
I will review the files, and pull the ones that need the update work and submit those separately.

**Comment by duckunix** [comment]
And, I think it would be easier if I just junk this PR, and create new ones.  So, closing.

**Comment by uberhacker** [comment]
It might make sense if you bundled each update in groups of 10 or less to make it more manageable.

**Comment by duckunix** [comment]
Okay...I can do that.  Where can I find a list of all the macros used in the build files?  Starting to look into some of them, and I see things like **/usr/local/etc**

**Comment by uberhacker** [comment]
If you examine the `crew build` command which is defined in `/usr/local/bin/crew`, you can drill down from there.

**Pull request closed without merging**
