### PR TITLE
Add kerberos (krb5)

### PR DESCRIPTION
**Pull request by flyingP0tat0**

### CODE REVIEW

**Comment by jam7** [comment]
Don't you mind to fix this strange indent?  Thanks.

**Comment by flyingP0tat0** [comment]
@jam7 Done.

**Comment by jam7** [comment]
Sry for saying this, but still TAB there.

**Comment by uberhacker** [comment]
Tabs are evil.  Four space indentation instead of two is less evil, but still undesirable.  Trailing whitespace is annoying.  :)

**Comment by flyingP0tat0** [comment]
Now it should be right.

**Pull request merged**
