### PR TITLE
Fix depends_on issue as pointed out by @lyxell

### PR DESCRIPTION
**Pull request by uberhacker**
Don't require php unless it isn't currently installed.  Reference #739.

### CODE REVIEW

**Comment by thedamian** [comment]
Wait WHAT?

1) Why would composer NOT require PHP (it makes no sense to be without PHP)
2) you're removed the "PHP5 or PHP7" and think requiring EITHER is important.

**Comment by lyxell** [comment]
@thedamian It works, but it is not super pretty.
The code could be read as:
```
if (php (any version) is not installed)
  require php7
```

**Comment by uberhacker** [comment]
Hey @thedamian: What @lyxell mentioned is correct.  I suppose we could also do something like `depends_on 'php7' not File.exists? '/usr/local/bin/php'`.

**Comment by lyxell** [comment]
The ruby idiom would probably be to use `unless`.

**Comment by uberhacker** [comment]
You mean like this? `depends_on 'php7' unless File.exists? '/usr/local/bin/php'`

**Comment by thedamian** [comment]
sorry guys. so "depends_on 'php7' is the same as check for ANY VERSION?

I definitely am NOT a ruby expert but this doesn't seem like the 7 would be ignored.

Just confirm. 

when you say "php7" the system is smart enough to ignore the 7 part. yes?

**Comment by uberhacker** [comment]
Hey @thedamian: What this line will do, basically, is _*ONLY*_ install php7 if there is no version of php installed currently.  Otherwise, if you have either the php5 or php7 packages installed, this line is skipped.

**Comment by thedamian** [comment]
@uberhacker  sorry. I guess it was the revert thinking of python that confused me.

I see: 1) It checks if ANY php is installed by checking for the directory. if it's NOT there, then it tries installs PHP7

NOW I get it. It's merged.

**Pull request merged**
