### PR TITLE
Remove CRLFs and replace with LFs in all packages

### PR DESCRIPTION
**Pull request by uberhacker**
This PR fixes the result of building packages in Windows which should never be used as a development environment for Chromebrew...ever. :)

### CODE REVIEW

**Comment by JL2210** [comment]
Wow. Maybe they used Wine or ReactOS? I can't imagine a Chromebrew user
doing this.

**Comment by skiman6010** [comment]
Haha this is funny. 

Thanks @uberhacker!

**Comment by JL2210** [comment]
Did you run `dos2unix`? That command is simply amazing.

**Comment by uberhacker** [comment]
Macs are poo-poo'd also since they use on CRs instead of LFs.  No reason to not develop on a Chromebook if creating Chromebrew packages.  How else would you test?

**Comment by sajjaadf** [comment]
What is a CR and a LF?

**Comment by uberhacker** [comment]
CR = carriage return (MacOS style)
LF = line feed (Unix/Linux style)
CRLF = carriage return + line feed (Windows/DOS style)

@JL2210: Yes, I did use dos2unix.

**Comment by sajjaadf** [comment]
Oh

**Comment by JL2210** [comment]
@sajjaadf Read above explanation by @uberhacker.

**Pull request merged**
