### PR TITLE
Remove need for sudo

### LINKED ISSUE #172: sudo/root needed at all?
I've installed (manually) uninstalled chromebrew 30 or so times in the last couple days...  I've been wondering why chromebrew needs to use sudo for some commands.

Maybe it's just my lenovo n21 chromebook, but all of /usr/local starts out writable by chronos user.

If the binary bootstrap packages didn't install as root-owned, you could theoretically have everything in /usr/local owned by and writable by chronos.

Experimentally, after initial install, I  "cd /usr/local &&  chown -R chronos:chronos *"

I then removed the instances of sudo in /usr/local/bin/crew

and pretty much everything seems to work as normal/expected.  

on MacOSX the homebrew code uses sudo on initial install to set the right ownership/permissions of stuff in /usr/local/ to you, but from then on out you never run sudo again.  Would this be a good operating model for chromebrew?

### PR DESCRIPTION
**Pull request by minektur**
For install, assumes that /usr/local is already writable by chronos and is rwx
chronos:chronos

fixes #172

(and a bunch of auto-changed whitespace...)

There are migration concerns - anyone who installed previously would need to manually make chronos own all the stuff that got installed.

roughly:

chown -R chronos:chronos /usr/local/*

### CODE REVIEW

**Comment by thedamian** [comment]
LOOOVE this idea. But don't you have to do a...
sudo chown -R chronos:chronos /usr/local
...first in the script for this to work?

P.S. removing the white spaces is a pain to look at in the change. You should have had only 3 lines changes, and instead you have 40 lines for us to look at.

This pull looks like it was done after last week's episode of "silicon valley"

**Comment by jazzonmym1nd** [comment]
you can check out the changes without the whitespace diff here:
https://github.com/skycocker/chromebrew/pull/176/files?w=1 
generally though, i try to not introduce whitespace changes in pull requests because it does add noise, and the authors might see removing the whitespace as being too picky or not important.

**Comment by minektur** [comment]
to be honest, I didn't really see the whitespace changes till I was submitting the pull request... sigh - I agree that I should have be more careful with my python-friendly vim settings :).  I can re-work it up and submit it if you'd like.

In the current state of this patch, it would only work for new installs.  I could probably throw something in the 'update' command to check file permissions and ask for a sudo one more time to fix them, as an upgrade path.  I can't think of a better way.... After I made this pull request I submitted several others where I was careful with the whitespace  :)

**Comment by thedamian** [comment]
@jazzonmym1nd AWESOME. Love that option, that will help complainers like me a lot. Thank you.
@minektur  This pull is very helpful and I think @jazzonmym1nd fixed any concern I could ever have.

In my pull ( https://github.com/skycocker/chromebrew/pull/173 ) I put the line:
sudo chown -R chronos:chronos /usr/local
... into the install.sh which I think will help with this pull.

I think this is an excellent pull and I don't see anything wrong with it, but haven't had the time to test it.

**Comment by minektur** [comment]
my big worry is that someone with an existing installation will get messed up by this when they do a 'crew upgrade' or 'crew update' - where the tree (and executables) get updated.  The scripts will be expecting perms to be right, but how does it get fixed in the upgrade case?

**Comment by lyxell** [comment]
This is great. Nice work.

**Comment by thedamian** [comment]
I tried to merge your work with my install.sh and it didn't work.

I had to powerwash my chromebook and merged your install.sh with my changes (not too many, just some ln's and permissions at the end)

And right away it failed with the making of the directries in /usr/local 

so I'd look at your code. I didn't have a chance to try to figure out what I needed to change, but what I can tell you is AS IT IS NOW, it doesn't work.

**Comment by lyxell** [comment]
@thedamian That's totally expected. There's no line containing `chown $USER:$USER -R /usr/local`, so you'll have to do it yourself.

**Comment by thedamian** [comment]
@lyxell  That makes sense, but if we are suppose to "chown" can't we put it in the script?

**Comment by lyxell** [comment]
@thedamian Yes, that would be ideal.

**Comment by thedamian** [comment]
@lyxell so should be merge this or should this have been rewritten better.

this is changing something WAY too important for me not to wipe my chromebook and try it before I merge it.

has anyone done that with success?

tell me about it.

**Comment by lyxell** [comment]
@thedamian Well, there's currently a conflict with install.sh.
But it should be possible to get this to work when that conflict is resolved.
I've tried this myself a couple of months back and as long as /usr/local is owned by chronos and writeable there should not be any need for sudo.

**Comment by lyxell** [comment]
This pull request introduces some whitespace changes, it's easier to read with the whitespace flag enabled https://github.com/skycocker/chromebrew/pull/176/commits/2cbbbe18ab698d5fa94527c6186f14b509a37176?w=1

**Comment by thedamian** [comment]
@lyxell you're one of the biggest contributors. 
I just installed crew on my CR-48 from scratch this morning. Should I try this PR first on it before approving it? The confict is a simpel one to fix.

But can we trust that it works (I guess one way to know)

I'm always scared of messing around with the install.sh or crew.sh because packages can easily be fixed but install.sh and crew.sh can cause serious harm that require a fresh re-install.

**Comment by minektur** [comment]
I'll work up and submit a new version of this PR.

**Comment by thedamian** [comment]
You rock @minektur thanks!

**Comment by thedamian** [comment]
had to re-install my chromebook pixel (64bit) and this install failed.

here's the errors I got 

Last-modified header missing -- time-stamps turned off.
2016-12-14 22:11:30 (53.2 MB/s) - 'linuxheaders.rb' saved [721/721]

bash: line 106: crew: command not found
bash: line 109: crew: command not found
ln: failed to create symbolic link ‘/usr/local/bin/cc’: No such file or directory
bash: line 115: cd: /usr/local/lib/crew/: No such file or directory
bash: line 116: git: command not found
bash: line 117: git: command not found
bash: line 118: git: command not found
bash: line 119: .git/info/sparse-checkout: No such file or directory
bash: line 120: .git/info/sparse-checkout: No such file or directory
bash: line 121: .git/info/sparse-checkout: No such file or directory
bash: line 122: git: command not found
bash: line 123: git: command not found
Chromebrew installed successfully and package lists updated.
chronos@localhost ~ $ 
chronos@localhost ~ $ 
chronos@localhost ~ $ git
bash: git: command not found
chronos@localhost ~ $ crew
bash: crew: command not found
chronos@localhost ~ $

**Comment by lyxell** [comment]
@thedamian Yeah, that's pretty expected, this pr assumes that /usr/local is owned by chronos. If it's not, everything will fail.

**Comment by thedamian** [comment]
@lyxell so then this has to be fixed before we can merge it? right? 

I was trying to see if it's ready and it seems it's not.

**Comment by lyxell** [comment]
@thedamian Correct.

**Comment by minektur** [comment]
Someone else in a separate issue mentioned that changing the permissions on /usr/local recursively may be a security issue for a multi-user-dev-mode-chromebook.  If that is the case... does the current behavior help that issue, and would changing it make things worse?

If /usr/local is already writable by chronos, then anyone who logs in and gets a shell would be able to change ownership/contents of those binaries right?  

It seems like to be secure, we need root to own all of /usr/local and everything in it.  Then an administrator could use the root password to install/update/remove packages, and users that didn't know the root password could just use whatever is in /usr/local/ but not modify it.

Which operating mode should we target?  

Option 1: the-only-or-all-users already have root password => /usr/local and contents owned by chronos for convenience

Option 2: only admin has root password => /usr/local/ and contents owned by root for security


I could see that maybe a teacher in an educational setting would be in Option 2 land.  for me, I'm in option-1 land.

Either way, I think that we're not doing either one right now - we have the worst of both worlds, not very secure, and somewhat inconvenient.


What do you all think?

**Comment by lyxell** [comment]
Like I've said before, even the guest user has sudo-rights so if he/she wants to change anything in /usr/local, the current ownership doesn't matter.

**Comment by uberhacker** [comment]
@minektur: I don't mind removing whitespace "noise" in any commit.  Keep them coming!  It doesn't distract me at all when I'm reviewing a PR.  Any modern IDE will remove trailing whitespace on save and it is a good best practice to not include it in files.  Regarding security, I think if you create a group and assign users to that group, you can still do the remove thing without sudo.  If we do something like `sudo chown -R root:admin /usr/local` and `sudo chmod -R g+w /usr/local` and add the chronos user (or any other user for that matter) to the admin group, problem solved.  With that said, I think this would be a welcome change and if you pull the latest changes from master and resolve merge conflicts with the crew command and install.sh, we should be good to go.

**Comment by lyxell** [comment]
@uberhacker `/etc/passwd` is mounted read-only, we can't really add/change groups or users.

**Comment by uberhacker** [comment]
Then I don't understand the concern about security.  Help me out here.

**Comment by lyxell** [comment]
@uberhacker Basically, we can choose between making everything owned by the root user or everything owned by the chronos (default) user.

**Comment by uberhacker** [comment]
@lyxell: Then let's just chown chronos on /usr/local and be done with this.  This silliness about multiuser logins is crazy talk.

**Comment by minektur** [comment]
Ed - I feel the same way... I'm just trying to be careful.

**Comment by uberhacker** [comment]
The chronos user basically has full admin privies currently via sudo.  The only thing that user cannot do is change the read-only mounts so I guess I'm confused why this would be a big deal.

**Comment by lyxell** [comment]
@uberhacker Well, it doesn't hurt to discuss it.

**Comment by uberhacker** [comment]
For over 6 months? LoL

**Comment by lyxell** [comment]
@uberhacker I don't think anyone was 'waiting' for the discussion, this pr just hasn't been prioritized.

**Comment by dragon788** [comment]
This is great, it reminds me a lot of 'brew-do' that does a similar thing for OSX. Basically they create a 'brew' user that is the one that owns the /usr/local/ and handles all the package installs, and allows sharing the binaries between users without one particular user owning them.

One thing that could be handy for this is rather than doing the `chown -R /usr/local` is adding a new sudoers.d file for 'chronos' that allows passwordless sudo for crew commands. This doesn't alter the security of the system by changing file permissions, and it increases the convenience for users, while not allowing the guest user to perform any system changes without sudo (and preventing sudo without a password for guest and changing the guest password would solve that security hole).

This new file will definitely need vetted with `sudo visudo -c -f /path/to/file` before moving it into the sudoers.d directory so that it doesn't break sudo on the system entirely. I can take a crack at the file and syntax if I can find some time as I've done a few of them for various development systems in the past.

**Comment by lyxell** [comment]
@dragon788 I'm pretty sure sudoers.d is mounted read-only, it is also likely that the directory could be overwritten on a system update.

**Comment by uberhacker** [comment]
Resolved by #645?  Can we close this?

**Pull request closed without merging**
