### PR TITLE
Add dmidecode package

### PR DESCRIPTION
**Pull request by uberhacker**
Dmidecode reports information about your system's hardware as described in your system BIOS according to the SMBIOS/DMI standard (see a sample output). This information typically includes system manufacturer, model name, serial number, BIOS version, asset tag as well as a lot of other details of varying level of interest and reliability depending on the manufacturer. This will often include usage status for the CPU sockets, expansion slots (e.g. AGP, PCI, ISA) and memory module slots, and the list of I/O ports (e.g. serial, parallel, USB).  See http://www.nongnu.org/dmidecode/.

### CODE REVIEW

**Comment by jam7** [comment]
When I try this PR, it shows:
```
$ sudo /usr/local/sbin/dmidecode
# dmidecode 3.1
Scanning /dev/mem for entry point.
/dev/mem: Operation not permitted
/dev/mem: Bad file descriptor
```
I think there is a problem on installation into armv7l.

**Comment by uberhacker** [comment]
@jam7: If you sudo a command and get errors, that is a permission issue instead of an installation issue.  Does the `/dev/mem` node exist on armv7l?

**Comment by jam7** [comment]
It exists.
```
$ ls -l /dev/mem 
crw-r-----. 1 root kmem 1, 1 Jul 29 14:45 /dev/mem
```

**Comment by jam7** [comment]
Ok.  I researched it little.  The answer is dmidecode doesn't work on arm.  I guess physical memory mapping to access BIOS information is different.

@uberhacker is it possible to add a comment like `# dmidecode doesn't support ARM atm` in dmidecode.rb?  Thanks.

**Comment by uberhacker** [comment]
@jam7: Should we make a stronger effort to get it working on arm?  Are there some switch options that we could use to make it work?

**Comment by uberhacker** [comment]
@jam7: I pushed up a new commit I think you will like.

**Comment by jam7** [comment]
it's way too much.
```
$ crew install healthcheck
healthcheck: Linux system health check.
https://github.com/SimplyLinuxFAQ/health-check-script
version 1cace5
The following packages also need to be installed: 
dmidecode 
Do you agree? [Y/n] y
Proceeding...
dmidecode: Dmidecode reports information about your system's hardware as described in your system BIOS according to the SMBIOS/DMI standard (see a sample output).
http://www.nongnu.org/dmidecode/
version 3.1
No precompiled binary available for your platform, downloading source...
######################################################################## 100.0%
Archive downloaded
Unpacking archive, this may take a while...
gcc (GCC) 4.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
armv7l architecture not supported.
```

**Comment by uberhacker** [comment]
@jam7: I changed the abort line to puts instead.  This should allow healthcheck to be installed.  Keep in mind, you will see errors when running healthcheck on arm.

**Pull request merged**
