### PR TITLE
ruby => 3.1.0

### PR DESCRIPTION
**Pull request by saltedcoffii**
works on all architectures. builds needed.

### CODE REVIEW

**Comment by uberhacker** [comment]
@satmandu knows these builds better than anybody.

**Comment by uberhacker** [comment]
That could also mean `cycle_test` needs to be updated.

**Comment by satmandu** [comment]
If that's the only issue, happy to reopen that earlier PR...

**Comment by saltedcoffii** [comment]
closing as duplicate

**Pull request closed without merging**
