### PR TITLE
Rebuild alsa_plugins with libav support

### PR DESCRIPTION
**Pull request by uberhacker**
Depends on #2805.
Tested on:
- [x] aarch64
- [x] armv7l
- [x] i686
- [x] x86_64

### CODE REVIEW

**Comment by JL2210** [comment]
Are you sure this enables libav? Are there any `--enable-libav` or `--enable-libffmpeg` options?

**Comment by uberhacker** [comment]
It auto detects the libraries if they are available.

**Comment by uberhacker** [comment]
I think I created a dependency loop with the pulseaudio and alsa_plugins packages.

**Comment by JL2210** [comment]
Great. lol. Maybe make an `alsa_plugins_sub` package like you do with Freetype?

**Comment by JL2210** [comment]
@uberhacker, did this work? What about the dependency loop?

**Pull request merged**
