### PR TITLE
Add dependencies to subversion package

### PR DESCRIPTION
**Pull request by uberhacker**

### CODE REVIEW

**Comment by jam7** [comment]
Please increment version number of subversion too like #978.

**Comment by uberhacker** [comment]
Done.

**Comment by jam7** [comment]
Thanks.  I tried subversion but having following errors on x86_64.  It looks like subversion confuse between sqlite and libsqlite...
```
$ crew install subversion
...
checking for sqlite3.h... yes
checking sqlite library version (via header)... unsupported SQLite version
checking sqlite library version (via pkg-config)... none or unsupported 3.7.7.1 
no

An appropriate version of sqlite could not be found.  We recommmend
3.7.15.1, but require at least 3.7.12.
Please either install a newer sqlite on this system

or

get the sqlite 3.7.15.1 amalgamation from:
    http://www.sqlite.org/sqlite-amalgamation-3071501.zip
unpack the archive using unzip and rename the resulting
directory to:
/usr/local/tmp/crew/subversion-1.9.6.tar.bz2.dir/subversion-1.9.6/sqlite-amalgamation

configure: error: Subversion requires SQLite
subversion failed to install: `./configure` exited with 1
$ crew search sqlite extra
(i) libsqlite3: SQLite is a software library that implements a self-contained, serverless, zero-configuration, transactional SQL database engine.
https://github.com/LuaDist/libsqlite3
version 3.7.7.1
(i) sqlite: SQLite is a self-contained, high-reliability, embedded, full-featured, public-domain, SQL database engine.
http://www.sqlite.org/
version 3.18.0-1
```
Once I removed libsqlite3, it works great.
```
$ crew remove libsqlite3
Libsqlite3 removed!
$ crew remove sqlite
...
$ crew install sqlite
....
$ crew install subversion
...
Installing...
Subversion installed!
```
I'll check details later.

**Comment by jam7** [comment]
I'm not sure, but it looks like libsqlite3 is personally forked old sqlite3.  So, I prefer to remove libsqlite3, but it is used by one package, aria2.

I check history of commit log and find you @uberhacker added libsqlite3 and aria2.  :(

Can you check them and correct them please?  Thanks.

**Comment by jam7** [comment]
Thanks

**Pull request merged**
