### PR TITLE
Update to 1.0.2l / V 1.0.2k FTP Link offline

### PR DESCRIPTION
**Pull request by beli3ver**

### CODE REVIEW

**Comment by Ulexus** [comment]
For me, this breaks the system `wget`'s TLS support, which, among other things, causes `crew` to fail to download.

**Comment by jam7** [comment]
It works fine on armv7l and x86_64.  Passed all test cases also.

**Comment by beli3ver** [comment]
> For me, this breaks the system wget's TLS support, which, among other things, causes crew to fail to download https-sourced files.

On my system, I have no problems.

**Comment by Ulexus** [comment]
I'm on arm64/armv8.  Perhaps that is the distinction, though I don't see why architecture should make a difference.

**Comment by flyingP0tat0** [comment]
I just saw this one after creating #709...
Why does this one have conflicts, while mine doesn't?

**Comment by flyingP0tat0** [comment]
@Ulexus Could you try it with 1.0.2k manually? Although I don't see any reason why this should cause a broken wget.

**Comment by Ulexus** [comment]
@flyingP0tat0 same problem with 1.0.2k manually.  I'm sure it's not related to the version bump per se, but rather that the openssl version itself is not compatible with whatever the system wget is compiled against.

Thus, there is no reason to hold this PR on my issue.  It looks like that deserves a separate issue.

**Comment by flyingP0tat0** [comment]
@Ulexus Yes, open a new issue with your problem.

**Comment by flyingP0tat0** [comment]
I think we should fix this problem with the openssl URL as fast as possible, as many packages depend on openssl. I already resloved the conflict in #709.

**Comment by flyingP0tat0** [comment]
@jam7's package with binaries for arm (#665) seems to be working, so we might just drop this one and he needs to push his package (with new version and via `http`).

**Comment by jam7** [comment]
@flyingP0tat0 I make #714.  Please let me know there is any problems.

**Pull request closed without merging**
