### PR TITLE
Add uninstall.sh script

### PR DESCRIPTION
**Pull request by uberhacker**
This might not be the most elegant way but it works and it makes testing a lot easier than the extreme measure of the dreaded powerwash.

### CODE REVIEW

**Comment by thedamian** [comment]
shouldn't the last line be to remove the directory where crew lives as well:
/usr/local/lib/crew/

and the link in /usr/local/bin/crew

**Comment by uberhacker** [comment]
@thedamian:  Good point.  It might be a good idea to recursively remove other directories under `/usr/local` as well since many packages build up residue with extra files post-installation.

**Comment by uberhacker** [comment]
@thedamian: I added your suggestions and a few more cleanup lines.  Sad that it takes hours to install all your favorite packages and less than a minute to uninstall everything. :)

**Comment by lyxell** [comment]
We can't be sure we're actually cleaning up everything, and the rm -rf's introduced might as well remove stuff that didn't originate from crew. I'm skeptic.

**Comment by thedamian** [comment]
@lyxell 

It removes the packages installed by crew how it is.
The next thing would simply to remove /usr/local/lib/crew itself and it's link in /usr/localbin

I'm not suggesting we clean the whole /usr/local/lib directory.

If we're truly uninstalling crew, this script is wonderful, but In my opinion 90% there.

**Comment by uberhacker** [comment]
@lyxell: I understand your concern.  However, some packages will add additional files after installation and we need a way to clean up this "residue" as part of the uninstall process.  In the case of node, python or ruby, for example, additional "packages" (ie. gems, npm and pip packages) can be installed post-installation.  We need an elegant way to remove these in addition to the main package.  I'm open to suggestions.

**Comment by lyxell** [comment]
I think it is better to continue the discussion on https://github.com/skycocker/chromebrew/issues/536
This would make removal straightforward, we need to find a way to work around the problems with a custom installation path though.

**Comment by jam7** [comment]
My suggestion is to stop removing files directly like `rm -rf /usr/local/...` way.  Nobody think something like that is safe.

You can simply performs only `crew remove ...`.  If you know several files are remain, you can shows warning messages.  Or you can remove them with prompt.  Or you can make different program named `uninstall-force` to remove additional files.

**Comment by uberhacker** [comment]
@jam7: I'm of the opinion that residue should be removed without prompting.  `rm -rf /usr/local/...` is perfectly safe if you know the implications.  I have tested this on CloudReady which includes symlinks everywhere (that can certainly have unintended consequences).  Let me know specifically which `rm -rf` lines in this script are not safe and I'll remove them.

**Comment by andzaytsev** [comment]
This script works great for me and is very useful. Is there anything that stops it from being merged?
Should there be a warning and a prompt before everything is removed?

**Comment by uberhacker** [comment]
Why are we so concerned about recursively wiping out entire directories when we can simply Powerwash and restore everything?  The whole point of this script is so you don't need to go through the extreme measure of a Powerwash.

**Comment by uberhacker** [comment]
Closing in favor of dev_install --uninstall

**Pull request closed without merging**
