### PR TITLE
Add Broadway (Open Gui apps in window tab) 

### PR DESCRIPTION
**Pull request by sajjaadf**
Just Look at the RB file, Im excited, this = apps with icons!

### CODE REVIEW

**Comment by uberhacker** [comment]
Looks like you have the README.md file changes included in this PR.  Please clone a fresh local repo from master and create a new branch before you submit a new PR.  Usually this kind of thing happens when you make changes to your local master branch or create a new branch from an existing branch (other than master).

**Comment by skiman6010** [comment]
Let's please keep our PR and issue titles concise and basic. You can add all this extra information into the actual body of the PR or issue. Thank you. :)

**Comment by sajjaadf** [comment]
How do you create a new fresh clone from master?
[image: Picture]
Sajjaad Farzad
About Me
<https://about.me/sajjaadf?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>

**Comment by uberhacker** [comment]
An easy way is to delete your fork and then re-fork and clone again.

**Comment by sajjaadf** [comment]
What about the hard way?

Sent from Mail for Windows 10

**Comment by uberhacker** [comment]
It looks like you edited on Github instead of your local system.  The hard way would be from a terminal (macOS or Linux) or Git Bash (Windows) session:
```
$ cd
$ git clone https://github.com/sajjaadf/chromebrew-Dev.git
$ cd chromebrew-Dev
$ git remote add chromebrew https://github.com/skycocker/chromebrew.git
$ git fetch chromebrew
$ git checkout chromebrew/master
$ git checkout -b my-new-branch (any branch name you want)
edit files and save
$ git add -A
$ git commit -m "Add README.md"
$ git push sajjaadf my-new-branch
visit https://github.com/sajjaadf/chromebrew-Dev and create a new pull request to master of https://github.com/skycocker/chromebrew
```

**Pull request closed without merging**
