### PR TITLE
Add mc package

### PR DESCRIPTION
**Pull request by uberhacker**
GNU Midnight Commander is a visual file manager, licensed under GNU General Public License and therefore qualifies as Free Software. It's a feature rich full-screen text mode application that allows you to copy, move and delete files and whole directory trees, search for files and run commands in the subshell. Internal viewer and editor are included.

Midnight Commander is based on versatile text interfaces, such as Ncurses or S-Lang, which allows it to work on a regular console, inside an X Window terminal, over SSH connections and all kinds of remote shells.

See http://midnight-commander.org/.

### CODE REVIEW

**Comment by uberhacker** [comment]
@VitaliyKulikov: Does this PR add what you were trying to build?

**Comment by VitaliyKulikov** [comment]
@uberhacker yep. hmm, is it working !? awesome 👍 
still need few packages to not use `chroot` or `crouton` :
- maven (not tried yet, seems should work ... just shell script based on jdk) and gradle (same)
- vscode or atom (seems challenging)
- meld (sometimes for three-way-compare during git rebase)

**Comment by uberhacker** [comment]
@VitaliyKulikov: Yes, however, the `slang` package is not building correctly for x86_64 systems since the libraries are not in the correct location.  I'll push a PR to fix soon.

**Comment by uberhacker** [comment]
@VitaliyKulikov: I would :heart: to get vscode or atom working in Chromebrew.  However, the problem is these editors require GUI support which is not currently available.  You might be able to get these apps working in CloudReady.  I've had luck with several GUI apps.  If you are interested in helping with the effort to get the GUI working in Chromebrew, see [this issue[(#889).

**Comment by uberhacker** [comment]
It looks like meld is a graphic app also.  You could use vimdiff in Chromebrew as an alternative.  Not as visually appealing as meld, I'm sure, but I use it all the time and find it "good enough" in most cases.

**Comment by VitaliyKulikov** [comment]
@uberhacker thank you for your feedback )) btw, could you provide correct URL for `get the GUI working in Chromebrew, see this issue.`

**Comment by uberhacker** [comment]
@VitaliyKulikov: Sorry, the link has been corrected.  GitHub markdown doesn't work quite like I expected.

**Pull request merged**
