### PR TITLE
Fix missing end!

### LINKED ISSUE #4618: Chromebrew fails trying to install python3
## Description
I was running the install command, and it failed trying to install python. I then ran the following command to try and get python, and it gave the following output.

```shell
crew install python3
```

Output:
```shell
/usr/local/bin/crew:98:in `print_package': undefined method `any?' for nil:NilClass (NoMethodError)
	from /usr/local/bin/crew:121:in `set_package'
	from /usr/local/bin/crew:199:in `block in search'
	from /usr/local/lib64/ruby/2.7.0/find.rb:49:in `block (2 levels) in find'
	from /usr/local/lib64/ruby/2.7.0/find.rb:48:in `catch'
	from /usr/local/lib64/ruby/2.7.0/find.rb:48:in `block in find'
	from /usr/local/lib64/ruby/2.7.0/find.rb:43:in `each'
	from /usr/local/lib64/ruby/2.7.0/find.rb:43:in `find'
	from /usr/local/bin/crew:198:in `search'
	from /usr/local/bin/crew:1005:in `block in install_command'
	from /usr/local/bin/crew:1003:in `each'
	from /usr/local/bin/crew:1003:in `install_command'
	from /usr/local/bin/crew:1089:in `<main>'
```

## Versions and system information
chromebrew: `1.5.1`

ChromeOS: `13421.99.0`

Model: HP Chromebook 11 G5 EE

Architecture: `x86_64`

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #4618 

Works properly:
- [x] x86_64

### CODE REVIEW

**Comment by satmandu** [comment]
crew needs to be robust to errors in package files. :/

**Comment by uberhacker** [comment]
Yep, these things can be difficult to debug sometimes.  Nice catch!

**Comment by cstrouse** [comment]
We should add a package linter and CI step. Do we do it custom or just write up a few rubocop rules to check for things we care about? Thoughts? @satmandu @uberhacker

**Comment by uberhacker** [comment]
Sounds like a good candidate for Github Actions.

**Comment by satmandu** [comment]
Right?

**Comment by cstrouse** [comment]
Yes, would be good for GH Actions. Adding the stale PR/issue workflow is another thing we could setup in Actions while we're there.

**Pull request merged**
