### PR TITLE
pygobject update to gnome 3.38

### PR DESCRIPTION
**Pull request by satmandu**
This is a BREAKING change as python2 support has been removed from this project.

Works properly:
- [x] x86_64

### CODE REVIEW

**Comment by uberhacker** [comment]
I'm hesitant to do this since so many projects already depend on python27.  Can you please verify this doesn't break other packages that depend on pygobject?  I get it that Python 2 needs to deprecate but this has been said for many years now. :)

**Comment by satmandu** [comment]
> I'm hesitant to do this since so many projects already depend on python27.  Can you please verify this doesn't break other packages that depend on pygobject?  I get it that Python 2 needs to deprecate but this has been said for many years now. :)

We could also rename the old one to pygobject2?

**Comment by satmandu** [comment]
I'm seeing these directly having pygobject dependencies:

pygtk
libpeas
mypaint

There's already a pygobject2 package though...

**Comment by uberhacker** [comment]
Yeah, we could but do the files overlap?  Also, the other packages would need the new dependency?

**Comment by satmandu** [comment]
They don't appear to have overlap.

Would we have to change dependencies in other packages? If Python3 works...

**Python 3 only pygobject:**
```crew files pygobject
pygobject: PyGObject is a Python package which provides bindings for GObject based libraries such as GTK+, GStreamer, WebKitGTK+, GLib, GIO and many more.
https://pygobject.readthedocs.io/en/latest/
version 3.28.3
/usr/local/include/pygobject-3.0/pygobject.h
/usr/local/lib/pkgconfig/pygobject-3.0.pc
/usr/local/lib/python3.8/site-packages/gi/_constants.py
/usr/local/lib/python3.8/site-packages/gi/docstring.py
/usr/local/lib/python3.8/site-packages/gi/_error.py
/usr/local/lib/python3.8/site-packages/gi/_gi_cairo.cpython-38-x86_64-linux-gnu.so
/usr/local/lib/python3.8/site-packages/gi/_gi.cpython-38-x86_64-linux-gnu.so
/usr/local/lib/python3.8/site-packages/gi/_gtktemplate.py
/usr/local/lib/python3.8/site-packages/gi/importer.py
/usr/local/lib/python3.8/site-packages/gi/__init__.py
/usr/local/lib/python3.8/site-packages/gi/module.py
/usr/local/lib/python3.8/site-packages/gi/_option.py
/usr/local/lib/python3.8/site-packages/gi/_ossighelper.py
/usr/local/lib/python3.8/site-packages/gi/overrides/GdkPixbuf.py
/usr/local/lib/python3.8/site-packages/gi/overrides/Gdk.py
/usr/local/lib/python3.8/site-packages/gi/overrides/GIMarshallingTests.py
/usr/local/lib/python3.8/site-packages/gi/overrides/Gio.py
/usr/local/lib/python3.8/site-packages/gi/overrides/GLib.py
/usr/local/lib/python3.8/site-packages/gi/overrides/GObject.py
/usr/local/lib/python3.8/site-packages/gi/overrides/Gtk.py
/usr/local/lib/python3.8/site-packages/gi/overrides/__init__.py
/usr/local/lib/python3.8/site-packages/gi/overrides/keysyms.py
/usr/local/lib/python3.8/site-packages/gi/overrides/Pango.py
/usr/local/lib/python3.8/site-packages/gi/overrides/__pycache__/Gdk.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/gi/overrides/__pycache__/GdkPixbuf.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/gi/overrides/__pycache__/GIMarshallingTests.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/gi/overrides/__pycache__/Gio.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/gi/overrides/__pycache__/GLib.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/gi/overrides/__pycache__/GObject.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/gi/overrides/__pycache__/Gtk.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/gi/overrides/__pycache__/__init__.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/gi/overrides/__pycache__/keysyms.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/gi/overrides/__pycache__/Pango.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/gi/_propertyhelper.py
/usr/local/lib/python3.8/site-packages/gi/__pycache__/_constants.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/gi/__pycache__/docstring.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/gi/__pycache__/_error.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/gi/__pycache__/_gtktemplate.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/gi/__pycache__/importer.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/gi/__pycache__/__init__.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/gi/__pycache__/module.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/gi/__pycache__/_option.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/gi/__pycache__/_ossighelper.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/gi/__pycache__/_propertyhelper.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/gi/__pycache__/pygtkcompat.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/gi/__pycache__/_signalhelper.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/gi/__pycache__/types.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/gi/pygtkcompat.py
/usr/local/lib/python3.8/site-packages/gi/repository/__init__.py
/usr/local/lib/python3.8/site-packages/gi/repository/__pycache__/__init__.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/gi/_signalhelper.py
/usr/local/lib/python3.8/site-packages/gi/types.py
/usr/local/lib/python3.8/site-packages/PyGObject-3.38.1-py3.8.egg-info/dependency_links.txt
/usr/local/lib/python3.8/site-packages/PyGObject-3.38.1-py3.8.egg-info/not-zip-safe
/usr/local/lib/python3.8/site-packages/PyGObject-3.38.1-py3.8.egg-info/PKG-INFO
/usr/local/lib/python3.8/site-packages/PyGObject-3.38.1-py3.8.egg-info/requires.txt
/usr/local/lib/python3.8/site-packages/PyGObject-3.38.1-py3.8.egg-info/SOURCES.txt
/usr/local/lib/python3.8/site-packages/PyGObject-3.38.1-py3.8.egg-info/top_level.txt
/usr/local/lib/python3.8/site-packages/pygtkcompat/generictreemodel.py
/usr/local/lib/python3.8/site-packages/pygtkcompat/__init__.py
/usr/local/lib/python3.8/site-packages/pygtkcompat/__pycache__/generictreemodel.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/pygtkcompat/__pycache__/__init__.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/pygtkcompat/__pycache__/pygtkcompat.cpython-38.pyc
/usr/local/lib/python3.8/site-packages/pygtkcompat/pygtkcompat.py
Total found: 64
Disk usage: 2.8MB
```
**pygobject2:**
```
pygobject2: PyGObject is a Python package which provides bindings for GObject based libraries such as GTK+, GStreamer, WebKitGTK+, GLib, GIO and many more.
https://pygobject.readthedocs.io/en/latest/
version 2.28.7
/usr/local/bin/pygobject-codegen-2.0
/usr/local/include/pygtk-2.0/pyglib.h
/usr/local/include/pygtk-2.0/pygobject.h
/usr/local/lib64/libpyglib-2.0-python.la
/usr/local/lib64/libpyglib-2.0-python.so
/usr/local/lib64/libpyglib-2.0-python.so.0
/usr/local/lib64/libpyglib-2.0-python.so.0.0.0
/usr/local/lib64/pkgconfig/pygobject-2.0.pc
/usr/local/lib/python2.7/site-packages/glib/_glib.la
/usr/local/lib/python2.7/site-packages/glib/_glib.so
/usr/local/lib/python2.7/site-packages/glib/__init__.py
/usr/local/lib/python2.7/site-packages/glib/__init__.pyc
/usr/local/lib/python2.7/site-packages/glib/__init__.pyo
/usr/local/lib/python2.7/site-packages/glib/option.py
/usr/local/lib/python2.7/site-packages/glib/option.pyc
/usr/local/lib/python2.7/site-packages/glib/option.pyo
/usr/local/lib/python2.7/site-packages/gobject/constants.py
/usr/local/lib/python2.7/site-packages/gobject/constants.pyc
/usr/local/lib/python2.7/site-packages/gobject/constants.pyo
/usr/local/lib/python2.7/site-packages/gobject/_gobject.la
/usr/local/lib/python2.7/site-packages/gobject/_gobject.so
/usr/local/lib/python2.7/site-packages/gobject/__init__.py
/usr/local/lib/python2.7/site-packages/gobject/__init__.pyc
/usr/local/lib/python2.7/site-packages/gobject/__init__.pyo
/usr/local/lib/python2.7/site-packages/gobject/propertyhelper.py
/usr/local/lib/python2.7/site-packages/gobject/propertyhelper.pyc
/usr/local/lib/python2.7/site-packages/gobject/propertyhelper.pyo
/usr/local/lib/python2.7/site-packages/gtk-2.0/dsextras.py
/usr/local/lib/python2.7/site-packages/gtk-2.0/dsextras.pyc
/usr/local/lib/python2.7/site-packages/gtk-2.0/dsextras.pyo
/usr/local/lib/python2.7/site-packages/gtk-2.0/gio/_gio.la
/usr/local/lib/python2.7/site-packages/gtk-2.0/gio/_gio.so
/usr/local/lib/python2.7/site-packages/gtk-2.0/gio/__init__.py
/usr/local/lib/python2.7/site-packages/gtk-2.0/gio/__init__.pyc
/usr/local/lib/python2.7/site-packages/gtk-2.0/gio/__init__.pyo
/usr/local/lib/python2.7/site-packages/gtk-2.0/gio/unix.la
/usr/local/lib/python2.7/site-packages/gtk-2.0/gio/unix.so
/usr/local/lib/python2.7/site-packages/pygtk.pth
/usr/local/lib/python2.7/site-packages/pygtk.py
/usr/local/lib/python2.7/site-packages/pygtk.pyc
/usr/local/lib/python2.7/site-packages/pygtk.pyo
/usr/local/share/gtk-doc/html/pygobject/class-gioappinfo.html
/usr/local/share/gtk-doc/html/pygobject/class-gioapplaunchcontext.html
/usr/local/share/gtk-doc/html/pygobject/class-gioasyncresult.html
/usr/local/share/gtk-doc/html/pygobject/class-giobufferedinputstream.html
/usr/local/share/gtk-doc/html/pygobject/class-giobufferedoutputstream.html
/usr/local/share/gtk-doc/html/pygobject/class-giocancellable.html
/usr/local/share/gtk-doc/html/pygobject/class-giodatainputstream.html
/usr/local/share/gtk-doc/html/pygobject/class-giodataoutputstream.html
/usr/local/share/gtk-doc/html/pygobject/class-giodrive.html
/usr/local/share/gtk-doc/html/pygobject/class-gioemblemedicon.html
/usr/local/share/gtk-doc/html/pygobject/class-gioemblem.html
/usr/local/share/gtk-doc/html/pygobject/class-giofileattributeinfo.html
/usr/local/share/gtk-doc/html/pygobject/class-giofileenumerator.html
/usr/local/share/gtk-doc/html/pygobject/class-giofile.html
/usr/local/share/gtk-doc/html/pygobject/class-giofileicon.html
/usr/local/share/gtk-doc/html/pygobject/class-giofileinfo.html
/usr/local/share/gtk-doc/html/pygobject/class-giofileinputstream.html
/usr/local/share/gtk-doc/html/pygobject/class-giofilemonitor.html
/usr/local/share/gtk-doc/html/pygobject/class-giofileoutputstream.html
/usr/local/share/gtk-doc/html/pygobject/class-giofilterinputstream.html
/usr/local/share/gtk-doc/html/pygobject/class-giofilteroutputstream.html
/usr/local/share/gtk-doc/html/pygobject/class-gioicon.html
/usr/local/share/gtk-doc/html/pygobject/class-gioinputstream.html
/usr/local/share/gtk-doc/html/pygobject/class-gioloadableicon.html
/usr/local/share/gtk-doc/html/pygobject/class-giomemoryinputstream.html
/usr/local/share/gtk-doc/html/pygobject/class-giomemoryoutputstream.html
/usr/local/share/gtk-doc/html/pygobject/class-giomount.html
/usr/local/share/gtk-doc/html/pygobject/class-giomountoperation.html
/usr/local/share/gtk-doc/html/pygobject/class-giooutputstream.html
/usr/local/share/gtk-doc/html/pygobject/class-gioseekable.html
/usr/local/share/gtk-doc/html/pygobject/class-giosimpleasyncresult.html
/usr/local/share/gtk-doc/html/pygobject/class-giothemedicon.html
/usr/local/share/gtk-doc/html/pygobject/class-giounixinputstream.html
/usr/local/share/gtk-doc/html/pygobject/class-giounixoutputstream.html
/usr/local/share/gtk-doc/html/pygobject/class-giovolume.html
/usr/local/share/gtk-doc/html/pygobject/class-giovolumemonitor.html
/usr/local/share/gtk-doc/html/pygobject/class-glibmaincontext.html
/usr/local/share/gtk-doc/html/pygobject/class-glibmainloop.html
/usr/local/share/gtk-doc/html/pygobject/class-gobjectgboxed.html
/usr/local/share/gtk-doc/html/pygobject/class-gobjectginterface.html
/usr/local/share/gtk-doc/html/pygobject/class-gobjectgpointer.html
/usr/local/share/gtk-doc/html/pygobject/class-gobject.html
/usr/local/share/gtk-doc/html/pygobject/gio-class-reference.html
/usr/local/share/gtk-doc/html/pygobject/gio-constants.html
/usr/local/share/gtk-doc/html/pygobject/gio-functions.html
/usr/local/share/gtk-doc/html/pygobject/giounix-class-reference.html
/usr/local/share/gtk-doc/html/pygobject/glib-class-reference.html
/usr/local/share/gtk-doc/html/pygobject/glib-constants.html
/usr/local/share/gtk-doc/html/pygobject/glib-functions.html
/usr/local/share/gtk-doc/html/pygobject/gobject-class-reference.html
/usr/local/share/gtk-doc/html/pygobject/gobject-constants.html
/usr/local/share/gtk-doc/html/pygobject/gobject-functions.html
/usr/local/share/gtk-doc/html/pygobject/index.html
/usr/local/share/gtk-doc/html/pygobject/index.sgml
/usr/local/share/gtk-doc/html/pygobject/pygobject.devhelp
/usr/local/share/gtk-doc/html/pygobject/pygobject-introduction.html
/usr/local/share/gtk-doc/html/pygobject/style.css
/usr/local/share/pygobject/2.0/codegen/argtypes.py
/usr/local/share/pygobject/2.0/codegen/argtypes.pyc
/usr/local/share/pygobject/2.0/codegen/argtypes.pyo
/usr/local/share/pygobject/2.0/codegen/code-coverage.py
/usr/local/share/pygobject/2.0/codegen/codegen.py
/usr/local/share/pygobject/2.0/codegen/createdefs.py
/usr/local/share/pygobject/2.0/codegen/definitions.py
/usr/local/share/pygobject/2.0/codegen/definitions.pyc
/usr/local/share/pygobject/2.0/codegen/definitions.pyo
/usr/local/share/pygobject/2.0/codegen/defsconvert.py
/usr/local/share/pygobject/2.0/codegen/defsgen.py
/usr/local/share/pygobject/2.0/codegen/defsparser.py
/usr/local/share/pygobject/2.0/codegen/defsparser.pyc
/usr/local/share/pygobject/2.0/codegen/defsparser.pyo
/usr/local/share/pygobject/2.0/codegen/docextract.py
/usr/local/share/pygobject/2.0/codegen/docextract.pyc
/usr/local/share/pygobject/2.0/codegen/docextract.pyo
/usr/local/share/pygobject/2.0/codegen/docextract_to_xml.py
/usr/local/share/pygobject/2.0/codegen/docgen.py
/usr/local/share/pygobject/2.0/codegen/h2def.py
/usr/local/share/pygobject/2.0/codegen/__init__.py
/usr/local/share/pygobject/2.0/codegen/__init__.pyc
/usr/local/share/pygobject/2.0/codegen/__init__.pyo
/usr/local/share/pygobject/2.0/codegen/mergedefs.py
/usr/local/share/pygobject/2.0/codegen/missingdefs.py
/usr/local/share/pygobject/2.0/codegen/mkskel.py
/usr/local/share/pygobject/2.0/codegen/override.py
/usr/local/share/pygobject/2.0/codegen/override.pyc
/usr/local/share/pygobject/2.0/codegen/override.pyo
/usr/local/share/pygobject/2.0/codegen/reversewrapper.py
/usr/local/share/pygobject/2.0/codegen/reversewrapper.pyc
/usr/local/share/pygobject/2.0/codegen/reversewrapper.pyo
/usr/local/share/pygobject/2.0/codegen/scanvirtuals.py
/usr/local/share/pygobject/2.0/codegen/scmexpr.py
/usr/local/share/pygobject/2.0/defs/gappinfo.override
/usr/local/share/pygobject/2.0/defs/gapplaunchcontext.override
/usr/local/share/pygobject/2.0/defs/gbufferedinputstream.override
/usr/local/share/pygobject/2.0/defs/gcancellable.override
/usr/local/share/pygobject/2.0/defs/gdatainputstream.override
/usr/local/share/pygobject/2.0/defs/gdrive.override
/usr/local/share/pygobject/2.0/defs/gfileattribute.override
/usr/local/share/pygobject/2.0/defs/gfileenumerator.override
/usr/local/share/pygobject/2.0/defs/gfileinfo.override
/usr/local/share/pygobject/2.0/defs/gfileinputstream.override
/usr/local/share/pygobject/2.0/defs/gfileiostream.override
/usr/local/share/pygobject/2.0/defs/gfileoutputstream.override
/usr/local/share/pygobject/2.0/defs/gfile.override
/usr/local/share/pygobject/2.0/defs/gicon.override
/usr/local/share/pygobject/2.0/defs/ginputstream.override
/usr/local/share/pygobject/2.0/defs/gio.defs
/usr/local/share/pygobject/2.0/defs/gio.override
/usr/local/share/pygobject/2.0/defs/giostream.override
/usr/local/share/pygobject/2.0/defs/gio-types.defs
/usr/local/share/pygobject/2.0/defs/gmemoryinputstream.override
/usr/local/share/pygobject/2.0/defs/gmemoryoutputstream.override
/usr/local/share/pygobject/2.0/defs/gmount.override
/usr/local/share/pygobject/2.0/defs/goutputstream.override
/usr/local/share/pygobject/2.0/defs/gresolver.override
/usr/local/share/pygobject/2.0/defs/gsocket.override
/usr/local/share/pygobject/2.0/defs/gvolumemonitor.override
/usr/local/share/pygobject/2.0/defs/gvolume.override
/usr/local/share/pygobject/2.0/defs/unix.defs
/usr/local/share/pygobject/2.0/defs/unix.override
/usr/local/share/pygobject/2.0/defs/unix-types.defs
/usr/local/share/pygobject/xsl/common.xsl
/usr/local/share/pygobject/xsl/devhelp.xsl
/usr/local/share/pygobject/xsl/fixxref.py
/usr/local/share/pygobject/xsl/html.xsl
/usr/local/share/pygobject/xsl/pdf-style.xsl
/usr/local/share/pygobject/xsl/pdf.xsl
/usr/local/share/pygobject/xsl/ref-html-style.xsl
du: cannot access '/usr/local/lib64/libpyglib-2.0-python.la': No such file or directory
Total found: 169
Disk usage: 3.6MB
```

**Comment by uberhacker** [comment]
I was thinking if we rename pygobject to pygobject2, then the packages with that dependency will need changed.  If you can confirm those other packages work with the pygobject update (recompile to find out?), then we can go ahead with the upgrade and not worry about creating the separate python 2 version.

**Comment by uberhacker** [comment]
Oh, I see now.  We already have the pygobject2 package.  This is fine to exclude the python 2 references then.

**Pull request merged**
