### PR TITLE
Fix broadway and sommelier to export environment variables

### PR DESCRIPTION
**Pull request by uberhacker**

### CODE REVIEW

**Comment by uberhacker** [comment]
Can you please provide some proof of how this affects the `scp` or `rcp` commands?  The only person who is bothered by the error messages is you.

**Comment by JL2210** [comment]
You **don't** think people are bothered by the error messages?
```
Warning: Unknown scale factor: 1111
Warning: Unknown scale factor: 952
Warning: Unknown scale factor: 909
Warning: Unknown scale factor: 870
Warning: Unknown scale factor: 833
Warning: Unknown scale factor: 769
Warning: Unknown scale factor: 667
sommelier process 3514 is running
/usr/local/sbin/sommelierd: line 2:  3514 Terminated              sommelier -X --x-display=$DISPLAY --scale=$SCALE --no-exit-with-child /bin/sh -c "/usr/local/etc/sommelierrc"
(EE) 
Fatal server error:
(EE) failed to read Wayland events: Broken pipe
(EE) 
Segmentation fault (core dumped)
```

**Comment by JL2210** [comment]
As for `scp` and `rcp`:
> `broadwayd process 4126 is running` is the only thing that it displays, and then it exits.

**Comment by uberhacker** [comment]
We should probably figure out a better way to terminate sommelier.  That `Segmentation fault (core dumped)` message is a bit worrisome.  It's probably filling up the disk with core dump logs.

**Comment by JL2210** [comment]
I have an idea, though it will take a little while to make it stable. We can kill `/bin/bash /usr/local/sbin/sommelierd` instead of `sommelier`.

**Comment by JL2210** [comment]
`SOMM=$(ps ax | grep '/usr/local/sbin/sommelierd' | grep -v 'grep' | cut -d' ' -f2)

**Comment by JL2210** [comment]
We can use `pkill` instead of `killall`. Sorry for the bad explanation.

**Comment by uberhacker** [comment]
If you kill sommelierd, the sommelier process will continue to run.  The killall is used to kill off both processes in one go.  We could use `killall -g sommelier` and it would be a bit more graceful.

**Comment by JL2210** [comment]
OK. To be honest, when I was using `pkill` in the original `broadway` package, I thought it was pretty hilarious that it printed `Terminated`. That brought back some good memories.

**Pull request merged**
