### PR TITLE
Update tilp from 1.18 to 1.19

### PR DESCRIPTION
**Pull request by uberhacker**
Fixes #2498.

### CODE REVIEW

**Comment by JL2210** [comment]
#2489 not #2498

**Comment by JL2210** [comment]
@uberhacker, can't you just use different delimeters with sed, such as colons instead of slashes? Then you could just sed out /usr/bin/getent with #{CREW_PREFIX}/bin/getent? It would take up less space and be less of a hack, plus it works.

**Comment by JL2210** [comment]
@uberhacker, ever heard of autoconf?

**Comment by uberhacker** [comment]
@JL2210: Yes, but it won't work in this instance.  The install script is poorly written and doesn't allow overrides.  Actually, my fix is not much of a hack at all.  It just allows for the `LIBDIR` override.

**Comment by JL2210** [comment]
Yes, but it completely removes a part instead of replacing the tool it tries to find with the tool it needs to find. BTW, you're using tilp2. Tilp1 has configure scripts.

**Comment by JL2210** [comment]
Also, you can get a versioned tarball from their SourceForge page: https://sourceforge.net/projects/tilp/files

**Comment by JL2210** [comment]
My second one worked just fine. But I closed it in favor of yours, because you seem to know what you're doing.

**Comment by JL2210** [comment]
This doesn't need to be clogging up this PR. I'll talk to you on the user group.

**Comment by uberhacker** [comment]
Actually, I'm not removing anything.  All I'm doing is wrapping the LIBDIR logic with an if statement so it overrides that section if the environment variable is set.  Nice find on the sourceforge.net project.  Does it handle the dependencies needed also?

**Comment by JL2210** [comment]
Yes. The deps are in another tarball.

**Comment by debrouxl** [comment]
Well, I'm not against fixing the upstream user install script, if there's a good reason for it ;)
It already allows overriding SRCDIR and PREFIX (the latter is then passed to autotools, as it should be). The LIBDIR section could easily be made conditional to the LIBDIR environment variable being empty, like SRCDIR and PREFIX are already handled.

You don't need the SF.net project: using releases is a bad idea, the versions in the Git repositories on Github (and now Gitlab, which is mirroring them) always contain fixes and improvements.

**Comment by uberhacker** [comment]
Github repo?  Do you have a url?

**Comment by debrouxl** [comment]
See install_tilp.sh: https://github.com/debrouxl/tilibs , https://github.com/debrouxl/tilp_and_gfm .

**Pull request merged**
