### PR TITLE
Add pcre dependency to less

### PR DESCRIPTION
**Pull request by uberhacker**

### CODE REVIEW

**Comment by flyingP0tat0** [comment]
@thedamian He added the `pcre` dependency.

**Comment by jam7** [comment]
Please add `--with-regex=pcre` option also.  Otherwise, regcomp in glibc is used.

**Comment by jam7** [comment]
I have a problem with this PR.  I often use `\<word\>` as a search string.  These `\<` and `\>` means word delimiter.  This works fine with original less.  However, this doesn't work with pcre enabled less.  I prefer former.

So, how about using `--with-regex=posix` to force to use default library even if pcre is installed?

**Comment by lyxell** [comment]
I agree with @jam7 here, I think most users will expect/want posix regex.

**Comment by uberhacker** [comment]
@lyxell: I was waiting on a response from @tomas on #1083.  But I can certainly make that change so this can be merged soon.

**Comment by jam7** [comment]
I'm also waiting for @tomas on #1083.  BTW, `depends_on 'pcre'` is not necessary if we use `--with-regex=posix`

**Comment by uberhacker** [comment]
`depends_on 'pcre'` might be necessary on @tomas' system.

**Comment by thedamian** [comment]
waiting on @uberhacker to merge. and decide if we need to remove the 'depends_on" which i'm always a fan of

**Comment by cstrouse** [comment]
I'd like to keep the posix behavior.

**Comment by cstrouse** [comment]
So what should we do on this? @lyxell @uberhacker @thedamian @jam7

**Comment by uberhacker** [comment]
I suppose we can remove the pcre dependency and go ahead and merge.  I'll push up a commit shortly.

**Comment by uberhacker** [comment]
Closing to replace with new PR.

**Pull request closed without merging**
