### PR TITLE
Openconnect

### PR DESCRIPTION
**Pull request by titpetric**
In some cases libxml2 would not build with python installed, disabled the option of libxml2 python bindings with ./configure --without-python, also included gnutls due to issues with bundled openssh lib (incompatibility with openconnect, drops vpn).

Other fixes are more general, added some `depends_on` entries.

### CODE REVIEW

**Comment by skycocker** [comment]
@titpetric everything seems ok, but could you please set the indentations to two spaces? I'd like to keep the files consistent across the project

**Comment by skycocker** [comment]
@titpetric I'd like to merge this PR, but could you spent a minute on changing the line indentation to 2 spaces? For example https://github.com/skycocker/chromebrew/blob/master/packages/binutils.rb is indented with 2 spaces. This way you will still be the commit author instead of me copy pasting your work.

**Comment by titpetric** [comment]
Sorry, not a prio atm due to ongoing projects. Feel free to take autorship.

**Comment by skycocker** [comment]
@titpetric merged with your authorship kept :) 
I retabbed those files in a separate commit.

**Pull request merged**
