### PR TITLE
Update sommelier to add daemon and postinstall config

### PR DESCRIPTION
**Pull request by uberhacker**
Followed the instructions at https://github.com/dnschneid/crouton/wiki/Sommelier-(A-more-native-alternative-to-xiwi) to build a more complete sommelier package.

### CODE REVIEW

**Comment by JL2210** [comment]
Good idea. I will add an update to tilp that catches all the files.

**Comment by uberhacker** [comment]
@JL2210: You don't need to do anything with tilp.  The dialog box pops up fine if you have the sommelierd daemon running in the background, :)  This should make @superloach happy.

**Comment by uberhacker** [comment]
If you want to make a change, just add `depends_on 'sommelier'` to the tilp package.

**Comment by JL2210** [comment]
Yes, I do. You have a hackish way to track most of the files. I will get them all with a patch that I got from Gentoo.

**Comment by uberhacker** [comment]
The only way you are going to get that working is if you create separate packages for all the libraries which are needed during the build process.  Is it worth it?  Maybe not.

**Comment by JL2210** [comment]
No, it's not. I'll package them all into one. Why do that when only one package needs the libs? I'll do two `make install`s, one to install the files and one to track them. I'll disable tests, because they seem to break some things, and I'll add sha256 digests for all of them. Not simple, but worthy.

**Comment by JL2210** [comment]
@uberhacker, remake this with the sommelier daemon running 2>/dev/null and 1>/dev/null. I don't want this stuff to show up when I'm starting my shell:
```
_FontTransOpen: Unable to Parse address ${prefix}/share/fonts/X11/misc/
_FontTransOpen: Unable to Parse address ${prefix}/share/fonts/X11/TTF/
_FontTransOpen: Unable to Parse address ${prefix}/share/fonts/X11/OTF/
_FontTransOpen: Unable to Parse address ${prefix}/share/fonts/X11/Type1/
_FontTransOpen: Unable to Parse address ${prefix}/share/fonts/X11/100dpi/
_FontTransOpen: Unable to Parse address ${prefix}/share/fonts/X11/75dpi/
```

**Comment by uberhacker** [comment]
It's not a very good idea to hide warnings just because it's annoying.  Why not fix so the warnings go away instead?  Novel concept, I know.  For now, they're just warnings so we can deal with it.

**Comment by JL2210** [comment]
They aren't warnings. The tests make the build fail, so I disable them.

**Comment by JL2210** [comment]
Oh. I thought you were talking about something else. Along with that, crosh doesn't exit at all anymore with that. When you type exit, it just hangs.

**Comment by uberhacker** [comment]
I don't have that problem.

**Comment by JL2210** [comment]
With either or just one?

**Comment by uberhacker** [comment]
With the _"warnings"_ shown.

**Comment by JL2210** [comment]
What package are those fonts from? We could always manually set all of
those to exact paths.

**Comment by JL2210** [comment]
Saw that. Does tilp fail to compile on your end?

On Aug 8, 2018 11:40 AM, "Ed Reel" <notifications@github.com> wrote:

Not sure but I did find out that xwayland was missing the font_util package
dependency.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/skycocker/chromebrew/pull/2521#issuecomment-411451799>,
or mute the thread

**Comment by uberhacker** [comment]
No, I was able to build the pre-built binaries.  Anything wrong with those?

**Comment by JL2210** [comment]
Yeah. You need to change the prefix to crew_dest_dir along with
crew_lib_prefix and others

**Comment by JL2210** [comment]
Or fix the configure script to do it that way.

**Comment by uberhacker** [comment]
You are welcome to submit a PR if you cannot live with my _"hacked"_ solution.

**Comment by JL2210** [comment]
K. Will do that. Almost done.

**Pull request merged**
