### PR TITLE
add file command package

### PR DESCRIPTION
**Pull request by minektur**
add chromeos missing file command

### CODE REVIEW

**Comment by minektur** [comment]
note - I now think I understand why homebrew named theirs the way they did, and why I think we need to put the name back to filepackage or filecmd or something.

If you try this out you'll see that while the code looks right, it fails because ruby has a built-in class File.  I'm no ruby expert... but it appears that crew packages have to be valid ruby class names, which means we can't have a package with the same name as one of the ruby core classes.  In this case naming the crew package 'file' requires the class in the package file to be named 'File' which conflicts with the ruby builtin - http://ruby-doc.org/core-2.2.0/File.html.

Is there a way to have the 'class' defined in the crew package not directly look for a .rb file of that same name?  e.g. in the file.rb have the line

    class Filecmd < Package

instead of 

     class File < Package

but still have the file named 'file.rb' so that crew can install it with that name?

**Comment by skycocker** [comment]
@minektur this should be possible, but would also be quite hacky and inconsistent therefore. You're right about that, let's keep it named Filecmd as it was previously. Sorry about that. I'll merge this one when you rename it back.

**Comment by thedamian** [comment]
@minektur can you make the changes skycocker asked for and we'll merge it.

**Comment by thedamian** [comment]
@minektur  can I ask you to name it something that makes sense like you mentioned?
I tried naming it Filepkg (just a suggestion) and upgraded to 5.29
(sha1 sig: 8d360aeed901e3e4f4d4a865696ac1e29efdfcca )

so choose a name and upgrade the version and I'll merge it.

**Comment by minektur** [comment]
I submitted a new pull request... I used the name 'filecmd' because that is what homebrew on the mac uses....

**Comment by lyxell** [comment]
Closing in favor of #239

**Pull request closed without merging**
