### PR TITLE
Ruby_latest for Ruby 2.4.0 and Fixing Node text at the end that was causing a failure.

### PR DESCRIPTION
**Pull request by thedamian**

### CODE REVIEW

**Comment by thedamian** [comment]
With no objections I'm merging.

**Comment by lyxell** [comment]
@thedamian Why are we reverting gettext? Is there an issue opened?

**Comment by lyxell** [comment]
Looks good to me.

**Comment by lyxell** [comment]
Actually, I think we should wait before merging this. Let me at least investigate for which architectures readline is natively included first.

**Comment by thedamian** [comment]
Sounds good to me my friend. You asked for a PR that moved read line back for the arm. So I did it.

Please let me know. I think we should keep it the way it is and hat should work in arm as much as it works in intel

**Pull request merged**
