### PR TITLE
Fix cmake

### PR DESCRIPTION
**Pull request by saltedcoffii**
make cmake FHS compliant

### CODE REVIEW

**Comment by uberhacker** [comment]
We will need binaries since this is an important build package.

**Comment by satmandu** [comment]
I can have binaries for this sometime Thursday. My i686/armv7l builders are busy with gcc/llvm at the moment...

**Comment by uberhacker** [comment]
@satmandu:  Were you still planning on generating binaries?

**Comment by satmandu** [comment]
Let me start that now...

**Comment by satmandu** [comment]
binaries added

**Pull request merged**
