### PR TITLE
Update for release 67 and above

### LINKED ISSUE #2348: Massive installation failure on ChromeOS Version 68.0.3425.0 (Canary)
## Description
After attempting the installation, common shell commands such as `clear` and `sudo su -` just return the error 
```shell
Segmentation fault (core dumped)
```
while trying to run `crew` results in
```shell
/usr/local/lib64/ruby/2.5.0/x86_64-linux/enc/encdb.so: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0002 p:-926128 s:0006 e:000005 TOP    [FINISH]
c:0001 p:0000 s:0003 E:0018e0 (none) [FINISH]


-- Machine register context ------------------------------------------------
 RIP: 0x0000000000000000 RBP: 0x00007ffee1658e50 RSP: 0x00007ffee1658d08
 RAX: 0x0000000000000001 RBX: 0x00007ffee1658d80 RCX: 0x0000000000723600
 RDX: 0x000000000000000a RDI: 0x0000000000000009 RSI: 0x0000000000000001
  R8: 0x0000000000000001  R9: 0x000000000000000a R10: 0x00007d3b1c2cc050
 R11: 0x0000000000000001 R12: 0x000000000000000a R13: 0x0000000000723760
 R14: 0x00007ffee1658d70 R15: 0x000000000000000b EFL: 0x0000000000010202

-- C level backtrace information -------------------------------------------
Inconsistency detected by ld.so: dl-load.c: 1020: _dl_map_object_from_fd: Assertion `r->r_state == RT_ADD' failed!
```

Here is the full output from the Chromebrew installation:
```shell
curl -Ls git.io/vddgY | bash
```

Output:
```shell
Creating new device.json...
Downloading ruby...
######################################################################## 100.0%
Verifying ruby...
ruby-2.5.1-chromeos-x86_64.tar.xz: OK
Extracting ruby (this may take a while)...
Installing ruby (this may take a while)...
Adding new ruby information to device.json...
Downloading git...
######################################################################## 100.0%
Verifying git...
git-2.17.0-chromeos-x86_64.tar.xz: OK
Extracting git (this may take a while)...
Installing git (this may take a while)...
Adding new git information to device.json...
Downloading libssh2...
######################################################################## 100.0%
Verifying libssh2...
libssh2-1.8.0-chromeos-x86_64.tar.xz: OK
Extracting libssh2 (this may take a while)...
Installing libssh2 (this may take a while)...
Adding new libssh2 information to device.json...
######################################################################## 100.0%
######################################################################## 100.0%
######################################################################## 100.0%
Initialized empty Git repository in /usr/local/lib/crew/.git/
Updating origin
remote: Counting objects: 15738, done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 15738 (delta 9), reused 16 (delta 5), pack-reused 15714
Receiving objects: 100% (15738/15738), 3.60 MiB | 407.00 KiB/s, done.
Resolving deltas: 100% (10352/10352), done.
From https://github.com/skycocker/chromebrew
 * [new branch]      deps_order                       -> origin/deps_order
 * [new branch]      gh-pages                         -> origin/gh-pages
 * [new branch]      master                           -> origin/master
 * [new branch]      pr/205                           -> origin/pr/205
 * [new branch]      revert-1030-add-vpnc-package     -> origin/revert-1030-add-vpnc-package
 * [new branch]      revert-1177-update-screenfetch   -> origin/revert-1177-update-screenfetch
 * [new branch]      revert-758-add-moreutils-package -> origin/revert-758-add-moreutils-package
 * [new branch]      revert-760-add-cron-package      -> origin/revert-760-add-cron-package
 * [new branch]      revert-936-update-emacs-package  -> origin/revert-936-update-emacs-package
 * [new tag]         0.4.1                            -> 0.4.1
 * [new tag]         v0.1                             -> v0.1
 * [new tag]         v0.1.1                           -> v0.1.1
 * [new tag]         v0.2                             -> v0.2
 * [new tag]         v0.2.1                           -> v0.2.1
 * [new tag]         v0.2.1.1                         -> v0.2.1.1
 * [new tag]         v0.2.1.2                         -> v0.2.1.2
 * [new tag]         v0.3                             -> v0.3
 * [new tag]         v0.3.1                           -> v0.3.1
 * [new tag]         v0.4                             -> v0.4
From https://github.com/skycocker/chromebrew
 * branch            master     -> FETCH_HEAD
HEAD is now at 7aaff36 Merge pull request #2345 from danielcbaldwin/krypton_fixes
buildessential: A collection of tools essential to compile and build software.
version 1.1
The following packages also need to be installed: 
libsigsegv ncurses mpfr gmp expat libffi libtasn1 m4 openssl libtool pkgconfig glibc223 glibc zlibpkg libunistring nettle trousers p11kit libunbound gnutls libxml2 perl perl_xml_parser autoconf binutils mpc isl cloog gcc7 linuxheaders make automake intltool patch diffutils bison flex util_macros gettext wget unzip zip gawk cmake 
Do you agree? [Y/n] Proceeding...
libsigsegv: GNU libsigsegv is a library for handling page faults in user mode.
https://www.gnu.org/software/libsigsegv/
version 2.12
Precompiled binary available, downloading...
Archive downloaded
Unpacking archive, this may take awhile...
Installing...
Performing post-install...
ncurses: The ncurses (new curses) library is a free software emulation of curses in System V Release 4.0 (SVr4), and more.
https://www.gnu.org/software/ncurses/
version 6.1-0
Precompiled binary available, downloading...
Archive downloaded
Unpacking archive, this may take awhile...
Installing...
Performing post-install...
mpfr: The MPFR library is a C library for multiple-precision floating-point computations with correct rounding.
http://www.mpfr.org/
version 4.0.1
Precompiled binary available, downloading...
Archive downloaded
Unpacking archive, this may take awhile...
Installing...
Performing post-install...
gmp: GMP is a free library for arbitrary precision arithmetic, operating on signed integers, rational numbers, and floating-point numbers.
https://gmplib.org/
version 6.1.2-2
Precompiled binary available, downloading...
Archive downloaded
Unpacking archive, this may take awhile...
Installing...
Performing post-install...
expat: James Clark's Expat XML parser library in C.
https://sourceforge.net/projects/expat/
version 2.2.5
Precompiled binary available, downloading...
Archive downloaded
Unpacking archive, this may take awhile...
Installing...
Performing post-install...
libffi: The libffi library provides a portable, high level programming interface to various calling conventions.
https://sourceware.org/libffi/
version 3.2.1-2
Precompiled binary available, downloading...
Archive downloaded
Unpacking archive, this may take awhile...
Installing...
Performing post-install...
libtasn1: Libtasn1 is the ASN.1 library used by GnuTLS, GNU Shishi and some other packages.
https://www.gnu.org/software/libtasn1/
version 4.13
Precompiled binary available, downloading...
Archive downloaded
Unpacking archive, this may take awhile...
Installing...
Performing post-install...
m4: GNU M4 is an implementation of the traditional Unix macro processor.
https://www.gnu.org/software/m4/
version 1.4.18
Precompiled binary available, downloading...
Archive downloaded
Unpacking archive, this may take awhile...
Installing...
Performing post-install...
openssl: OpenSSL is an open source project that provides a robust, commercial-grade, and full-featured toolkit for the Transport Layer Security (TLS) and Secure Sockets Layer (SSL) protocols.
https://www.openssl.org/
version 1.0.2o
Precompiled binary available, downloading...
Archive downloaded
Unpacking archive, this may take awhile...
Installing...
Performing post-install...
libtool: GNU libtool is a generic library support script. Libtool hides the complexity of using shared libraries behind a consistent, portable interface.
https://www.gnu.org/software/libtool/
version 2.4.6-3
Precompiled binary available, downloading...
Archive downloaded
Unpacking archive, this may take awhile...
Installing...
Performing post-install...
pkgconfig: pkg-config is a helper tool used when compiling applications and libraries.
https://www.freedesktop.org/wiki/Software/pkg-config/
version 0.29.2-0
Precompiled binary available, downloading...
Archive downloaded
Unpacking archive, this may take awhile...
Installing...
Performing post-install...
glibc223: GNU C Library
https://www.gnu.org/software/libc/
version 2.23-3
Precompiled binary available, downloading...
Archive downloaded
Unpacking archive, this may take awhile...
Installing...
Performing post-install...
glibc: The GNU C Library project provides the core libraries for GNU/Linux systems.
https://www.gnu.org/software/libc/
version 1.1
zlibpkg: zlib is a massively spiffy yet delicately unobtrusive compression library.
http://www.zlib.net/
version 1.2.11-1
Precompiled binary available, downloading...
mkdir: cannot create directory ‘dest’: File exists
Traceback (most recent call last):
        12: from /usr/local/bin/crew:911:in `<main>'
        11: from /usr/local/bin/crew:853:in `install_command'
        10: from /usr/local/bin/crew:853:in `each'
         9: from /usr/local/bin/crew:857:in `block in install_command'
         8: from /usr/local/bin/crew:556:in `resolve_dependencies_and_install'
         7: from /usr/local/bin/crew:641:in `resolve_dependencies'
         6: from /usr/local/bin/crew:641:in `each'
         5: from /usr/local/bin/crew:643:in `block in resolve_dependencies'
         4: from /usr/local/bin/crew:655:in `install'
         3: from /usr/local/bin/crew:382:in `download'
         2: from /usr/local/bin/crew:382:in `chdir'
         1: from /usr/local/bin/crew:389:in `block in download'
/usr/local/bin/crew:389:in `read': No such file or directory @ rb_sysopen - ./zlibpkg-1.2.11-1-chromeos-x86_64.tar.xz (Errno::ENOENT)
/usr/local/lib64/ruby/2.5.0/x86_64-linux/enc/encdb.so: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0002 p:-2955696 s:0006 e:000005 TOP    [FINISH]
c:0001 p:0000 s:0003 E:000b60 (none) [FINISH]


-- Machine register context ------------------------------------------------
 RIP: 0x0000000000000000 RBP: 0x00007fff3d188130 RSP: 0x00007fff3d187fe8
 RAX: 0x0000000000000001 RBX: 0x00007fff3d188060 RCX: 0x000000000169f600
 RDX: 0x000000000000000a RDI: 0x0000000000000009 RSI: 0x0000000000000001
  R8: 0x0000000000000001  R9: 0x000000000000000a R10: 0x0000791da0e8f050
 R11: 0x0000000000000001 R12: 0x000000000000000a R13: 0x000000000169f760
 R14: 0x00007fff3d188050 R15: 0x000000000000000b EFL: 0x0000000000010202

-- C level backtrace information -------------------------------------------
Inconsistency detected by ld.so: dl-load.c: 1020: _dl_map_object_from_fd: Assertion `r->r_state == RT_ADD' failed!
/usr/local/lib64/ruby/2.5.0/x86_64-linux/enc/encdb.so: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0002 p:-1161136 s:0006 e:000005 TOP    [FINISH]
c:0001 p:0000 s:0003 E:001920 (none) [FINISH]


-- Machine register context ------------------------------------------------
 RIP: 0x0000000000000000 RBP: 0x00007fff66467610 RSP: 0x00007fff664674c8
 RAX: 0x0000000000000001 RBX: 0x00007fff66467540 RCX: 0x00000000008ee600
 RDX: 0x000000000000000a RDI: 0x0000000000000009 RSI: 0x0000000000000001
 R8: 0x0000000000000001  R9: 0x000000000000000a R10: 0x00007b6cc9c86050
 R11: 0x0000000000000001 R12: 0x000000000000000a R13: 0x00000000008ee760
 R14: 0x00007fff66467530 R15: 0x000000000000000b EFL: 0x0000000000010202

-- C level backtrace information -------------------------------------------
Inconsistency detected by ld.so: dl-load.c: 1020: _dl_map_object_from_fd: Assertion `r->r_state == RT_ADD' failed!

To set the default PAGER environment variable to be able to use less:
echo "export PAGER=/usr/local/bin/less" >> ~/.bashrc && . ~/.bashrc

Alternatively, you could use most.  Why settle for less, right?
echo "export PAGER=/usr/local/bin/most" >> ~/.bashrc && . ~/.bashrc

Chromebrew installed successfully and package lists updated.
```

## Versions and system information
chromebrew: `crew --version`

ChromeOS: `cat /etc/lsb-release`
```shell
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={BB86912A-29BE-A59B-31EF-8F4DD1C023E2}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_RELEASE_BOARD=enguarde-signed-mp-v25keys
CHROMEOS_RELEASE_BRANCH_NUMBER=0
CHROMEOS_RELEASE_BUILDER_PATH=enguarde-release/R68-10663.0.0
CHROMEOS_RELEASE_BUILD_NUMBER=10663
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=68
CHROMEOS_RELEASE_DESCRIPTION=10663.0.0 (Official Build) canary-channel enguarde 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=canary-channel
CHROMEOS_RELEASE_VERSION=10663.0.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10663.0.0
```

Model: Lenovo N21

Architecture: `uname -m`
x86_64

## Addtional information
Obviously I understand that Canary channel is a beta product so one can expect certain things not to work properly, but this seems like a pretty major failure which I thought you should be aware of.

### PR DESCRIPTION
**Pull request by uberhacker**
Fixes #2348.

If you receive segfault errors while running commands in releases 67 and above, the way to fix it after this PR is merged into master is below:
```
$ sudo rm -rf /usr/local
$ curl -Ls git.io/vddgY | bash
```
You may get an error `rm: cannot remove '/usr/local': Read-only file system` but that is fine.

If this method is not elegant enough for you, then you also have the option to powerwash and install normally.

I added another Q and A regarding this issue in the [FAQ](https://github.com/skycocker/chromebrew/wiki/FAQ).

### CODE REVIEW

**Comment by skiman6010** [comment]
Does this also lay the groundwork for versioned releases of Chromebrew?

**Comment by uberhacker** [comment]
@skiman6010: That is a very good question.  We will see how well this works going forward and if we need to recompile packages on versions 67 and above, then it will likely become necessary.

**Comment by skiman6010** [comment]
Tested and confirmed working on 67 after wiping usr/local and reinstalling. Merged into master!

**Comment by pgdagenais** [comment]
Awesome work @uberhacker alot simpler ! Thank you

**Comment by Yolotroll101** [comment]
what does running `sudo rm -rf /usr/local` even do?

**Comment by uberhacker** [comment]
Yeah, if you have Crouton stuff in there, that gets wiped away also.  The sad thing is you cannot run even a simple backup command in this corrupted state.

**Comment by Yolotroll101** [comment]
so how can i save my chroots and stuff from being wiped?

**Comment by uberhacker** [comment]
It's not straightforward but you could try this:
```
$ cd /lib (/lib64 if x86_64)
$ ls *2.23* | xargs
$ cd /usr/local/lib (/usr/local/lib64 if x86_64)
$ rm <paste the output of ls *2.23* | xargs from above>
```
This might get you to a state where commands aren't segfaulting.  If it does, then you are in luck and can backup your chroot stuff.

**Comment by Yolotroll101** [comment]
well ok then, error with first command:
```bash: syntax error near unexpected token `('```

**Comment by Yolotroll101** [comment]
:/

**Comment by uberhacker** [comment]
That makes sense if you just copied the commands.  What is your architecture (ie. output of `uname -m`)?

**Comment by Yolotroll101** [comment]
```
chronos@localhost / $ uname -m
x86_64
```

**Comment by uberhacker** [comment]
These would be the commands:
```
$ cd /lib64
$ ls *2.23* | xargs
$ cd /usr/local/lib64
$ rm <paste the output of ls *2.23* | xargs from above>
```

**Comment by Yolotroll101** [comment]
**oof:**
```
chronos@localhost / $ cd /lib64
chronos@localhost /lib64 $ ls *2.23* | xargs
Segmentation fault (core dumped)
```

**Comment by uberhacker** [comment]
Yep, that is what I meant by not straightforward.  Try this:
```
$ cd /usr/local/lib64
$ rm ld-2.23.so libanl-2.23.so libBrokenLocale-2.23.so libc-2.23.so libcidn-2.23.so libcrypt-2.23.so libdl-2.23.so libm-2.23.so libnsl-2.23.so libnss_compat-2.23.so libnss_db-2.23.so libnss_dns-2.23.so libnss_files-2.23.so libnss_hesiod-2.23.so libnss_nis-2.23.so libnss_nisplus-2.23.so libpthread-2.23.so libresolv-2.23.so librt-2.23.so libutil-2.23.so
```

**Comment by Yolotroll101** [comment]
cool worked. so now re-install chromebrew?

**Comment by uberhacker** [comment]
Try this first:
```
$ crew remove glibc223
$ crew update
$ crew upgrade
```
If that doesn't work then try a reinstall.  Backup your chroots first, if you can.

**Comment by Yolotroll101** [comment]
nice worked

**Comment by uberhacker** [comment]
FYI: I update the [FAQ](https://github.com/skycocker/chromebrew/wiki/FAQ) and added a Q and A regarding this workaround.

**Pull request merged**
