### PR TITLE
Add Redis 3.0.6

### PR DESCRIPTION
**Pull request by Tivoli**

### CODE REVIEW

**Comment by thedamian** [comment]
TESTED: PASS

Copied redis.rb to /usr/local/lib/crew/packages
did a "crew search" and "redis" is listed
did a "crew install redis" and it finished successfully.
At the end I got this (SUCCESS)
"Installation success!
To start the redis server: redis-server --daemonize yes
To connect to the server: redis-cli
Installing...
Redis installed!"

Running this allowed me to run and check that redis was working. (no full extended testing. Just started the daemon and connected to it successfully)

NOW It did complain that I should have the "Crew BuildEssentials package" but it needed the "gcc" package not only the build essentials.  THAT made it work. 

I suggest we add this package.

**Comment by Tivoli** [comment]
@thedamian BuildEssentials depends on gcc, so it should install with it.

**Comment by thedamian** [comment]
BuildEssentials was installed and I even tried to install again with it finding nothign new to install.
regardless AFTER I installed GCC then it worked just fine as noticed.

I wanted to make sure everythign would work, and it looks like it did.

**Comment by skycocker** [comment]
@thedamian `buildessential` contains gcc.

**Pull request merged**
