### PR TITLE
Update isl from 0.19 to 0.20

### PR DESCRIPTION
**Pull request by uberhacker**
Tested on:
- [x] armv7l
- [x] i686
- [x] x86_64

### CODE REVIEW

**Comment by JL2210** [comment]
Why don't you use the tarball from http://isl.gforge.inria.fr ?

**Comment by uberhacker** [comment]
Because it's easier to grab the tagged release from git?  Sorry, that was a joke.  I'll update with the release tarball.  It also doesn't require autogen.sh to create a configure script.

**Comment by JL2210** [comment]
OK. Well, if it has autogen.sh, that might be nice. Our autoconf doesn't work that well.

**Comment by uberhacker** [comment]
Does that look any better @JL2210?

**Comment by JL2210** [comment]
I couldn't have done any better myself. Good job!

**Pull request merged**
