### PR TITLE
Update wine

### PR DESCRIPTION
**Pull request by flyingP0tat0**
Change aarch64 to use 32-bit install method.
Hopefully solves #796.

### CODE REVIEW

**Comment by uberhacker** [comment]
@flyingP0tat0: Good call.  Thanks for this PR.  Can you please add another commit to avoid a merge conflict with PR #836?  See below:
```
-  source_sha1 '886bc24c315b2accbc2ad41d921e92177768f3a5'
 +  source_sha256 '488df7ffd2e81da455bf428fc9eb784bb4273a890334500895665711bd52f179'
```

**Comment by flyingP0tat0** [comment]
@uberhacker Done.

**Comment by lyxell** [comment]
@uberhacker It wouldn't have created a conflict, git is smart enough to automatically merge files where there's changes but on different lines.

**Comment by uberhacker** [comment]
@lyxell: Right, but if my PR was merged in first, his PR would have reverted the sha256 change back to sha1 which would have been even worse than a merge conflict.

**Comment by lyxell** [comment]
@uberhacker No, both pull requests would have merged fine.

**Comment by uberhacker** [comment]
@lyxell: My understanding is either of us would have needed to resolve merge conflicts if one PR was merged in before the other.  The reason it would create a merge conflict is the code being merged would not match master without resolving locally and pushing again.  Believe me, I've ran across this situation many times regarding pending PRs with changes on the same file.

**Comment by uberhacker** [comment]
I might be wrong about this but if git works anything like patches, if any of the line numbers don't match in the patch, it won't apply successfully.  In our case, we were lucky since there weren't any lines changed above the requested change(s).  In any event, we should be careful when merging multiple pending PRs that request changes on the same file.

**Pull request merged**
