### PR TITLE
Update php packages

### PR DESCRIPTION
**Pull request by uberhacker**
Tested on:
- [x] aarch64
- [x] armv7l
- [x] i686
- [x] x86_64

### CODE REVIEW

**Comment by skiman6010** [comment]
I hate PHP. Denied.

**Comment by uberhacker** [comment]
PHP is not all that bad.  It's the wrapper stuff around it that gives it a bad reputation.  Example: WordPress :)

**Comment by skiman6010** [comment]
Shhh it's Saturday, don't talk about WordPress. I have to fight the database for data Monday through Friday. This is my break day.

**Comment by JL2210** [comment]
lol

**Pull request merged**
