### PR TITLE
Added ShPkg package

### PR DESCRIPTION
**Pull request by JL2210**
A simple dpkg-compatible package manager implemented in Bash.

This package manager is going to be the basis for my operating system, along with `shapt` (Soon to come!).

### CODE REVIEW

**Comment by uberhacker** [comment]
Do we really need another package manager? ;)  Oh no!  Not another operating system!

**Comment by uberhacker** [comment]
Why re-invent the wheel?  https://github.com/bpkg/bpkg

**Comment by JL2210** [comment]
Not the same at all. I created a different format, and it only has dpkg COMPATIBILITY mode, for when dpkg isn't working.

**Comment by JL2210** [comment]
The new format has an empty control file, and instead of the `debian-binary` file it has a `sha256sum` with the checksums of `data.tar.xz` and `control.tar.xz`.

**Comment by uberhacker** [comment]
If this is a wrapper for dpkg, shouldn't that be a dependency for this package?  My point is...why?

**Comment by JL2210** [comment]
This is a replacement for `dpkg`.

**Comment by JL2210** [comment]
<whisper>I want to have Chromebrew be the package manager for my operating system, but it might need this first.</whisper>

**Comment by JL2210** [comment]
I want Chromebrew to be the secondary package manager for my operating system. This will just be the upater for the system.

**Comment by uberhacker** [comment]
Where are you getting the packages?  Don't you need a repository?

**Comment by JL2210** [comment]
Yes, I do. I have them in the `binaries/` directory of my chroot right now. Usually, I would build them by hand. This package would just help by allowing me to build them outside of the chroot.

**Comment by JL2210** [comment]
Plus, that would be what `shapt` will be for. If `dpkg` ever breaks, this will also be a fallback.

**Comment by uberhacker** [comment]
I don't think we need this package here then, right?

**Comment by uberhacker** [comment]
I wish I could encourage you to work on other things like maybe an apt package for this project?  I would think that would be a bit more useful than a new package manager that pulls binaries from who knows where, don't you think?

**Comment by JL2210** [comment]
Fine. I suppose with `docbook` fixed, I could. One issue is that it will try to install binaries in `/usr`, though.

**Pull request closed without merging**
