### PR TITLE
update some python packages

### PR DESCRIPTION
**Pull request by saltedcoffii**
Just some updates for the python core packages and a few other things that I noticed. Needs binaries.

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/saltedcoffii/chromebrew.git CREW_TESTING_BRANCH=python-core-upgrades-Dec10 CREW_TESTING=1 crew update
```

### CODE REVIEW

**Comment by satmandu** [comment]
Would you please merge master?

**Comment by saltedcoffii** [comment]
@satmandu master merged

**Comment by satmandu** [comment]
I get git errors trying to build py3_nuitka:
```
fatal: remote error: upload-pack: not our ref 166c1fe240bfe1d855fccf2b9e55bd60018a4bd8
fatal: remote error: upload-pack: not our ref 01fcff2984112aaa3f2e2cef34cb18f9e5d91a92
fatal: remote error: upload-pack: not our ref 04e1c8315ccc10b9bba374c4704c77a9372d99d8
```

**Comment by satmandu** [comment]
Had to add `py3_typing_extensions` to get `py3_cryptography` to build on `x86_64` too.

**Comment by saltedcoffii** [comment]
@satmandu it looks like nuitka's submodules aren't exactly working. I'm just going to use a tarball from pypi.org.

**Pull request merged**
