### PR TITLE
add zip source file support, fix a minor nit

### PR DESCRIPTION
**Pull request by minektur**
Add zip support for source code repos.  Support "all files in top level of zip file" and "all files inside a top-level directory" style zip files, as discussed in an earlier PR.

### CODE REVIEW

**Comment by thedamian** [comment]
As has been said in the other pull for unzip (I love the unzip idea)

We'd need to inject a dependancy to unzip or add unzip along with the base package because no Chromebook comes with unzip built in

**Comment by thedamian** [comment]
@minektur where is the .strib variable? I don't see it. will your change work?

**Comment by minektur** [comment]
The alternative is just to make sure that each package that uses this
requires/depends on the unzip package. Would that be sufficient?

**Comment by minektur** [comment]
Strip isn't a variable it is a string method that removes whitespace from
both ends of the string which is all that TR command was doing in the
backticks.

**Comment by minektur** [comment]
and yes it works - run the following ruby code:

--------------
a = `uname -m`.strip
b = `uname -m | tr -d '\n\r`

puts a,a.length
puts b,b.length
----------

and you'll see that the output is identical.  the 'tr' command in linux translates characters  in a stream.  e.g. you could translate all 'a's to 'b's or whatever.  In this case the command line argument to tr says find all '\r\n' and substitute it with nothing.  So it is just removing the whitespace - the cr/nl - on the end of the string.  strip does the same thing, but does it in ruby, without the fork/exec needed to invoke tr.  Alternatively, you can use the perl-inspired chomp ruby string method where you can remove or "chomp" arbitrary things off the end of the string - if you give it an argument it will remove that string off the end - if you give it no argument, it removes non-printing/whitespace....  Note about 10 lines later chomp is used for just this - in this case, either way it works. 

 It just annoyed me that we relied on a command line pipe to do a less-than-one-liner in ruby, for more expense.  There are a bunch more little inconsistencies like this as happens any time multiple people are working on the code.  I was also thinking about replacing that line that calculates topdir for tar archives:

topdir = `tar -tf #{meta[:filename]} | sed -e 's@/.*@@' | uniq`.chomp!


with more ruby and less bash/command line.  The code does, roughly, get a listing of all files in the archive, on each line remove everything after the first /, then remove duplicates (all the lines are duplicates at this point because everthing after the first / was removed) and return the one line to ruby, chomping it to remove whitespace, and then stick the results into topdir.  It works as is, and it would have to be replaced by multiple lines of ruby to massage the output of 'tar -tf' similarly, so... I guess we leave it alone for now.  

I'm actually a better bash programmer than I am a ruby programmer, but I figure since this is a ruby project....  we should probably do as much ruby as reasonable.

**Comment by thedamian** [comment]
I'm SOLD that this is a perfect PR.

I'd just like to see the unzip dependancy injected if they have a .zip package.

Or should we leave that to the package creator?

**Comment by lyxell** [comment]
Just a heads up, there's a typo on line 18.

**Comment by minektur** [comment]
Oh, I'm a moron.  strib != strip - now I see what you were asking about.... sigh.

Fixed.

**Comment by minektur** [comment]
As for dependency injection.... this would only affect package authors right?  I'm ok with them needing to know to add it as a dependency, but having at least one example to follow in packages would probably help.  I'll be adding a package in a day or 3 depending on spare time.  Or just explain where/how to do it and I'll add the code.

**Comment by lyxell** [comment]
Instead of the topdir stuff you're doing, I guess one could use:
```ruby
topdir = `zipinfo -1 #{meta[:filename]} | sed -e 's@/.*@@' | uniq`.chomp!
```
Zipinfo is installed when installing unzip.

**Comment by thedamian** [comment]
I think we're ready to merge then.

@lyxell any objections if he does or doesn't use your suggestion in the next PR?

**Comment by lyxell** [comment]
@thedamian No objections except the one I just mentioned.

**Comment by thedamian** [comment]
I love this PR 
I love your suggestion lyxell 
And I'm good with the package creators dealing with the unzip dependancy.

I'm going to merge it since lyxell has no objections but I'd love to see that patch in the future

**Comment by lyxell** [comment]
Alright, I'll add that patch right away then.

**Pull request merged**
