### PR TITLE
Add compressdoc package

### PR DESCRIPTION
**Pull request by uberhacker**
Compress (with bzip2 or gzip) all man pages in a hierarchy and update symlinks.  See https://github.com/ojab/BLFS/blob/master/auxfiles/compressdoc.

### CODE REVIEW

**Comment by lyxell** [comment]
Is there a way to install this package with the standard procedure?
I.e. download a tar-ball, copy the files needed to CREW_DEST_DIR, and be done?

**Comment by uberhacker** [comment]
@lyxell: I thought that is what I was doing?  The GitHub tarball is just a throw away to get to the compressdoc file.  I actually use this same technique with a few other packages.  If you can suggest a better way and include a code snippet, that would be helpful.

**Comment by lyxell** [comment]
The "throw away" seems like a bad practice to me, why download files and check their hashsum if you're not using them? Isn't there a way to only download the files you're actually using? And let Chromebrew check the hashsum automatically?

**Comment by uberhacker** [comment]
Suggestions?  I'm certainly open to "what works".

**Comment by lyxell** [comment]
Untested, but maybe something like this:
```
require 'package'

class Compressdoc < Package
  source_url 'https://github.com/ojab/BLFS/archive/9b2b12c0d809e287e1ea3fa4790a73a71feffbe4.zip'
  source_sha1 'dd55e750128972ffd1022808b1b26cff2de242b1'
  version '9b2b12c0d809e287e1ea3fa4790a73a71feffbe4'

  depends_on 'unzip'

  def self.install
    system "mkdir -p #{CREW_DEST_DIR}/usr/local/bin"
    system "chmod +x auxfiles/compressdoc"
    system "cp auxfiles/compressdoc #{CREW_DEST_DIR}/usr/local/bin"
  end
end
```

**Comment by uberhacker** [comment]
@lyxell: I appreciate your enthusiasm but the problem with this approach is the zip archive is a moving target unless it has a release tag.  If this archive is from the master branch then any new commits will render the sha1 hash invalid.  With that said, you could probably say the same thing about `auxfiles/compressdoc`.  We might be better off just removing the whole manual checksum line.  If the download is corrupted and you can't install then no biggie.  You just try again.

**Comment by jam7** [comment]
I think any new commits take its own tag, so I guess this particularly
tagged zip file won't modified.  just thought, I've not tried it yet.

2017年6月26日(月) 14:44 Ed Reel <notifications@github.com>:

**Comment by uberhacker** [comment]
OK, you guys convinced me.  I just learned how to grab the latest archive from the project page.  I have pushed up a new commit with the proposed changes.  Thank you for the help.

**Comment by lyxell** [comment]
@jam7 Is correct.

**Pull request merged**
