### PR TITLE
Add libmagic shared library to filecmd

### LINKED ISSUE #5827: [filecmd] Missing libmagic.so.1 shared library
```
/usr/local/bin/more: error while loading shared libraries: libmagic.so.1: cannot open shared object file: No such file or directory
```

### PR DESCRIPTION
**Pull request by uberhacker**
Fixes #5827.  Tested on all architectures.  All tests passed.

### CODE REVIEW

**Comment by satmandu** [comment]
I want to make sure that there is a close to static file...  let me check this real quick...

**Comment by satmandu** [comment]
Otherwise this might work:
```
require 'package'

class Filecmd < Package
  description 'file command determines the file type.'
  homepage 'http://ftp.astron.com/'
  @_ver = '5.40'
  version @_ver
  license 'BSD-2 and GPL-3+' # Chromebrew's filefix is GPL-3+, file itself is BSD-2
  compatibility 'all'
  source_url "http://ftp.astron.com/pub/file/file-#{@_ver}.tar.gz"
  source_sha256 '167321f43c148a553f68a0ea7f579821ef3b11c27b8cbe158e4df897e4a5dd57'

  def self.build
    # The filefix command changes the full path of the file command in configure scripts.
    # Execute this command from your source code root directory.
    @filefix = <<~EOF
      #!/bin/bash
      for f in $(find . -name configure); do
        sed -i 's,/usr/bin/file,#{CREW_PREFIX}/bin/file,g' ${f}
      done
    EOF
    IO.write('./filefix', @filefix)
    # Optimization flags from https://github.com/InBetweenNames/gentooLTO
    # Build static for use in case needed with glibc brokenness.
    system "env  CFLAGS='-flto=auto -pipe -O3 -ffat-lto-objects -fipa-pta -fno-semantic-interposition -fdevirtualize-at-ltrans' \
      CXXFLAGS='-flto=auto -pipe -O3 -ffat-lto-objects -fipa-pta -fno-semantic-interposition -fdevirtualize-at-ltrans' \
      LDFLAGS='-flto=auto -static' \
      ./configure \
      #{CREW_OPTIONS} \
      --enable-static \
      --enable-shared \
      --disable-libseccomp"
    system 'make'
    FileUtils.mv 'src/file', 'file.static'
    system "env  CFLAGS='-flto=auto -pipe -O3 -ffat-lto-objects -fipa-pta -fno-semantic-interposition -fdevirtualize-at-ltrans' \
      CXXFLAGS='-flto=auto -pipe -O3 -ffat-lto-objects -fipa-pta -fno-semantic-interposition -fdevirtualize-at-ltrans' \
      LDFLAGS='-flto=auto' \
      ./configure \
      #{CREW_OPTIONS} \
      --enable-static \
      --enable-shared \
      --disable-libseccomp"
    system 'make'
  end

  def self.check
    system 'make', 'check'
  end

  def self.install
    FileUtils.mkdir_p "#{CREW_DEST_PREFIX}/bin/"
    FileUtils.install 'filefix', "#{CREW_DEST_PREFIX}/bin/filefix", mode: 0o755
    system 'make', "DESTDIR=#{CREW_DEST_DIR}", 'install-strip'
    FileUtils.cp 'file.static',"#{CREW_DEST_PREFIX}/bin/file"
  end
end
```

**Comment by satmandu** [comment]
This brings us back to
```
ldd `which file`
        linux-vdso.so.1 (0x00007ffe0b71f000)
        libmagic.so.1 => /usr/local/lib64/libmagic.so.1 (0x000079abd3305000)
        liblzma.so.5 => /usr/local/lib64/liblzma.so.5 (0x000079abd32e1000)
        libbz2.so.1.0 => /usr/local/lib64/libbz2.so.1.0 (0x000079abd32cf000)
        libz.so.1 => /usr/local/lib64/libz.so.1 (0x000079abd32b0000)
        libc.so.6 => /usr/local/lib64/libc.so.6 (0x000079abd3105000)
        libpthread.so.0 => /usr/local/lib64/libpthread.so.0 (0x000079abd30e5000)
        /lib64/ld-linux-x86-64.so.2 => /usr/local/lib64/ld-linux-x86-64.so.2 (0x000079abd333c000)
```

Whereas the static build gives us
```
ldd `which file`
        linux-vdso.so.1 (0x00007ffd12ff7000)
        libc.so.6 => /usr/local/lib64/libc.so.6 (0x00007c04f8d5c000)
        /lib64/ld-linux-x86-64.so.2 => /usr/local/lib64/ld-linux-x86-64.so.2 (0x00007c04f8f37000)
```

So let me do a quick rebuild which gives us both the static filecmd and the libmagic.so.1...

**Comment by uberhacker** [comment]
That's what I did.  We have both the shared and static libraries in this PR.

**Comment by satmandu** [comment]
The shared and static libaries are there, but the _file binary isn't static_, which is what I was going for.

**Comment by satmandu** [comment]
See https://github.com/skycocker/chromebrew/pull/5832

**Pull request closed without merging**
