### PR TITLE
Move crew

### PR DESCRIPTION
**Pull request by saltedcoffii**
Take 2 of moving the crew executable. This time I tested it on an existing install and it works.

Also included is a fix for #5612

### CODE REVIEW

**Comment by uberhacker** [comment]
No, this is what breaks crew.  Try a fresh install.

**Comment by saltedcoffii** [comment]
I did try a fresh install. I'll fix install.sh without moving crew.

**Comment by saltedcoffii** [comment]
Alright @uberhacker there's no more conflict

**Comment by uberhacker** [comment]
Bump crew version?

**Pull request merged**
