### PR TITLE
Add pip package

### PR DESCRIPTION
**Pull request by uberhacker**
Unless you install the python27 package, pip is unavailable even if the python and/or python3 packages are installed.  Sometimes you need python version 3 which justifies having this package available.

### CODE REVIEW

**Comment by jam7** [comment]
I thought I replied this one but it doesn't appear here.  Writing it again from web UI.

I think python.rb is out of date.  You can install python3.rb instead and it install pip from the beginning.  We may think to remove python.rb.

**Comment by uberhacker** [comment]
What do you think about removing the python.rb package and renaming python3.rb to python.rb?  I think the confusion for users is they will not know that they need to enter the `python3` and `pip3` commands to execute.  But if we can create symlinks from python3.6 to python and pip3.6 to pip if the python27.rb package is not installed, that might be the ticket.

**Comment by jam7** [comment]
As @lyxell explained you several weeks ago, /usr/bin/python is python 2.7 on many linux distributions.  So, I think pretending that python3 is python is not a good idea.  I already saw a few packages has wrong depends_on line because of command name conflicts.  Making such symbolic link increase the possibility of wrong depends_on lines in the future.

I have no opinion about the package name.  I have above opinion about making such symbolic links.

**Comment by uberhacker** [comment]
The symlinks could work with the following caveats.  Both packages would need to look for existing installations and NOT add the symlinks/binaries if they're already installed.  The only time you would need the symlinks added is if the python3.rb package is the only python version installed.  Likewise, if the python27.rb package is installed after python3.rb, then python27 should NOT add /usr/local/bin/python or /usr/local/bin/pip.

**Comment by uberhacker** [comment]
Closing since apparently, we want Chromebrew to be like every other package manager.

**Comment by jam7** [comment]
FYI, python3 is not compatible with python2.  It's the reason why ppl leave `python` as is and install python 3.x as `python3`.  You can google about differences.

Anyway, leave `pyhon` intact is good manner for few more years, I think.

**Pull request closed without merging**
