### PR TITLE
Update v4l_utils from 1.16.3 to 1.18.0

### PR DESCRIPTION
**Pull request by uberhacker**
Tested on all architectures.

### CODE REVIEW

**Comment by cstrouse** [comment]
I just installed this from binaries on aarch64 and the binaries dump core when I try to run them. I'll see if a source build yields the same results.

**Comment by uberhacker** [comment]
@cstrouse: Which specific binaries are dumping core?  I just tested this again and it works fine on my aarch64 system.

**Comment by uberhacker** [comment]
@cstrouse: I just updated to the latest ChromeOS release 80.0.3987.158.  Did you update recently?

**Comment by cstrouse** [comment]
Works fine after a fresh crew install. I updated to `80.0.3987.158 (Official Build) (32-bit)` and had a bunch of issues before I reinstalled crew.

**Pull request merged**
