### PR TITLE
Add torbrowser package

### PR DESCRIPTION
**Pull request by uberhacker**
See https://www.torproject.org/about/history/.  Tested on x86_64.

### CODE REVIEW

**Comment by satmandu** [comment]
> See https://www.torproject.org/about/history/.  Tested on x86_64.  No sound. :(

For sound something like this?

https://gitlab.torproject.org/legacy/trac/-/issues/29360

**Comment by satmandu** [comment]
As suggested in that thread to fix audio with pulseaudio:

```
$ cp -pf $HOME/.esd_auth $HOME/.tor-browser/INSTALL/Browser
$ cp -pfr $HOME/.config/pulse/ $HOME/.tor-browser/INSTALL/Browser
```

**Comment by supechicken** [comment]
Try to install `cras`? By the way the sound works perfectly for me :)

**Comment by uberhacker** [comment]
@supechicken is correct.  Sound is working.  Not sure why but I didn't need any special fixes to get it working.  Probably user error. :)

**Pull request merged**
