### PR TITLE
Add crew -V|--version and -v|--verbose options

### LINKED ISSUE #1385: crew -v|--version should display the version
Currently, `crew -v|--version` does not work.  However, to complicate matters, the `-v` switch is also used to get verbose output from `crew search <package> -v`.  I propose we repurpose the `-v|--verbose` switch to something like `-x|--expand` instead so we can get `crew -v|--version` working.

### PR DESCRIPTION
**Pull request by uberhacker**
Closes #1385.

### CODE REVIEW

**Comment by skiman6010** [comment]
When testing this commit, I get the following error when typing `crew [command] `: 
```
/usr/local/bin/crew:40:in `<main>': uninitialized constant CREW_VERSION (NameError)
Did you mean?  CREW_NPROC
```

Seems to be an issue with const.rb for me.

**Comment by uberhacker** [comment]
Before you test, make sure `lib/const.rb` and `lib/package.rb` are copied to `/usr/local/lib/crew/lib` and crew should be copied to `/usr/local/bin`.

**Comment by skiman6010** [comment]
They were, but I nuked my crew installation and started from scratch and then it worked fine.

**Comment by cstrouse** [comment]
LGTM.

**Pull request merged**
