### PR TITLE
Update crew to allow aarch64 to build armv7l binaries

### LINKED ISSUE #1324: [go] go failed to install on armv8
I want to build mongodb on my chromebook plus. But Go failed to build.
```
# runtime/cgo
In file included from _cgo_export.c:3:0:
cgo-gcc-export-header-prolog:25:14: error: size of array ‘_check_for_64_bit_pointer_matching_GoInt’ is negative
testing/quick
cmd/internal/dwarf
cmd/asm/internal/flags
cmd/internal/obj
testing/internal/testdeps
go/doc
html/template
cmd/asm/internal/lex
cmd/internal/bio
go/build
cmd/compile/internal/syntax
cmd/internal/gcprog
cmd/internal/browser
cmd/dist
cmd/internal/obj/arm
cmd/internal/obj/arm64
cmd/internal/obj/mips
go/internal/gccgoimporter
go/internal/gcimporter
go/internal/srcimporter
cmd/api
cmd/internal/obj/ppc64
cmd/internal/obj/s390x
go/importer
cmd/internal/obj/x86
cmd/compile/internal/types
cmd/cover
cmd/doc
cmd/fix
cmd/go/internal/cfg
cmd/go/internal/str
cmd/go/internal/base
cmd/go/internal/buildid
cmd/gofmt
cmd/go/internal/doc
cmd/go/internal/help
cmd/go/internal/load
cmd/go/internal/cmdflag
cmd/go/internal/tool
cmd/go/internal/version
cmd/link/internal/ld
cmd/nm
cmd/asm/internal/arch
cmd/compile/internal/ssa
cmd/objdump
cmd/go/internal/work
cmd/go/internal/fix
cmd/asm/internal/asm
cmd/go/internal/fmtcmd
cmd/pack
cmd/vendor/github.com/google/pprof/internal/elfexec
cmd/asm
cmd/vendor/github.com/google/pprof/profile
cmd/vendor/github.com/ianlancetaylor/demangle
cmd/go/internal/envcmd
cmd/go/internal/clean
cmd/go/internal/generate
cmd/go/internal/list
cmd/go/internal/run
cmd/go/internal/test
cmd/go/internal/vet
cmd/vendor/github.com/google/pprof/third_party/svg
cmd/vendor/github.com/google/pprof/internal/proftest
cmd/vet/internal/cfg
cmd/vendor/github.com/google/pprof/internal/plugin
cmd/vendor/github.com/google/pprof/internal/measurement
cmd/vendor/github.com/google/pprof/internal/binutils
cmd/vendor/github.com/google/pprof/internal/symbolz
cmd/vet
cmd/vendor/github.com/google/pprof/internal/graph
cmd/vendor/github.com/google/pprof/internal/report
cmd/link/internal/amd64
cmd/link/internal/arm64
cmd/link/internal/arm
cmd/link/internal/mips
cmd/link/internal/mips64
cmd/link/internal/ppc64
cmd/link/internal/s390x
cmd/link/internal/x86
cmd/link
cmd/compile/internal/gc
cmd/compile/internal/arm
cmd/compile/internal/amd64
cmd/compile/internal/arm64
cmd/compile/internal/mips
cmd/compile/internal/mips64
cmd/compile/internal/ppc64
cmd/compile/internal/s390x
cmd/compile/internal/x86
cmd/compile
go failed to install: `GOROOT_BOOTSTRAP=/usr/local/lib/go_bootstrap/go                 TMPDIR=/usr/local/tmp    GOROOT_FINAL=/usr/local/lib/go    ./make.bash` exited with 2

### LINKED ISSUE #1378: [strace] Build fails on aarch64
On Samsung Chromebook Plus (aarch64) `strace` fails to build properly.

```bash
gcc -DHAVE_CONFIG_H   -I./linux/aarch64 -I./linux/aarch64 -I./linux -I./linux -I. -I.    -Wall -Wempty-body -Wformat-security -Wignored-qualifiers -Winit-self -Wlogical-op -Wmissing-parameter-type -Wnested-externs -Wold-style-declaration -Wold-style-definition -Wsign-compare -Wtype-limits -Wwrite-strings  -g -O2 -MT strace-truncate.o -MD -MP -MF .deps/strace-truncate.Tpo -c -o strace-truncate.o `test -f 'truncate.c' || echo './'`truncate.c
mv -f .deps/strace-times.Tpo .deps/strace-times.Po
In file included from syscall.c:1007:0:
./linux/aarch64/arch_regs.c:24:22: error: field ‘aarch64_r’ has incomplete type
  struct user_pt_regs aarch64_r;
                      ^
gcc -DHAVE_CONFIG_H   -I./linux/aarch64 -I./linux/aarch64 -I./linux -I./linux -I. -I.    -Wall -Wempty-body -Wformat-security -Wignored-qualifiers -Winit-self -Wlogical-op -Wmissing-parameter-type -Wnested-externs -Wold-style-declaration -Wold-style-definition -Wsign-compare -Wtype-limits -Wwrite-strings  -g -O2 -MT strace-ubi.o -MD -MP -MF .deps/strace-ubi.Tpo -c -o strace-ubi.o `test -f 'ubi.c' || echo './'`ubi.c
mv -f .deps/strace-truncate.Tpo .deps/strace-truncate.Po
make[2]: *** [Makefile:5868: strace-syscall.o] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f .deps/strace-term.Tpo .deps/strace-term.Po
mv -f .deps/strace-ubi.Tpo .deps/strace-ubi.Po
mv -f .deps/strace-time.Tpo .deps/strace-time.Po
mv -f .deps/strace-strace.Tpo .deps/strace-strace.Po
make[2]: Leaving directory '/usr/local/tmp/crew/strace-4.19.tar.xz.dir/strace-4.19'
make[1]: *** [Makefile:6295: all-recursive] Error 1
make[1]: Leaving directory '/usr/local/tmp/crew/strace-4.19.tar.xz.dir/strace-4.19'
make: *** [Makefile:1804: all] Error 2
rm ioctlsort0 ioctlsort0.o ioctlsort1 ioctlsort1.o ioctls_all1.h ioctls_all0.h
strace failed to install: `make -j6` exited with 2
```

### LINKED ISSUE #1406: [gnutls] Building from source fails on aarch64
The build spews a bunch of assembler-related errors (representative snippet below):

```
lib/accelerated/aarch64/elf/sha256-armv8.s.tmp.S:1170: Error: ARM register expected -- `sub x3,x3,#64*4-16'
lib/accelerated/aarch64/elf/sha256-armv8.s.tmp.S:1171: Error: bad arguments to instruction -- `orr v2.16b,v0.16b,v0.16b'
lib/accelerated/aarch64/elf/sha256-armv8.s.tmp.S:1175: Error: ARM register expected -- `add v17.4s,v17.4s,v7.4s'
lib/accelerated/aarch64/elf/sha256-armv8.s.tmp.S:1176: Error: bad arguments to instruction -- `orr v2.16b,v0.16b,v0.16b'
lib/accelerated/aarch64/elf/sha256-armv8.s.tmp.S:1180: Error: ARM register expected -- `add v0.4s,v0.4s,v18.4s'
lib/accelerated/aarch64/elf/sha256-armv8.s.tmp.S:1181: Error: bad size 4 in type specifier
lib/accelerated/aarch64/elf/sha256-armv8.s.tmp.S:1181: Error: bad arguments to instruction -- `add v1.4s,v1.4s,v19.4s'
lib/accelerated/aarch64/elf/sha256-armv8.s.tmp.S:1183: Error: selected processor does not support ARM mode `cbnz x2,.Loop_hw'
lib/accelerated/aarch64/elf/sha256-armv8.s.tmp.S:1185: Error: bad instruction `st1 {v0.4s,v1.4s},[x0]'
lib/accelerated/aarch64/elf/sha256-armv8.s.tmp.S:1187: Error: ARM register expected -- `ldr x29,[sp],#16'
lib/accelerated/aarch64/elf/sha256-armv8.s.tmp.S:1188: Error: bad instruction `ret'
lib/accelerated/aarch64/elf/sha256-armv8.s.tmp.S:1047: Error: bad relocation fixup type (1)
make[5]: *** [Makefile:1475: elf/sha256-armv8.lo] Error 1
make[5]: Leaving directory '/usr/local/tmp/crew/gnutls-3.5.15.tar.xz.dir/gnutls-3.5.15/lib/accelerated/aarch64'
make[4]: *** [Makefile:1488: all-recursive] Error 1
make[4]: Leaving directory '/usr/local/tmp/crew/gnutls-3.5.15.tar.xz.dir/gnutls-3.5.15/lib/accelerated'
make[3]: *** [Makefile:1949: all-recursive] Error 1
make[3]: Leaving directory '/usr/local/tmp/crew/gnutls-3.5.15.tar.xz.dir/gnutls-3.5.15/lib'
make[2]: *** [Makefile:1636: all] Error 2
make[2]: Leaving directory '/usr/local/tmp/crew/gnutls-3.5.15.tar.xz.dir/gnutls-3.5.15/lib'
make[1]: *** [Makefile:1463: all-recursive] Error 1
make[1]: Leaving directory '/usr/local/tmp/crew/gnutls-3.5.15.tar.xz.dir/gnutls-3.5.15'
make: *** [Makefile:1391: all] Error 2
gnutls failed to install: `make -j6 V=0` exited with 2
```

### LINKED ISSUE #3512: [pandoc] binaries don't work on ARMv8
At first I thought this was due to stripping behavior since it complains that it doesn't recognize the format but I think the real issue is that they only provide 64-bit binaries and while ARMv8 Chromebooks are 64-bit hardware CrOS is 32-bit.

```
chronos@localhost /usr/local/tmp $ pandoc
bash: /usr/local/bin/pandoc: cannot execute binary file: Exec format error
```

Once we fix `ghc` (see #3511) we can try creating a source build for `pandoc` and build 32-bit binaries for ARMv8.

### PR DESCRIPTION
**Pull request by uberhacker**
Tested on aarch64.
Fixes #1324.
Fixes #1378.
Fixes #1406.
Fixes #3512.

@cstrouse:  The way this works is use `#{CREW_OPTIONS}` to replace `--prefix=#{CREW_PREFIX}` and `--libdir=#{CREW_LIB_PREFIX}` configure options.  See the output of `crew const CREW_OPTIONS`.  Example `self.build` section:
```
  def self.build
    system "./configure \
           #{CREW_OPTIONS} \
           --enable-shared \
           --enable-static \
           --enable-relocatable \
           --enable-extra-encodings"
    system 'make'
  end
```

### CODE REVIEW

**Comment by cstrouse** [comment]
@uberhacker Cool I'll try this out today and let you know.

**Comment by uberhacker** [comment]
@cstrouse: Did you get a chance to check this out yet?

**Comment by cstrouse** [comment]
Sorry, was unable to get to this because my Chromebook kept running out of disk space compiling things because Android is eating it all up.

I just tried this version out and so far both go and strace still don't build.

**Comment by cstrouse** [comment]
This doesn't solve the pandoc issue either since the binaries that are downloaded are 64-bit.

**Comment by uberhacker** [comment]
That looks correct.  It's building for armv7l, not aarch64.  What is in the logs?

**Comment by uberhacker** [comment]
I just complied gnutls on aarch64 and it worked fine.  You have to configure like this:
```
system "./configure #{CREW_OPTIONS} --enable-shared --disable-static --with-pic \
    --with-system-priority-file=#{CREW_PREFIX}/etc/gnutls/default-priorities \
    --with-unbound-root-key-file=#{CREW_PREFIX}/etc/unbound/root.key"
```
It doesn't work if you separate the options with commas because of the way ruby parses the line.

**Comment by cstrouse** [comment]
Here's what happens when trying to build gnutls from source using this branch:

Screenshot 2020-02-24 at 4 46 17 AM

And here's the output of `crew const`:

```bash
chronos@localhost:/usr/local/lib/crew/packages ((54fa4906...)) $ crew const
ARCH=aarch64
ARCH_LIB=lib
CHROMEOS_RELEASE=79
CREW_BREW_DIR=/usr/local/tmp/crew/
CREW_BUILD=armv7l-cros-linux-gnueabihf
CREW_CONFIG_PATH=/usr/local/etc/crew/
CREW_DEST_DIR=/usr/local/tmp/crew/dest
CREW_DEST_HOME=/usr/local/tmp/crew/dest/home/chronos/user
CREW_DEST_LIB_PREFIX=/usr/local/tmp/crew/dest/usr/local/lib
CREW_DEST_PREFIX=/usr/local/tmp/crew/dest/usr/local
CREW_LIB_PATH=/usr/local/lib/crew/
CREW_LIB_PREFIX=/usr/local/lib
CREW_NOT_COMPRESS=
CREW_NOT_STRIP=
CREW_NPROC=6
CREW_OPTIONS=--prefix=/usr/local --libdir=/usr/local/lib --build=armv7l-cros-linux-gnueabihf --host=armv7l-cros-linux-gnueabihf --target=armv7l-cros-linux-gnueabihf
CREW_PREFIX=/usr/local
CREW_VERSION=1.3.0
HOME=/home/chronos/user
LIBC_VERSION=2.27
USER=chronos
```

**Comment by uberhacker** [comment]
Yes, that is what I experienced also when I didn't reformat the configure options to remove the commas.  The `CREW_OPTIONS` constant is space delimited.

**Comment by cstrouse** [comment]
Still doesn't resolve the issue.

Screenshot 2020-02-24 at 6 52 37 AM

**Comment by uberhacker** [comment]
That looks like there is something wrong with your nettle.  What happens if you `crew reinstall nettle`?

**Comment by cstrouse** [comment]
Same thing. Already tried that.

**Comment by uberhacker** [comment]
I don't have that issue.  Maybe try a fresh chromebrew install?  This is usually a good first step before testing anyway.

**Comment by cstrouse** [comment]
Yeah but if things constantly break on updates that's not good either. I'll try it though.

**Comment by cstrouse** [comment]
Ok, did a fresh install, made the configure a single line with spaces separating the arguments, and got the same assembler errors. Which chipset and CPU is your ARMv8 machine that it's working on? For some reason on the Samsung Chromebook Plus V1 it continues to use the aarch64 versions of the assembler code even though everything in `crew const` and the `config.log` seems like it was setup properly.

**Comment by uberhacker** [comment]
I'll have to check my aarch64 system after work tonight.

**Comment by uberhacker** [comment]
@cstrouse: Output of /etc/lsb-release below:
```
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=6113486
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={AAE972E1-A913-C860-B7AB-BF7F267F199B}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={AAE972E1-A913-C860-B7AB-BF7F267F199B}
CHROMEOS_RELEASE_BOARD=hana-signed-mp-v6keys
CHROMEOS_RELEASE_BRANCH_NUMBER=82
CHROMEOS_RELEASE_BUILDER_PATH=hana-release/R79-12607.82.0
CHROMEOS_RELEASE_BUILD_NUMBER=12607
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=79
CHROMEOS_RELEASE_DESCRIPTION=12607.82.0 (Official Build) stable-channel hana 
CHROMEOS_RELEASE_KEYSET=mp-v6
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=12607.82.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=12607.82.0
```

**Comment by uberhacker** [comment]
Output of lshw below:
```
localhost
    description: ARMv8 Processor rev 2 (v8l)
    product: Mediatek Hana rev0 board
    width: 4294967295 bits
    capabilities: smp cp15_barrier setend swp
  *-core
       description: Motherboard
       physical id: 0
     *-cpu:0
          description: CPU
          product: cpu
          physical id: 0
          bus info: cpu@0
          size: 1703MHz
          capacity: 1703MHz
          capabilities: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpufreq
```

**Comment by uberhacker** [comment]
@cstrouse: Should I go ahead and close this or do you think it still might be useful?

**Comment by cstrouse** [comment]
It doesn't solve all of the issues related to this but it has merit and I think we should merge it in anyway since it does help with some other package builds.

**Pull request closed without merging**
