### PR TITLE
neofetch add binaries

### LINKED ISSUE #6383: Neofetch depends on make
Hi,
I got this error after trying to install neofetch:

```
chronos@localhost / $ crew install neofetch
neofetch: A fast, highly customizable system info script
https://github.com/dylanaraps/neofetch
Version: 7.1.0
License: MIT-with-advertising
Performing pre-flight checks...
No precompiled binary available for your platform, downloading source...
#### 100.0% -=#=- #      #       #                                                                                                                                                
Neofetch archive downloaded.
Unpacking archive using 'tar', this may take a while...
Building from source, this may take a while...
Rename all *.la files to *.la_tmp
Preconfiguring package...
neofetch failed to install: `make DESTDIR=/usr/local/tmp/crew/dest PREFIX=/usr/local install` exited with 127
```

I've solved it installing make. 

`chronos@localhost / $ crew install make
`

Neofetch should be marked as dependent on make.

## Versions and system information
chromebrew: 1.18.2 x86_64

Regards

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #6383 

Works properly:
- [x] x86_64
- [x] armv7l
- [ ] i686 ?
### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=neofetch CREW_TESTING=1 crew update
```

### CODE REVIEW

**Comment by saltedcoffii** [comment]
Neofetch is pure bash, so there's no reason we can't use the same binary for all architectures.

**Comment by saltedcoffii** [comment]
Maybe add an `is_arch_independent` to a package file like `is_fake` or something like that.

**Comment by satmandu** [comment]
@uberhacker thoughts on having an`is_arch_independent` option?

**Comment by uberhacker** [comment]
Maybe it's overkill to have `is_arch_independent`?  The Makefile basically doesn't compile but installs all the files in the correct location.  Still doesn't hurt to have binaries which can speed up installs.  In this case, the speed is probably negligible but it removes the need for build dependencies.

**Pull request merged**
