### PR TITLE
add proxychains package

### PR DESCRIPTION
**Pull request by elnx**

### CODE REVIEW

**Comment by uberhacker** [comment]
Thank you for the new package @elnx.  Can you please abstract the library directory?  The reason we want to do this is on x86_64 systems, the library path is `/usr/local/lib64`.  The change is shown below:
```
-    system "./configure", "--prefix=#{CREW_PREFIX}"
+    system "./configure", "--prefix=#{CREW_PREFIX}", "--libdir=#{CREW_LIB_PREFIX}"
```
You can test if it installed correctly by executing:
```
$ crew files proxychains
(i) proxychains: a tool that forces any TCP connection made by any given application to follow through proxy like TOR or any other SOCKS4, SOCKS5 or HTTP(S) proxy.
https://github.com/haad/proxychains
version 4.2.0
/usr/local/bin/proxychains4
/usr/local/lib64/libproxychains4.so
Total found: 2
```
Thanks

**Comment by cstrouse** [comment]
@elnx Next time please work in a feature branch instead of master.

**Comment by uberhacker** [comment]
@elnx: Here is what the postinstall section should look like:
```
  def self.postinstall
    system "make install-config"
  end
```

**Comment by elnx** [comment]
@uberhacker  Thanks for your reply. However, the makefile in proxychains does not support `make install-config`.
```
proxychains: a tool that forces any TCP connection made by any given application to follow through proxy like TOR or any other SOCKS4, SOCKS5 or HTTP(S) proxy.
https://github.com/haad/proxychains
version 4.2.0
No precompiled binary available for your platform, downloading source...
Archive downloaded
Unpacking archive, this may take awhile...
gcc (GCC) 4.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
Linux
LD_SET_SONAME=-ldl
done, now run make && make install
cc -Wall -O2 -g -std=c99 -D_GNU_SOURCE -pipe -DTHREAD_SAFE -Werror    -DLIB_DIR=\"/usr/local/lib\" -DINSTALL_PREFIX=\"/usr/local\" -DDLL_NAME=\"libproxychains4.so\" -DSYSCONFDIR=\"/usr/local/etc\"  -fPIC -c -o src/core.o src/core.c
cc -Wall -O2 -g -std=c99 -D_GNU_SOURCE -pipe -DTHREAD_SAFE -Werror    -DLIB_DIR=\"/usr/local/lib\" -DINSTALL_PREFIX=\"/usr/local\" -DDLL_NAME=\"libproxychains4.so\" -DSYSCONFDIR=\"/usr/local/etc\"  -fPIC -c -o src/common.o src/common.c
cc -Wall -O2 -g -std=c99 -D_GNU_SOURCE -pipe -DTHREAD_SAFE -Werror    -DLIB_DIR=\"/usr/local/lib\" -DINSTALL_PREFIX=\"/usr/local\" -DDLL_NAME=\"libproxychains4.so\" -DSYSCONFDIR=\"/usr/local/etc\"  -fPIC -c -o src/libproxychains.o src/libproxychains.c
cc -Wall -O2 -g -std=c99 -D_GNU_SOURCE -pipe -DTHREAD_SAFE -Werror    -DLIB_DIR=\"/usr/local/lib\" -DINSTALL_PREFIX=\"/usr/local\" -DDLL_NAME=\"libproxychains4.so\" -DSYSCONFDIR=\"/usr/local/etc\"  -fPIC -c -o src/main.o src/main.c
cc -shared -fPIC -lpthread   -Wl,-soname=libproxychains4.so -o libproxychains4.so src/core.o src/common.o src/libproxychains.o
cc src/main.o src/common.o -o proxychains4
Preconfiguring package...
install -d /usr/local/tmp/crew/dest//usr/local/bin /usr/local/tmp/crew/dest//usr/local/lib /usr/local/tmp/crew/dest//usr/local/etc /usr/local/tmp/crew/dest//usr/local/include
install -D -m 755 proxychains4 /usr/local/tmp/crew/dest//usr/local/bin/
install -D -m 644 libproxychains4.so /usr/local/tmp/crew/dest//usr/local/lib/
Installing...
Performing post-install...
make: *** No rule to make target 'install-config'.  Stop.
proxychains failed to install: `make install-config` exited with 2
```

**Comment by uberhacker** [comment]
@elnx: After looking at the README, I was able to figure out what they were looking for in the Configuration section.  If you do something like below, it will fix the issue with the config:
```
   def self.install
     system "make", "DESTDIR=#{CREW_DEST_DIR}", "install"
+    system "install -Dm644 src/proxychains.conf #{CREW_DEST_PREFIX}/$HOME/.proxychains/proxychains.conf"
+    system "install -Dm644 src/proxychains.conf #{CREW_DEST_PREFIX}/etc/proxychains.conf"
+    system "mkdir -p HOME/.proxychains && cp src/proxychains.conf $HOME/.proxychains"
+    system "install -Dm755 src/proxyresolv #{CREW_DEST_PREFIX}/bin/proxyresolv"
   end
```

**Comment by elnx** [comment]
@uberhacker thanks for you help. i added your code and delete the "postinstall".
It works now.
```
(i) proxychains: a tool that forces any TCP connection made by any given application to follow through proxy like TOR or any other SOCKS4, SOCKS5 or HTTP(S) proxy.
https://github.com/haad/proxychains
version 4.2.0
/usr/local/bin/proxychains4
/usr/local/bin/proxyresolv
/usr/local/etc/proxychains.conf
/usr/local/home/chronos/user/.proxychains/proxychains.conf
/usr/local/lib/libproxychains4.so
Total found: 5
```

**Pull request merged**
