### PR TITLE
Update heroku.rb

### PR DESCRIPTION
**Pull request by skiman6010**
Update to v6.14.41. 

Need pre-compiled binaries for aarch64, armv7l and i686.

### CODE REVIEW

**Comment by uberhacker** [comment]
Thank you for the update @skiman6010!  Can you please remove the pre-compiled binaries from your commit?  Also, if you could please change the install section like below, that would be better:
```
    system "mkdir -p #{CREW_DEST_PREFIX}/share/heroku"
    system "cp -r . #{CREW_DEST_PREFIX}/share/heroku"
    system "mkdir -p #{CREW_DEST_PREFIX}/bin"
    system "ln -s #{CREW_DEST_PREFIX}/share/heroku/bin/run #{CREW_DEST_PREFIX}/bin/heroku"
```
Thanks

**Comment by skiman6010** [comment]
Should I remove the updated x86_64 binary I made and uploaded?

**Comment by uberhacker** [comment]
Yes, the url can be simplified. :)  We should be adding binaries for all architectures on one commit, otherwise it creates confusion.  The versions of the binaries should always match the source in the package.

**Comment by skiman6010** [comment]
I was hoping someone else could compile the binaries for the extra architectures before the pull request was merged, but we can just do a new pull request for those then. I made your changes.

**Comment by uberhacker** [comment]
Can you please remove the indentation?  It makes the changes easier to detect.  Also, this might be a good time to learn how to squash your commits.  See https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git.  You will need to force the commit when you push it back to the repo using the `-f` flag.

**Comment by skiman6010** [comment]
Wow that's cool. Didn't know you could squash commits like that. How's that looking?

**Comment by uberhacker** [comment]
Yeah, squashing doesn't clutter up the commit log as much.  Looks like we have some blank lines with trailing whitespace and `Her  oku` in the description.  Can you please clean this up a bit? :)

**Pull request closed without merging**
