### PR TITLE
Binutils -> 2.37

### PR DESCRIPTION
**Pull request by satmandu**
- Fixes dwarf error I was seeing when rebuilding `inetutils`.
- i686 build please @uberhacker ?

Works properly:
- [x] x86_64
- [x] armv7l
- [x] i686

### CODE REVIEW

**Comment by saltedcoffii** [comment]
Could we add the `--default-gold` ./configure argument? It would compliment the `-fuse-ld=gold` command line argument for compiles

**Comment by satmandu** [comment]
I'd be ok with that. @uberhacker ?

**Comment by uberhacker** [comment]
I wish that change was made earlier.  Now I have to restart my overnight build from last night. 😞

**Comment by satmandu** [comment]
Are we good to merge then?

**Comment by uberhacker** [comment]
No, I'm getting segfaults in i686.  I'll try another attempt in Docker.

**Review by saltedcoffii — APPROVED** [review]

**Comment by saltedcoffii** [comment]
```
$ ld
ld: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ld)

$ crew install gcc11
...

$ ld
ld: fatal error: no input files
```

It looks like someone needs to separate libstdcxx into its own package. I'll do it.

**Comment by satmandu** [comment]
> ```
> $ ld
> ld: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ld)
> 
> $ crew install gcc11
> ...
> 
> $ ld
> ld: fatal error: no input files
> ```
> 
> It looks like someone needs to separate libstdcxx into its own package. I'll do it.

Why shouldn't ld depend upon GCC?

(Also can we just have the dependency be extracting that one file from the GCC package? This should be relatively easy now...)

**Comment by satmandu** [comment]
@uberhacker Can you see if this i686 build works?

**Comment by uberhacker** [comment]
The latest i686 binary executables are still segfaulting (at least on my very outdated Samsung Series 5 chromebook).

**Comment by satmandu** [comment]
This has been rebuilt to work with armv7l glibc 2.27. This is also ready to be built for i686.

**Comment by uberhacker** [comment]
Nice!  The i686 binaries work now.

**Comment by satmandu** [comment]
Just have to note here that unlike in the package file, the i686 binary was built after LTO was disabled, and using GCC 10.2.0.

**Pull request merged**
