### PR TITLE
Update php7 from 7.1.0 to 7.1.2

### PR DESCRIPTION
**Pull request by uberhacker**
- Include --readline configure option to enable interactive shell

### CODE REVIEW

**Comment by jam7** [comment]
@uberhacker Just curious, does using `--with-gd` require `libgd`?

**Comment by uberhacker** [comment]
@jam7:  That is a good question.  I tried a power wash and clean install awhile back and it worked fine so maybe not?

**Comment by jam7** [comment]
I see.  if so, that's fine.  thank you for your reply.

2017年2月22日(水) 23:39 Ed Reel <notifications@github.com>:

**Comment by uberhacker** [comment]
Hey @lyxell @thedamian: Anything holding this PR back?  It would kill me if 7.1.3 rolls out and this is still in the queue. :)

**Comment by uberhacker** [comment]
@jam7: I have confirmed the `libgd` package is not needed for the `--with-gd` configure option.

**Pull request merged**
